# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from importlib import import_module

from .base import CircularReferenceError, JsonValue, PropertyMetadata, SchemaEnum, SchemaModel, SchemaScalar, SchemaValue
from .schema_version import SCHEMA_VERSION, SCHEMA_SOURCE, SCHEMA_SOURCE_SHA256, SCHEMA_VOCABULARY_SHA256

_MODEL_MODULES = {
    'ThreeDModel': 'three_d_model',
    'AMRadioChannel': 'am_radio_channel',
    'APIReference': 'api_reference',
    'AboutPage': 'about_page',
    'AcceptAction': 'accept_action',
    'Accommodation': 'accommodation',
    'AccountingService': 'accounting_service',
    'AchieveAction': 'achieve_action',
    'Action': 'action',
    'ActionAccessSpecification': 'action_access_specification',
    'ActivateAction': 'activate_action',
    'AddAction': 'add_action',
    'AdministrativeArea': 'administrative_area',
    'AdultEntertainment': 'adult_entertainment',
    'AdvertiserContentArticle': 'advertiser_content_article',
    'AggregateOffer': 'aggregate_offer',
    'AggregateRating': 'aggregate_rating',
    'AgreeAction': 'agree_action',
    'Airline': 'airline',
    'Airport': 'airport',
    'AlignmentObject': 'alignment_object',
    'AllocateAction': 'allocate_action',
    'AmpStory': 'amp_story',
    'AmusementPark': 'amusement_park',
    'AnalysisNewsArticle': 'analysis_news_article',
    'AnatomicalStructure': 'anatomical_structure',
    'AnatomicalSystem': 'anatomical_system',
    'AnimalShelter': 'animal_shelter',
    'Answer': 'answer',
    'Apartment': 'apartment',
    'ApartmentComplex': 'apartment_complex',
    'AppendAction': 'append_action',
    'ApplyAction': 'apply_action',
    'ApprovedIndication': 'approved_indication',
    'Aquarium': 'aquarium',
    'ArchiveComponent': 'archive_component',
    'ArchiveOrganization': 'archive_organization',
    'ArriveAction': 'arrive_action',
    'ArtGallery': 'art_gallery',
    'Artery': 'artery',
    'Article': 'article',
    'AskAction': 'ask_action',
    'AskPublicNewsArticle': 'ask_public_news_article',
    'AssessAction': 'assess_action',
    'AssignAction': 'assign_action',
    'Atlas': 'atlas',
    'Attorney': 'attorney',
    'Audience': 'audience',
    'AudioObject': 'audio_object',
    'AudioObjectSnapshot': 'audio_object_snapshot',
    'Audiobook': 'audiobook',
    'AuthenticateAction': 'authenticate_action',
    'AuthorizeAction': 'authorize_action',
    'AutoBodyShop': 'auto_body_shop',
    'AutoDealer': 'auto_dealer',
    'AutoPartsStore': 'auto_parts_store',
    'AutoRental': 'auto_rental',
    'AutoRepair': 'auto_repair',
    'AutoWash': 'auto_wash',
    'AutomatedTeller': 'automated_teller',
    'AutomotiveBusiness': 'automotive_business',
    'BackgroundNewsArticle': 'background_news_article',
    'Bakery': 'bakery',
    'BankAccount': 'bank_account',
    'BankOrCreditUnion': 'bank_or_credit_union',
    'BarOrPub': 'bar_or_pub',
    'Barcode': 'barcode',
    'Beach': 'beach',
    'BeautySalon': 'beauty_salon',
    'BedAndBreakfast': 'bed_and_breakfast',
    'BedDetails': 'bed_details',
    'BefriendAction': 'befriend_action',
    'BikeStore': 'bike_store',
    'BioChemEntity': 'bio_chem_entity',
    'Blog': 'blog',
    'BlogPosting': 'blog_posting',
    'BloodTest': 'blood_test',
    'BoatReservation': 'boat_reservation',
    'BoatTerminal': 'boat_terminal',
    'BoatTrip': 'boat_trip',
    'BodyOfWater': 'body_of_water',
    'Bone': 'bone',
    'Book': 'book',
    'BookSeries': 'book_series',
    'BookStore': 'book_store',
    'BookmarkAction': 'bookmark_action',
    'BorrowAction': 'borrow_action',
    'BowlingAlley': 'bowling_alley',
    'BrainStructure': 'brain_structure',
    'Brand': 'brand',
    'BreadcrumbList': 'breadcrumb_list',
    'Brewery': 'brewery',
    'Bridge': 'bridge',
    'BroadcastChannel': 'broadcast_channel',
    'BroadcastEvent': 'broadcast_event',
    'BroadcastFrequencySpecification': 'broadcast_frequency_specification',
    'BroadcastService': 'broadcast_service',
    'BrokerageAccount': 'brokerage_account',
    'BuddhistTemple': 'buddhist_temple',
    'BusOrCoach': 'bus_or_coach',
    'BusReservation': 'bus_reservation',
    'BusStation': 'bus_station',
    'BusStop': 'bus_stop',
    'BusTrip': 'bus_trip',
    'BusinessAudience': 'business_audience',
    'BusinessEvent': 'business_event',
    'BuyAction': 'buy_action',
    'CDCPMDRecord': 'cdcpmd_record',
    'CableOrSatelliteService': 'cable_or_satellite_service',
    'CafeOrCoffeeShop': 'cafe_or_coffee_shop',
    'Campground': 'campground',
    'CampingPitch': 'camping_pitch',
    'Canal': 'canal',
    'CancelAction': 'cancel_action',
    'Car': 'car',
    'Casino': 'casino',
    'CategoryCode': 'category_code',
    'CategoryCodeSet': 'category_code_set',
    'CatholicChurch': 'catholic_church',
    'Cemetery': 'cemetery',
    'Certification': 'certification',
    'Chapter': 'chapter',
    'CheckAction': 'check_action',
    'CheckInAction': 'check_in_action',
    'CheckOutAction': 'check_out_action',
    'CheckoutPage': 'checkout_page',
    'ChemicalSubstance': 'chemical_substance',
    'ChildCare': 'child_care',
    'ChildrensEvent': 'childrens_event',
    'ChooseAction': 'choose_action',
    'Church': 'church',
    'City': 'city',
    'CityHall': 'city_hall',
    'CivicStructure': 'civic_structure',
    'Claim': 'claim',
    'ClaimReview': 'claim_review',
    'Class': 'class_',
    'Clip': 'clip',
    'ClothingStore': 'clothing_store',
    'Code': 'code',
    'Collection': 'collection',
    'CollectionPage': 'collection_page',
    'CollegeOrUniversity': 'college_or_university',
    'ComedyClub': 'comedy_club',
    'ComedyEvent': 'comedy_event',
    'ComicCoverArt': 'comic_cover_art',
    'ComicIssue': 'comic_issue',
    'ComicSeries': 'comic_series',
    'ComicStory': 'comic_story',
    'Comment': 'comment',
    'CommentAction': 'comment_action',
    'CommunicateAction': 'communicate_action',
    'CompleteDataFeed': 'complete_data_feed',
    'CompoundPriceSpecification': 'compound_price_specification',
    'ComputerLanguage': 'computer_language',
    'ComputerStore': 'computer_store',
    'ConferenceEvent': 'conference_event',
    'ConfirmAction': 'confirm_action',
    'Consortium': 'consortium',
    'ConstraintNode': 'constraint_node',
    'ConsumeAction': 'consume_action',
    'ContactPage': 'contact_page',
    'ContactPoint': 'contact_point',
    'Continent': 'continent',
    'ControlAction': 'control_action',
    'ConvenienceStore': 'convenience_store',
    'Conversation': 'conversation',
    'CookAction': 'cook_action',
    'Cooperative': 'cooperative',
    'Corporation': 'corporation',
    'CorrectionComment': 'correction_comment',
    'Country': 'country',
    'Course': 'course',
    'CourseInstance': 'course_instance',
    'Courthouse': 'courthouse',
    'CoverArt': 'cover_art',
    'CovidTestingFacility': 'covid_testing_facility',
    'CreateAction': 'create_action',
    'CreativeWork': 'creative_work',
    'CreativeWorkSeason': 'creative_work_season',
    'CreativeWorkSeries': 'creative_work_series',
    'Credential': 'credential',
    'CreditCard': 'credit_card',
    'Crematorium': 'crematorium',
    'CriticReview': 'critic_review',
    'CurrencyConversionService': 'currency_conversion_service',
    'DDxElement': 'd_dx_element',
    'DanceEvent': 'dance_event',
    'DanceGroup': 'dance_group',
    'DataCatalog': 'data_catalog',
    'DataDownload': 'data_download',
    'DataFeed': 'data_feed',
    'DataFeedItem': 'data_feed_item',
    'Dataset': 'dataset',
    'DatedMoneySpecification': 'dated_money_specification',
    'DaySpa': 'day_spa',
    'DeactivateAction': 'deactivate_action',
    'DefenceEstablishment': 'defence_establishment',
    'DefinedRegion': 'defined_region',
    'DefinedTerm': 'defined_term',
    'DefinedTermSet': 'defined_term_set',
    'DeleteAction': 'delete_action',
    'DeliveryChargeSpecification': 'delivery_charge_specification',
    'DeliveryEvent': 'delivery_event',
    'DeliveryTimeSettings': 'delivery_time_settings',
    'Demand': 'demand',
    'Dentist': 'dentist',
    'DepartAction': 'depart_action',
    'DepartmentStore': 'department_store',
    'DepositAccount': 'deposit_account',
    'DiagnosticLab': 'diagnostic_lab',
    'DiagnosticProcedure': 'diagnostic_procedure',
    'Diet': 'diet',
    'DietarySupplement': 'dietary_supplement',
    'DigitalDocument': 'digital_document',
    'DigitalDocumentPermission': 'digital_document_permission',
    'DisagreeAction': 'disagree_action',
    'DiscoverAction': 'discover_action',
    'DiscussionForumPosting': 'discussion_forum_posting',
    'DislikeAction': 'dislike_action',
    'Distillery': 'distillery',
    'DonateAction': 'donate_action',
    'DoseSchedule': 'dose_schedule',
    'DownloadAction': 'download_action',
    'DrawAction': 'draw_action',
    'Drawing': 'drawing',
    'DrinkAction': 'drink_action',
    'Drug': 'drug',
    'DrugClass': 'drug_class',
    'DrugCost': 'drug_cost',
    'DrugLegalStatus': 'drug_legal_status',
    'DrugStrength': 'drug_strength',
    'DryCleaningOrLaundry': 'dry_cleaning_or_laundry',
    'EatAction': 'eat_action',
    'EducationEvent': 'education_event',
    'EducationalAudience': 'educational_audience',
    'EducationalOccupationalCredential': 'educational_occupational_credential',
    'EducationalOccupationalProgram': 'educational_occupational_program',
    'EducationalOrganization': 'educational_organization',
    'Electrician': 'electrician',
    'ElectronicsStore': 'electronics_store',
    'ElementarySchool': 'elementary_school',
    'EmailMessage': 'email_message',
    'Embassy': 'embassy',
    'EmergencyService': 'emergency_service',
    'EmployeeRole': 'employee_role',
    'EmployerAggregateRating': 'employer_aggregate_rating',
    'EmployerReview': 'employer_review',
    'EmploymentAgency': 'employment_agency',
    'EndorseAction': 'endorse_action',
    'EndorsementRating': 'endorsement_rating',
    'EnergyConsumptionDetails': 'energy_consumption_details',
    'EngineSpecification': 'engine_specification',
    'EntertainmentBusiness': 'entertainment_business',
    'EntryPoint': 'entry_point',
    'Episode': 'episode',
    'Error': 'error',
    'Event': 'event',
    'EventReservation': 'event_reservation',
    'EventSeries': 'event_series',
    'EventVenue': 'event_venue',
    'ExchangeRateSpecification': 'exchange_rate_specification',
    'ExerciseAction': 'exercise_action',
    'ExerciseGym': 'exercise_gym',
    'ExercisePlan': 'exercise_plan',
    'ExhibitionEvent': 'exhibition_event',
    'FAQPage': 'faq_page',
    'FMRadioChannel': 'fm_radio_channel',
    'FastFoodRestaurant': 'fast_food_restaurant',
    'Festival': 'festival',
    'FilmAction': 'film_action',
    'FinancialIncentive': 'financial_incentive',
    'FinancialProduct': 'financial_product',
    'FinancialService': 'financial_service',
    'FindAction': 'find_action',
    'FireStation': 'fire_station',
    'Flight': 'flight',
    'FlightReservation': 'flight_reservation',
    'FloorPlan': 'floor_plan',
    'Florist': 'florist',
    'FollowAction': 'follow_action',
    'FoodEstablishment': 'food_establishment',
    'FoodEstablishmentReservation': 'food_establishment_reservation',
    'FoodEvent': 'food_event',
    'FoodService': 'food_service',
    'FundingAgency': 'funding_agency',
    'FundingScheme': 'funding_scheme',
    'FurnitureStore': 'furniture_store',
    'Game': 'game',
    'GameServer': 'game_server',
    'GardenStore': 'garden_store',
    'GasStation': 'gas_station',
    'GatedResidenceCommunity': 'gated_residence_community',
    'Gene': 'gene',
    'GeneralContractor': 'general_contractor',
    'GeoCircle': 'geo_circle',
    'GeoCoordinates': 'geo_coordinates',
    'GeoShape': 'geo_shape',
    'GeospatialGeometry': 'geospatial_geometry',
    'GiveAction': 'give_action',
    'GolfCourse': 'golf_course',
    'GovernmentBuilding': 'government_building',
    'GovernmentOffice': 'government_office',
    'GovernmentOrganization': 'government_organization',
    'GovernmentPermit': 'government_permit',
    'GovernmentService': 'government_service',
    'Grant': 'grant',
    'GroceryStore': 'grocery_store',
    'Guide': 'guide',
    'HVACBusiness': 'hvac_business',
    'Hackathon': 'hackathon',
    'HairSalon': 'hair_salon',
    'HardwareStore': 'hardware_store',
    'HealthAndBeautyBusiness': 'health_and_beauty_business',
    'HealthClub': 'health_club',
    'HealthInsurancePlan': 'health_insurance_plan',
    'HealthPlanCostSharingSpecification': 'health_plan_cost_sharing_specification',
    'HealthPlanFormulary': 'health_plan_formulary',
    'HealthPlanNetwork': 'health_plan_network',
    'HealthTopicContent': 'health_topic_content',
    'HighSchool': 'high_school',
    'HinduTemple': 'hindu_temple',
    'HobbyShop': 'hobby_shop',
    'HomeAndConstructionBusiness': 'home_and_construction_business',
    'HomeGoodsStore': 'home_goods_store',
    'Hospital': 'hospital',
    'Hostel': 'hostel',
    'Hotel': 'hotel',
    'HotelRoom': 'hotel_room',
    'House': 'house',
    'HousePainter': 'house_painter',
    'HowTo': 'how_to',
    'HowToDirection': 'how_to_direction',
    'HowToItem': 'how_to_item',
    'HowToSection': 'how_to_section',
    'HowToStep': 'how_to_step',
    'HowToSupply': 'how_to_supply',
    'HowToTip': 'how_to_tip',
    'HowToTool': 'how_to_tool',
    'HyperToc': 'hyper_toc',
    'HyperTocEntry': 'hyper_toc_entry',
    'IceCreamShop': 'ice_cream_shop',
    'IgnoreAction': 'ignore_action',
    'ImageGallery': 'image_gallery',
    'ImageObject': 'image_object',
    'ImageObjectSnapshot': 'image_object_snapshot',
    'ImagingTest': 'imaging_test',
    'IndividualPhysician': 'individual_physician',
    'IndividualProduct': 'individual_product',
    'InfectiousDisease': 'infectious_disease',
    'InformAction': 'inform_action',
    'InsertAction': 'insert_action',
    'InstallAction': 'install_action',
    'InstantaneousEvent': 'instantaneous_event',
    'InsuranceAgency': 'insurance_agency',
    'Intangible': 'intangible',
    'InteractAction': 'interact_action',
    'InteractionCounter': 'interaction_counter',
    'InternetCafe': 'internet_cafe',
    'InvestmentFund': 'investment_fund',
    'InvestmentOrDeposit': 'investment_or_deposit',
    'InviteAction': 'invite_action',
    'Invoice': 'invoice',
    'ItemList': 'item_list',
    'ItemPage': 'item_page',
    'JewelryStore': 'jewelry_store',
    'JobPosting': 'job_posting',
    'JoinAction': 'join_action',
    'Joint': 'joint',
    'LakeBodyOfWater': 'lake_body_of_water',
    'Landform': 'landform',
    'LandmarksOrHistoricalBuildings': 'landmarks_or_historical_buildings',
    'Language': 'language',
    'LearningResource': 'learning_resource',
    'LeaveAction': 'leave_action',
    'LegalService': 'legal_service',
    'Legislation': 'legislation',
    'LegislationObject': 'legislation_object',
    'LegislativeBuilding': 'legislative_building',
    'LendAction': 'lend_action',
    'Library': 'library',
    'LibrarySystem': 'library_system',
    'LifestyleModification': 'lifestyle_modification',
    'Ligament': 'ligament',
    'LikeAction': 'like_action',
    'LinkRole': 'link_role',
    'LiquorStore': 'liquor_store',
    'ListItem': 'list_item',
    'ListenAction': 'listen_action',
    'LiteraryEvent': 'literary_event',
    'LiveBlogPosting': 'live_blog_posting',
    'LoanOrCredit': 'loan_or_credit',
    'LocalBusiness': 'local_business',
    'LocationFeatureSpecification': 'location_feature_specification',
    'Locksmith': 'locksmith',
    'LodgingBusiness': 'lodging_business',
    'LodgingReservation': 'lodging_reservation',
    'LoginAction': 'login_action',
    'LoseAction': 'lose_action',
    'LymphaticVessel': 'lymphatic_vessel',
    'Manuscript': 'manuscript',
    'Map': 'map',
    'MarryAction': 'marry_action',
    'MathSolver': 'math_solver',
    'MaximumDoseSchedule': 'maximum_dose_schedule',
    'MediaGallery': 'media_gallery',
    'MediaObject': 'media_object',
    'MediaReview': 'media_review',
    'MediaReviewItem': 'media_review_item',
    'MediaSubscription': 'media_subscription',
    'MedicalAudience': 'medical_audience',
    'MedicalBusiness': 'medical_business',
    'MedicalCause': 'medical_cause',
    'MedicalClinic': 'medical_clinic',
    'MedicalCode': 'medical_code',
    'MedicalCondition': 'medical_condition',
    'MedicalConditionStage': 'medical_condition_stage',
    'MedicalContraindication': 'medical_contraindication',
    'MedicalDevice': 'medical_device',
    'MedicalEntity': 'medical_entity',
    'MedicalGuideline': 'medical_guideline',
    'MedicalGuidelineContraindication': 'medical_guideline_contraindication',
    'MedicalGuidelineRecommendation': 'medical_guideline_recommendation',
    'MedicalIndication': 'medical_indication',
    'MedicalIntangible': 'medical_intangible',
    'MedicalObservationalStudy': 'medical_observational_study',
    'MedicalOrganization': 'medical_organization',
    'MedicalProcedure': 'medical_procedure',
    'MedicalRiskCalculator': 'medical_risk_calculator',
    'MedicalRiskEstimator': 'medical_risk_estimator',
    'MedicalRiskFactor': 'medical_risk_factor',
    'MedicalRiskScore': 'medical_risk_score',
    'MedicalScholarlyArticle': 'medical_scholarly_article',
    'MedicalSign': 'medical_sign',
    'MedicalSignOrSymptom': 'medical_sign_or_symptom',
    'MedicalStudy': 'medical_study',
    'MedicalSymptom': 'medical_symptom',
    'MedicalTest': 'medical_test',
    'MedicalTestPanel': 'medical_test_panel',
    'MedicalTherapy': 'medical_therapy',
    'MedicalTrial': 'medical_trial',
    'MedicalWebPage': 'medical_web_page',
    'MeetingRoom': 'meeting_room',
    'MemberProgram': 'member_program',
    'MemberProgramTier': 'member_program_tier',
    'MensClothingStore': 'mens_clothing_store',
    'Menu': 'menu',
    'MenuItem': 'menu_item',
    'MenuSection': 'menu_section',
    'MerchantReturnPolicy': 'merchant_return_policy',
    'MerchantReturnPolicySeasonalOverride': 'merchant_return_policy_seasonal_override',
    'Message': 'message',
    'MiddleSchool': 'middle_school',
    'MobileApplication': 'mobile_application',
    'MobilePhoneStore': 'mobile_phone_store',
    'MolecularEntity': 'molecular_entity',
    'MonetaryAmount': 'monetary_amount',
    'MonetaryAmountDistribution': 'monetary_amount_distribution',
    'MonetaryGrant': 'monetary_grant',
    'MoneyTransfer': 'money_transfer',
    'MortgageLoan': 'mortgage_loan',
    'Mosque': 'mosque',
    'Motel': 'motel',
    'Motorcycle': 'motorcycle',
    'MotorcycleDealer': 'motorcycle_dealer',
    'MotorcycleRepair': 'motorcycle_repair',
    'MotorizedBicycle': 'motorized_bicycle',
    'Mountain': 'mountain',
    'MoveAction': 'move_action',
    'Movie': 'movie',
    'MovieClip': 'movie_clip',
    'MovieRentalStore': 'movie_rental_store',
    'MovieSeries': 'movie_series',
    'MovieTheater': 'movie_theater',
    'MovingCompany': 'moving_company',
    'Muscle': 'muscle',
    'Museum': 'museum',
    'MusicAlbum': 'music_album',
    'MusicComposition': 'music_composition',
    'MusicEvent': 'music_event',
    'MusicGroup': 'music_group',
    'MusicPlaylist': 'music_playlist',
    'MusicRecording': 'music_recording',
    'MusicRelease': 'music_release',
    'MusicStore': 'music_store',
    'MusicVenue': 'music_venue',
    'MusicVideoObject': 'music_video_object',
    'NGO': 'ngo',
    'NailSalon': 'nail_salon',
    'Nerve': 'nerve',
    'NewsArticle': 'news_article',
    'NewsMediaOrganization': 'news_media_organization',
    'Newspaper': 'newspaper',
    'NightClub': 'night_club',
    'Notary': 'notary',
    'NoteDigitalDocument': 'note_digital_document',
    'NutritionInformation': 'nutrition_information',
    'Observation': 'observation',
    'Occupation': 'occupation',
    'OccupationalExperienceRequirements': 'occupational_experience_requirements',
    'OccupationalTherapy': 'occupational_therapy',
    'OceanBodyOfWater': 'ocean_body_of_water',
    'Offer': 'offer',
    'OfferCatalog': 'offer_catalog',
    'OfferForLease': 'offer_for_lease',
    'OfferForPurchase': 'offer_for_purchase',
    'OfferShippingDetails': 'offer_shipping_details',
    'OfficeEquipmentStore': 'office_equipment_store',
    'OnDemandEvent': 'on_demand_event',
    'OnlineBusiness': 'online_business',
    'OnlineMarketplace': 'online_marketplace',
    'OnlineStore': 'online_store',
    'OpeningHoursSpecification': 'opening_hours_specification',
    'OperatingSystem': 'operating_system',
    'OpinionNewsArticle': 'opinion_news_article',
    'Optician': 'optician',
    'Order': 'order',
    'OrderAction': 'order_action',
    'OrderItem': 'order_item',
    'Organization': 'organization',
    'OrganizationRole': 'organization_role',
    'OrganizeAction': 'organize_action',
    'OutletStore': 'outlet_store',
    'OwnershipInfo': 'ownership_info',
    'PaintAction': 'paint_action',
    'Painting': 'painting',
    'PalliativeProcedure': 'palliative_procedure',
    'ParcelDelivery': 'parcel_delivery',
    'ParentAudience': 'parent_audience',
    'Park': 'park',
    'ParkingFacility': 'parking_facility',
    'PathologyTest': 'pathology_test',
    'Patient': 'patient',
    'PawnShop': 'pawn_shop',
    'PayAction': 'pay_action',
    'PaymentCard': 'payment_card',
    'PaymentChargeSpecification': 'payment_charge_specification',
    'PaymentMethod': 'payment_method',
    'PaymentService': 'payment_service',
    'PeopleAudience': 'people_audience',
    'PerformAction': 'perform_action',
    'PerformanceRole': 'performance_role',
    'PerformingArtsEvent': 'performing_arts_event',
    'PerformingArtsTheater': 'performing_arts_theater',
    'PerformingGroup': 'performing_group',
    'Periodical': 'periodical',
    'Permit': 'permit',
    'Person': 'person',
    'PetStore': 'pet_store',
    'Pharmacy': 'pharmacy',
    'Photograph': 'photograph',
    'PhotographAction': 'photograph_action',
    'PhysicalActivity': 'physical_activity',
    'PhysicalTherapy': 'physical_therapy',
    'Physician': 'physician',
    'PhysiciansOffice': 'physicians_office',
    'Place': 'place',
    'PlaceOfWorship': 'place_of_worship',
    'PlanAction': 'plan_action',
    'Play': 'play',
    'PlayAction': 'play_action',
    'PlayGameAction': 'play_game_action',
    'Playground': 'playground',
    'Plumber': 'plumber',
    'PodcastEpisode': 'podcast_episode',
    'PodcastSeason': 'podcast_season',
    'PodcastSeries': 'podcast_series',
    'PoliceStation': 'police_station',
    'PoliticalParty': 'political_party',
    'Pond': 'pond',
    'PostOffice': 'post_office',
    'PostalAddress': 'postal_address',
    'PostalCodeRangeSpecification': 'postal_code_range_specification',
    'Poster': 'poster',
    'PreOrderAction': 'pre_order_action',
    'PrependAction': 'prepend_action',
    'Preschool': 'preschool',
    'PresentationDigitalDocument': 'presentation_digital_document',
    'PreventionIndication': 'prevention_indication',
    'PriceSpecification': 'price_specification',
    'Product': 'product',
    'ProductCollection': 'product_collection',
    'ProductGroup': 'product_group',
    'ProductModel': 'product_model',
    'ProductReturnPolicy': 'product_return_policy',
    'ProfessionalService': 'professional_service',
    'ProfilePage': 'profile_page',
    'ProgramMembership': 'program_membership',
    'Project': 'project',
    'Property': 'property',
    'PropertyValue': 'property_value',
    'PropertyValueSpecification': 'property_value_specification',
    'Protein': 'protein',
    'PsychologicalTreatment': 'psychological_treatment',
    'PublicSwimmingPool': 'public_swimming_pool',
    'PublicToilet': 'public_toilet',
    'PublicationEvent': 'publication_event',
    'PublicationIssue': 'publication_issue',
    'PublicationVolume': 'publication_volume',
    'QAPage': 'qa_page',
    'QuantitativeValue': 'quantitative_value',
    'QuantitativeValueDistribution': 'quantitative_value_distribution',
    'Question': 'question',
    'Quiz': 'quiz',
    'Quotation': 'quotation',
    'QuoteAction': 'quote_action',
    'RVPark': 'rv_park',
    'RadiationTherapy': 'radiation_therapy',
    'RadioBroadcastService': 'radio_broadcast_service',
    'RadioChannel': 'radio_channel',
    'RadioClip': 'radio_clip',
    'RadioEpisode': 'radio_episode',
    'RadioSeason': 'radio_season',
    'RadioSeries': 'radio_series',
    'RadioStation': 'radio_station',
    'Rating': 'rating',
    'ReactAction': 'react_action',
    'ReadAction': 'read_action',
    'RealEstateAgent': 'real_estate_agent',
    'RealEstateListing': 'real_estate_listing',
    'ReceiveAction': 'receive_action',
    'Recipe': 'recipe',
    'Recommendation': 'recommendation',
    'RecommendedDoseSchedule': 'recommended_dose_schedule',
    'RecyclingCenter': 'recycling_center',
    'RegisterAction': 'register_action',
    'RejectAction': 'reject_action',
    'RentAction': 'rent_action',
    'RentalCarReservation': 'rental_car_reservation',
    'RepaymentSpecification': 'repayment_specification',
    'ReplaceAction': 'replace_action',
    'ReplyAction': 'reply_action',
    'Report': 'report',
    'ReportageNewsArticle': 'reportage_news_article',
    'ReportedDoseSchedule': 'reported_dose_schedule',
    'ResearchOrganization': 'research_organization',
    'ResearchProject': 'research_project',
    'Researcher': 'researcher',
    'Reservation': 'reservation',
    'ReservationPackage': 'reservation_package',
    'ReserveAction': 'reserve_action',
    'Reservoir': 'reservoir',
    'ResetPasswordAction': 'reset_password_action',
    'Residence': 'residence',
    'Resort': 'resort',
    'Restaurant': 'restaurant',
    'ResumeAction': 'resume_action',
    'ReturnAction': 'return_action',
    'Review': 'review',
    'ReviewAction': 'review_action',
    'ReviewNewsArticle': 'review_news_article',
    'RiverBodyOfWater': 'river_body_of_water',
    'Role': 'role',
    'RoofingContractor': 'roofing_contractor',
    'Room': 'room',
    'RsvpAction': 'rsvp_action',
    'RuntimePlatform': 'runtime_platform',
    'SaleEvent': 'sale_event',
    'SatiricalArticle': 'satirical_article',
    'Schedule': 'schedule',
    'ScheduleAction': 'schedule_action',
    'ScholarlyArticle': 'scholarly_article',
    'School': 'school',
    'SchoolDistrict': 'school_district',
    'ScreeningEvent': 'screening_event',
    'Sculpture': 'sculpture',
    'SeaBodyOfWater': 'sea_body_of_water',
    'SearchAction': 'search_action',
    'SearchRescueOrganization': 'search_rescue_organization',
    'SearchResultsPage': 'search_results_page',
    'Season': 'season',
    'Seat': 'seat',
    'SeekToAction': 'seek_to_action',
    'SelfStorage': 'self_storage',
    'SellAction': 'sell_action',
    'SendAction': 'send_action',
    'SequentialArt': 'sequential_art',
    'Series': 'series',
    'Service': 'service',
    'ServiceChannel': 'service_channel',
    'ServicePeriod': 'service_period',
    'ShareAction': 'share_action',
    'SheetMusic': 'sheet_music',
    'ShippingConditions': 'shipping_conditions',
    'ShippingDeliveryTime': 'shipping_delivery_time',
    'ShippingRateSettings': 'shipping_rate_settings',
    'ShippingService': 'shipping_service',
    'ShoeStore': 'shoe_store',
    'ShoppingCenter': 'shopping_center',
    'ShortStory': 'short_story',
    'SingleFamilyResidence': 'single_family_residence',
    'SiteNavigationElement': 'site_navigation_element',
    'SkiResort': 'ski_resort',
    'SocialEvent': 'social_event',
    'SocialMediaPosting': 'social_media_posting',
    'SoftwareApplication': 'software_application',
    'SoftwareSourceCode': 'software_source_code',
    'SolveMathAction': 'solve_math_action',
    'SomeProducts': 'some_products',
    'SpeakableSpecification': 'speakable_specification',
    'SpecialAnnouncement': 'special_announcement',
    'SportingGoodsStore': 'sporting_goods_store',
    'SportsActivityLocation': 'sports_activity_location',
    'SportsClub': 'sports_club',
    'SportsEvent': 'sports_event',
    'SportsOrganization': 'sports_organization',
    'SportsTeam': 'sports_team',
    'SpreadsheetDigitalDocument': 'spreadsheet_digital_document',
    'StadiumOrArena': 'stadium_or_arena',
    'State': 'state',
    'Statement': 'statement',
    'StatisticalPopulation': 'statistical_population',
    'StatisticalVariable': 'statistical_variable',
    'Store': 'store',
    'StructuredValue': 'structured_value',
    'StupidType': 'stupid_type',
    'SubscribeAction': 'subscribe_action',
    'Substance': 'substance',
    'SubwayStation': 'subway_station',
    'Suite': 'suite',
    'SuperficialAnatomy': 'superficial_anatomy',
    'SurgicalProcedure': 'surgical_procedure',
    'SuspendAction': 'suspend_action',
    'Syllabus': 'syllabus',
    'Synagogue': 'synagogue',
    'TVClip': 'tv_clip',
    'TVEpisode': 'tv_episode',
    'TVSeason': 'tv_season',
    'TVSeries': 'tv_series',
    'Table': 'table',
    'TakeAction': 'take_action',
    'TattooParlor': 'tattoo_parlor',
    'Taxi': 'taxi',
    'TaxiReservation': 'taxi_reservation',
    'TaxiService': 'taxi_service',
    'TaxiStand': 'taxi_stand',
    'Taxon': 'taxon',
    'TechArticle': 'tech_article',
    'TelevisionChannel': 'television_channel',
    'TelevisionStation': 'television_station',
    'TennisComplex': 'tennis_complex',
    'TextDigitalDocument': 'text_digital_document',
    'TextObject': 'text_object',
    'TheaterEvent': 'theater_event',
    'TheaterGroup': 'theater_group',
    'TherapeuticProcedure': 'therapeutic_procedure',
    'Thesis': 'thesis',
    'Thing': 'thing',
    'Ticket': 'ticket',
    'TieAction': 'tie_action',
    'TipAction': 'tip_action',
    'TireShop': 'tire_shop',
    'TouristAttraction': 'tourist_attraction',
    'TouristDestination': 'tourist_destination',
    'TouristInformationCenter': 'tourist_information_center',
    'TouristTrip': 'tourist_trip',
    'ToyStore': 'toy_store',
    'TrackAction': 'track_action',
    'TradeAction': 'trade_action',
    'TrainReservation': 'train_reservation',
    'TrainStation': 'train_station',
    'TrainTrip': 'train_trip',
    'TransferAction': 'transfer_action',
    'TravelAction': 'travel_action',
    'TravelAgency': 'travel_agency',
    'TreatmentIndication': 'treatment_indication',
    'Trip': 'trip',
    'TypeAndQuantityNode': 'type_and_quantity_node',
    'UnRegisterAction': 'un_register_action',
    'UnitPriceSpecification': 'unit_price_specification',
    'UpdateAction': 'update_action',
    'UseAction': 'use_action',
    'UserBlocks': 'user_blocks',
    'UserCheckins': 'user_checkins',
    'UserComments': 'user_comments',
    'UserDownloads': 'user_downloads',
    'UserInteraction': 'user_interaction',
    'UserLikes': 'user_likes',
    'UserPageVisits': 'user_page_visits',
    'UserPlays': 'user_plays',
    'UserPlusOnes': 'user_plus_ones',
    'UserReview': 'user_review',
    'UserTweets': 'user_tweets',
    'VacationRental': 'vacation_rental',
    'Vehicle': 'vehicle',
    'Vein': 'vein',
    'Vessel': 'vessel',
    'VeterinaryCare': 'veterinary_care',
    'VideoGallery': 'video_gallery',
    'VideoGame': 'video_game',
    'VideoGameClip': 'video_game_clip',
    'VideoGameSeries': 'video_game_series',
    'VideoObject': 'video_object',
    'VideoObjectSnapshot': 'video_object_snapshot',
    'ViewAction': 'view_action',
    'VirtualLocation': 'virtual_location',
    'VisualArtsEvent': 'visual_arts_event',
    'VisualArtwork': 'visual_artwork',
    'VitalSign': 'vital_sign',
    'Volcano': 'volcano',
    'VoteAction': 'vote_action',
    'WPAdBlock': 'wp_ad_block',
    'WPFooter': 'wp_footer',
    'WPHeader': 'wp_header',
    'WPSideBar': 'wp_side_bar',
    'WantAction': 'want_action',
    'WarrantyPromise': 'warranty_promise',
    'WatchAction': 'watch_action',
    'Waterfall': 'waterfall',
    'WearAction': 'wear_action',
    'WebAPI': 'web_api',
    'WebApplication': 'web_application',
    'WebContent': 'web_content',
    'WebPage': 'web_page',
    'WebPageElement': 'web_page_element',
    'WebSite': 'web_site',
    'WholesaleStore': 'wholesale_store',
    'WinAction': 'win_action',
    'Winery': 'winery',
    'WorkBasedProgram': 'work_based_program',
    'WorkersUnion': 'workers_union',
    'WriteAction': 'write_action',
    'Zoo': 'zoo',
}
_ENUM_NAMES = {
    'ActionStatusType': 'ActionStatusType',
    'AdultOrientedEnumeration': 'AdultOrientedEnumeration',
    'BedType': 'BedType',
    'BoardingPolicyType': 'BoardingPolicyType',
    'BodyMeasurementTypeEnumeration': 'BodyMeasurementTypeEnumeration',
    'BookFormatType': 'BookFormatType',
    'BusinessEntityType': 'BusinessEntityType',
    'BusinessFunction': 'BusinessFunction',
    'CarUsageType': 'CarUsageType',
    'CertificationStatusEnumeration': 'CertificationStatusEnumeration',
    'ContactPointOption': 'ContactPointOption',
    'DENonprofitType': 'DENonprofitType',
    'DayOfWeek': 'DayOfWeek',
    'DeliveryMethod': 'DeliveryMethod',
    'DigitalDocumentPermissionType': 'DigitalDocumentPermissionType',
    'DigitalPlatformEnumeration': 'DigitalPlatformEnumeration',
    'DriveWheelConfigurationValue': 'DriveWheelConfigurationValue',
    'DrugCostCategory': 'DrugCostCategory',
    'DrugPregnancyCategory': 'DrugPregnancyCategory',
    'DrugPrescriptionStatus': 'DrugPrescriptionStatus',
    'EUEnergyEfficiencyEnumeration': 'EUEnergyEfficiencyEnumeration',
    'EnergyEfficiencyEnumeration': 'EnergyEfficiencyEnumeration',
    'EnergyStarEnergyEfficiencyEnumeration': 'EnergyStarEnergyEfficiencyEnumeration',
    'Enumeration': 'Enumeration',
    'EventAttendanceModeEnumeration': 'EventAttendanceModeEnumeration',
    'EventStatusType': 'EventStatusType',
    'FulfillmentTypeEnumeration': 'FulfillmentTypeEnumeration',
    'GameAvailabilityEnumeration': 'GameAvailabilityEnumeration',
    'GamePlayMode': 'GamePlayMode',
    'GameServerStatus': 'GameServerStatus',
    'GenderType': 'GenderType',
    'GovernmentBenefitsType': 'GovernmentBenefitsType',
    'HealthAspectEnumeration': 'HealthAspectEnumeration',
    'IPTCDigitalSourceEnumeration': 'IPTCDigitalSourceEnumeration',
    'ITNonprofitType': 'ITNonprofitType',
    'IncentiveQualifiedExpenseType': 'IncentiveQualifiedExpenseType',
    'IncentiveStatus': 'IncentiveStatus',
    'IncentiveType': 'IncentiveType',
    'InfectiousAgentClass': 'InfectiousAgentClass',
    'ItemAvailability': 'ItemAvailability',
    'ItemListOrderType': 'ItemListOrderType',
    'LegalForceStatus': 'LegalForceStatus',
    'LegalValueLevel': 'LegalValueLevel',
    'MapCategoryType': 'MapCategoryType',
    'MeasurementMethodEnum': 'MeasurementMethodEnum',
    'MeasurementTypeEnumeration': 'MeasurementTypeEnumeration',
    'MediaEnumeration': 'MediaEnumeration',
    'MediaManipulationRatingEnumeration': 'MediaManipulationRatingEnumeration',
    'MedicalAudienceType': 'MedicalAudienceType',
    'MedicalDevicePurpose': 'MedicalDevicePurpose',
    'MedicalEnumeration': 'MedicalEnumeration',
    'MedicalEvidenceLevel': 'MedicalEvidenceLevel',
    'MedicalImagingTechnique': 'MedicalImagingTechnique',
    'MedicalObservationalStudyDesign': 'MedicalObservationalStudyDesign',
    'MedicalProcedureType': 'MedicalProcedureType',
    'MedicalSpecialty': 'MedicalSpecialty',
    'MedicalStudyStatus': 'MedicalStudyStatus',
    'MedicalTrialDesign': 'MedicalTrialDesign',
    'MedicineSystem': 'MedicineSystem',
    'MerchantReturnEnumeration': 'MerchantReturnEnumeration',
    'MusicAlbumProductionType': 'MusicAlbumProductionType',
    'MusicAlbumReleaseType': 'MusicAlbumReleaseType',
    'MusicReleaseFormatType': 'MusicReleaseFormatType',
    'NLNonprofitType': 'NLNonprofitType',
    'NonprofitType': 'NonprofitType',
    'OfferItemCondition': 'OfferItemCondition',
    'OrderStatus': 'OrderStatus',
    'PaymentMethodType': 'PaymentMethodType',
    'PaymentStatusType': 'PaymentStatusType',
    'PhysicalActivityCategory': 'PhysicalActivityCategory',
    'PhysicalExam': 'PhysicalExam',
    'PriceComponentTypeEnumeration': 'PriceComponentTypeEnumeration',
    'PriceTypeEnumeration': 'PriceTypeEnumeration',
    'ProductReturnEnumeration': 'ProductReturnEnumeration',
    'PurchaseType': 'PurchaseType',
    'QualitativeValue': 'QualitativeValue',
    'RefundTypeEnumeration': 'RefundTypeEnumeration',
    'ReservationStatusType': 'ReservationStatusType',
    'RestrictedDiet': 'RestrictedDiet',
    'ReturnFeesEnumeration': 'ReturnFeesEnumeration',
    'ReturnLabelSourceEnumeration': 'ReturnLabelSourceEnumeration',
    'ReturnMethodEnumeration': 'ReturnMethodEnumeration',
    'RsvpResponseType': 'RsvpResponseType',
    'SizeGroupEnumeration': 'SizeGroupEnumeration',
    'SizeSpecification': 'SizeSpecification',
    'SizeSystemEnumeration': 'SizeSystemEnumeration',
    'Specialty': 'Specialty',
    'StatusEnumeration': 'StatusEnumeration',
    'SteeringPositionValue': 'SteeringPositionValue',
    'TierBenefitEnumeration': 'TierBenefitEnumeration',
    'UKNonprofitType': 'UKNonprofitType',
    'USNonprofitType': 'USNonprofitType',
    'WarrantyScope': 'WarrantyScope',
    'WearableMeasurementTypeEnumeration': 'WearableMeasurementTypeEnumeration',
    'WearableSizeGroupEnumeration': 'WearableSizeGroupEnumeration',
    'WearableSizeSystemEnumeration': 'WearableSizeSystemEnumeration',
}

def __getattr__(name: str):
    module_name = _MODEL_MODULES.get(name)
    if module_name is not None:
        model = getattr(import_module(f'.models.{module_name}', __name__), name)
        from . import registry
        return registry.rebuild(next(term for term, cls_name in registry._MODEL_CLASSES.items() if cls_name == name))
    enum_name = _ENUM_NAMES.get(name)
    if enum_name is not None:
        return getattr(import_module('.enums', __name__), enum_name)
    raise AttributeError(name)

__all__ = [
    'ThreeDModel',
    'AMRadioChannel',
    'APIReference',
    'AboutPage',
    'AcceptAction',
    'Accommodation',
    'AccountingService',
    'AchieveAction',
    'Action',
    'ActionAccessSpecification',
    'ActivateAction',
    'AddAction',
    'AdministrativeArea',
    'AdultEntertainment',
    'AdvertiserContentArticle',
    'AggregateOffer',
    'AggregateRating',
    'AgreeAction',
    'Airline',
    'Airport',
    'AlignmentObject',
    'AllocateAction',
    'AmpStory',
    'AmusementPark',
    'AnalysisNewsArticle',
    'AnatomicalStructure',
    'AnatomicalSystem',
    'AnimalShelter',
    'Answer',
    'Apartment',
    'ApartmentComplex',
    'AppendAction',
    'ApplyAction',
    'ApprovedIndication',
    'Aquarium',
    'ArchiveComponent',
    'ArchiveOrganization',
    'ArriveAction',
    'ArtGallery',
    'Artery',
    'Article',
    'AskAction',
    'AskPublicNewsArticle',
    'AssessAction',
    'AssignAction',
    'Atlas',
    'Attorney',
    'Audience',
    'AudioObject',
    'AudioObjectSnapshot',
    'Audiobook',
    'AuthenticateAction',
    'AuthorizeAction',
    'AutoBodyShop',
    'AutoDealer',
    'AutoPartsStore',
    'AutoRental',
    'AutoRepair',
    'AutoWash',
    'AutomatedTeller',
    'AutomotiveBusiness',
    'BackgroundNewsArticle',
    'Bakery',
    'BankAccount',
    'BankOrCreditUnion',
    'BarOrPub',
    'Barcode',
    'Beach',
    'BeautySalon',
    'BedAndBreakfast',
    'BedDetails',
    'BefriendAction',
    'BikeStore',
    'BioChemEntity',
    'Blog',
    'BlogPosting',
    'BloodTest',
    'BoatReservation',
    'BoatTerminal',
    'BoatTrip',
    'BodyOfWater',
    'Bone',
    'Book',
    'BookSeries',
    'BookStore',
    'BookmarkAction',
    'BorrowAction',
    'BowlingAlley',
    'BrainStructure',
    'Brand',
    'BreadcrumbList',
    'Brewery',
    'Bridge',
    'BroadcastChannel',
    'BroadcastEvent',
    'BroadcastFrequencySpecification',
    'BroadcastService',
    'BrokerageAccount',
    'BuddhistTemple',
    'BusOrCoach',
    'BusReservation',
    'BusStation',
    'BusStop',
    'BusTrip',
    'BusinessAudience',
    'BusinessEvent',
    'BuyAction',
    'CDCPMDRecord',
    'CableOrSatelliteService',
    'CafeOrCoffeeShop',
    'Campground',
    'CampingPitch',
    'Canal',
    'CancelAction',
    'Car',
    'Casino',
    'CategoryCode',
    'CategoryCodeSet',
    'CatholicChurch',
    'Cemetery',
    'Certification',
    'Chapter',
    'CheckAction',
    'CheckInAction',
    'CheckOutAction',
    'CheckoutPage',
    'ChemicalSubstance',
    'ChildCare',
    'ChildrensEvent',
    'ChooseAction',
    'Church',
    'City',
    'CityHall',
    'CivicStructure',
    'Claim',
    'ClaimReview',
    'Class',
    'Clip',
    'ClothingStore',
    'Code',
    'Collection',
    'CollectionPage',
    'CollegeOrUniversity',
    'ComedyClub',
    'ComedyEvent',
    'ComicCoverArt',
    'ComicIssue',
    'ComicSeries',
    'ComicStory',
    'Comment',
    'CommentAction',
    'CommunicateAction',
    'CompleteDataFeed',
    'CompoundPriceSpecification',
    'ComputerLanguage',
    'ComputerStore',
    'ConferenceEvent',
    'ConfirmAction',
    'Consortium',
    'ConstraintNode',
    'ConsumeAction',
    'ContactPage',
    'ContactPoint',
    'Continent',
    'ControlAction',
    'ConvenienceStore',
    'Conversation',
    'CookAction',
    'Cooperative',
    'Corporation',
    'CorrectionComment',
    'Country',
    'Course',
    'CourseInstance',
    'Courthouse',
    'CoverArt',
    'CovidTestingFacility',
    'CreateAction',
    'CreativeWork',
    'CreativeWorkSeason',
    'CreativeWorkSeries',
    'Credential',
    'CreditCard',
    'Crematorium',
    'CriticReview',
    'CurrencyConversionService',
    'DDxElement',
    'DanceEvent',
    'DanceGroup',
    'DataCatalog',
    'DataDownload',
    'DataFeed',
    'DataFeedItem',
    'Dataset',
    'DatedMoneySpecification',
    'DaySpa',
    'DeactivateAction',
    'DefenceEstablishment',
    'DefinedRegion',
    'DefinedTerm',
    'DefinedTermSet',
    'DeleteAction',
    'DeliveryChargeSpecification',
    'DeliveryEvent',
    'DeliveryTimeSettings',
    'Demand',
    'Dentist',
    'DepartAction',
    'DepartmentStore',
    'DepositAccount',
    'DiagnosticLab',
    'DiagnosticProcedure',
    'Diet',
    'DietarySupplement',
    'DigitalDocument',
    'DigitalDocumentPermission',
    'DisagreeAction',
    'DiscoverAction',
    'DiscussionForumPosting',
    'DislikeAction',
    'Distillery',
    'DonateAction',
    'DoseSchedule',
    'DownloadAction',
    'DrawAction',
    'Drawing',
    'DrinkAction',
    'Drug',
    'DrugClass',
    'DrugCost',
    'DrugLegalStatus',
    'DrugStrength',
    'DryCleaningOrLaundry',
    'EatAction',
    'EducationEvent',
    'EducationalAudience',
    'EducationalOccupationalCredential',
    'EducationalOccupationalProgram',
    'EducationalOrganization',
    'Electrician',
    'ElectronicsStore',
    'ElementarySchool',
    'EmailMessage',
    'Embassy',
    'EmergencyService',
    'EmployeeRole',
    'EmployerAggregateRating',
    'EmployerReview',
    'EmploymentAgency',
    'EndorseAction',
    'EndorsementRating',
    'EnergyConsumptionDetails',
    'EngineSpecification',
    'EntertainmentBusiness',
    'EntryPoint',
    'Episode',
    'Error',
    'Event',
    'EventReservation',
    'EventSeries',
    'EventVenue',
    'ExchangeRateSpecification',
    'ExerciseAction',
    'ExerciseGym',
    'ExercisePlan',
    'ExhibitionEvent',
    'FAQPage',
    'FMRadioChannel',
    'FastFoodRestaurant',
    'Festival',
    'FilmAction',
    'FinancialIncentive',
    'FinancialProduct',
    'FinancialService',
    'FindAction',
    'FireStation',
    'Flight',
    'FlightReservation',
    'FloorPlan',
    'Florist',
    'FollowAction',
    'FoodEstablishment',
    'FoodEstablishmentReservation',
    'FoodEvent',
    'FoodService',
    'FundingAgency',
    'FundingScheme',
    'FurnitureStore',
    'Game',
    'GameServer',
    'GardenStore',
    'GasStation',
    'GatedResidenceCommunity',
    'Gene',
    'GeneralContractor',
    'GeoCircle',
    'GeoCoordinates',
    'GeoShape',
    'GeospatialGeometry',
    'GiveAction',
    'GolfCourse',
    'GovernmentBuilding',
    'GovernmentOffice',
    'GovernmentOrganization',
    'GovernmentPermit',
    'GovernmentService',
    'Grant',
    'GroceryStore',
    'Guide',
    'HVACBusiness',
    'Hackathon',
    'HairSalon',
    'HardwareStore',
    'HealthAndBeautyBusiness',
    'HealthClub',
    'HealthInsurancePlan',
    'HealthPlanCostSharingSpecification',
    'HealthPlanFormulary',
    'HealthPlanNetwork',
    'HealthTopicContent',
    'HighSchool',
    'HinduTemple',
    'HobbyShop',
    'HomeAndConstructionBusiness',
    'HomeGoodsStore',
    'Hospital',
    'Hostel',
    'Hotel',
    'HotelRoom',
    'House',
    'HousePainter',
    'HowTo',
    'HowToDirection',
    'HowToItem',
    'HowToSection',
    'HowToStep',
    'HowToSupply',
    'HowToTip',
    'HowToTool',
    'HyperToc',
    'HyperTocEntry',
    'IceCreamShop',
    'IgnoreAction',
    'ImageGallery',
    'ImageObject',
    'ImageObjectSnapshot',
    'ImagingTest',
    'IndividualPhysician',
    'IndividualProduct',
    'InfectiousDisease',
    'InformAction',
    'InsertAction',
    'InstallAction',
    'InstantaneousEvent',
    'InsuranceAgency',
    'Intangible',
    'InteractAction',
    'InteractionCounter',
    'InternetCafe',
    'InvestmentFund',
    'InvestmentOrDeposit',
    'InviteAction',
    'Invoice',
    'ItemList',
    'ItemPage',
    'JewelryStore',
    'JobPosting',
    'JoinAction',
    'Joint',
    'LakeBodyOfWater',
    'Landform',
    'LandmarksOrHistoricalBuildings',
    'Language',
    'LearningResource',
    'LeaveAction',
    'LegalService',
    'Legislation',
    'LegislationObject',
    'LegislativeBuilding',
    'LendAction',
    'Library',
    'LibrarySystem',
    'LifestyleModification',
    'Ligament',
    'LikeAction',
    'LinkRole',
    'LiquorStore',
    'ListItem',
    'ListenAction',
    'LiteraryEvent',
    'LiveBlogPosting',
    'LoanOrCredit',
    'LocalBusiness',
    'LocationFeatureSpecification',
    'Locksmith',
    'LodgingBusiness',
    'LodgingReservation',
    'LoginAction',
    'LoseAction',
    'LymphaticVessel',
    'Manuscript',
    'Map',
    'MarryAction',
    'MathSolver',
    'MaximumDoseSchedule',
    'MediaGallery',
    'MediaObject',
    'MediaReview',
    'MediaReviewItem',
    'MediaSubscription',
    'MedicalAudience',
    'MedicalBusiness',
    'MedicalCause',
    'MedicalClinic',
    'MedicalCode',
    'MedicalCondition',
    'MedicalConditionStage',
    'MedicalContraindication',
    'MedicalDevice',
    'MedicalEntity',
    'MedicalGuideline',
    'MedicalGuidelineContraindication',
    'MedicalGuidelineRecommendation',
    'MedicalIndication',
    'MedicalIntangible',
    'MedicalObservationalStudy',
    'MedicalOrganization',
    'MedicalProcedure',
    'MedicalRiskCalculator',
    'MedicalRiskEstimator',
    'MedicalRiskFactor',
    'MedicalRiskScore',
    'MedicalScholarlyArticle',
    'MedicalSign',
    'MedicalSignOrSymptom',
    'MedicalStudy',
    'MedicalSymptom',
    'MedicalTest',
    'MedicalTestPanel',
    'MedicalTherapy',
    'MedicalTrial',
    'MedicalWebPage',
    'MeetingRoom',
    'MemberProgram',
    'MemberProgramTier',
    'MensClothingStore',
    'Menu',
    'MenuItem',
    'MenuSection',
    'MerchantReturnPolicy',
    'MerchantReturnPolicySeasonalOverride',
    'Message',
    'MiddleSchool',
    'MobileApplication',
    'MobilePhoneStore',
    'MolecularEntity',
    'MonetaryAmount',
    'MonetaryAmountDistribution',
    'MonetaryGrant',
    'MoneyTransfer',
    'MortgageLoan',
    'Mosque',
    'Motel',
    'Motorcycle',
    'MotorcycleDealer',
    'MotorcycleRepair',
    'MotorizedBicycle',
    'Mountain',
    'MoveAction',
    'Movie',
    'MovieClip',
    'MovieRentalStore',
    'MovieSeries',
    'MovieTheater',
    'MovingCompany',
    'Muscle',
    'Museum',
    'MusicAlbum',
    'MusicComposition',
    'MusicEvent',
    'MusicGroup',
    'MusicPlaylist',
    'MusicRecording',
    'MusicRelease',
    'MusicStore',
    'MusicVenue',
    'MusicVideoObject',
    'NGO',
    'NailSalon',
    'Nerve',
    'NewsArticle',
    'NewsMediaOrganization',
    'Newspaper',
    'NightClub',
    'Notary',
    'NoteDigitalDocument',
    'NutritionInformation',
    'Observation',
    'Occupation',
    'OccupationalExperienceRequirements',
    'OccupationalTherapy',
    'OceanBodyOfWater',
    'Offer',
    'OfferCatalog',
    'OfferForLease',
    'OfferForPurchase',
    'OfferShippingDetails',
    'OfficeEquipmentStore',
    'OnDemandEvent',
    'OnlineBusiness',
    'OnlineMarketplace',
    'OnlineStore',
    'OpeningHoursSpecification',
    'OperatingSystem',
    'OpinionNewsArticle',
    'Optician',
    'Order',
    'OrderAction',
    'OrderItem',
    'Organization',
    'OrganizationRole',
    'OrganizeAction',
    'OutletStore',
    'OwnershipInfo',
    'PaintAction',
    'Painting',
    'PalliativeProcedure',
    'ParcelDelivery',
    'ParentAudience',
    'Park',
    'ParkingFacility',
    'PathologyTest',
    'Patient',
    'PawnShop',
    'PayAction',
    'PaymentCard',
    'PaymentChargeSpecification',
    'PaymentMethod',
    'PaymentService',
    'PeopleAudience',
    'PerformAction',
    'PerformanceRole',
    'PerformingArtsEvent',
    'PerformingArtsTheater',
    'PerformingGroup',
    'Periodical',
    'Permit',
    'Person',
    'PetStore',
    'Pharmacy',
    'Photograph',
    'PhotographAction',
    'PhysicalActivity',
    'PhysicalTherapy',
    'Physician',
    'PhysiciansOffice',
    'Place',
    'PlaceOfWorship',
    'PlanAction',
    'Play',
    'PlayAction',
    'PlayGameAction',
    'Playground',
    'Plumber',
    'PodcastEpisode',
    'PodcastSeason',
    'PodcastSeries',
    'PoliceStation',
    'PoliticalParty',
    'Pond',
    'PostOffice',
    'PostalAddress',
    'PostalCodeRangeSpecification',
    'Poster',
    'PreOrderAction',
    'PrependAction',
    'Preschool',
    'PresentationDigitalDocument',
    'PreventionIndication',
    'PriceSpecification',
    'Product',
    'ProductCollection',
    'ProductGroup',
    'ProductModel',
    'ProductReturnPolicy',
    'ProfessionalService',
    'ProfilePage',
    'ProgramMembership',
    'Project',
    'Property',
    'PropertyValue',
    'PropertyValueSpecification',
    'Protein',
    'PsychologicalTreatment',
    'PublicSwimmingPool',
    'PublicToilet',
    'PublicationEvent',
    'PublicationIssue',
    'PublicationVolume',
    'QAPage',
    'QuantitativeValue',
    'QuantitativeValueDistribution',
    'Question',
    'Quiz',
    'Quotation',
    'QuoteAction',
    'RVPark',
    'RadiationTherapy',
    'RadioBroadcastService',
    'RadioChannel',
    'RadioClip',
    'RadioEpisode',
    'RadioSeason',
    'RadioSeries',
    'RadioStation',
    'Rating',
    'ReactAction',
    'ReadAction',
    'RealEstateAgent',
    'RealEstateListing',
    'ReceiveAction',
    'Recipe',
    'Recommendation',
    'RecommendedDoseSchedule',
    'RecyclingCenter',
    'RegisterAction',
    'RejectAction',
    'RentAction',
    'RentalCarReservation',
    'RepaymentSpecification',
    'ReplaceAction',
    'ReplyAction',
    'Report',
    'ReportageNewsArticle',
    'ReportedDoseSchedule',
    'ResearchOrganization',
    'ResearchProject',
    'Researcher',
    'Reservation',
    'ReservationPackage',
    'ReserveAction',
    'Reservoir',
    'ResetPasswordAction',
    'Residence',
    'Resort',
    'Restaurant',
    'ResumeAction',
    'ReturnAction',
    'Review',
    'ReviewAction',
    'ReviewNewsArticle',
    'RiverBodyOfWater',
    'Role',
    'RoofingContractor',
    'Room',
    'RsvpAction',
    'RuntimePlatform',
    'SaleEvent',
    'SatiricalArticle',
    'Schedule',
    'ScheduleAction',
    'ScholarlyArticle',
    'School',
    'SchoolDistrict',
    'ScreeningEvent',
    'Sculpture',
    'SeaBodyOfWater',
    'SearchAction',
    'SearchRescueOrganization',
    'SearchResultsPage',
    'Season',
    'Seat',
    'SeekToAction',
    'SelfStorage',
    'SellAction',
    'SendAction',
    'SequentialArt',
    'Series',
    'Service',
    'ServiceChannel',
    'ServicePeriod',
    'ShareAction',
    'SheetMusic',
    'ShippingConditions',
    'ShippingDeliveryTime',
    'ShippingRateSettings',
    'ShippingService',
    'ShoeStore',
    'ShoppingCenter',
    'ShortStory',
    'SingleFamilyResidence',
    'SiteNavigationElement',
    'SkiResort',
    'SocialEvent',
    'SocialMediaPosting',
    'SoftwareApplication',
    'SoftwareSourceCode',
    'SolveMathAction',
    'SomeProducts',
    'SpeakableSpecification',
    'SpecialAnnouncement',
    'SportingGoodsStore',
    'SportsActivityLocation',
    'SportsClub',
    'SportsEvent',
    'SportsOrganization',
    'SportsTeam',
    'SpreadsheetDigitalDocument',
    'StadiumOrArena',
    'State',
    'Statement',
    'StatisticalPopulation',
    'StatisticalVariable',
    'Store',
    'StructuredValue',
    'StupidType',
    'SubscribeAction',
    'Substance',
    'SubwayStation',
    'Suite',
    'SuperficialAnatomy',
    'SurgicalProcedure',
    'SuspendAction',
    'Syllabus',
    'Synagogue',
    'TVClip',
    'TVEpisode',
    'TVSeason',
    'TVSeries',
    'Table',
    'TakeAction',
    'TattooParlor',
    'Taxi',
    'TaxiReservation',
    'TaxiService',
    'TaxiStand',
    'Taxon',
    'TechArticle',
    'TelevisionChannel',
    'TelevisionStation',
    'TennisComplex',
    'TextDigitalDocument',
    'TextObject',
    'TheaterEvent',
    'TheaterGroup',
    'TherapeuticProcedure',
    'Thesis',
    'Thing',
    'Ticket',
    'TieAction',
    'TipAction',
    'TireShop',
    'TouristAttraction',
    'TouristDestination',
    'TouristInformationCenter',
    'TouristTrip',
    'ToyStore',
    'TrackAction',
    'TradeAction',
    'TrainReservation',
    'TrainStation',
    'TrainTrip',
    'TransferAction',
    'TravelAction',
    'TravelAgency',
    'TreatmentIndication',
    'Trip',
    'TypeAndQuantityNode',
    'UnRegisterAction',
    'UnitPriceSpecification',
    'UpdateAction',
    'UseAction',
    'UserBlocks',
    'UserCheckins',
    'UserComments',
    'UserDownloads',
    'UserInteraction',
    'UserLikes',
    'UserPageVisits',
    'UserPlays',
    'UserPlusOnes',
    'UserReview',
    'UserTweets',
    'VacationRental',
    'Vehicle',
    'Vein',
    'Vessel',
    'VeterinaryCare',
    'VideoGallery',
    'VideoGame',
    'VideoGameClip',
    'VideoGameSeries',
    'VideoObject',
    'VideoObjectSnapshot',
    'ViewAction',
    'VirtualLocation',
    'VisualArtsEvent',
    'VisualArtwork',
    'VitalSign',
    'Volcano',
    'VoteAction',
    'WPAdBlock',
    'WPFooter',
    'WPHeader',
    'WPSideBar',
    'WantAction',
    'WarrantyPromise',
    'WatchAction',
    'Waterfall',
    'WearAction',
    'WebAPI',
    'WebApplication',
    'WebContent',
    'WebPage',
    'WebPageElement',
    'WebSite',
    'WholesaleStore',
    'WinAction',
    'Winery',
    'WorkBasedProgram',
    'WorkersUnion',
    'WriteAction',
    'Zoo',
    'ActionStatusType',
    'AdultOrientedEnumeration',
    'BedType',
    'BoardingPolicyType',
    'BodyMeasurementTypeEnumeration',
    'BookFormatType',
    'BusinessEntityType',
    'BusinessFunction',
    'CarUsageType',
    'CertificationStatusEnumeration',
    'ContactPointOption',
    'DENonprofitType',
    'DayOfWeek',
    'DeliveryMethod',
    'DigitalDocumentPermissionType',
    'DigitalPlatformEnumeration',
    'DriveWheelConfigurationValue',
    'DrugCostCategory',
    'DrugPregnancyCategory',
    'DrugPrescriptionStatus',
    'EUEnergyEfficiencyEnumeration',
    'EnergyEfficiencyEnumeration',
    'EnergyStarEnergyEfficiencyEnumeration',
    'Enumeration',
    'EventAttendanceModeEnumeration',
    'EventStatusType',
    'FulfillmentTypeEnumeration',
    'GameAvailabilityEnumeration',
    'GamePlayMode',
    'GameServerStatus',
    'GenderType',
    'GovernmentBenefitsType',
    'HealthAspectEnumeration',
    'IPTCDigitalSourceEnumeration',
    'ITNonprofitType',
    'IncentiveQualifiedExpenseType',
    'IncentiveStatus',
    'IncentiveType',
    'InfectiousAgentClass',
    'ItemAvailability',
    'ItemListOrderType',
    'LegalForceStatus',
    'LegalValueLevel',
    'MapCategoryType',
    'MeasurementMethodEnum',
    'MeasurementTypeEnumeration',
    'MediaEnumeration',
    'MediaManipulationRatingEnumeration',
    'MedicalAudienceType',
    'MedicalDevicePurpose',
    'MedicalEnumeration',
    'MedicalEvidenceLevel',
    'MedicalImagingTechnique',
    'MedicalObservationalStudyDesign',
    'MedicalProcedureType',
    'MedicalSpecialty',
    'MedicalStudyStatus',
    'MedicalTrialDesign',
    'MedicineSystem',
    'MerchantReturnEnumeration',
    'MusicAlbumProductionType',
    'MusicAlbumReleaseType',
    'MusicReleaseFormatType',
    'NLNonprofitType',
    'NonprofitType',
    'OfferItemCondition',
    'OrderStatus',
    'PaymentMethodType',
    'PaymentStatusType',
    'PhysicalActivityCategory',
    'PhysicalExam',
    'PriceComponentTypeEnumeration',
    'PriceTypeEnumeration',
    'ProductReturnEnumeration',
    'PurchaseType',
    'QualitativeValue',
    'RefundTypeEnumeration',
    'ReservationStatusType',
    'RestrictedDiet',
    'ReturnFeesEnumeration',
    'ReturnLabelSourceEnumeration',
    'ReturnMethodEnumeration',
    'RsvpResponseType',
    'SizeGroupEnumeration',
    'SizeSpecification',
    'SizeSystemEnumeration',
    'Specialty',
    'StatusEnumeration',
    'SteeringPositionValue',
    'TierBenefitEnumeration',
    'UKNonprofitType',
    'USNonprofitType',
    'WarrantyScope',
    'WearableMeasurementTypeEnumeration',
    'WearableSizeGroupEnumeration',
    'WearableSizeSystemEnumeration',
    'SCHEMA_VERSION',
    'SCHEMA_SOURCE',
    'SCHEMA_SOURCE_SHA256',
    'SCHEMA_VOCABULARY_SHA256',
    'SchemaModel',
    'SchemaEnum',
    'CircularReferenceError',
]
