# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from importlib import import_module
from typing import TYPE_CHECKING

from .base import (
    CircularReferenceError,
    ClassMetadata,
    EnumerationMemberMetadata,
    JsonValue,
    PropertyMetadata,
    SchemaEnum,
    SchemaMap,
    SchemaModel,
    SchemaScalar,
    SchemaValue,
)
from .schema_version import SCHEMA_VERSION

if TYPE_CHECKING:
    from .enums import (
        ActionStatusType,
        AdultOrientedEnumeration,
        BedType,
        BoardingPolicyType,
        BodyMeasurementTypeEnumeration,
        BookFormatType,
        BusinessEntityType,
        BusinessFunction,
        CarUsageType,
        CertificationStatusEnumeration,
        ContactPointOption,
        DayOfWeek,
        DeliveryMethod,
        DENonprofitType,
        DigitalDocumentPermissionType,
        DigitalPlatformEnumeration,
        DriveWheelConfigurationValue,
        DrugCostCategory,
        DrugPregnancyCategory,
        DrugPrescriptionStatus,
        EnergyEfficiencyEnumeration,
        EnergyStarEnergyEfficiencyEnumeration,
        Enumeration,
        EUEnergyEfficiencyEnumeration,
        EventAttendanceModeEnumeration,
        EventStatusType,
        FulfillmentTypeEnumeration,
        GameAvailabilityEnumeration,
        GamePlayMode,
        GameServerStatus,
        GenderType,
        GovernmentBenefitsType,
        HealthAspectEnumeration,
        IncentiveQualifiedExpenseType,
        IncentiveStatus,
        IncentiveType,
        InfectiousAgentClass,
        IPTCDigitalSourceEnumeration,
        ItemAvailability,
        ItemListOrderType,
        ITNonprofitType,
        LegalForceStatus,
        LegalValueLevel,
        MapCategoryType,
        MeasurementMethodEnum,
        MeasurementTypeEnumeration,
        MediaEnumeration,
        MediaManipulationRatingEnumeration,
        MedicalAudienceType,
        MedicalDevicePurpose,
        MedicalEnumeration,
        MedicalEvidenceLevel,
        MedicalImagingTechnique,
        MedicalObservationalStudyDesign,
        MedicalProcedureType,
        MedicalSpecialty,
        MedicalStudyStatus,
        MedicalTrialDesign,
        MedicineSystem,
        MerchantReturnEnumeration,
        MusicAlbumProductionType,
        MusicAlbumReleaseType,
        MusicReleaseFormatType,
        NLNonprofitType,
        NonprofitType,
        OfferItemCondition,
        OrderStatus,
        PaymentMethodType,
        PaymentStatusType,
        PhysicalActivityCategory,
        PhysicalExam,
        PriceComponentTypeEnumeration,
        PriceTypeEnumeration,
        ProductReturnEnumeration,
        PurchaseType,
        QualitativeValue,
        RefundTypeEnumeration,
        ReservationStatusType,
        RestrictedDiet,
        ReturnFeesEnumeration,
        ReturnLabelSourceEnumeration,
        ReturnMethodEnumeration,
        RsvpResponseType,
        SizeGroupEnumeration,
        SizeSpecification,
        SizeSystemEnumeration,
        Specialty,
        StatusEnumeration,
        SteeringPositionValue,
        TierBenefitEnumeration,
        UKNonprofitType,
        USNonprofitType,
        WarrantyScope,
        WearableMeasurementTypeEnumeration,
        WearableSizeGroupEnumeration,
        WearableSizeSystemEnumeration,
    )
    from .models import (  # noqa: F401
        NGO,
        AboutPage,
        AcceptAction,
        Accommodation,
        AccountingService,
        AchieveAction,
        Action,
        ActionAccessSpecification,
        ActivateAction,
        AddAction,
        AdministrativeArea,
        AdultEntertainment,
        AdvertiserContentArticle,
        AggregateOffer,
        AggregateRating,
        AgreeAction,
        Airline,
        Airport,
        AlignmentObject,
        AllocateAction,
        AmpStory,
        AMRadioChannel,
        AmusementPark,
        AnalysisNewsArticle,
        AnatomicalStructure,
        AnatomicalSystem,
        AnimalShelter,
        Answer,
        Apartment,
        ApartmentComplex,
        APIReference,
        AppendAction,
        ApplyAction,
        ApprovedIndication,
        Aquarium,
        ArchiveComponent,
        ArchiveOrganization,
        ArriveAction,
        Artery,
        ArtGallery,
        Article,
        AskAction,
        AskPublicNewsArticle,
        AssessAction,
        AssignAction,
        Atlas,
        Attorney,
        Audience,
        Audiobook,
        AudioObject,
        AudioObjectSnapshot,
        AuthenticateAction,
        AuthorizeAction,
        AutoBodyShop,
        AutoDealer,
        AutomatedTeller,
        AutomotiveBusiness,
        AutoPartsStore,
        AutoRental,
        AutoRepair,
        AutoWash,
        BackgroundNewsArticle,
        Bakery,
        BankAccount,
        BankOrCreditUnion,
        Barcode,
        BarOrPub,
        Beach,
        BeautySalon,
        BedAndBreakfast,
        BedDetails,
        BefriendAction,
        BikeStore,
        BioChemEntity,
        Blog,
        BlogPosting,
        BloodTest,
        BoatReservation,
        BoatTerminal,
        BoatTrip,
        BodyOfWater,
        Bone,
        Book,
        BookmarkAction,
        BookSeries,
        BookStore,
        BorrowAction,
        BowlingAlley,
        BrainStructure,
        Brand,
        BreadcrumbList,
        Brewery,
        Bridge,
        BroadcastChannel,
        BroadcastEvent,
        BroadcastFrequencySpecification,
        BroadcastService,
        BrokerageAccount,
        BuddhistTemple,
        BusinessAudience,
        BusinessEvent,
        BusOrCoach,
        BusReservation,
        BusStation,
        BusStop,
        BusTrip,
        BuyAction,
        CableOrSatelliteService,
        CafeOrCoffeeShop,
        Campground,
        CampingPitch,
        Canal,
        CancelAction,
        Car,
        Casino,
        CategoryCode,
        CategoryCodeSet,
        CatholicChurch,
        CDCPMDRecord,
        Cemetery,
        Certification,
        Chapter,
        CheckAction,
        CheckInAction,
        CheckOutAction,
        CheckoutPage,
        ChemicalSubstance,
        ChildCare,
        ChildrensEvent,
        ChooseAction,
        Church,
        City,
        CityHall,
        CivicStructure,
        Claim,
        ClaimReview,
        Class,
        Clip,
        ClothingStore,
        Code,
        Collection,
        CollectionPage,
        CollegeOrUniversity,
        ComedyClub,
        ComedyEvent,
        ComicCoverArt,
        ComicIssue,
        ComicSeries,
        ComicStory,
        Comment,
        CommentAction,
        CommunicateAction,
        CompleteDataFeed,
        CompoundPriceSpecification,
        ComputerLanguage,
        ComputerStore,
        ConferenceEvent,
        ConfirmAction,
        Consortium,
        ConstraintNode,
        ConsumeAction,
        ContactPage,
        ContactPoint,
        Continent,
        ControlAction,
        ConvenienceStore,
        Conversation,
        CookAction,
        Cooperative,
        Corporation,
        CorrectionComment,
        Country,
        Course,
        CourseInstance,
        Courthouse,
        CoverArt,
        CovidTestingFacility,
        CreateAction,
        CreativeWork,
        CreativeWorkSeason,
        CreativeWorkSeries,
        Credential,
        CreditCard,
        Crematorium,
        CriticReview,
        CurrencyConversionService,
        DanceEvent,
        DanceGroup,
        DataCatalog,
        DataDownload,
        DataFeed,
        DataFeedItem,
        Dataset,
        DatedMoneySpecification,
        DaySpa,
        DDxElement,
        DeactivateAction,
        DefenceEstablishment,
        DefinedRegion,
        DefinedTerm,
        DefinedTermSet,
        DeleteAction,
        DeliveryChargeSpecification,
        DeliveryEvent,
        DeliveryTimeSettings,
        Demand,
        Dentist,
        DepartAction,
        DepartmentStore,
        DepositAccount,
        DiagnosticLab,
        DiagnosticProcedure,
        Diet,
        DietarySupplement,
        DigitalDocument,
        DigitalDocumentPermission,
        DisagreeAction,
        DiscoverAction,
        DiscussionForumPosting,
        DislikeAction,
        Distillery,
        DonateAction,
        DoseSchedule,
        DownloadAction,
        DrawAction,
        Drawing,
        DrinkAction,
        Drug,
        DrugClass,
        DrugCost,
        DrugLegalStatus,
        DrugStrength,
        DryCleaningOrLaundry,
        EatAction,
        EducationalAudience,
        EducationalOccupationalCredential,
        EducationalOccupationalProgram,
        EducationalOrganization,
        EducationEvent,
        Electrician,
        ElectronicsStore,
        ElementarySchool,
        EmailMessage,
        Embassy,
        EmergencyService,
        EmployeeRole,
        EmployerAggregateRating,
        EmployerReview,
        EmploymentAgency,
        EndorseAction,
        EndorsementRating,
        EnergyConsumptionDetails,
        EngineSpecification,
        EntertainmentBusiness,
        EntryPoint,
        Episode,
        Error,
        Event,
        EventReservation,
        EventSeries,
        EventVenue,
        ExchangeRateSpecification,
        ExerciseAction,
        ExerciseGym,
        ExercisePlan,
        ExhibitionEvent,
        FAQPage,
        FastFoodRestaurant,
        Festival,
        FilmAction,
        FinancialIncentive,
        FinancialProduct,
        FinancialService,
        FindAction,
        FireStation,
        Flight,
        FlightReservation,
        FloorPlan,
        Florist,
        FMRadioChannel,
        FollowAction,
        FoodEstablishment,
        FoodEstablishmentReservation,
        FoodEvent,
        FoodService,
        FundingAgency,
        FundingScheme,
        FurnitureStore,
        Game,
        GameServer,
        GardenStore,
        GasStation,
        GatedResidenceCommunity,
        Gene,
        GeneralContractor,
        GeoCircle,
        GeoCoordinates,
        GeoShape,
        GeospatialGeometry,
        GiveAction,
        GolfCourse,
        GovernmentBuilding,
        GovernmentOffice,
        GovernmentOrganization,
        GovernmentPermit,
        GovernmentService,
        Grant,
        GroceryStore,
        Guide,
        Hackathon,
        HairSalon,
        HardwareStore,
        HealthAndBeautyBusiness,
        HealthClub,
        HealthInsurancePlan,
        HealthPlanCostSharingSpecification,
        HealthPlanFormulary,
        HealthPlanNetwork,
        HealthTopicContent,
        HighSchool,
        HinduTemple,
        HobbyShop,
        HomeAndConstructionBusiness,
        HomeGoodsStore,
        Hospital,
        Hostel,
        Hotel,
        HotelRoom,
        House,
        HousePainter,
        HowTo,
        HowToDirection,
        HowToItem,
        HowToSection,
        HowToStep,
        HowToSupply,
        HowToTip,
        HowToTool,
        HVACBusiness,
        HyperToc,
        HyperTocEntry,
        IceCreamShop,
        IgnoreAction,
        ImageGallery,
        ImageObject,
        ImageObjectSnapshot,
        ImagingTest,
        IndividualPhysician,
        IndividualProduct,
        InfectiousDisease,
        InformAction,
        InsertAction,
        InstallAction,
        InstantaneousEvent,
        InsuranceAgency,
        Intangible,
        InteractAction,
        InteractionCounter,
        InternetCafe,
        InvestmentFund,
        InvestmentOrDeposit,
        InviteAction,
        Invoice,
        ItemList,
        ItemPage,
        JewelryStore,
        JobPosting,
        JoinAction,
        Joint,
        LakeBodyOfWater,
        Landform,
        LandmarksOrHistoricalBuildings,
        Language,
        LearningResource,
        LeaveAction,
        LegalService,
        Legislation,
        LegislationObject,
        LegislativeBuilding,
        LendAction,
        Library,
        LibrarySystem,
        LifestyleModification,
        Ligament,
        LikeAction,
        LinkRole,
        LiquorStore,
        ListenAction,
        ListItem,
        LiteraryEvent,
        LiveBlogPosting,
        LoanOrCredit,
        LocalBusiness,
        LocationFeatureSpecification,
        Locksmith,
        LodgingBusiness,
        LodgingReservation,
        LoginAction,
        LoseAction,
        LymphaticVessel,
        Manuscript,
        Map,
        MarryAction,
        MathSolver,
        MaximumDoseSchedule,
        MediaGallery,
        MediaObject,
        MediaReview,
        MediaReviewItem,
        MediaSubscription,
        MedicalAudience,
        MedicalBusiness,
        MedicalCause,
        MedicalClinic,
        MedicalCode,
        MedicalCondition,
        MedicalConditionStage,
        MedicalContraindication,
        MedicalDevice,
        MedicalEntity,
        MedicalGuideline,
        MedicalGuidelineContraindication,
        MedicalGuidelineRecommendation,
        MedicalIndication,
        MedicalIntangible,
        MedicalObservationalStudy,
        MedicalOrganization,
        MedicalProcedure,
        MedicalRiskCalculator,
        MedicalRiskEstimator,
        MedicalRiskFactor,
        MedicalRiskScore,
        MedicalScholarlyArticle,
        MedicalSign,
        MedicalSignOrSymptom,
        MedicalStudy,
        MedicalSymptom,
        MedicalTest,
        MedicalTestPanel,
        MedicalTherapy,
        MedicalTrial,
        MedicalWebPage,
        MeetingRoom,
        MemberProgram,
        MemberProgramTier,
        MensClothingStore,
        Menu,
        MenuItem,
        MenuSection,
        MerchantReturnPolicy,
        MerchantReturnPolicySeasonalOverride,
        Message,
        MiddleSchool,
        MobileApplication,
        MobilePhoneStore,
        MolecularEntity,
        MonetaryAmount,
        MonetaryAmountDistribution,
        MonetaryGrant,
        MoneyTransfer,
        MortgageLoan,
        Mosque,
        Motel,
        Motorcycle,
        MotorcycleDealer,
        MotorcycleRepair,
        MotorizedBicycle,
        Mountain,
        MoveAction,
        Movie,
        MovieClip,
        MovieRentalStore,
        MovieSeries,
        MovieTheater,
        MovingCompany,
        Muscle,
        Museum,
        MusicAlbum,
        MusicComposition,
        MusicEvent,
        MusicGroup,
        MusicPlaylist,
        MusicRecording,
        MusicRelease,
        MusicStore,
        MusicVenue,
        MusicVideoObject,
        NailSalon,
        Nerve,
        NewsArticle,
        NewsMediaOrganization,
        Newspaper,
        NightClub,
        Notary,
        NoteDigitalDocument,
        NutritionInformation,
        Observation,
        Occupation,
        OccupationalExperienceRequirements,
        OccupationalTherapy,
        OceanBodyOfWater,
        Offer,
        OfferCatalog,
        OfferForLease,
        OfferForPurchase,
        OfferShippingDetails,
        OfficeEquipmentStore,
        OnDemandEvent,
        OnlineBusiness,
        OnlineMarketplace,
        OnlineStore,
        OpeningHoursSpecification,
        OperatingSystem,
        OpinionNewsArticle,
        Optician,
        Order,
        OrderAction,
        OrderItem,
        Organization,
        OrganizationRole,
        OrganizeAction,
        OutletStore,
        OwnershipInfo,
        PaintAction,
        Painting,
        PalliativeProcedure,
        ParcelDelivery,
        ParentAudience,
        Park,
        ParkingFacility,
        PathologyTest,
        Patient,
        PawnShop,
        PayAction,
        PaymentCard,
        PaymentChargeSpecification,
        PaymentMethod,
        PaymentService,
        PeopleAudience,
        PerformAction,
        PerformanceRole,
        PerformingArtsEvent,
        PerformingArtsTheater,
        PerformingGroup,
        Periodical,
        Permit,
        Person,
        PetStore,
        Pharmacy,
        Photograph,
        PhotographAction,
        PhysicalActivity,
        PhysicalTherapy,
        Physician,
        PhysiciansOffice,
        Place,
        PlaceOfWorship,
        PlanAction,
        Play,
        PlayAction,
        PlayGameAction,
        Playground,
        Plumber,
        PodcastEpisode,
        PodcastSeason,
        PodcastSeries,
        PoliceStation,
        PoliticalParty,
        Pond,
        PostalAddress,
        PostalCodeRangeSpecification,
        Poster,
        PostOffice,
        PreOrderAction,
        PrependAction,
        Preschool,
        PresentationDigitalDocument,
        PreventionIndication,
        PriceSpecification,
        Product,
        ProductCollection,
        ProductGroup,
        ProductModel,
        ProductReturnPolicy,
        ProfessionalService,
        ProfilePage,
        ProgramMembership,
        Project,
        Property,
        PropertyValue,
        PropertyValueSpecification,
        Protein,
        PsychologicalTreatment,
        PublicationEvent,
        PublicationIssue,
        PublicationVolume,
        PublicSwimmingPool,
        PublicToilet,
        QAPage,
        QuantitativeValue,
        QuantitativeValueDistribution,
        Question,
        Quiz,
        Quotation,
        QuoteAction,
        RadiationTherapy,
        RadioBroadcastService,
        RadioChannel,
        RadioClip,
        RadioEpisode,
        RadioSeason,
        RadioSeries,
        RadioStation,
        Rating,
        ReactAction,
        ReadAction,
        RealEstateAgent,
        RealEstateListing,
        ReceiveAction,
        Recipe,
        Recommendation,
        RecommendedDoseSchedule,
        RecyclingCenter,
        RegisterAction,
        RejectAction,
        RentAction,
        RentalCarReservation,
        RepaymentSpecification,
        ReplaceAction,
        ReplyAction,
        Report,
        ReportageNewsArticle,
        ReportedDoseSchedule,
        Researcher,
        ResearchOrganization,
        ResearchProject,
        Reservation,
        ReservationPackage,
        ReserveAction,
        Reservoir,
        ResetPasswordAction,
        Residence,
        Resort,
        Restaurant,
        ResumeAction,
        ReturnAction,
        Review,
        ReviewAction,
        ReviewNewsArticle,
        RiverBodyOfWater,
        Role,
        RoofingContractor,
        Room,
        RsvpAction,
        RuntimePlatform,
        RVPark,
        SaleEvent,
        SatiricalArticle,
        Schedule,
        ScheduleAction,
        ScholarlyArticle,
        School,
        SchoolDistrict,
        ScreeningEvent,
        Sculpture,
        SeaBodyOfWater,
        SearchAction,
        SearchRescueOrganization,
        SearchResultsPage,
        Season,
        Seat,
        SeekToAction,
        SelfStorage,
        SellAction,
        SendAction,
        SequentialArt,
        Series,
        Service,
        ServiceChannel,
        ServicePeriod,
        ShareAction,
        SheetMusic,
        ShippingConditions,
        ShippingDeliveryTime,
        ShippingRateSettings,
        ShippingService,
        ShoeStore,
        ShoppingCenter,
        ShortStory,
        SingleFamilyResidence,
        SiteNavigationElement,
        SkiResort,
        SocialEvent,
        SocialMediaPosting,
        SoftwareApplication,
        SoftwareSourceCode,
        SolveMathAction,
        SomeProducts,
        SpeakableSpecification,
        SpecialAnnouncement,
        SportingGoodsStore,
        SportsActivityLocation,
        SportsClub,
        SportsEvent,
        SportsOrganization,
        SportsTeam,
        SpreadsheetDigitalDocument,
        StadiumOrArena,
        State,
        Statement,
        StatisticalPopulation,
        StatisticalVariable,
        Store,
        StructuredValue,
        StupidType,
        SubscribeAction,
        Substance,
        SubwayStation,
        Suite,
        SuperficialAnatomy,
        SurgicalProcedure,
        SuspendAction,
        Syllabus,
        Synagogue,
        Table,
        TakeAction,
        TattooParlor,
        Taxi,
        TaxiReservation,
        TaxiService,
        TaxiStand,
        Taxon,
        TechArticle,
        TelevisionChannel,
        TelevisionStation,
        TennisComplex,
        TextDigitalDocument,
        TextObject,
        TheaterEvent,
        TheaterGroup,
        TherapeuticProcedure,
        Thesis,
        Thing,
        ThreeDModel,
        Ticket,
        TieAction,
        TipAction,
        TireShop,
        TouristAttraction,
        TouristDestination,
        TouristInformationCenter,
        TouristTrip,
        ToyStore,
        TrackAction,
        TradeAction,
        TrainReservation,
        TrainStation,
        TrainTrip,
        TransferAction,
        TravelAction,
        TravelAgency,
        TreatmentIndication,
        Trip,
        TVClip,
        TVEpisode,
        TVSeason,
        TVSeries,
        TypeAndQuantityNode,
        UnitPriceSpecification,
        UnRegisterAction,
        UpdateAction,
        UseAction,
        UserBlocks,
        UserCheckins,
        UserComments,
        UserDownloads,
        UserInteraction,
        UserLikes,
        UserPageVisits,
        UserPlays,
        UserPlusOnes,
        UserReview,
        UserTweets,
        VacationRental,
        Vehicle,
        Vein,
        Vessel,
        VeterinaryCare,
        VideoGallery,
        VideoGame,
        VideoGameClip,
        VideoGameSeries,
        VideoObject,
        VideoObjectSnapshot,
        ViewAction,
        VirtualLocation,
        VisualArtsEvent,
        VisualArtwork,
        VitalSign,
        Volcano,
        VoteAction,
        WantAction,
        WarrantyPromise,
        WatchAction,
        Waterfall,
        WearAction,
        WebAPI,
        WebApplication,
        WebContent,
        WebPage,
        WebPageElement,
        WebSite,
        WholesaleStore,
        WinAction,
        Winery,
        WorkBasedProgram,
        WorkersUnion,
        WPAdBlock,
        WPFooter,
        WPHeader,
        WPSideBar,
        WriteAction,
        Zoo,
    )

_SCHEMA_BY_EXPORT = {
    'ThreeDModel': '3DModel',
    'AMRadioChannel': 'AMRadioChannel',
    'APIReference': 'APIReference',
    'AboutPage': 'AboutPage',
    'AcceptAction': 'AcceptAction',
    'Accommodation': 'Accommodation',
    'AccountingService': 'AccountingService',
    'AchieveAction': 'AchieveAction',
    'Action': 'Action',
    'ActionAccessSpecification': 'ActionAccessSpecification',
    'ActivateAction': 'ActivateAction',
    'AddAction': 'AddAction',
    'AdministrativeArea': 'AdministrativeArea',
    'AdultEntertainment': 'AdultEntertainment',
    'AdvertiserContentArticle': 'AdvertiserContentArticle',
    'AggregateOffer': 'AggregateOffer',
    'AggregateRating': 'AggregateRating',
    'AgreeAction': 'AgreeAction',
    'Airline': 'Airline',
    'Airport': 'Airport',
    'AlignmentObject': 'AlignmentObject',
    'AllocateAction': 'AllocateAction',
    'AmpStory': 'AmpStory',
    'AmusementPark': 'AmusementPark',
    'AnalysisNewsArticle': 'AnalysisNewsArticle',
    'AnatomicalStructure': 'AnatomicalStructure',
    'AnatomicalSystem': 'AnatomicalSystem',
    'AnimalShelter': 'AnimalShelter',
    'Answer': 'Answer',
    'Apartment': 'Apartment',
    'ApartmentComplex': 'ApartmentComplex',
    'AppendAction': 'AppendAction',
    'ApplyAction': 'ApplyAction',
    'ApprovedIndication': 'ApprovedIndication',
    'Aquarium': 'Aquarium',
    'ArchiveComponent': 'ArchiveComponent',
    'ArchiveOrganization': 'ArchiveOrganization',
    'ArriveAction': 'ArriveAction',
    'ArtGallery': 'ArtGallery',
    'Artery': 'Artery',
    'Article': 'Article',
    'AskAction': 'AskAction',
    'AskPublicNewsArticle': 'AskPublicNewsArticle',
    'AssessAction': 'AssessAction',
    'AssignAction': 'AssignAction',
    'Atlas': 'Atlas',
    'Attorney': 'Attorney',
    'Audience': 'Audience',
    'AudioObject': 'AudioObject',
    'AudioObjectSnapshot': 'AudioObjectSnapshot',
    'Audiobook': 'Audiobook',
    'AuthenticateAction': 'AuthenticateAction',
    'AuthorizeAction': 'AuthorizeAction',
    'AutoBodyShop': 'AutoBodyShop',
    'AutoDealer': 'AutoDealer',
    'AutoPartsStore': 'AutoPartsStore',
    'AutoRental': 'AutoRental',
    'AutoRepair': 'AutoRepair',
    'AutoWash': 'AutoWash',
    'AutomatedTeller': 'AutomatedTeller',
    'AutomotiveBusiness': 'AutomotiveBusiness',
    'BackgroundNewsArticle': 'BackgroundNewsArticle',
    'Bakery': 'Bakery',
    'BankAccount': 'BankAccount',
    'BankOrCreditUnion': 'BankOrCreditUnion',
    'BarOrPub': 'BarOrPub',
    'Barcode': 'Barcode',
    'Beach': 'Beach',
    'BeautySalon': 'BeautySalon',
    'BedAndBreakfast': 'BedAndBreakfast',
    'BedDetails': 'BedDetails',
    'BefriendAction': 'BefriendAction',
    'BikeStore': 'BikeStore',
    'BioChemEntity': 'BioChemEntity',
    'Blog': 'Blog',
    'BlogPosting': 'BlogPosting',
    'BloodTest': 'BloodTest',
    'BoatReservation': 'BoatReservation',
    'BoatTerminal': 'BoatTerminal',
    'BoatTrip': 'BoatTrip',
    'BodyOfWater': 'BodyOfWater',
    'Bone': 'Bone',
    'Book': 'Book',
    'BookSeries': 'BookSeries',
    'BookStore': 'BookStore',
    'BookmarkAction': 'BookmarkAction',
    'BorrowAction': 'BorrowAction',
    'BowlingAlley': 'BowlingAlley',
    'BrainStructure': 'BrainStructure',
    'Brand': 'Brand',
    'BreadcrumbList': 'BreadcrumbList',
    'Brewery': 'Brewery',
    'Bridge': 'Bridge',
    'BroadcastChannel': 'BroadcastChannel',
    'BroadcastEvent': 'BroadcastEvent',
    'BroadcastFrequencySpecification': 'BroadcastFrequencySpecification',
    'BroadcastService': 'BroadcastService',
    'BrokerageAccount': 'BrokerageAccount',
    'BuddhistTemple': 'BuddhistTemple',
    'BusOrCoach': 'BusOrCoach',
    'BusReservation': 'BusReservation',
    'BusStation': 'BusStation',
    'BusStop': 'BusStop',
    'BusTrip': 'BusTrip',
    'BusinessAudience': 'BusinessAudience',
    'BusinessEvent': 'BusinessEvent',
    'BuyAction': 'BuyAction',
    'CDCPMDRecord': 'CDCPMDRecord',
    'CableOrSatelliteService': 'CableOrSatelliteService',
    'CafeOrCoffeeShop': 'CafeOrCoffeeShop',
    'Campground': 'Campground',
    'CampingPitch': 'CampingPitch',
    'Canal': 'Canal',
    'CancelAction': 'CancelAction',
    'Car': 'Car',
    'Casino': 'Casino',
    'CategoryCode': 'CategoryCode',
    'CategoryCodeSet': 'CategoryCodeSet',
    'CatholicChurch': 'CatholicChurch',
    'Cemetery': 'Cemetery',
    'Certification': 'Certification',
    'Chapter': 'Chapter',
    'CheckAction': 'CheckAction',
    'CheckInAction': 'CheckInAction',
    'CheckOutAction': 'CheckOutAction',
    'CheckoutPage': 'CheckoutPage',
    'ChemicalSubstance': 'ChemicalSubstance',
    'ChildCare': 'ChildCare',
    'ChildrensEvent': 'ChildrensEvent',
    'ChooseAction': 'ChooseAction',
    'Church': 'Church',
    'City': 'City',
    'CityHall': 'CityHall',
    'CivicStructure': 'CivicStructure',
    'Claim': 'Claim',
    'ClaimReview': 'ClaimReview',
    'Class': 'Class',
    'Clip': 'Clip',
    'ClothingStore': 'ClothingStore',
    'Code': 'Code',
    'Collection': 'Collection',
    'CollectionPage': 'CollectionPage',
    'CollegeOrUniversity': 'CollegeOrUniversity',
    'ComedyClub': 'ComedyClub',
    'ComedyEvent': 'ComedyEvent',
    'ComicCoverArt': 'ComicCoverArt',
    'ComicIssue': 'ComicIssue',
    'ComicSeries': 'ComicSeries',
    'ComicStory': 'ComicStory',
    'Comment': 'Comment',
    'CommentAction': 'CommentAction',
    'CommunicateAction': 'CommunicateAction',
    'CompleteDataFeed': 'CompleteDataFeed',
    'CompoundPriceSpecification': 'CompoundPriceSpecification',
    'ComputerLanguage': 'ComputerLanguage',
    'ComputerStore': 'ComputerStore',
    'ConferenceEvent': 'ConferenceEvent',
    'ConfirmAction': 'ConfirmAction',
    'Consortium': 'Consortium',
    'ConstraintNode': 'ConstraintNode',
    'ConsumeAction': 'ConsumeAction',
    'ContactPage': 'ContactPage',
    'ContactPoint': 'ContactPoint',
    'Continent': 'Continent',
    'ControlAction': 'ControlAction',
    'ConvenienceStore': 'ConvenienceStore',
    'Conversation': 'Conversation',
    'CookAction': 'CookAction',
    'Cooperative': 'Cooperative',
    'Corporation': 'Corporation',
    'CorrectionComment': 'CorrectionComment',
    'Country': 'Country',
    'Course': 'Course',
    'CourseInstance': 'CourseInstance',
    'Courthouse': 'Courthouse',
    'CoverArt': 'CoverArt',
    'CovidTestingFacility': 'CovidTestingFacility',
    'CreateAction': 'CreateAction',
    'CreativeWork': 'CreativeWork',
    'CreativeWorkSeason': 'CreativeWorkSeason',
    'CreativeWorkSeries': 'CreativeWorkSeries',
    'Credential': 'Credential',
    'CreditCard': 'CreditCard',
    'Crematorium': 'Crematorium',
    'CriticReview': 'CriticReview',
    'CurrencyConversionService': 'CurrencyConversionService',
    'DDxElement': 'DDxElement',
    'DanceEvent': 'DanceEvent',
    'DanceGroup': 'DanceGroup',
    'DataCatalog': 'DataCatalog',
    'DataDownload': 'DataDownload',
    'DataFeed': 'DataFeed',
    'DataFeedItem': 'DataFeedItem',
    'Dataset': 'Dataset',
    'DatedMoneySpecification': 'DatedMoneySpecification',
    'DaySpa': 'DaySpa',
    'DeactivateAction': 'DeactivateAction',
    'DefenceEstablishment': 'DefenceEstablishment',
    'DefinedRegion': 'DefinedRegion',
    'DefinedTerm': 'DefinedTerm',
    'DefinedTermSet': 'DefinedTermSet',
    'DeleteAction': 'DeleteAction',
    'DeliveryChargeSpecification': 'DeliveryChargeSpecification',
    'DeliveryEvent': 'DeliveryEvent',
    'DeliveryTimeSettings': 'DeliveryTimeSettings',
    'Demand': 'Demand',
    'Dentist': 'Dentist',
    'DepartAction': 'DepartAction',
    'DepartmentStore': 'DepartmentStore',
    'DepositAccount': 'DepositAccount',
    'DiagnosticLab': 'DiagnosticLab',
    'DiagnosticProcedure': 'DiagnosticProcedure',
    'Diet': 'Diet',
    'DietarySupplement': 'DietarySupplement',
    'DigitalDocument': 'DigitalDocument',
    'DigitalDocumentPermission': 'DigitalDocumentPermission',
    'DisagreeAction': 'DisagreeAction',
    'DiscoverAction': 'DiscoverAction',
    'DiscussionForumPosting': 'DiscussionForumPosting',
    'DislikeAction': 'DislikeAction',
    'Distillery': 'Distillery',
    'DonateAction': 'DonateAction',
    'DoseSchedule': 'DoseSchedule',
    'DownloadAction': 'DownloadAction',
    'DrawAction': 'DrawAction',
    'Drawing': 'Drawing',
    'DrinkAction': 'DrinkAction',
    'Drug': 'Drug',
    'DrugClass': 'DrugClass',
    'DrugCost': 'DrugCost',
    'DrugLegalStatus': 'DrugLegalStatus',
    'DrugStrength': 'DrugStrength',
    'DryCleaningOrLaundry': 'DryCleaningOrLaundry',
    'EatAction': 'EatAction',
    'EducationEvent': 'EducationEvent',
    'EducationalAudience': 'EducationalAudience',
    'EducationalOccupationalCredential': 'EducationalOccupationalCredential',
    'EducationalOccupationalProgram': 'EducationalOccupationalProgram',
    'EducationalOrganization': 'EducationalOrganization',
    'Electrician': 'Electrician',
    'ElectronicsStore': 'ElectronicsStore',
    'ElementarySchool': 'ElementarySchool',
    'EmailMessage': 'EmailMessage',
    'Embassy': 'Embassy',
    'EmergencyService': 'EmergencyService',
    'EmployeeRole': 'EmployeeRole',
    'EmployerAggregateRating': 'EmployerAggregateRating',
    'EmployerReview': 'EmployerReview',
    'EmploymentAgency': 'EmploymentAgency',
    'EndorseAction': 'EndorseAction',
    'EndorsementRating': 'EndorsementRating',
    'EnergyConsumptionDetails': 'EnergyConsumptionDetails',
    'EngineSpecification': 'EngineSpecification',
    'EntertainmentBusiness': 'EntertainmentBusiness',
    'EntryPoint': 'EntryPoint',
    'Episode': 'Episode',
    'Error': 'Error',
    'Event': 'Event',
    'EventReservation': 'EventReservation',
    'EventSeries': 'EventSeries',
    'EventVenue': 'EventVenue',
    'ExchangeRateSpecification': 'ExchangeRateSpecification',
    'ExerciseAction': 'ExerciseAction',
    'ExerciseGym': 'ExerciseGym',
    'ExercisePlan': 'ExercisePlan',
    'ExhibitionEvent': 'ExhibitionEvent',
    'FAQPage': 'FAQPage',
    'FMRadioChannel': 'FMRadioChannel',
    'FastFoodRestaurant': 'FastFoodRestaurant',
    'Festival': 'Festival',
    'FilmAction': 'FilmAction',
    'FinancialIncentive': 'FinancialIncentive',
    'FinancialProduct': 'FinancialProduct',
    'FinancialService': 'FinancialService',
    'FindAction': 'FindAction',
    'FireStation': 'FireStation',
    'Flight': 'Flight',
    'FlightReservation': 'FlightReservation',
    'FloorPlan': 'FloorPlan',
    'Florist': 'Florist',
    'FollowAction': 'FollowAction',
    'FoodEstablishment': 'FoodEstablishment',
    'FoodEstablishmentReservation': 'FoodEstablishmentReservation',
    'FoodEvent': 'FoodEvent',
    'FoodService': 'FoodService',
    'FundingAgency': 'FundingAgency',
    'FundingScheme': 'FundingScheme',
    'FurnitureStore': 'FurnitureStore',
    'Game': 'Game',
    'GameServer': 'GameServer',
    'GardenStore': 'GardenStore',
    'GasStation': 'GasStation',
    'GatedResidenceCommunity': 'GatedResidenceCommunity',
    'Gene': 'Gene',
    'GeneralContractor': 'GeneralContractor',
    'GeoCircle': 'GeoCircle',
    'GeoCoordinates': 'GeoCoordinates',
    'GeoShape': 'GeoShape',
    'GeospatialGeometry': 'GeospatialGeometry',
    'GiveAction': 'GiveAction',
    'GolfCourse': 'GolfCourse',
    'GovernmentBuilding': 'GovernmentBuilding',
    'GovernmentOffice': 'GovernmentOffice',
    'GovernmentOrganization': 'GovernmentOrganization',
    'GovernmentPermit': 'GovernmentPermit',
    'GovernmentService': 'GovernmentService',
    'Grant': 'Grant',
    'GroceryStore': 'GroceryStore',
    'Guide': 'Guide',
    'HVACBusiness': 'HVACBusiness',
    'Hackathon': 'Hackathon',
    'HairSalon': 'HairSalon',
    'HardwareStore': 'HardwareStore',
    'HealthAndBeautyBusiness': 'HealthAndBeautyBusiness',
    'HealthClub': 'HealthClub',
    'HealthInsurancePlan': 'HealthInsurancePlan',
    'HealthPlanCostSharingSpecification': 'HealthPlanCostSharingSpecification',
    'HealthPlanFormulary': 'HealthPlanFormulary',
    'HealthPlanNetwork': 'HealthPlanNetwork',
    'HealthTopicContent': 'HealthTopicContent',
    'HighSchool': 'HighSchool',
    'HinduTemple': 'HinduTemple',
    'HobbyShop': 'HobbyShop',
    'HomeAndConstructionBusiness': 'HomeAndConstructionBusiness',
    'HomeGoodsStore': 'HomeGoodsStore',
    'Hospital': 'Hospital',
    'Hostel': 'Hostel',
    'Hotel': 'Hotel',
    'HotelRoom': 'HotelRoom',
    'House': 'House',
    'HousePainter': 'HousePainter',
    'HowTo': 'HowTo',
    'HowToDirection': 'HowToDirection',
    'HowToItem': 'HowToItem',
    'HowToSection': 'HowToSection',
    'HowToStep': 'HowToStep',
    'HowToSupply': 'HowToSupply',
    'HowToTip': 'HowToTip',
    'HowToTool': 'HowToTool',
    'HyperToc': 'HyperToc',
    'HyperTocEntry': 'HyperTocEntry',
    'IceCreamShop': 'IceCreamShop',
    'IgnoreAction': 'IgnoreAction',
    'ImageGallery': 'ImageGallery',
    'ImageObject': 'ImageObject',
    'ImageObjectSnapshot': 'ImageObjectSnapshot',
    'ImagingTest': 'ImagingTest',
    'IndividualPhysician': 'IndividualPhysician',
    'IndividualProduct': 'IndividualProduct',
    'InfectiousDisease': 'InfectiousDisease',
    'InformAction': 'InformAction',
    'InsertAction': 'InsertAction',
    'InstallAction': 'InstallAction',
    'InstantaneousEvent': 'InstantaneousEvent',
    'InsuranceAgency': 'InsuranceAgency',
    'Intangible': 'Intangible',
    'InteractAction': 'InteractAction',
    'InteractionCounter': 'InteractionCounter',
    'InternetCafe': 'InternetCafe',
    'InvestmentFund': 'InvestmentFund',
    'InvestmentOrDeposit': 'InvestmentOrDeposit',
    'InviteAction': 'InviteAction',
    'Invoice': 'Invoice',
    'ItemList': 'ItemList',
    'ItemPage': 'ItemPage',
    'JewelryStore': 'JewelryStore',
    'JobPosting': 'JobPosting',
    'JoinAction': 'JoinAction',
    'Joint': 'Joint',
    'LakeBodyOfWater': 'LakeBodyOfWater',
    'Landform': 'Landform',
    'LandmarksOrHistoricalBuildings': 'LandmarksOrHistoricalBuildings',
    'Language': 'Language',
    'LearningResource': 'LearningResource',
    'LeaveAction': 'LeaveAction',
    'LegalService': 'LegalService',
    'Legislation': 'Legislation',
    'LegislationObject': 'LegislationObject',
    'LegislativeBuilding': 'LegislativeBuilding',
    'LendAction': 'LendAction',
    'Library': 'Library',
    'LibrarySystem': 'LibrarySystem',
    'LifestyleModification': 'LifestyleModification',
    'Ligament': 'Ligament',
    'LikeAction': 'LikeAction',
    'LinkRole': 'LinkRole',
    'LiquorStore': 'LiquorStore',
    'ListItem': 'ListItem',
    'ListenAction': 'ListenAction',
    'LiteraryEvent': 'LiteraryEvent',
    'LiveBlogPosting': 'LiveBlogPosting',
    'LoanOrCredit': 'LoanOrCredit',
    'LocalBusiness': 'LocalBusiness',
    'LocationFeatureSpecification': 'LocationFeatureSpecification',
    'Locksmith': 'Locksmith',
    'LodgingBusiness': 'LodgingBusiness',
    'LodgingReservation': 'LodgingReservation',
    'LoginAction': 'LoginAction',
    'LoseAction': 'LoseAction',
    'LymphaticVessel': 'LymphaticVessel',
    'Manuscript': 'Manuscript',
    'Map': 'Map',
    'MarryAction': 'MarryAction',
    'MathSolver': 'MathSolver',
    'MaximumDoseSchedule': 'MaximumDoseSchedule',
    'MediaGallery': 'MediaGallery',
    'MediaObject': 'MediaObject',
    'MediaReview': 'MediaReview',
    'MediaReviewItem': 'MediaReviewItem',
    'MediaSubscription': 'MediaSubscription',
    'MedicalAudience': 'MedicalAudience',
    'MedicalBusiness': 'MedicalBusiness',
    'MedicalCause': 'MedicalCause',
    'MedicalClinic': 'MedicalClinic',
    'MedicalCode': 'MedicalCode',
    'MedicalCondition': 'MedicalCondition',
    'MedicalConditionStage': 'MedicalConditionStage',
    'MedicalContraindication': 'MedicalContraindication',
    'MedicalDevice': 'MedicalDevice',
    'MedicalEntity': 'MedicalEntity',
    'MedicalGuideline': 'MedicalGuideline',
    'MedicalGuidelineContraindication': 'MedicalGuidelineContraindication',
    'MedicalGuidelineRecommendation': 'MedicalGuidelineRecommendation',
    'MedicalIndication': 'MedicalIndication',
    'MedicalIntangible': 'MedicalIntangible',
    'MedicalObservationalStudy': 'MedicalObservationalStudy',
    'MedicalOrganization': 'MedicalOrganization',
    'MedicalProcedure': 'MedicalProcedure',
    'MedicalRiskCalculator': 'MedicalRiskCalculator',
    'MedicalRiskEstimator': 'MedicalRiskEstimator',
    'MedicalRiskFactor': 'MedicalRiskFactor',
    'MedicalRiskScore': 'MedicalRiskScore',
    'MedicalScholarlyArticle': 'MedicalScholarlyArticle',
    'MedicalSign': 'MedicalSign',
    'MedicalSignOrSymptom': 'MedicalSignOrSymptom',
    'MedicalStudy': 'MedicalStudy',
    'MedicalSymptom': 'MedicalSymptom',
    'MedicalTest': 'MedicalTest',
    'MedicalTestPanel': 'MedicalTestPanel',
    'MedicalTherapy': 'MedicalTherapy',
    'MedicalTrial': 'MedicalTrial',
    'MedicalWebPage': 'MedicalWebPage',
    'MeetingRoom': 'MeetingRoom',
    'MemberProgram': 'MemberProgram',
    'MemberProgramTier': 'MemberProgramTier',
    'MensClothingStore': 'MensClothingStore',
    'Menu': 'Menu',
    'MenuItem': 'MenuItem',
    'MenuSection': 'MenuSection',
    'MerchantReturnPolicy': 'MerchantReturnPolicy',
    'MerchantReturnPolicySeasonalOverride': 'MerchantReturnPolicySeasonalOverride',
    'Message': 'Message',
    'MiddleSchool': 'MiddleSchool',
    'MobileApplication': 'MobileApplication',
    'MobilePhoneStore': 'MobilePhoneStore',
    'MolecularEntity': 'MolecularEntity',
    'MonetaryAmount': 'MonetaryAmount',
    'MonetaryAmountDistribution': 'MonetaryAmountDistribution',
    'MonetaryGrant': 'MonetaryGrant',
    'MoneyTransfer': 'MoneyTransfer',
    'MortgageLoan': 'MortgageLoan',
    'Mosque': 'Mosque',
    'Motel': 'Motel',
    'Motorcycle': 'Motorcycle',
    'MotorcycleDealer': 'MotorcycleDealer',
    'MotorcycleRepair': 'MotorcycleRepair',
    'MotorizedBicycle': 'MotorizedBicycle',
    'Mountain': 'Mountain',
    'MoveAction': 'MoveAction',
    'Movie': 'Movie',
    'MovieClip': 'MovieClip',
    'MovieRentalStore': 'MovieRentalStore',
    'MovieSeries': 'MovieSeries',
    'MovieTheater': 'MovieTheater',
    'MovingCompany': 'MovingCompany',
    'Muscle': 'Muscle',
    'Museum': 'Museum',
    'MusicAlbum': 'MusicAlbum',
    'MusicComposition': 'MusicComposition',
    'MusicEvent': 'MusicEvent',
    'MusicGroup': 'MusicGroup',
    'MusicPlaylist': 'MusicPlaylist',
    'MusicRecording': 'MusicRecording',
    'MusicRelease': 'MusicRelease',
    'MusicStore': 'MusicStore',
    'MusicVenue': 'MusicVenue',
    'MusicVideoObject': 'MusicVideoObject',
    'NGO': 'NGO',
    'NailSalon': 'NailSalon',
    'Nerve': 'Nerve',
    'NewsArticle': 'NewsArticle',
    'NewsMediaOrganization': 'NewsMediaOrganization',
    'Newspaper': 'Newspaper',
    'NightClub': 'NightClub',
    'Notary': 'Notary',
    'NoteDigitalDocument': 'NoteDigitalDocument',
    'NutritionInformation': 'NutritionInformation',
    'Observation': 'Observation',
    'Occupation': 'Occupation',
    'OccupationalExperienceRequirements': 'OccupationalExperienceRequirements',
    'OccupationalTherapy': 'OccupationalTherapy',
    'OceanBodyOfWater': 'OceanBodyOfWater',
    'Offer': 'Offer',
    'OfferCatalog': 'OfferCatalog',
    'OfferForLease': 'OfferForLease',
    'OfferForPurchase': 'OfferForPurchase',
    'OfferShippingDetails': 'OfferShippingDetails',
    'OfficeEquipmentStore': 'OfficeEquipmentStore',
    'OnDemandEvent': 'OnDemandEvent',
    'OnlineBusiness': 'OnlineBusiness',
    'OnlineMarketplace': 'OnlineMarketplace',
    'OnlineStore': 'OnlineStore',
    'OpeningHoursSpecification': 'OpeningHoursSpecification',
    'OperatingSystem': 'OperatingSystem',
    'OpinionNewsArticle': 'OpinionNewsArticle',
    'Optician': 'Optician',
    'Order': 'Order',
    'OrderAction': 'OrderAction',
    'OrderItem': 'OrderItem',
    'Organization': 'Organization',
    'OrganizationRole': 'OrganizationRole',
    'OrganizeAction': 'OrganizeAction',
    'OutletStore': 'OutletStore',
    'OwnershipInfo': 'OwnershipInfo',
    'PaintAction': 'PaintAction',
    'Painting': 'Painting',
    'PalliativeProcedure': 'PalliativeProcedure',
    'ParcelDelivery': 'ParcelDelivery',
    'ParentAudience': 'ParentAudience',
    'Park': 'Park',
    'ParkingFacility': 'ParkingFacility',
    'PathologyTest': 'PathologyTest',
    'Patient': 'Patient',
    'PawnShop': 'PawnShop',
    'PayAction': 'PayAction',
    'PaymentCard': 'PaymentCard',
    'PaymentChargeSpecification': 'PaymentChargeSpecification',
    'PaymentMethod': 'PaymentMethod',
    'PaymentService': 'PaymentService',
    'PeopleAudience': 'PeopleAudience',
    'PerformAction': 'PerformAction',
    'PerformanceRole': 'PerformanceRole',
    'PerformingArtsEvent': 'PerformingArtsEvent',
    'PerformingArtsTheater': 'PerformingArtsTheater',
    'PerformingGroup': 'PerformingGroup',
    'Periodical': 'Periodical',
    'Permit': 'Permit',
    'Person': 'Person',
    'PetStore': 'PetStore',
    'Pharmacy': 'Pharmacy',
    'Photograph': 'Photograph',
    'PhotographAction': 'PhotographAction',
    'PhysicalActivity': 'PhysicalActivity',
    'PhysicalTherapy': 'PhysicalTherapy',
    'Physician': 'Physician',
    'PhysiciansOffice': 'PhysiciansOffice',
    'Place': 'Place',
    'PlaceOfWorship': 'PlaceOfWorship',
    'PlanAction': 'PlanAction',
    'Play': 'Play',
    'PlayAction': 'PlayAction',
    'PlayGameAction': 'PlayGameAction',
    'Playground': 'Playground',
    'Plumber': 'Plumber',
    'PodcastEpisode': 'PodcastEpisode',
    'PodcastSeason': 'PodcastSeason',
    'PodcastSeries': 'PodcastSeries',
    'PoliceStation': 'PoliceStation',
    'PoliticalParty': 'PoliticalParty',
    'Pond': 'Pond',
    'PostOffice': 'PostOffice',
    'PostalAddress': 'PostalAddress',
    'PostalCodeRangeSpecification': 'PostalCodeRangeSpecification',
    'Poster': 'Poster',
    'PreOrderAction': 'PreOrderAction',
    'PrependAction': 'PrependAction',
    'Preschool': 'Preschool',
    'PresentationDigitalDocument': 'PresentationDigitalDocument',
    'PreventionIndication': 'PreventionIndication',
    'PriceSpecification': 'PriceSpecification',
    'Product': 'Product',
    'ProductCollection': 'ProductCollection',
    'ProductGroup': 'ProductGroup',
    'ProductModel': 'ProductModel',
    'ProductReturnPolicy': 'ProductReturnPolicy',
    'ProfessionalService': 'ProfessionalService',
    'ProfilePage': 'ProfilePage',
    'ProgramMembership': 'ProgramMembership',
    'Project': 'Project',
    'Property': 'Property',
    'PropertyValue': 'PropertyValue',
    'PropertyValueSpecification': 'PropertyValueSpecification',
    'Protein': 'Protein',
    'PsychologicalTreatment': 'PsychologicalTreatment',
    'PublicSwimmingPool': 'PublicSwimmingPool',
    'PublicToilet': 'PublicToilet',
    'PublicationEvent': 'PublicationEvent',
    'PublicationIssue': 'PublicationIssue',
    'PublicationVolume': 'PublicationVolume',
    'QAPage': 'QAPage',
    'QuantitativeValue': 'QuantitativeValue',
    'QuantitativeValueDistribution': 'QuantitativeValueDistribution',
    'Question': 'Question',
    'Quiz': 'Quiz',
    'Quotation': 'Quotation',
    'QuoteAction': 'QuoteAction',
    'RVPark': 'RVPark',
    'RadiationTherapy': 'RadiationTherapy',
    'RadioBroadcastService': 'RadioBroadcastService',
    'RadioChannel': 'RadioChannel',
    'RadioClip': 'RadioClip',
    'RadioEpisode': 'RadioEpisode',
    'RadioSeason': 'RadioSeason',
    'RadioSeries': 'RadioSeries',
    'RadioStation': 'RadioStation',
    'Rating': 'Rating',
    'ReactAction': 'ReactAction',
    'ReadAction': 'ReadAction',
    'RealEstateAgent': 'RealEstateAgent',
    'RealEstateListing': 'RealEstateListing',
    'ReceiveAction': 'ReceiveAction',
    'Recipe': 'Recipe',
    'Recommendation': 'Recommendation',
    'RecommendedDoseSchedule': 'RecommendedDoseSchedule',
    'RecyclingCenter': 'RecyclingCenter',
    'RegisterAction': 'RegisterAction',
    'RejectAction': 'RejectAction',
    'RentAction': 'RentAction',
    'RentalCarReservation': 'RentalCarReservation',
    'RepaymentSpecification': 'RepaymentSpecification',
    'ReplaceAction': 'ReplaceAction',
    'ReplyAction': 'ReplyAction',
    'Report': 'Report',
    'ReportageNewsArticle': 'ReportageNewsArticle',
    'ReportedDoseSchedule': 'ReportedDoseSchedule',
    'ResearchOrganization': 'ResearchOrganization',
    'ResearchProject': 'ResearchProject',
    'Researcher': 'Researcher',
    'Reservation': 'Reservation',
    'ReservationPackage': 'ReservationPackage',
    'ReserveAction': 'ReserveAction',
    'Reservoir': 'Reservoir',
    'ResetPasswordAction': 'ResetPasswordAction',
    'Residence': 'Residence',
    'Resort': 'Resort',
    'Restaurant': 'Restaurant',
    'ResumeAction': 'ResumeAction',
    'ReturnAction': 'ReturnAction',
    'Review': 'Review',
    'ReviewAction': 'ReviewAction',
    'ReviewNewsArticle': 'ReviewNewsArticle',
    'RiverBodyOfWater': 'RiverBodyOfWater',
    'Role': 'Role',
    'RoofingContractor': 'RoofingContractor',
    'Room': 'Room',
    'RsvpAction': 'RsvpAction',
    'RuntimePlatform': 'RuntimePlatform',
    'SaleEvent': 'SaleEvent',
    'SatiricalArticle': 'SatiricalArticle',
    'Schedule': 'Schedule',
    'ScheduleAction': 'ScheduleAction',
    'ScholarlyArticle': 'ScholarlyArticle',
    'School': 'School',
    'SchoolDistrict': 'SchoolDistrict',
    'ScreeningEvent': 'ScreeningEvent',
    'Sculpture': 'Sculpture',
    'SeaBodyOfWater': 'SeaBodyOfWater',
    'SearchAction': 'SearchAction',
    'SearchRescueOrganization': 'SearchRescueOrganization',
    'SearchResultsPage': 'SearchResultsPage',
    'Season': 'Season',
    'Seat': 'Seat',
    'SeekToAction': 'SeekToAction',
    'SelfStorage': 'SelfStorage',
    'SellAction': 'SellAction',
    'SendAction': 'SendAction',
    'SequentialArt': 'SequentialArt',
    'Series': 'Series',
    'Service': 'Service',
    'ServiceChannel': 'ServiceChannel',
    'ServicePeriod': 'ServicePeriod',
    'ShareAction': 'ShareAction',
    'SheetMusic': 'SheetMusic',
    'ShippingConditions': 'ShippingConditions',
    'ShippingDeliveryTime': 'ShippingDeliveryTime',
    'ShippingRateSettings': 'ShippingRateSettings',
    'ShippingService': 'ShippingService',
    'ShoeStore': 'ShoeStore',
    'ShoppingCenter': 'ShoppingCenter',
    'ShortStory': 'ShortStory',
    'SingleFamilyResidence': 'SingleFamilyResidence',
    'SiteNavigationElement': 'SiteNavigationElement',
    'SkiResort': 'SkiResort',
    'SocialEvent': 'SocialEvent',
    'SocialMediaPosting': 'SocialMediaPosting',
    'SoftwareApplication': 'SoftwareApplication',
    'SoftwareSourceCode': 'SoftwareSourceCode',
    'SolveMathAction': 'SolveMathAction',
    'SomeProducts': 'SomeProducts',
    'SpeakableSpecification': 'SpeakableSpecification',
    'SpecialAnnouncement': 'SpecialAnnouncement',
    'SportingGoodsStore': 'SportingGoodsStore',
    'SportsActivityLocation': 'SportsActivityLocation',
    'SportsClub': 'SportsClub',
    'SportsEvent': 'SportsEvent',
    'SportsOrganization': 'SportsOrganization',
    'SportsTeam': 'SportsTeam',
    'SpreadsheetDigitalDocument': 'SpreadsheetDigitalDocument',
    'StadiumOrArena': 'StadiumOrArena',
    'State': 'State',
    'Statement': 'Statement',
    'StatisticalPopulation': 'StatisticalPopulation',
    'StatisticalVariable': 'StatisticalVariable',
    'Store': 'Store',
    'StructuredValue': 'StructuredValue',
    'StupidType': 'StupidType',
    'SubscribeAction': 'SubscribeAction',
    'Substance': 'Substance',
    'SubwayStation': 'SubwayStation',
    'Suite': 'Suite',
    'SuperficialAnatomy': 'SuperficialAnatomy',
    'SurgicalProcedure': 'SurgicalProcedure',
    'SuspendAction': 'SuspendAction',
    'Syllabus': 'Syllabus',
    'Synagogue': 'Synagogue',
    'TVClip': 'TVClip',
    'TVEpisode': 'TVEpisode',
    'TVSeason': 'TVSeason',
    'TVSeries': 'TVSeries',
    'Table': 'Table',
    'TakeAction': 'TakeAction',
    'TattooParlor': 'TattooParlor',
    'Taxi': 'Taxi',
    'TaxiReservation': 'TaxiReservation',
    'TaxiService': 'TaxiService',
    'TaxiStand': 'TaxiStand',
    'Taxon': 'Taxon',
    'TechArticle': 'TechArticle',
    'TelevisionChannel': 'TelevisionChannel',
    'TelevisionStation': 'TelevisionStation',
    'TennisComplex': 'TennisComplex',
    'TextDigitalDocument': 'TextDigitalDocument',
    'TextObject': 'TextObject',
    'TheaterEvent': 'TheaterEvent',
    'TheaterGroup': 'TheaterGroup',
    'TherapeuticProcedure': 'TherapeuticProcedure',
    'Thesis': 'Thesis',
    'Thing': 'Thing',
    'Ticket': 'Ticket',
    'TieAction': 'TieAction',
    'TipAction': 'TipAction',
    'TireShop': 'TireShop',
    'TouristAttraction': 'TouristAttraction',
    'TouristDestination': 'TouristDestination',
    'TouristInformationCenter': 'TouristInformationCenter',
    'TouristTrip': 'TouristTrip',
    'ToyStore': 'ToyStore',
    'TrackAction': 'TrackAction',
    'TradeAction': 'TradeAction',
    'TrainReservation': 'TrainReservation',
    'TrainStation': 'TrainStation',
    'TrainTrip': 'TrainTrip',
    'TransferAction': 'TransferAction',
    'TravelAction': 'TravelAction',
    'TravelAgency': 'TravelAgency',
    'TreatmentIndication': 'TreatmentIndication',
    'Trip': 'Trip',
    'TypeAndQuantityNode': 'TypeAndQuantityNode',
    'UnRegisterAction': 'UnRegisterAction',
    'UnitPriceSpecification': 'UnitPriceSpecification',
    'UpdateAction': 'UpdateAction',
    'UseAction': 'UseAction',
    'UserBlocks': 'UserBlocks',
    'UserCheckins': 'UserCheckins',
    'UserComments': 'UserComments',
    'UserDownloads': 'UserDownloads',
    'UserInteraction': 'UserInteraction',
    'UserLikes': 'UserLikes',
    'UserPageVisits': 'UserPageVisits',
    'UserPlays': 'UserPlays',
    'UserPlusOnes': 'UserPlusOnes',
    'UserReview': 'UserReview',
    'UserTweets': 'UserTweets',
    'VacationRental': 'VacationRental',
    'Vehicle': 'Vehicle',
    'Vein': 'Vein',
    'Vessel': 'Vessel',
    'VeterinaryCare': 'VeterinaryCare',
    'VideoGallery': 'VideoGallery',
    'VideoGame': 'VideoGame',
    'VideoGameClip': 'VideoGameClip',
    'VideoGameSeries': 'VideoGameSeries',
    'VideoObject': 'VideoObject',
    'VideoObjectSnapshot': 'VideoObjectSnapshot',
    'ViewAction': 'ViewAction',
    'VirtualLocation': 'VirtualLocation',
    'VisualArtsEvent': 'VisualArtsEvent',
    'VisualArtwork': 'VisualArtwork',
    'VitalSign': 'VitalSign',
    'Volcano': 'Volcano',
    'VoteAction': 'VoteAction',
    'WPAdBlock': 'WPAdBlock',
    'WPFooter': 'WPFooter',
    'WPHeader': 'WPHeader',
    'WPSideBar': 'WPSideBar',
    'WantAction': 'WantAction',
    'WarrantyPromise': 'WarrantyPromise',
    'WatchAction': 'WatchAction',
    'Waterfall': 'Waterfall',
    'WearAction': 'WearAction',
    'WebAPI': 'WebAPI',
    'WebApplication': 'WebApplication',
    'WebContent': 'WebContent',
    'WebPage': 'WebPage',
    'WebPageElement': 'WebPageElement',
    'WebSite': 'WebSite',
    'WholesaleStore': 'WholesaleStore',
    'WinAction': 'WinAction',
    'Winery': 'Winery',
    'WorkBasedProgram': 'WorkBasedProgram',
    'WorkersUnion': 'WorkersUnion',
    'WriteAction': 'WriteAction',
    'Zoo': 'Zoo',
}
_ENUM_NAMES = {
    'ActionStatusType': 'ActionStatusType',
    'AdultOrientedEnumeration': 'AdultOrientedEnumeration',
    'BedType': 'BedType',
    'BoardingPolicyType': 'BoardingPolicyType',
    'BodyMeasurementTypeEnumeration': 'BodyMeasurementTypeEnumeration',
    'BookFormatType': 'BookFormatType',
    'BusinessEntityType': 'BusinessEntityType',
    'BusinessFunction': 'BusinessFunction',
    'CarUsageType': 'CarUsageType',
    'CertificationStatusEnumeration': 'CertificationStatusEnumeration',
    'ContactPointOption': 'ContactPointOption',
    'DayOfWeek': 'DayOfWeek',
    'DeliveryMethod': 'DeliveryMethod',
    'DENonprofitType': 'DENonprofitType',
    'DigitalDocumentPermissionType': 'DigitalDocumentPermissionType',
    'DigitalPlatformEnumeration': 'DigitalPlatformEnumeration',
    'DriveWheelConfigurationValue': 'DriveWheelConfigurationValue',
    'DrugCostCategory': 'DrugCostCategory',
    'DrugPregnancyCategory': 'DrugPregnancyCategory',
    'DrugPrescriptionStatus': 'DrugPrescriptionStatus',
    'EnergyEfficiencyEnumeration': 'EnergyEfficiencyEnumeration',
    'EnergyStarEnergyEfficiencyEnumeration': 'EnergyStarEnergyEfficiencyEnumeration',
    'Enumeration': 'Enumeration',
    'EUEnergyEfficiencyEnumeration': 'EUEnergyEfficiencyEnumeration',
    'EventAttendanceModeEnumeration': 'EventAttendanceModeEnumeration',
    'EventStatusType': 'EventStatusType',
    'FulfillmentTypeEnumeration': 'FulfillmentTypeEnumeration',
    'GameAvailabilityEnumeration': 'GameAvailabilityEnumeration',
    'GamePlayMode': 'GamePlayMode',
    'GameServerStatus': 'GameServerStatus',
    'GenderType': 'GenderType',
    'GovernmentBenefitsType': 'GovernmentBenefitsType',
    'HealthAspectEnumeration': 'HealthAspectEnumeration',
    'IncentiveQualifiedExpenseType': 'IncentiveQualifiedExpenseType',
    'IncentiveStatus': 'IncentiveStatus',
    'IncentiveType': 'IncentiveType',
    'InfectiousAgentClass': 'InfectiousAgentClass',
    'IPTCDigitalSourceEnumeration': 'IPTCDigitalSourceEnumeration',
    'ItemAvailability': 'ItemAvailability',
    'ItemListOrderType': 'ItemListOrderType',
    'ITNonprofitType': 'ITNonprofitType',
    'LegalForceStatus': 'LegalForceStatus',
    'LegalValueLevel': 'LegalValueLevel',
    'MapCategoryType': 'MapCategoryType',
    'MeasurementMethodEnum': 'MeasurementMethodEnum',
    'MeasurementTypeEnumeration': 'MeasurementTypeEnumeration',
    'MediaEnumeration': 'MediaEnumeration',
    'MediaManipulationRatingEnumeration': 'MediaManipulationRatingEnumeration',
    'MedicalAudienceType': 'MedicalAudienceType',
    'MedicalDevicePurpose': 'MedicalDevicePurpose',
    'MedicalEnumeration': 'MedicalEnumeration',
    'MedicalEvidenceLevel': 'MedicalEvidenceLevel',
    'MedicalImagingTechnique': 'MedicalImagingTechnique',
    'MedicalObservationalStudyDesign': 'MedicalObservationalStudyDesign',
    'MedicalProcedureType': 'MedicalProcedureType',
    'MedicalSpecialty': 'MedicalSpecialty',
    'MedicalStudyStatus': 'MedicalStudyStatus',
    'MedicalTrialDesign': 'MedicalTrialDesign',
    'MedicineSystem': 'MedicineSystem',
    'MerchantReturnEnumeration': 'MerchantReturnEnumeration',
    'MusicAlbumProductionType': 'MusicAlbumProductionType',
    'MusicAlbumReleaseType': 'MusicAlbumReleaseType',
    'MusicReleaseFormatType': 'MusicReleaseFormatType',
    'NLNonprofitType': 'NLNonprofitType',
    'NonprofitType': 'NonprofitType',
    'OfferItemCondition': 'OfferItemCondition',
    'OrderStatus': 'OrderStatus',
    'PaymentMethodType': 'PaymentMethodType',
    'PaymentStatusType': 'PaymentStatusType',
    'PhysicalActivityCategory': 'PhysicalActivityCategory',
    'PhysicalExam': 'PhysicalExam',
    'PriceComponentTypeEnumeration': 'PriceComponentTypeEnumeration',
    'PriceTypeEnumeration': 'PriceTypeEnumeration',
    'ProductReturnEnumeration': 'ProductReturnEnumeration',
    'PurchaseType': 'PurchaseType',
    'QualitativeValue': 'QualitativeValue',
    'RefundTypeEnumeration': 'RefundTypeEnumeration',
    'ReservationStatusType': 'ReservationStatusType',
    'RestrictedDiet': 'RestrictedDiet',
    'ReturnFeesEnumeration': 'ReturnFeesEnumeration',
    'ReturnLabelSourceEnumeration': 'ReturnLabelSourceEnumeration',
    'ReturnMethodEnumeration': 'ReturnMethodEnumeration',
    'RsvpResponseType': 'RsvpResponseType',
    'SizeGroupEnumeration': 'SizeGroupEnumeration',
    'SizeSpecification': 'SizeSpecification',
    'SizeSystemEnumeration': 'SizeSystemEnumeration',
    'Specialty': 'Specialty',
    'StatusEnumeration': 'StatusEnumeration',
    'SteeringPositionValue': 'SteeringPositionValue',
    'TierBenefitEnumeration': 'TierBenefitEnumeration',
    'UKNonprofitType': 'UKNonprofitType',
    'USNonprofitType': 'USNonprofitType',
    'WarrantyScope': 'WarrantyScope',
    'WearableMeasurementTypeEnumeration': 'WearableMeasurementTypeEnumeration',
    'WearableSizeGroupEnumeration': 'WearableSizeGroupEnumeration',
    'WearableSizeSystemEnumeration': 'WearableSizeSystemEnumeration',
}

def __getattr__(name: str):
    schema_name = _SCHEMA_BY_EXPORT.get(name)
    if schema_name is not None:
        from . import registry
        model = registry.get_model(schema_name)
        globals()[name] = model
        return model
    enum_name = _ENUM_NAMES.get(name)
    if enum_name is not None:
        enum = getattr(import_module('.enums', __name__), enum_name)
        globals()[name] = enum
        return enum
    raise AttributeError(name)

__all__ = [
    'SCHEMA_VERSION',
    'ActionStatusType',
    'AdultOrientedEnumeration',
    'BedType',
    'BoardingPolicyType',
    'BodyMeasurementTypeEnumeration',
    'BookFormatType',
    'BusinessEntityType',
    'BusinessFunction',
    'CarUsageType',
    'CertificationStatusEnumeration',
    'CircularReferenceError',
    'ClassMetadata',
    'ContactPointOption',
    'DENonprofitType',
    'DayOfWeek',
    'DeliveryMethod',
    'DigitalDocumentPermissionType',
    'DigitalPlatformEnumeration',
    'DriveWheelConfigurationValue',
    'DrugCostCategory',
    'DrugPregnancyCategory',
    'DrugPrescriptionStatus',
    'EUEnergyEfficiencyEnumeration',
    'EnergyEfficiencyEnumeration',
    'EnergyStarEnergyEfficiencyEnumeration',
    'Enumeration',
    'EnumerationMemberMetadata',
    'EventAttendanceModeEnumeration',
    'EventStatusType',
    'FulfillmentTypeEnumeration',
    'GameAvailabilityEnumeration',
    'GamePlayMode',
    'GameServerStatus',
    'GenderType',
    'GovernmentBenefitsType',
    'HealthAspectEnumeration',
    'IPTCDigitalSourceEnumeration',
    'ITNonprofitType',
    'IncentiveQualifiedExpenseType',
    'IncentiveStatus',
    'IncentiveType',
    'InfectiousAgentClass',
    'ItemAvailability',
    'ItemListOrderType',
    'JsonValue',
    'LegalForceStatus',
    'LegalValueLevel',
    'MapCategoryType',
    'MeasurementMethodEnum',
    'MeasurementTypeEnumeration',
    'MediaEnumeration',
    'MediaManipulationRatingEnumeration',
    'MedicalAudienceType',
    'MedicalDevicePurpose',
    'MedicalEnumeration',
    'MedicalEvidenceLevel',
    'MedicalImagingTechnique',
    'MedicalObservationalStudyDesign',
    'MedicalProcedureType',
    'MedicalSpecialty',
    'MedicalStudyStatus',
    'MedicalTrialDesign',
    'MedicineSystem',
    'MerchantReturnEnumeration',
    'MusicAlbumProductionType',
    'MusicAlbumReleaseType',
    'MusicReleaseFormatType',
    'NLNonprofitType',
    'NonprofitType',
    'OfferItemCondition',
    'OrderStatus',
    'PaymentMethodType',
    'PaymentStatusType',
    'PhysicalActivityCategory',
    'PhysicalExam',
    'PriceComponentTypeEnumeration',
    'PriceTypeEnumeration',
    'ProductReturnEnumeration',
    'PropertyMetadata',
    'PurchaseType',
    'QualitativeValue',
    'RefundTypeEnumeration',
    'ReservationStatusType',
    'RestrictedDiet',
    'ReturnFeesEnumeration',
    'ReturnLabelSourceEnumeration',
    'ReturnMethodEnumeration',
    'RsvpResponseType',
    'SchemaEnum',
    'SchemaMap',
    'SchemaModel',
    'SchemaScalar',
    'SchemaValue',
    'SizeGroupEnumeration',
    'SizeSpecification',
    'SizeSystemEnumeration',
    'Specialty',
    'StatusEnumeration',
    'SteeringPositionValue',
    'TierBenefitEnumeration',
    'UKNonprofitType',
    'USNonprofitType',
    'WarrantyScope',
    'WearableMeasurementTypeEnumeration',
    'WearableSizeGroupEnumeration',
    'WearableSizeSystemEnumeration',
]

def __dir__():
    return sorted(set(globals()) | set(_SCHEMA_BY_EXPORT) | set(_ENUM_NAMES))
