# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from schema_org.base import SchemaEnum

class ActionStatusType(SchemaEnum):
    ACTIVE_ACTION_STATUS = 'https://schema.org/ActiveActionStatus'
    COMPLETED_ACTION_STATUS = 'https://schema.org/CompletedActionStatus'
    FAILED_ACTION_STATUS = 'https://schema.org/FailedActionStatus'
    POTENTIAL_ACTION_STATUS = 'https://schema.org/PotentialActionStatus'

class AdultOrientedEnumeration(SchemaEnum):
    ALCOHOL_CONSIDERATION = 'https://schema.org/AlcoholConsideration'
    DANGEROUS_GOOD_CONSIDERATION = 'https://schema.org/DangerousGoodConsideration'
    HEALTHCARE_CONSIDERATION = 'https://schema.org/HealthcareConsideration'
    NARCOTIC_CONSIDERATION = 'https://schema.org/NarcoticConsideration'
    REDUCED_RELEVANCE_FOR_CHILDREN_CONSIDERATION = 'https://schema.org/ReducedRelevanceForChildrenConsideration'
    SEXUAL_CONTENT_CONSIDERATION = 'https://schema.org/SexualContentConsideration'
    TOBACCO_NICOTINE_CONSIDERATION = 'https://schema.org/TobaccoNicotineConsideration'
    UNCLASSIFIED_ADULT_CONSIDERATION = 'https://schema.org/UnclassifiedAdultConsideration'
    VIOLENCE_CONSIDERATION = 'https://schema.org/ViolenceConsideration'
    WEAPON_CONSIDERATION = 'https://schema.org/WeaponConsideration'

class BedType(SchemaEnum):
    pass

class BoardingPolicyType(SchemaEnum):
    GROUP_BOARDING_POLICY = 'https://schema.org/GroupBoardingPolicy'
    ZONE_BOARDING_POLICY = 'https://schema.org/ZoneBoardingPolicy'

class BodyMeasurementTypeEnumeration(SchemaEnum):
    BODY_MEASUREMENT_ARM = 'https://schema.org/BodyMeasurementArm'
    BODY_MEASUREMENT_BUST = 'https://schema.org/BodyMeasurementBust'
    BODY_MEASUREMENT_CHEST = 'https://schema.org/BodyMeasurementChest'
    BODY_MEASUREMENT_FOOT = 'https://schema.org/BodyMeasurementFoot'
    BODY_MEASUREMENT_HAND = 'https://schema.org/BodyMeasurementHand'
    BODY_MEASUREMENT_HEAD = 'https://schema.org/BodyMeasurementHead'
    BODY_MEASUREMENT_HEIGHT = 'https://schema.org/BodyMeasurementHeight'
    BODY_MEASUREMENT_HIPS = 'https://schema.org/BodyMeasurementHips'
    BODY_MEASUREMENT_INSIDE_LEG = 'https://schema.org/BodyMeasurementInsideLeg'
    BODY_MEASUREMENT_NECK = 'https://schema.org/BodyMeasurementNeck'
    BODY_MEASUREMENT_UNDERBUST = 'https://schema.org/BodyMeasurementUnderbust'
    BODY_MEASUREMENT_WAIST = 'https://schema.org/BodyMeasurementWaist'
    BODY_MEASUREMENT_WEIGHT = 'https://schema.org/BodyMeasurementWeight'

class BookFormatType(SchemaEnum):
    AUDIOBOOK_FORMAT = 'https://schema.org/AudiobookFormat'
    E_BOOK = 'https://schema.org/EBook'
    GRAPHIC_NOVEL = 'https://schema.org/GraphicNovel'
    HARDCOVER = 'https://schema.org/Hardcover'
    PAMPHLET = 'https://schema.org/Pamphlet'
    PAPERBACK = 'https://schema.org/Paperback'

class BusinessEntityType(SchemaEnum):
    pass

class BusinessFunction(SchemaEnum):
    pass

class CarUsageType(SchemaEnum):
    DRIVING_SCHOOL_VEHICLE_USAGE = 'https://schema.org/DrivingSchoolVehicleUsage'
    RENTAL_VEHICLE_USAGE = 'https://schema.org/RentalVehicleUsage'
    TAXI_VEHICLE_USAGE = 'https://schema.org/TaxiVehicleUsage'

class CertificationStatusEnumeration(SchemaEnum):
    CERTIFICATION_ACTIVE = 'https://schema.org/CertificationActive'
    CERTIFICATION_INACTIVE = 'https://schema.org/CertificationInactive'

class ContactPointOption(SchemaEnum):
    HEARING_IMPAIRED_SUPPORTED = 'https://schema.org/HearingImpairedSupported'
    TOLL_FREE = 'https://schema.org/TollFree'

class DENonprofitType(SchemaEnum):
    DE_COOPERATIVE_CHARITY = 'https://schema.org/DECooperativeCharity'
    DE_FOUNDATION_CHARITY = 'https://schema.org/DEFoundationCharity'
    DE_JOINT_STOCK_COMPANY_CHARITY = 'https://schema.org/DEJointStockCompanyCharity'
    DE_LIMITED_LIABILITY_CHARITY = 'https://schema.org/DELimitedLiabilityCharity'
    DE_NOT_REGISTERED_ASSOCIATION_CHARITY = 'https://schema.org/DENotRegisteredAssociationCharity'
    DE_PUBLIC_CHARITY = 'https://schema.org/DEPublicCharity'
    DE_REGISTERED_ASSOCIATION_CHARITY = 'https://schema.org/DERegisteredAssociationCharity'

class DayOfWeek(SchemaEnum):
    FRIDAY = 'https://schema.org/Friday'
    MONDAY = 'https://schema.org/Monday'
    PUBLIC_HOLIDAYS = 'https://schema.org/PublicHolidays'
    SATURDAY = 'https://schema.org/Saturday'
    SUNDAY = 'https://schema.org/Sunday'
    THURSDAY = 'https://schema.org/Thursday'
    TUESDAY = 'https://schema.org/Tuesday'
    WEDNESDAY = 'https://schema.org/Wednesday'

class DeliveryMethod(SchemaEnum):
    LOCKER_DELIVERY = 'https://schema.org/LockerDelivery'
    ON_SITE_PICKUP = 'https://schema.org/OnSitePickup'
    PARCEL_SERVICE = 'https://schema.org/ParcelService'

class DigitalDocumentPermissionType(SchemaEnum):
    COMMENT_PERMISSION = 'https://schema.org/CommentPermission'
    READ_PERMISSION = 'https://schema.org/ReadPermission'
    WRITE_PERMISSION = 'https://schema.org/WritePermission'

class DigitalPlatformEnumeration(SchemaEnum):
    ANDROID_PLATFORM = 'https://schema.org/AndroidPlatform'
    DESKTOP_WEB_PLATFORM = 'https://schema.org/DesktopWebPlatform'
    GENERIC_WEB_PLATFORM = 'https://schema.org/GenericWebPlatform'
    IOS_PLATFORM = 'https://schema.org/IOSPlatform'
    MOBILE_WEB_PLATFORM = 'https://schema.org/MobileWebPlatform'

class DriveWheelConfigurationValue(SchemaEnum):
    ALL_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/AllWheelDriveConfiguration'
    FOUR_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/FourWheelDriveConfiguration'
    FRONT_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/FrontWheelDriveConfiguration'
    REAR_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/RearWheelDriveConfiguration'

class DrugCostCategory(SchemaEnum):
    REIMBURSEMENT_CAP = 'https://schema.org/ReimbursementCap'
    RETAIL = 'https://schema.org/Retail'
    WHOLESALE = 'https://schema.org/Wholesale'

class DrugPregnancyCategory(SchemaEnum):
    FD_ACATEGORY_A = 'https://schema.org/FDAcategoryA'
    FD_ACATEGORY_B = 'https://schema.org/FDAcategoryB'
    FD_ACATEGORY_C = 'https://schema.org/FDAcategoryC'
    FD_ACATEGORY_D = 'https://schema.org/FDAcategoryD'
    FD_ACATEGORY_X = 'https://schema.org/FDAcategoryX'
    FD_ANOT_EVALUATED = 'https://schema.org/FDAnotEvaluated'

class DrugPrescriptionStatus(SchemaEnum):
    OTC = 'https://schema.org/OTC'
    PRESCRIPTION_ONLY = 'https://schema.org/PrescriptionOnly'

class EUEnergyEfficiencyEnumeration(SchemaEnum):
    EU_ENERGY_EFFICIENCY_CATEGORY_A = 'https://schema.org/EUEnergyEfficiencyCategoryA'
    EU_ENERGY_EFFICIENCY_CATEGORY_A1_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA1Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_A2_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA2Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_A3_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA3Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_B = 'https://schema.org/EUEnergyEfficiencyCategoryB'
    EU_ENERGY_EFFICIENCY_CATEGORY_C = 'https://schema.org/EUEnergyEfficiencyCategoryC'
    EU_ENERGY_EFFICIENCY_CATEGORY_D = 'https://schema.org/EUEnergyEfficiencyCategoryD'
    EU_ENERGY_EFFICIENCY_CATEGORY_E = 'https://schema.org/EUEnergyEfficiencyCategoryE'
    EU_ENERGY_EFFICIENCY_CATEGORY_F = 'https://schema.org/EUEnergyEfficiencyCategoryF'
    EU_ENERGY_EFFICIENCY_CATEGORY_G = 'https://schema.org/EUEnergyEfficiencyCategoryG'

class EnergyEfficiencyEnumeration(SchemaEnum):
    EU_ENERGY_EFFICIENCY_CATEGORY_A = 'https://schema.org/EUEnergyEfficiencyCategoryA'
    EU_ENERGY_EFFICIENCY_CATEGORY_A1_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA1Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_A2_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA2Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_A3_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA3Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_B = 'https://schema.org/EUEnergyEfficiencyCategoryB'
    EU_ENERGY_EFFICIENCY_CATEGORY_C = 'https://schema.org/EUEnergyEfficiencyCategoryC'
    EU_ENERGY_EFFICIENCY_CATEGORY_D = 'https://schema.org/EUEnergyEfficiencyCategoryD'
    EU_ENERGY_EFFICIENCY_CATEGORY_E = 'https://schema.org/EUEnergyEfficiencyCategoryE'
    EU_ENERGY_EFFICIENCY_CATEGORY_F = 'https://schema.org/EUEnergyEfficiencyCategoryF'
    EU_ENERGY_EFFICIENCY_CATEGORY_G = 'https://schema.org/EUEnergyEfficiencyCategoryG'
    ENERGY_STAR_CERTIFIED = 'https://schema.org/EnergyStarCertified'

class EnergyStarEnergyEfficiencyEnumeration(SchemaEnum):
    ENERGY_STAR_CERTIFIED = 'https://schema.org/EnergyStarCertified'

class Enumeration(SchemaEnum):
    ABDOMEN = 'https://schema.org/Abdomen'
    ACTIVATION_FEE = 'https://schema.org/ActivationFee'
    ACTIVE_ACTION_STATUS = 'https://schema.org/ActiveActionStatus'
    ACTIVE_NOT_RECRUITING = 'https://schema.org/ActiveNotRecruiting'
    AEROBIC_ACTIVITY = 'https://schema.org/AerobicActivity'
    ALBUM_RELEASE = 'https://schema.org/AlbumRelease'
    ALCOHOL_CONSIDERATION = 'https://schema.org/AlcoholConsideration'
    ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/AlgorithmicMediaDigitalSource'
    ALGORITHMICALLY_ENHANCED_DIGITAL_SOURCE = 'https://schema.org/AlgorithmicallyEnhancedDigitalSource'
    ALL_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/AllWheelDriveConfiguration'
    ALLERGIES_HEALTH_ASPECT = 'https://schema.org/AllergiesHealthAspect'
    ANAEROBIC_ACTIVITY = 'https://schema.org/AnaerobicActivity'
    ANDROID_PLATFORM = 'https://schema.org/AndroidPlatform'
    ANESTHESIA = 'https://schema.org/Anesthesia'
    APPEARANCE = 'https://schema.org/Appearance'
    AUDIOBOOK_FORMAT = 'https://schema.org/AudiobookFormat'
    AUTHORITATIVE_LEGAL_VALUE = 'https://schema.org/AuthoritativeLegalValue'
    AYURVEDIC = 'https://schema.org/Ayurvedic'
    BACK_ORDER = 'https://schema.org/BackOrder'
    BACTERIA = 'https://schema.org/Bacteria'
    BALANCE = 'https://schema.org/Balance'
    BASIC_INCOME = 'https://schema.org/BasicIncome'
    BENEFITS_HEALTH_ASPECT = 'https://schema.org/BenefitsHealthAspect'
    BODY_MEASUREMENT_ARM = 'https://schema.org/BodyMeasurementArm'
    BODY_MEASUREMENT_BUST = 'https://schema.org/BodyMeasurementBust'
    BODY_MEASUREMENT_CHEST = 'https://schema.org/BodyMeasurementChest'
    BODY_MEASUREMENT_FOOT = 'https://schema.org/BodyMeasurementFoot'
    BODY_MEASUREMENT_HAND = 'https://schema.org/BodyMeasurementHand'
    BODY_MEASUREMENT_HEAD = 'https://schema.org/BodyMeasurementHead'
    BODY_MEASUREMENT_HEIGHT = 'https://schema.org/BodyMeasurementHeight'
    BODY_MEASUREMENT_HIPS = 'https://schema.org/BodyMeasurementHips'
    BODY_MEASUREMENT_INSIDE_LEG = 'https://schema.org/BodyMeasurementInsideLeg'
    BODY_MEASUREMENT_NECK = 'https://schema.org/BodyMeasurementNeck'
    BODY_MEASUREMENT_UNDERBUST = 'https://schema.org/BodyMeasurementUnderbust'
    BODY_MEASUREMENT_WAIST = 'https://schema.org/BodyMeasurementWaist'
    BODY_MEASUREMENT_WEIGHT = 'https://schema.org/BodyMeasurementWeight'
    BROADCAST_RELEASE = 'https://schema.org/BroadcastRelease'
    BUSINESS_SUPPORT = 'https://schema.org/BusinessSupport'
    BY_BANK_TRANSFER_IN_ADVANCE = 'https://schema.org/ByBankTransferInAdvance'
    BY_INVOICE = 'https://schema.org/ByInvoice'
    CD_FORMAT = 'https://schema.org/CDFormat'
    COD = 'https://schema.org/COD'
    CT = 'https://schema.org/CT'
    CARDIOVASCULAR = 'https://schema.org/Cardiovascular'
    CARDIOVASCULAR_EXAM = 'https://schema.org/CardiovascularExam'
    CASE_SERIES = 'https://schema.org/CaseSeries'
    CASH = 'https://schema.org/Cash'
    CASSETTE_FORMAT = 'https://schema.org/CassetteFormat'
    CAUSES_HEALTH_ASPECT = 'https://schema.org/CausesHealthAspect'
    CERTIFICATION_ACTIVE = 'https://schema.org/CertificationActive'
    CERTIFICATION_INACTIVE = 'https://schema.org/CertificationInactive'
    CHARITABLE_INCORPORATED_ORGANIZATION = 'https://schema.org/CharitableIncorporatedOrganization'
    CHECK_IN_ADVANCE = 'https://schema.org/CheckInAdvance'
    CHIROPRACTIC = 'https://schema.org/Chiropractic'
    CLEANING_FEE = 'https://schema.org/CleaningFee'
    CLINICIAN = 'https://schema.org/Clinician'
    CO_OP = 'https://schema.org/CoOp'
    COHORT_STUDY = 'https://schema.org/CohortStudy'
    COMMENT_PERMISSION = 'https://schema.org/CommentPermission'
    COMMUNITY_HEALTH = 'https://schema.org/CommunityHealth'
    COMPILATION_ALBUM = 'https://schema.org/CompilationAlbum'
    COMPLETED = 'https://schema.org/Completed'
    COMPLETED_ACTION_STATUS = 'https://schema.org/CompletedActionStatus'
    COMPOSITE_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/CompositeCaptureDigitalSource'
    COMPOSITE_DIGITAL_SOURCE = 'https://schema.org/CompositeDigitalSource'
    COMPOSITE_SYNTHETIC_DIGITAL_SOURCE = 'https://schema.org/CompositeSyntheticDigitalSource'
    COMPOSITE_WITH_TRAINED_ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/CompositeWithTrainedAlgorithmicMediaDigitalSource'
    CONTAGIOUSNESS_HEALTH_ASPECT = 'https://schema.org/ContagiousnessHealthAspect'
    CROSS_SECTIONAL = 'https://schema.org/CrossSectional'
    DE_COOPERATIVE_CHARITY = 'https://schema.org/DECooperativeCharity'
    DE_FOUNDATION_CHARITY = 'https://schema.org/DEFoundationCharity'
    DE_JOINT_STOCK_COMPANY_CHARITY = 'https://schema.org/DEJointStockCompanyCharity'
    DE_LIMITED_LIABILITY_CHARITY = 'https://schema.org/DELimitedLiabilityCharity'
    DE_NOT_REGISTERED_ASSOCIATION_CHARITY = 'https://schema.org/DENotRegisteredAssociationCharity'
    DE_PUBLIC_CHARITY = 'https://schema.org/DEPublicCharity'
    DE_REGISTERED_ASSOCIATION_CHARITY = 'https://schema.org/DERegisteredAssociationCharity'
    DJ_MIX_ALBUM = 'https://schema.org/DJMixAlbum'
    DVD_FORMAT = 'https://schema.org/DVDFormat'
    DAMAGED_CONDITION = 'https://schema.org/DamagedCondition'
    DANGEROUS_GOOD_CONSIDERATION = 'https://schema.org/DangerousGoodConsideration'
    DATA_DRIVEN_MEDIA_DIGITAL_SOURCE = 'https://schema.org/DataDrivenMediaDigitalSource'
    DECONTEXTUALIZED_CONTENT = 'https://schema.org/DecontextualizedContent'
    DEFINITIVE_LEGAL_VALUE = 'https://schema.org/DefinitiveLegalValue'
    DEMO_ALBUM = 'https://schema.org/DemoAlbum'
    DEMO_GAME_AVAILABILITY = 'https://schema.org/DemoGameAvailability'
    DENTISTRY = 'https://schema.org/Dentistry'
    DERMATOLOGIC = 'https://schema.org/Dermatologic'
    DERMATOLOGY = 'https://schema.org/Dermatology'
    DESKTOP_WEB_PLATFORM = 'https://schema.org/DesktopWebPlatform'
    DIABETIC_DIET = 'https://schema.org/DiabeticDiet'
    DIAGNOSTIC = 'https://schema.org/Diagnostic'
    DIET_NUTRITION = 'https://schema.org/DietNutrition'
    DIGITAL_ART_DIGITAL_SOURCE = 'https://schema.org/DigitalArtDigitalSource'
    DIGITAL_AUDIO_TAPE_FORMAT = 'https://schema.org/DigitalAudioTapeFormat'
    DIGITAL_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/DigitalCaptureDigitalSource'
    DIGITAL_FORMAT = 'https://schema.org/DigitalFormat'
    DIRECT_DEBIT = 'https://schema.org/DirectDebit'
    DISABILITY_SUPPORT = 'https://schema.org/DisabilitySupport'
    DISCONTINUED = 'https://schema.org/Discontinued'
    DISTANCE_FEE = 'https://schema.org/DistanceFee'
    DOUBLE_BLINDED_TRIAL = 'https://schema.org/DoubleBlindedTrial'
    DOWNPAYMENT = 'https://schema.org/Downpayment'
    DRIVING_SCHOOL_VEHICLE_USAGE = 'https://schema.org/DrivingSchoolVehicleUsage'
    E_BOOK = 'https://schema.org/EBook'
    EP_RELEASE = 'https://schema.org/EPRelease'
    EU_ENERGY_EFFICIENCY_CATEGORY_A = 'https://schema.org/EUEnergyEfficiencyCategoryA'
    EU_ENERGY_EFFICIENCY_CATEGORY_A1_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA1Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_A2_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA2Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_A3_PLUS = 'https://schema.org/EUEnergyEfficiencyCategoryA3Plus'
    EU_ENERGY_EFFICIENCY_CATEGORY_B = 'https://schema.org/EUEnergyEfficiencyCategoryB'
    EU_ENERGY_EFFICIENCY_CATEGORY_C = 'https://schema.org/EUEnergyEfficiencyCategoryC'
    EU_ENERGY_EFFICIENCY_CATEGORY_D = 'https://schema.org/EUEnergyEfficiencyCategoryD'
    EU_ENERGY_EFFICIENCY_CATEGORY_E = 'https://schema.org/EUEnergyEfficiencyCategoryE'
    EU_ENERGY_EFFICIENCY_CATEGORY_F = 'https://schema.org/EUEnergyEfficiencyCategoryF'
    EU_ENERGY_EFFICIENCY_CATEGORY_G = 'https://schema.org/EUEnergyEfficiencyCategoryG'
    EAR = 'https://schema.org/Ear'
    EDITED_OR_CROPPED_CONTENT = 'https://schema.org/EditedOrCroppedContent'
    EFFECTIVENESS_HEALTH_ASPECT = 'https://schema.org/EffectivenessHealthAspect'
    EMERGENCY = 'https://schema.org/Emergency'
    ENDOCRINE = 'https://schema.org/Endocrine'
    ENERGY_STAR_CERTIFIED = 'https://schema.org/EnergyStarCertified'
    ENROLLING_BY_INVITATION = 'https://schema.org/EnrollingByInvitation'
    EVENT_CANCELLED = 'https://schema.org/EventCancelled'
    EVENT_MOVED_ONLINE = 'https://schema.org/EventMovedOnline'
    EVENT_POSTPONED = 'https://schema.org/EventPostponed'
    EVENT_RESCHEDULED = 'https://schema.org/EventRescheduled'
    EVENT_SCHEDULED = 'https://schema.org/EventScheduled'
    EVIDENCE_LEVEL_A = 'https://schema.org/EvidenceLevelA'
    EVIDENCE_LEVEL_B = 'https://schema.org/EvidenceLevelB'
    EVIDENCE_LEVEL_C = 'https://schema.org/EvidenceLevelC'
    EXAMPLE_MEASUREMENT_METHOD_ENUM = 'https://schema.org/ExampleMeasurementMethodEnum'
    EXCHANGE_REFUND = 'https://schema.org/ExchangeRefund'
    EYE = 'https://schema.org/Eye'
    FD_ACATEGORY_A = 'https://schema.org/FDAcategoryA'
    FD_ACATEGORY_B = 'https://schema.org/FDAcategoryB'
    FD_ACATEGORY_C = 'https://schema.org/FDAcategoryC'
    FD_ACATEGORY_D = 'https://schema.org/FDAcategoryD'
    FD_ACATEGORY_X = 'https://schema.org/FDAcategoryX'
    FD_ANOT_EVALUATED = 'https://schema.org/FDAnotEvaluated'
    FAILED_ACTION_STATUS = 'https://schema.org/FailedActionStatus'
    FEMALE = 'https://schema.org/Female'
    FLEXIBILITY = 'https://schema.org/Flexibility'
    FOUR_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/FourWheelDriveConfiguration'
    FREE_RETURN = 'https://schema.org/FreeReturn'
    FRIDAY = 'https://schema.org/Friday'
    FRONT_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/FrontWheelDriveConfiguration'
    FULFILLMENT_TYPE_COLLECTION_POINT = 'https://schema.org/FulfillmentTypeCollectionPoint'
    FULFILLMENT_TYPE_DELIVERY = 'https://schema.org/FulfillmentTypeDelivery'
    FULFILLMENT_TYPE_PICKUP_DROPOFF = 'https://schema.org/FulfillmentTypePickupDropoff'
    FULFILLMENT_TYPE_PICKUP_IN_STORE = 'https://schema.org/FulfillmentTypePickupInStore'
    FULFILLMENT_TYPE_SCHEDULED_DELIVERY = 'https://schema.org/FulfillmentTypeScheduledDelivery'
    FULL_GAME_AVAILABILITY = 'https://schema.org/FullGameAvailability'
    FULL_REFUND = 'https://schema.org/FullRefund'
    FUNGUS = 'https://schema.org/Fungus'
    GASTROENTEROLOGIC = 'https://schema.org/Gastroenterologic'
    GENERIC_WEB_PLATFORM = 'https://schema.org/GenericWebPlatform'
    GENETIC = 'https://schema.org/Genetic'
    GENITOURINARY = 'https://schema.org/Genitourinary'
    GERIATRIC = 'https://schema.org/Geriatric'
    GETTING_ACCESS_HEALTH_ASPECT = 'https://schema.org/GettingAccessHealthAspect'
    GLUTEN_FREE_DIET = 'https://schema.org/GlutenFreeDiet'
    GRAPHIC_NOVEL = 'https://schema.org/GraphicNovel'
    GROUP_BOARDING_POLICY = 'https://schema.org/GroupBoardingPolicy'
    GYNECOLOGIC = 'https://schema.org/Gynecologic'
    HALAL_DIET = 'https://schema.org/HalalDiet'
    HARDCOVER = 'https://schema.org/Hardcover'
    HEAD = 'https://schema.org/Head'
    HEALTH_CARE = 'https://schema.org/HealthCare'
    HEALTHCARE_CONSIDERATION = 'https://schema.org/HealthcareConsideration'
    HEARING_IMPAIRED_SUPPORTED = 'https://schema.org/HearingImpairedSupported'
    HEMATOLOGIC = 'https://schema.org/Hematologic'
    HINDU_DIET = 'https://schema.org/HinduDiet'
    HOMEOPATHIC = 'https://schema.org/Homeopathic'
    HOW_IT_WORKS_HEALTH_ASPECT = 'https://schema.org/HowItWorksHealthAspect'
    HOW_OR_WHERE_HEALTH_ASPECT = 'https://schema.org/HowOrWhereHealthAspect'
    IOS_PLATFORM = 'https://schema.org/IOSPlatform'
    IT_COOPERATIVE_CHARITY = 'https://schema.org/ITCooperativeCharity'
    IT_MUTUAL_AID_CHARITY = 'https://schema.org/ITMutualAidCharity'
    IT_SOCIAL_COMPANY_CHARITY = 'https://schema.org/ITSocialCompanyCharity'
    IT_SOCIAL_PROMOTION_CHARITY = 'https://schema.org/ITSocialPromotionCharity'
    IT_SPORT_COMPANY_CHARITY = 'https://schema.org/ITSportCompanyCharity'
    IT_VOLUNTEER_ASSOCIATION_CHARITY = 'https://schema.org/ITVolunteerAssociationCharity'
    IN_FORCE = 'https://schema.org/InForce'
    IN_STOCK = 'https://schema.org/InStock'
    IN_STORE_ONLY = 'https://schema.org/InStoreOnly'
    IN_STORE_PREPAY = 'https://schema.org/InStorePrepay'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_GOODS_ONLY = 'https://schema.org/IncentiveQualifiedExpenseTypeGoodsOnly'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_GOODS_OR_SERVICES = 'https://schema.org/IncentiveQualifiedExpenseTypeGoodsOrServices'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_SERVICES_ONLY = 'https://schema.org/IncentiveQualifiedExpenseTypeServicesOnly'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_UTILITY_BILL = 'https://schema.org/IncentiveQualifiedExpenseTypeUtilityBill'
    INCENTIVE_STATUS_ACTIVE = 'https://schema.org/IncentiveStatusActive'
    INCENTIVE_STATUS_IN_DEVELOPMENT = 'https://schema.org/IncentiveStatusInDevelopment'
    INCENTIVE_STATUS_ON_HOLD = 'https://schema.org/IncentiveStatusOnHold'
    INCENTIVE_STATUS_RETIRED = 'https://schema.org/IncentiveStatusRetired'
    INCENTIVE_TYPE_LOAN = 'https://schema.org/IncentiveTypeLoan'
    INCENTIVE_TYPE_REBATE_OR_SUBSIDY = 'https://schema.org/IncentiveTypeRebateOrSubsidy'
    INCENTIVE_TYPE_TAX_CREDIT = 'https://schema.org/IncentiveTypeTaxCredit'
    INCENTIVE_TYPE_TAX_DEDUCTION = 'https://schema.org/IncentiveTypeTaxDeduction'
    INCENTIVE_TYPE_TAX_WAIVER = 'https://schema.org/IncentiveTypeTaxWaiver'
    INFECTIOUS = 'https://schema.org/Infectious'
    INGREDIENTS_HEALTH_ASPECT = 'https://schema.org/IngredientsHealthAspect'
    INSTALLMENT = 'https://schema.org/Installment'
    INTERNATIONAL_TRIAL = 'https://schema.org/InternationalTrial'
    INVOICE_PRICE = 'https://schema.org/InvoicePrice'
    ITEM_LIST_ORDER_ASCENDING = 'https://schema.org/ItemListOrderAscending'
    ITEM_LIST_ORDER_DESCENDING = 'https://schema.org/ItemListOrderDescending'
    ITEM_LIST_UNORDERED = 'https://schema.org/ItemListUnordered'
    KEEP_PRODUCT = 'https://schema.org/KeepProduct'
    KOSHER_DIET = 'https://schema.org/KosherDiet'
    LABORATORY_SCIENCE = 'https://schema.org/LaboratoryScience'
    LASER_DISC_FORMAT = 'https://schema.org/LaserDiscFormat'
    LEFT_HAND_DRIVING = 'https://schema.org/LeftHandDriving'
    LEISURE_TIME_ACTIVITY = 'https://schema.org/LeisureTimeActivity'
    LIMITED_AVAILABILITY = 'https://schema.org/LimitedAvailability'
    LIMITED_BY_GUARANTEE_CHARITY = 'https://schema.org/LimitedByGuaranteeCharity'
    LIST_PRICE = 'https://schema.org/ListPrice'
    LIVE_ALBUM = 'https://schema.org/LiveAlbum'
    LIVING_WITH_HEALTH_ASPECT = 'https://schema.org/LivingWithHealthAspect'
    LOCKER_DELIVERY = 'https://schema.org/LockerDelivery'
    LONGITUDINAL = 'https://schema.org/Longitudinal'
    LOW_CALORIE_DIET = 'https://schema.org/LowCalorieDiet'
    LOW_FAT_DIET = 'https://schema.org/LowFatDiet'
    LOW_LACTOSE_DIET = 'https://schema.org/LowLactoseDiet'
    LOW_SALT_DIET = 'https://schema.org/LowSaltDiet'
    LUNG = 'https://schema.org/Lung'
    MRI = 'https://schema.org/MRI'
    MSRP = 'https://schema.org/MSRP'
    MADE_TO_ORDER = 'https://schema.org/MadeToOrder'
    MALE = 'https://schema.org/Male'
    MAY_TREAT_HEALTH_ASPECT = 'https://schema.org/MayTreatHealthAspect'
    MEDICAL_RESEARCHER = 'https://schema.org/MedicalResearcher'
    MERCHANT_RETURN_FINITE_RETURN_WINDOW = 'https://schema.org/MerchantReturnFiniteReturnWindow'
    MERCHANT_RETURN_NOT_PERMITTED = 'https://schema.org/MerchantReturnNotPermitted'
    MERCHANT_RETURN_UNLIMITED_WINDOW = 'https://schema.org/MerchantReturnUnlimitedWindow'
    MERCHANT_RETURN_UNSPECIFIED = 'https://schema.org/MerchantReturnUnspecified'
    MIDWIFERY = 'https://schema.org/Midwifery'
    MINIMUM_ADVERTISED_PRICE = 'https://schema.org/MinimumAdvertisedPrice'
    MINOR_HUMAN_EDITS_DIGITAL_SOURCE = 'https://schema.org/MinorHumanEditsDigitalSource'
    MISCONCEPTIONS_HEALTH_ASPECT = 'https://schema.org/MisconceptionsHealthAspect'
    MIXED_EVENT_ATTENDANCE_MODE = 'https://schema.org/MixedEventAttendanceMode'
    MIXTAPE_ALBUM = 'https://schema.org/MixtapeAlbum'
    MOBILE_WEB_PLATFORM = 'https://schema.org/MobileWebPlatform'
    MONDAY = 'https://schema.org/Monday'
    MULTI_CENTER_TRIAL = 'https://schema.org/MultiCenterTrial'
    MULTI_FRAME_COMPUTATIONAL_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/MultiFrameComputationalCaptureDigitalSource'
    MULTI_PLAYER = 'https://schema.org/MultiPlayer'
    MULTICELLULAR_PARASITE = 'https://schema.org/MulticellularParasite'
    MUSCULOSKELETAL = 'https://schema.org/Musculoskeletal'
    MUSCULOSKELETAL_EXAM = 'https://schema.org/MusculoskeletalExam'
    NARCOTIC_CONSIDERATION = 'https://schema.org/NarcoticConsideration'
    NECK = 'https://schema.org/Neck'
    NEGATIVE_FILM_DIGITAL_SOURCE = 'https://schema.org/NegativeFilmDigitalSource'
    NEURO = 'https://schema.org/Neuro'
    NEUROLOGIC = 'https://schema.org/Neurologic'
    NEW_CONDITION = 'https://schema.org/NewCondition'
    NONINVASIVE_PROCEDURE = 'https://schema.org/NoninvasiveProcedure'
    NONPROFIT501A = 'https://schema.org/Nonprofit501a'
    NONPROFIT501C1 = 'https://schema.org/Nonprofit501c1'
    NONPROFIT501C10 = 'https://schema.org/Nonprofit501c10'
    NONPROFIT501C11 = 'https://schema.org/Nonprofit501c11'
    NONPROFIT501C12 = 'https://schema.org/Nonprofit501c12'
    NONPROFIT501C13 = 'https://schema.org/Nonprofit501c13'
    NONPROFIT501C14 = 'https://schema.org/Nonprofit501c14'
    NONPROFIT501C15 = 'https://schema.org/Nonprofit501c15'
    NONPROFIT501C16 = 'https://schema.org/Nonprofit501c16'
    NONPROFIT501C17 = 'https://schema.org/Nonprofit501c17'
    NONPROFIT501C18 = 'https://schema.org/Nonprofit501c18'
    NONPROFIT501C19 = 'https://schema.org/Nonprofit501c19'
    NONPROFIT501C2 = 'https://schema.org/Nonprofit501c2'
    NONPROFIT501C20 = 'https://schema.org/Nonprofit501c20'
    NONPROFIT501C21 = 'https://schema.org/Nonprofit501c21'
    NONPROFIT501C22 = 'https://schema.org/Nonprofit501c22'
    NONPROFIT501C23 = 'https://schema.org/Nonprofit501c23'
    NONPROFIT501C24 = 'https://schema.org/Nonprofit501c24'
    NONPROFIT501C25 = 'https://schema.org/Nonprofit501c25'
    NONPROFIT501C26 = 'https://schema.org/Nonprofit501c26'
    NONPROFIT501C27 = 'https://schema.org/Nonprofit501c27'
    NONPROFIT501C28 = 'https://schema.org/Nonprofit501c28'
    NONPROFIT501C3 = 'https://schema.org/Nonprofit501c3'
    NONPROFIT501C4 = 'https://schema.org/Nonprofit501c4'
    NONPROFIT501C5 = 'https://schema.org/Nonprofit501c5'
    NONPROFIT501C6 = 'https://schema.org/Nonprofit501c6'
    NONPROFIT501C7 = 'https://schema.org/Nonprofit501c7'
    NONPROFIT501C8 = 'https://schema.org/Nonprofit501c8'
    NONPROFIT501C9 = 'https://schema.org/Nonprofit501c9'
    NONPROFIT501D = 'https://schema.org/Nonprofit501d'
    NONPROFIT501E = 'https://schema.org/Nonprofit501e'
    NONPROFIT501F = 'https://schema.org/Nonprofit501f'
    NONPROFIT501K = 'https://schema.org/Nonprofit501k'
    NONPROFIT501N = 'https://schema.org/Nonprofit501n'
    NONPROFIT501Q = 'https://schema.org/Nonprofit501q'
    NONPROFIT527 = 'https://schema.org/Nonprofit527'
    NONPROFIT_ANBI = 'https://schema.org/NonprofitANBI'
    NONPROFIT_SBBI = 'https://schema.org/NonprofitSBBI'
    NOSE = 'https://schema.org/Nose'
    NOT_IN_FORCE = 'https://schema.org/NotInForce'
    NOT_YET_RECRUITING = 'https://schema.org/NotYetRecruiting'
    NURSING = 'https://schema.org/Nursing'
    OTC = 'https://schema.org/OTC'
    OBSERVATIONAL = 'https://schema.org/Observational'
    OBSTETRIC = 'https://schema.org/Obstetric'
    OCCUPATIONAL_ACTIVITY = 'https://schema.org/OccupationalActivity'
    OFFICIAL_LEGAL_VALUE = 'https://schema.org/OfficialLegalValue'
    OFFLINE_EVENT_ATTENDANCE_MODE = 'https://schema.org/OfflineEventAttendanceMode'
    OFFLINE_PERMANENTLY = 'https://schema.org/OfflinePermanently'
    OFFLINE_TEMPORARILY = 'https://schema.org/OfflineTemporarily'
    ON_SITE_PICKUP = 'https://schema.org/OnSitePickup'
    ONCOLOGIC = 'https://schema.org/Oncologic'
    ONE_TIME_PAYMENTS = 'https://schema.org/OneTimePayments'
    ONLINE = 'https://schema.org/Online'
    ONLINE_EVENT_ATTENDANCE_MODE = 'https://schema.org/OnlineEventAttendanceMode'
    ONLINE_FULL = 'https://schema.org/OnlineFull'
    ONLINE_ONLY = 'https://schema.org/OnlineOnly'
    OPEN_TRIAL = 'https://schema.org/OpenTrial'
    OPTOMETRIC = 'https://schema.org/Optometric'
    ORDER_CANCELLED = 'https://schema.org/OrderCancelled'
    ORDER_DELIVERED = 'https://schema.org/OrderDelivered'
    ORDER_IN_TRANSIT = 'https://schema.org/OrderInTransit'
    ORDER_PAYMENT_DUE = 'https://schema.org/OrderPaymentDue'
    ORDER_PICKUP_AVAILABLE = 'https://schema.org/OrderPickupAvailable'
    ORDER_PROBLEM = 'https://schema.org/OrderProblem'
    ORDER_PROCESSING = 'https://schema.org/OrderProcessing'
    ORDER_RETURNED = 'https://schema.org/OrderReturned'
    ORIGINAL_MEDIA_CONTENT = 'https://schema.org/OriginalMediaContent'
    ORIGINAL_SHIPPING_FEES = 'https://schema.org/OriginalShippingFees'
    OSTEOPATHIC = 'https://schema.org/Osteopathic'
    OTOLARYNGOLOGIC = 'https://schema.org/Otolaryngologic'
    OUT_OF_STOCK = 'https://schema.org/OutOfStock'
    OVERVIEW_HEALTH_ASPECT = 'https://schema.org/OverviewHealthAspect'
    PET = 'https://schema.org/PET'
    PAID_LEAVE = 'https://schema.org/PaidLeave'
    PAMPHLET = 'https://schema.org/Pamphlet'
    PAPERBACK = 'https://schema.org/Paperback'
    PARCEL_SERVICE = 'https://schema.org/ParcelService'
    PARENTAL_SUPPORT = 'https://schema.org/ParentalSupport'
    PARKING_MAP = 'https://schema.org/ParkingMap'
    PARTIALLY_IN_FORCE = 'https://schema.org/PartiallyInForce'
    PATHOLOGY = 'https://schema.org/Pathology'
    PATIENT_EXPERIENCE_HEALTH_ASPECT = 'https://schema.org/PatientExperienceHealthAspect'
    PAYMENT_AUTOMATICALLY_APPLIED = 'https://schema.org/PaymentAutomaticallyApplied'
    PAYMENT_COMPLETE = 'https://schema.org/PaymentComplete'
    PAYMENT_DECLINED = 'https://schema.org/PaymentDeclined'
    PAYMENT_DUE = 'https://schema.org/PaymentDue'
    PAYMENT_PAST_DUE = 'https://schema.org/PaymentPastDue'
    PEDIATRIC = 'https://schema.org/Pediatric'
    PERCUTANEOUS_PROCEDURE = 'https://schema.org/PercutaneousProcedure'
    PHARMACY_SPECIALTY = 'https://schema.org/PharmacySpecialty'
    PHONE_CARRIER_PAYMENT = 'https://schema.org/PhoneCarrierPayment'
    PHYSIOTHERAPY = 'https://schema.org/Physiotherapy'
    PLACEBO_CONTROLLED_TRIAL = 'https://schema.org/PlaceboControlledTrial'
    PLASTIC_SURGERY = 'https://schema.org/PlasticSurgery'
    PODIATRIC = 'https://schema.org/Podiatric'
    POSITIVE_FILM_DIGITAL_SOURCE = 'https://schema.org/PositiveFilmDigitalSource'
    POTENTIAL_ACTION_STATUS = 'https://schema.org/PotentialActionStatus'
    PRE_ORDER = 'https://schema.org/PreOrder'
    PRE_SALE = 'https://schema.org/PreSale'
    PREGNANCY_HEALTH_ASPECT = 'https://schema.org/PregnancyHealthAspect'
    PRESCRIPTION_ONLY = 'https://schema.org/PrescriptionOnly'
    PREVENTION_HEALTH_ASPECT = 'https://schema.org/PreventionHealthAspect'
    PRIMARY_CARE = 'https://schema.org/PrimaryCare'
    PRINT_DIGITAL_SOURCE = 'https://schema.org/PrintDigitalSource'
    PRION = 'https://schema.org/Prion'
    PRODUCT_RETURN_FINITE_RETURN_WINDOW = 'https://schema.org/ProductReturnFiniteReturnWindow'
    PRODUCT_RETURN_NOT_PERMITTED = 'https://schema.org/ProductReturnNotPermitted'
    PRODUCT_RETURN_UNLIMITED_WINDOW = 'https://schema.org/ProductReturnUnlimitedWindow'
    PRODUCT_RETURN_UNSPECIFIED = 'https://schema.org/ProductReturnUnspecified'
    PROGNOSIS_HEALTH_ASPECT = 'https://schema.org/PrognosisHealthAspect'
    PROTOZOA = 'https://schema.org/Protozoa'
    PSYCHIATRIC = 'https://schema.org/Psychiatric'
    PUBLIC_HEALTH = 'https://schema.org/PublicHealth'
    PUBLIC_HOLIDAYS = 'https://schema.org/PublicHolidays'
    PULMONARY = 'https://schema.org/Pulmonary'
    PURCHASE_TYPE_LEASE = 'https://schema.org/PurchaseTypeLease'
    PURCHASE_TYPE_NEW_PURCHASE = 'https://schema.org/PurchaseTypeNewPurchase'
    PURCHASE_TYPE_TRADE_IN = 'https://schema.org/PurchaseTypeTradeIn'
    PURCHASE_TYPE_USED_PURCHASE = 'https://schema.org/PurchaseTypeUsedPurchase'
    RADIOGRAPHY = 'https://schema.org/Radiography'
    RANDOMIZED_TRIAL = 'https://schema.org/RandomizedTrial'
    READ_PERMISSION = 'https://schema.org/ReadPermission'
    REAR_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/RearWheelDriveConfiguration'
    RECRUITING = 'https://schema.org/Recruiting'
    REDUCED_RELEVANCE_FOR_CHILDREN_CONSIDERATION = 'https://schema.org/ReducedRelevanceForChildrenConsideration'
    REFURBISHED_CONDITION = 'https://schema.org/RefurbishedCondition'
    REGISTRY = 'https://schema.org/Registry'
    REGULAR_PRICE = 'https://schema.org/RegularPrice'
    REIMBURSEMENT_CAP = 'https://schema.org/ReimbursementCap'
    RELATED_TOPICS_HEALTH_ASPECT = 'https://schema.org/RelatedTopicsHealthAspect'
    REMIX_ALBUM = 'https://schema.org/RemixAlbum'
    RENAL = 'https://schema.org/Renal'
    RENTAL_VEHICLE_USAGE = 'https://schema.org/RentalVehicleUsage'
    RESERVATION_CANCELLED = 'https://schema.org/ReservationCancelled'
    RESERVATION_CONFIRMED = 'https://schema.org/ReservationConfirmed'
    RESERVATION_HOLD = 'https://schema.org/ReservationHold'
    RESERVATION_PENDING = 'https://schema.org/ReservationPending'
    RESERVED = 'https://schema.org/Reserved'
    RESPIRATORY_THERAPY = 'https://schema.org/RespiratoryTherapy'
    RESTOCKING_FEES = 'https://schema.org/RestockingFees'
    RESULTS_AVAILABLE = 'https://schema.org/ResultsAvailable'
    RESULTS_NOT_AVAILABLE = 'https://schema.org/ResultsNotAvailable'
    RETAIL = 'https://schema.org/Retail'
    RETURN_AT_KIOSK = 'https://schema.org/ReturnAtKiosk'
    RETURN_BY_MAIL = 'https://schema.org/ReturnByMail'
    RETURN_FEES_CUSTOMER_RESPONSIBILITY = 'https://schema.org/ReturnFeesCustomerResponsibility'
    RETURN_IN_STORE = 'https://schema.org/ReturnInStore'
    RETURN_LABEL_CUSTOMER_RESPONSIBILITY = 'https://schema.org/ReturnLabelCustomerResponsibility'
    RETURN_LABEL_DOWNLOAD_AND_PRINT = 'https://schema.org/ReturnLabelDownloadAndPrint'
    RETURN_LABEL_IN_BOX = 'https://schema.org/ReturnLabelInBox'
    RETURN_SHIPPING_FEES = 'https://schema.org/ReturnShippingFees'
    RHEUMATOLOGIC = 'https://schema.org/Rheumatologic'
    RIGHT_HAND_DRIVING = 'https://schema.org/RightHandDriving'
    RISKS_OR_COMPLICATIONS_HEALTH_ASPECT = 'https://schema.org/RisksOrComplicationsHealthAspect'
    RSVP_RESPONSE_MAYBE = 'https://schema.org/RsvpResponseMaybe'
    RSVP_RESPONSE_NO = 'https://schema.org/RsvpResponseNo'
    RSVP_RESPONSE_YES = 'https://schema.org/RsvpResponseYes'
    SRP = 'https://schema.org/SRP'
    SAFETY_HEALTH_ASPECT = 'https://schema.org/SafetyHealthAspect'
    SALE_PRICE = 'https://schema.org/SalePrice'
    SATIRE_OR_PARODY_CONTENT = 'https://schema.org/SatireOrParodyContent'
    SATURDAY = 'https://schema.org/Saturday'
    SCREEN_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/ScreenCaptureDigitalSource'
    SCREENING_HEALTH_ASPECT = 'https://schema.org/ScreeningHealthAspect'
    SEATING_MAP = 'https://schema.org/SeatingMap'
    SEE_DOCTOR_HEALTH_ASPECT = 'https://schema.org/SeeDoctorHealthAspect'
    SELF_CARE_HEALTH_ASPECT = 'https://schema.org/SelfCareHealthAspect'
    SEXUAL_CONTENT_CONSIDERATION = 'https://schema.org/SexualContentConsideration'
    SIDE_EFFECTS_HEALTH_ASPECT = 'https://schema.org/SideEffectsHealthAspect'
    SINGLE_BLINDED_TRIAL = 'https://schema.org/SingleBlindedTrial'
    SINGLE_CENTER_TRIAL = 'https://schema.org/SingleCenterTrial'
    SINGLE_PLAYER = 'https://schema.org/SinglePlayer'
    SINGLE_RELEASE = 'https://schema.org/SingleRelease'
    SIZE_SYSTEM_IMPERIAL = 'https://schema.org/SizeSystemImperial'
    SIZE_SYSTEM_METRIC = 'https://schema.org/SizeSystemMetric'
    SKIN = 'https://schema.org/Skin'
    SOLD_OUT = 'https://schema.org/SoldOut'
    SOUNDTRACK_ALBUM = 'https://schema.org/SoundtrackAlbum'
    SPEECH_PATHOLOGY = 'https://schema.org/SpeechPathology'
    SPOKEN_WORD_ALBUM = 'https://schema.org/SpokenWordAlbum'
    STAGED_CONTENT = 'https://schema.org/StagedContent'
    STAGES_HEALTH_ASPECT = 'https://schema.org/StagesHealthAspect'
    STORE_CREDIT_REFUND = 'https://schema.org/StoreCreditRefund'
    STRENGTH_TRAINING = 'https://schema.org/StrengthTraining'
    STRIKETHROUGH_PRICE = 'https://schema.org/StrikethroughPrice'
    STUDIO_ALBUM = 'https://schema.org/StudioAlbum'
    SUBSCRIPTION = 'https://schema.org/Subscription'
    SUNDAY = 'https://schema.org/Sunday'
    SURGICAL = 'https://schema.org/Surgical'
    SUSPENDED = 'https://schema.org/Suspended'
    SYMPTOMS_HEALTH_ASPECT = 'https://schema.org/SymptomsHealthAspect'
    TAXI_VEHICLE_USAGE = 'https://schema.org/TaxiVehicleUsage'
    TERMINATED = 'https://schema.org/Terminated'
    THERAPEUTIC = 'https://schema.org/Therapeutic'
    THROAT = 'https://schema.org/Throat'
    THURSDAY = 'https://schema.org/Thursday'
    TIER_BENEFIT_LOYALTY_POINTS = 'https://schema.org/TierBenefitLoyaltyPoints'
    TIER_BENEFIT_LOYALTY_PRICE = 'https://schema.org/TierBenefitLoyaltyPrice'
    TIER_BENEFIT_LOYALTY_RETURNS = 'https://schema.org/TierBenefitLoyaltyReturns'
    TIER_BENEFIT_LOYALTY_SHIPPING = 'https://schema.org/TierBenefitLoyaltyShipping'
    TOBACCO_NICOTINE_CONSIDERATION = 'https://schema.org/TobaccoNicotineConsideration'
    TOLL_FREE = 'https://schema.org/TollFree'
    TOXICOLOGIC = 'https://schema.org/Toxicologic'
    TRADITIONAL_CHINESE = 'https://schema.org/TraditionalChinese'
    TRAINED_ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/TrainedAlgorithmicMediaDigitalSource'
    TRANSFORMED_CONTENT = 'https://schema.org/TransformedContent'
    TRANSIT_MAP = 'https://schema.org/TransitMap'
    TREATMENTS_HEALTH_ASPECT = 'https://schema.org/TreatmentsHealthAspect'
    TRIPLE_BLINDED_TRIAL = 'https://schema.org/TripleBlindedTrial'
    TUESDAY = 'https://schema.org/Tuesday'
    TYPES_HEALTH_ASPECT = 'https://schema.org/TypesHealthAspect'
    UK_TRUST = 'https://schema.org/UKTrust'
    ULTRASOUND = 'https://schema.org/Ultrasound'
    UNCLASSIFIED_ADULT_CONSIDERATION = 'https://schema.org/UnclassifiedAdultConsideration'
    UNEMPLOYMENT_SUPPORT = 'https://schema.org/UnemploymentSupport'
    UNINCORPORATED_ASSOCIATION_CHARITY = 'https://schema.org/UnincorporatedAssociationCharity'
    UNOFFICIAL_LEGAL_VALUE = 'https://schema.org/UnofficialLegalValue'
    UROLOGIC = 'https://schema.org/Urologic'
    USAGE_OR_SCHEDULE_HEALTH_ASPECT = 'https://schema.org/UsageOrScheduleHealthAspect'
    USED_CONDITION = 'https://schema.org/UsedCondition'
    VEGAN_DIET = 'https://schema.org/VeganDiet'
    VEGETARIAN_DIET = 'https://schema.org/VegetarianDiet'
    VENUE_MAP = 'https://schema.org/VenueMap'
    VINYL_FORMAT = 'https://schema.org/VinylFormat'
    VIOLENCE_CONSIDERATION = 'https://schema.org/ViolenceConsideration'
    VIRTUAL_RECORDING_DIGITAL_SOURCE = 'https://schema.org/VirtualRecordingDigitalSource'
    VIRUS = 'https://schema.org/Virus'
    WEAPON_CONSIDERATION = 'https://schema.org/WeaponConsideration'
    WEARABLE_MEASUREMENT_BACK = 'https://schema.org/WearableMeasurementBack'
    WEARABLE_MEASUREMENT_CHEST_OR_BUST = 'https://schema.org/WearableMeasurementChestOrBust'
    WEARABLE_MEASUREMENT_COLLAR = 'https://schema.org/WearableMeasurementCollar'
    WEARABLE_MEASUREMENT_CUP = 'https://schema.org/WearableMeasurementCup'
    WEARABLE_MEASUREMENT_HEIGHT = 'https://schema.org/WearableMeasurementHeight'
    WEARABLE_MEASUREMENT_HIPS = 'https://schema.org/WearableMeasurementHips'
    WEARABLE_MEASUREMENT_INSEAM = 'https://schema.org/WearableMeasurementInseam'
    WEARABLE_MEASUREMENT_LENGTH = 'https://schema.org/WearableMeasurementLength'
    WEARABLE_MEASUREMENT_OUTSIDE_LEG = 'https://schema.org/WearableMeasurementOutsideLeg'
    WEARABLE_MEASUREMENT_SLEEVE = 'https://schema.org/WearableMeasurementSleeve'
    WEARABLE_MEASUREMENT_WAIST = 'https://schema.org/WearableMeasurementWaist'
    WEARABLE_MEASUREMENT_WIDTH = 'https://schema.org/WearableMeasurementWidth'
    WEARABLE_SIZE_GROUP_BIG = 'https://schema.org/WearableSizeGroupBig'
    WEARABLE_SIZE_GROUP_BOYS = 'https://schema.org/WearableSizeGroupBoys'
    WEARABLE_SIZE_GROUP_EXTRA_SHORT = 'https://schema.org/WearableSizeGroupExtraShort'
    WEARABLE_SIZE_GROUP_EXTRA_TALL = 'https://schema.org/WearableSizeGroupExtraTall'
    WEARABLE_SIZE_GROUP_GIRLS = 'https://schema.org/WearableSizeGroupGirls'
    WEARABLE_SIZE_GROUP_HUSKY = 'https://schema.org/WearableSizeGroupHusky'
    WEARABLE_SIZE_GROUP_INFANTS = 'https://schema.org/WearableSizeGroupInfants'
    WEARABLE_SIZE_GROUP_JUNIORS = 'https://schema.org/WearableSizeGroupJuniors'
    WEARABLE_SIZE_GROUP_MATERNITY = 'https://schema.org/WearableSizeGroupMaternity'
    WEARABLE_SIZE_GROUP_MENS = 'https://schema.org/WearableSizeGroupMens'
    WEARABLE_SIZE_GROUP_MISSES = 'https://schema.org/WearableSizeGroupMisses'
    WEARABLE_SIZE_GROUP_PETITE = 'https://schema.org/WearableSizeGroupPetite'
    WEARABLE_SIZE_GROUP_PLUS = 'https://schema.org/WearableSizeGroupPlus'
    WEARABLE_SIZE_GROUP_REGULAR = 'https://schema.org/WearableSizeGroupRegular'
    WEARABLE_SIZE_GROUP_SHORT = 'https://schema.org/WearableSizeGroupShort'
    WEARABLE_SIZE_GROUP_TALL = 'https://schema.org/WearableSizeGroupTall'
    WEARABLE_SIZE_GROUP_WOMENS = 'https://schema.org/WearableSizeGroupWomens'
    WEARABLE_SIZE_SYSTEM_AU = 'https://schema.org/WearableSizeSystemAU'
    WEARABLE_SIZE_SYSTEM_BR = 'https://schema.org/WearableSizeSystemBR'
    WEARABLE_SIZE_SYSTEM_CN = 'https://schema.org/WearableSizeSystemCN'
    WEARABLE_SIZE_SYSTEM_CONTINENTAL = 'https://schema.org/WearableSizeSystemContinental'
    WEARABLE_SIZE_SYSTEM_DE = 'https://schema.org/WearableSizeSystemDE'
    WEARABLE_SIZE_SYSTEM_EN13402 = 'https://schema.org/WearableSizeSystemEN13402'
    WEARABLE_SIZE_SYSTEM_EUROPE = 'https://schema.org/WearableSizeSystemEurope'
    WEARABLE_SIZE_SYSTEM_FR = 'https://schema.org/WearableSizeSystemFR'
    WEARABLE_SIZE_SYSTEM_GS1 = 'https://schema.org/WearableSizeSystemGS1'
    WEARABLE_SIZE_SYSTEM_IT = 'https://schema.org/WearableSizeSystemIT'
    WEARABLE_SIZE_SYSTEM_JP = 'https://schema.org/WearableSizeSystemJP'
    WEARABLE_SIZE_SYSTEM_MX = 'https://schema.org/WearableSizeSystemMX'
    WEARABLE_SIZE_SYSTEM_UK = 'https://schema.org/WearableSizeSystemUK'
    WEARABLE_SIZE_SYSTEM_US = 'https://schema.org/WearableSizeSystemUS'
    WEDNESDAY = 'https://schema.org/Wednesday'
    WESTERN_CONVENTIONAL = 'https://schema.org/WesternConventional'
    WHOLESALE = 'https://schema.org/Wholesale'
    WITHDRAWN = 'https://schema.org/Withdrawn'
    WRITE_PERMISSION = 'https://schema.org/WritePermission'
    X_RAY = 'https://schema.org/XRay'
    ZONE_BOARDING_POLICY = 'https://schema.org/ZoneBoardingPolicy'

class EventAttendanceModeEnumeration(SchemaEnum):
    MIXED_EVENT_ATTENDANCE_MODE = 'https://schema.org/MixedEventAttendanceMode'
    OFFLINE_EVENT_ATTENDANCE_MODE = 'https://schema.org/OfflineEventAttendanceMode'
    ONLINE_EVENT_ATTENDANCE_MODE = 'https://schema.org/OnlineEventAttendanceMode'

class EventStatusType(SchemaEnum):
    EVENT_CANCELLED = 'https://schema.org/EventCancelled'
    EVENT_MOVED_ONLINE = 'https://schema.org/EventMovedOnline'
    EVENT_POSTPONED = 'https://schema.org/EventPostponed'
    EVENT_RESCHEDULED = 'https://schema.org/EventRescheduled'
    EVENT_SCHEDULED = 'https://schema.org/EventScheduled'

class FulfillmentTypeEnumeration(SchemaEnum):
    FULFILLMENT_TYPE_COLLECTION_POINT = 'https://schema.org/FulfillmentTypeCollectionPoint'
    FULFILLMENT_TYPE_DELIVERY = 'https://schema.org/FulfillmentTypeDelivery'
    FULFILLMENT_TYPE_PICKUP_DROPOFF = 'https://schema.org/FulfillmentTypePickupDropoff'
    FULFILLMENT_TYPE_PICKUP_IN_STORE = 'https://schema.org/FulfillmentTypePickupInStore'
    FULFILLMENT_TYPE_SCHEDULED_DELIVERY = 'https://schema.org/FulfillmentTypeScheduledDelivery'

class GameAvailabilityEnumeration(SchemaEnum):
    DEMO_GAME_AVAILABILITY = 'https://schema.org/DemoGameAvailability'
    FULL_GAME_AVAILABILITY = 'https://schema.org/FullGameAvailability'

class GamePlayMode(SchemaEnum):
    CO_OP = 'https://schema.org/CoOp'
    MULTI_PLAYER = 'https://schema.org/MultiPlayer'
    SINGLE_PLAYER = 'https://schema.org/SinglePlayer'

class GameServerStatus(SchemaEnum):
    OFFLINE_PERMANENTLY = 'https://schema.org/OfflinePermanently'
    OFFLINE_TEMPORARILY = 'https://schema.org/OfflineTemporarily'
    ONLINE = 'https://schema.org/Online'
    ONLINE_FULL = 'https://schema.org/OnlineFull'

class GenderType(SchemaEnum):
    FEMALE = 'https://schema.org/Female'
    MALE = 'https://schema.org/Male'

class GovernmentBenefitsType(SchemaEnum):
    BASIC_INCOME = 'https://schema.org/BasicIncome'
    BUSINESS_SUPPORT = 'https://schema.org/BusinessSupport'
    DISABILITY_SUPPORT = 'https://schema.org/DisabilitySupport'
    HEALTH_CARE = 'https://schema.org/HealthCare'
    ONE_TIME_PAYMENTS = 'https://schema.org/OneTimePayments'
    PAID_LEAVE = 'https://schema.org/PaidLeave'
    PARENTAL_SUPPORT = 'https://schema.org/ParentalSupport'
    UNEMPLOYMENT_SUPPORT = 'https://schema.org/UnemploymentSupport'

class HealthAspectEnumeration(SchemaEnum):
    ALLERGIES_HEALTH_ASPECT = 'https://schema.org/AllergiesHealthAspect'
    BENEFITS_HEALTH_ASPECT = 'https://schema.org/BenefitsHealthAspect'
    CAUSES_HEALTH_ASPECT = 'https://schema.org/CausesHealthAspect'
    CONTAGIOUSNESS_HEALTH_ASPECT = 'https://schema.org/ContagiousnessHealthAspect'
    EFFECTIVENESS_HEALTH_ASPECT = 'https://schema.org/EffectivenessHealthAspect'
    GETTING_ACCESS_HEALTH_ASPECT = 'https://schema.org/GettingAccessHealthAspect'
    HOW_IT_WORKS_HEALTH_ASPECT = 'https://schema.org/HowItWorksHealthAspect'
    HOW_OR_WHERE_HEALTH_ASPECT = 'https://schema.org/HowOrWhereHealthAspect'
    INGREDIENTS_HEALTH_ASPECT = 'https://schema.org/IngredientsHealthAspect'
    LIVING_WITH_HEALTH_ASPECT = 'https://schema.org/LivingWithHealthAspect'
    MAY_TREAT_HEALTH_ASPECT = 'https://schema.org/MayTreatHealthAspect'
    MISCONCEPTIONS_HEALTH_ASPECT = 'https://schema.org/MisconceptionsHealthAspect'
    OVERVIEW_HEALTH_ASPECT = 'https://schema.org/OverviewHealthAspect'
    PATIENT_EXPERIENCE_HEALTH_ASPECT = 'https://schema.org/PatientExperienceHealthAspect'
    PREGNANCY_HEALTH_ASPECT = 'https://schema.org/PregnancyHealthAspect'
    PREVENTION_HEALTH_ASPECT = 'https://schema.org/PreventionHealthAspect'
    PROGNOSIS_HEALTH_ASPECT = 'https://schema.org/PrognosisHealthAspect'
    RELATED_TOPICS_HEALTH_ASPECT = 'https://schema.org/RelatedTopicsHealthAspect'
    RISKS_OR_COMPLICATIONS_HEALTH_ASPECT = 'https://schema.org/RisksOrComplicationsHealthAspect'
    SAFETY_HEALTH_ASPECT = 'https://schema.org/SafetyHealthAspect'
    SCREENING_HEALTH_ASPECT = 'https://schema.org/ScreeningHealthAspect'
    SEE_DOCTOR_HEALTH_ASPECT = 'https://schema.org/SeeDoctorHealthAspect'
    SELF_CARE_HEALTH_ASPECT = 'https://schema.org/SelfCareHealthAspect'
    SIDE_EFFECTS_HEALTH_ASPECT = 'https://schema.org/SideEffectsHealthAspect'
    STAGES_HEALTH_ASPECT = 'https://schema.org/StagesHealthAspect'
    SYMPTOMS_HEALTH_ASPECT = 'https://schema.org/SymptomsHealthAspect'
    TREATMENTS_HEALTH_ASPECT = 'https://schema.org/TreatmentsHealthAspect'
    TYPES_HEALTH_ASPECT = 'https://schema.org/TypesHealthAspect'
    USAGE_OR_SCHEDULE_HEALTH_ASPECT = 'https://schema.org/UsageOrScheduleHealthAspect'

class IPTCDigitalSourceEnumeration(SchemaEnum):
    ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/AlgorithmicMediaDigitalSource'
    ALGORITHMICALLY_ENHANCED_DIGITAL_SOURCE = 'https://schema.org/AlgorithmicallyEnhancedDigitalSource'
    COMPOSITE_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/CompositeCaptureDigitalSource'
    COMPOSITE_DIGITAL_SOURCE = 'https://schema.org/CompositeDigitalSource'
    COMPOSITE_SYNTHETIC_DIGITAL_SOURCE = 'https://schema.org/CompositeSyntheticDigitalSource'
    COMPOSITE_WITH_TRAINED_ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/CompositeWithTrainedAlgorithmicMediaDigitalSource'
    DATA_DRIVEN_MEDIA_DIGITAL_SOURCE = 'https://schema.org/DataDrivenMediaDigitalSource'
    DIGITAL_ART_DIGITAL_SOURCE = 'https://schema.org/DigitalArtDigitalSource'
    DIGITAL_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/DigitalCaptureDigitalSource'
    MINOR_HUMAN_EDITS_DIGITAL_SOURCE = 'https://schema.org/MinorHumanEditsDigitalSource'
    MULTI_FRAME_COMPUTATIONAL_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/MultiFrameComputationalCaptureDigitalSource'
    NEGATIVE_FILM_DIGITAL_SOURCE = 'https://schema.org/NegativeFilmDigitalSource'
    POSITIVE_FILM_DIGITAL_SOURCE = 'https://schema.org/PositiveFilmDigitalSource'
    PRINT_DIGITAL_SOURCE = 'https://schema.org/PrintDigitalSource'
    SCREEN_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/ScreenCaptureDigitalSource'
    TRAINED_ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/TrainedAlgorithmicMediaDigitalSource'
    VIRTUAL_RECORDING_DIGITAL_SOURCE = 'https://schema.org/VirtualRecordingDigitalSource'

class ITNonprofitType(SchemaEnum):
    IT_COOPERATIVE_CHARITY = 'https://schema.org/ITCooperativeCharity'
    IT_MUTUAL_AID_CHARITY = 'https://schema.org/ITMutualAidCharity'
    IT_SOCIAL_COMPANY_CHARITY = 'https://schema.org/ITSocialCompanyCharity'
    IT_SOCIAL_PROMOTION_CHARITY = 'https://schema.org/ITSocialPromotionCharity'
    IT_SPORT_COMPANY_CHARITY = 'https://schema.org/ITSportCompanyCharity'
    IT_VOLUNTEER_ASSOCIATION_CHARITY = 'https://schema.org/ITVolunteerAssociationCharity'

class IncentiveQualifiedExpenseType(SchemaEnum):
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_GOODS_ONLY = 'https://schema.org/IncentiveQualifiedExpenseTypeGoodsOnly'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_GOODS_OR_SERVICES = 'https://schema.org/IncentiveQualifiedExpenseTypeGoodsOrServices'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_SERVICES_ONLY = 'https://schema.org/IncentiveQualifiedExpenseTypeServicesOnly'
    INCENTIVE_QUALIFIED_EXPENSE_TYPE_UTILITY_BILL = 'https://schema.org/IncentiveQualifiedExpenseTypeUtilityBill'

class IncentiveStatus(SchemaEnum):
    INCENTIVE_STATUS_ACTIVE = 'https://schema.org/IncentiveStatusActive'
    INCENTIVE_STATUS_IN_DEVELOPMENT = 'https://schema.org/IncentiveStatusInDevelopment'
    INCENTIVE_STATUS_ON_HOLD = 'https://schema.org/IncentiveStatusOnHold'
    INCENTIVE_STATUS_RETIRED = 'https://schema.org/IncentiveStatusRetired'

class IncentiveType(SchemaEnum):
    INCENTIVE_TYPE_LOAN = 'https://schema.org/IncentiveTypeLoan'
    INCENTIVE_TYPE_REBATE_OR_SUBSIDY = 'https://schema.org/IncentiveTypeRebateOrSubsidy'
    INCENTIVE_TYPE_TAX_CREDIT = 'https://schema.org/IncentiveTypeTaxCredit'
    INCENTIVE_TYPE_TAX_DEDUCTION = 'https://schema.org/IncentiveTypeTaxDeduction'
    INCENTIVE_TYPE_TAX_WAIVER = 'https://schema.org/IncentiveTypeTaxWaiver'

class InfectiousAgentClass(SchemaEnum):
    BACTERIA = 'https://schema.org/Bacteria'
    FUNGUS = 'https://schema.org/Fungus'
    MULTICELLULAR_PARASITE = 'https://schema.org/MulticellularParasite'
    PRION = 'https://schema.org/Prion'
    PROTOZOA = 'https://schema.org/Protozoa'
    VIRUS = 'https://schema.org/Virus'

class ItemAvailability(SchemaEnum):
    BACK_ORDER = 'https://schema.org/BackOrder'
    DISCONTINUED = 'https://schema.org/Discontinued'
    IN_STOCK = 'https://schema.org/InStock'
    IN_STORE_ONLY = 'https://schema.org/InStoreOnly'
    LIMITED_AVAILABILITY = 'https://schema.org/LimitedAvailability'
    MADE_TO_ORDER = 'https://schema.org/MadeToOrder'
    ONLINE_ONLY = 'https://schema.org/OnlineOnly'
    OUT_OF_STOCK = 'https://schema.org/OutOfStock'
    PRE_ORDER = 'https://schema.org/PreOrder'
    PRE_SALE = 'https://schema.org/PreSale'
    RESERVED = 'https://schema.org/Reserved'
    SOLD_OUT = 'https://schema.org/SoldOut'

class ItemListOrderType(SchemaEnum):
    ITEM_LIST_ORDER_ASCENDING = 'https://schema.org/ItemListOrderAscending'
    ITEM_LIST_ORDER_DESCENDING = 'https://schema.org/ItemListOrderDescending'
    ITEM_LIST_UNORDERED = 'https://schema.org/ItemListUnordered'

class LegalForceStatus(SchemaEnum):
    IN_FORCE = 'https://schema.org/InForce'
    NOT_IN_FORCE = 'https://schema.org/NotInForce'
    PARTIALLY_IN_FORCE = 'https://schema.org/PartiallyInForce'

class LegalValueLevel(SchemaEnum):
    AUTHORITATIVE_LEGAL_VALUE = 'https://schema.org/AuthoritativeLegalValue'
    DEFINITIVE_LEGAL_VALUE = 'https://schema.org/DefinitiveLegalValue'
    OFFICIAL_LEGAL_VALUE = 'https://schema.org/OfficialLegalValue'
    UNOFFICIAL_LEGAL_VALUE = 'https://schema.org/UnofficialLegalValue'

class MapCategoryType(SchemaEnum):
    PARKING_MAP = 'https://schema.org/ParkingMap'
    SEATING_MAP = 'https://schema.org/SeatingMap'
    TRANSIT_MAP = 'https://schema.org/TransitMap'
    VENUE_MAP = 'https://schema.org/VenueMap'

class MeasurementMethodEnum(SchemaEnum):
    EXAMPLE_MEASUREMENT_METHOD_ENUM = 'https://schema.org/ExampleMeasurementMethodEnum'

class MeasurementTypeEnumeration(SchemaEnum):
    BODY_MEASUREMENT_ARM = 'https://schema.org/BodyMeasurementArm'
    BODY_MEASUREMENT_BUST = 'https://schema.org/BodyMeasurementBust'
    BODY_MEASUREMENT_CHEST = 'https://schema.org/BodyMeasurementChest'
    BODY_MEASUREMENT_FOOT = 'https://schema.org/BodyMeasurementFoot'
    BODY_MEASUREMENT_HAND = 'https://schema.org/BodyMeasurementHand'
    BODY_MEASUREMENT_HEAD = 'https://schema.org/BodyMeasurementHead'
    BODY_MEASUREMENT_HEIGHT = 'https://schema.org/BodyMeasurementHeight'
    BODY_MEASUREMENT_HIPS = 'https://schema.org/BodyMeasurementHips'
    BODY_MEASUREMENT_INSIDE_LEG = 'https://schema.org/BodyMeasurementInsideLeg'
    BODY_MEASUREMENT_NECK = 'https://schema.org/BodyMeasurementNeck'
    BODY_MEASUREMENT_UNDERBUST = 'https://schema.org/BodyMeasurementUnderbust'
    BODY_MEASUREMENT_WAIST = 'https://schema.org/BodyMeasurementWaist'
    BODY_MEASUREMENT_WEIGHT = 'https://schema.org/BodyMeasurementWeight'
    WEARABLE_MEASUREMENT_BACK = 'https://schema.org/WearableMeasurementBack'
    WEARABLE_MEASUREMENT_CHEST_OR_BUST = 'https://schema.org/WearableMeasurementChestOrBust'
    WEARABLE_MEASUREMENT_COLLAR = 'https://schema.org/WearableMeasurementCollar'
    WEARABLE_MEASUREMENT_CUP = 'https://schema.org/WearableMeasurementCup'
    WEARABLE_MEASUREMENT_HEIGHT = 'https://schema.org/WearableMeasurementHeight'
    WEARABLE_MEASUREMENT_HIPS = 'https://schema.org/WearableMeasurementHips'
    WEARABLE_MEASUREMENT_INSEAM = 'https://schema.org/WearableMeasurementInseam'
    WEARABLE_MEASUREMENT_LENGTH = 'https://schema.org/WearableMeasurementLength'
    WEARABLE_MEASUREMENT_OUTSIDE_LEG = 'https://schema.org/WearableMeasurementOutsideLeg'
    WEARABLE_MEASUREMENT_SLEEVE = 'https://schema.org/WearableMeasurementSleeve'
    WEARABLE_MEASUREMENT_WAIST = 'https://schema.org/WearableMeasurementWaist'
    WEARABLE_MEASUREMENT_WIDTH = 'https://schema.org/WearableMeasurementWidth'

class MediaEnumeration(SchemaEnum):
    ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/AlgorithmicMediaDigitalSource'
    ALGORITHMICALLY_ENHANCED_DIGITAL_SOURCE = 'https://schema.org/AlgorithmicallyEnhancedDigitalSource'
    COMPOSITE_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/CompositeCaptureDigitalSource'
    COMPOSITE_DIGITAL_SOURCE = 'https://schema.org/CompositeDigitalSource'
    COMPOSITE_SYNTHETIC_DIGITAL_SOURCE = 'https://schema.org/CompositeSyntheticDigitalSource'
    COMPOSITE_WITH_TRAINED_ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/CompositeWithTrainedAlgorithmicMediaDigitalSource'
    DATA_DRIVEN_MEDIA_DIGITAL_SOURCE = 'https://schema.org/DataDrivenMediaDigitalSource'
    DIGITAL_ART_DIGITAL_SOURCE = 'https://schema.org/DigitalArtDigitalSource'
    DIGITAL_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/DigitalCaptureDigitalSource'
    MINOR_HUMAN_EDITS_DIGITAL_SOURCE = 'https://schema.org/MinorHumanEditsDigitalSource'
    MULTI_FRAME_COMPUTATIONAL_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/MultiFrameComputationalCaptureDigitalSource'
    NEGATIVE_FILM_DIGITAL_SOURCE = 'https://schema.org/NegativeFilmDigitalSource'
    POSITIVE_FILM_DIGITAL_SOURCE = 'https://schema.org/PositiveFilmDigitalSource'
    PRINT_DIGITAL_SOURCE = 'https://schema.org/PrintDigitalSource'
    SCREEN_CAPTURE_DIGITAL_SOURCE = 'https://schema.org/ScreenCaptureDigitalSource'
    TRAINED_ALGORITHMIC_MEDIA_DIGITAL_SOURCE = 'https://schema.org/TrainedAlgorithmicMediaDigitalSource'
    VIRTUAL_RECORDING_DIGITAL_SOURCE = 'https://schema.org/VirtualRecordingDigitalSource'

class MediaManipulationRatingEnumeration(SchemaEnum):
    DECONTEXTUALIZED_CONTENT = 'https://schema.org/DecontextualizedContent'
    EDITED_OR_CROPPED_CONTENT = 'https://schema.org/EditedOrCroppedContent'
    ORIGINAL_MEDIA_CONTENT = 'https://schema.org/OriginalMediaContent'
    SATIRE_OR_PARODY_CONTENT = 'https://schema.org/SatireOrParodyContent'
    STAGED_CONTENT = 'https://schema.org/StagedContent'
    TRANSFORMED_CONTENT = 'https://schema.org/TransformedContent'

class MedicalAudienceType(SchemaEnum):
    CLINICIAN = 'https://schema.org/Clinician'
    MEDICAL_RESEARCHER = 'https://schema.org/MedicalResearcher'

class MedicalDevicePurpose(SchemaEnum):
    DIAGNOSTIC = 'https://schema.org/Diagnostic'
    THERAPEUTIC = 'https://schema.org/Therapeutic'

class MedicalEnumeration(SchemaEnum):
    ABDOMEN = 'https://schema.org/Abdomen'
    ACTIVE_NOT_RECRUITING = 'https://schema.org/ActiveNotRecruiting'
    ANESTHESIA = 'https://schema.org/Anesthesia'
    APPEARANCE = 'https://schema.org/Appearance'
    AYURVEDIC = 'https://schema.org/Ayurvedic'
    BACTERIA = 'https://schema.org/Bacteria'
    CT = 'https://schema.org/CT'
    CARDIOVASCULAR = 'https://schema.org/Cardiovascular'
    CARDIOVASCULAR_EXAM = 'https://schema.org/CardiovascularExam'
    CASE_SERIES = 'https://schema.org/CaseSeries'
    CHIROPRACTIC = 'https://schema.org/Chiropractic'
    CLINICIAN = 'https://schema.org/Clinician'
    COHORT_STUDY = 'https://schema.org/CohortStudy'
    COMMUNITY_HEALTH = 'https://schema.org/CommunityHealth'
    COMPLETED = 'https://schema.org/Completed'
    CROSS_SECTIONAL = 'https://schema.org/CrossSectional'
    DENTISTRY = 'https://schema.org/Dentistry'
    DERMATOLOGIC = 'https://schema.org/Dermatologic'
    DERMATOLOGY = 'https://schema.org/Dermatology'
    DIAGNOSTIC = 'https://schema.org/Diagnostic'
    DIET_NUTRITION = 'https://schema.org/DietNutrition'
    DOUBLE_BLINDED_TRIAL = 'https://schema.org/DoubleBlindedTrial'
    EAR = 'https://schema.org/Ear'
    EMERGENCY = 'https://schema.org/Emergency'
    ENDOCRINE = 'https://schema.org/Endocrine'
    ENROLLING_BY_INVITATION = 'https://schema.org/EnrollingByInvitation'
    EVIDENCE_LEVEL_A = 'https://schema.org/EvidenceLevelA'
    EVIDENCE_LEVEL_B = 'https://schema.org/EvidenceLevelB'
    EVIDENCE_LEVEL_C = 'https://schema.org/EvidenceLevelC'
    EYE = 'https://schema.org/Eye'
    FD_ACATEGORY_A = 'https://schema.org/FDAcategoryA'
    FD_ACATEGORY_B = 'https://schema.org/FDAcategoryB'
    FD_ACATEGORY_C = 'https://schema.org/FDAcategoryC'
    FD_ACATEGORY_D = 'https://schema.org/FDAcategoryD'
    FD_ACATEGORY_X = 'https://schema.org/FDAcategoryX'
    FD_ANOT_EVALUATED = 'https://schema.org/FDAnotEvaluated'
    FUNGUS = 'https://schema.org/Fungus'
    GASTROENTEROLOGIC = 'https://schema.org/Gastroenterologic'
    GENETIC = 'https://schema.org/Genetic'
    GENITOURINARY = 'https://schema.org/Genitourinary'
    GERIATRIC = 'https://schema.org/Geriatric'
    GYNECOLOGIC = 'https://schema.org/Gynecologic'
    HEAD = 'https://schema.org/Head'
    HEMATOLOGIC = 'https://schema.org/Hematologic'
    HOMEOPATHIC = 'https://schema.org/Homeopathic'
    INFECTIOUS = 'https://schema.org/Infectious'
    INTERNATIONAL_TRIAL = 'https://schema.org/InternationalTrial'
    LABORATORY_SCIENCE = 'https://schema.org/LaboratoryScience'
    LONGITUDINAL = 'https://schema.org/Longitudinal'
    LUNG = 'https://schema.org/Lung'
    MRI = 'https://schema.org/MRI'
    MEDICAL_RESEARCHER = 'https://schema.org/MedicalResearcher'
    MIDWIFERY = 'https://schema.org/Midwifery'
    MULTI_CENTER_TRIAL = 'https://schema.org/MultiCenterTrial'
    MULTICELLULAR_PARASITE = 'https://schema.org/MulticellularParasite'
    MUSCULOSKELETAL = 'https://schema.org/Musculoskeletal'
    MUSCULOSKELETAL_EXAM = 'https://schema.org/MusculoskeletalExam'
    NECK = 'https://schema.org/Neck'
    NEURO = 'https://schema.org/Neuro'
    NEUROLOGIC = 'https://schema.org/Neurologic'
    NONINVASIVE_PROCEDURE = 'https://schema.org/NoninvasiveProcedure'
    NOSE = 'https://schema.org/Nose'
    NOT_YET_RECRUITING = 'https://schema.org/NotYetRecruiting'
    NURSING = 'https://schema.org/Nursing'
    OTC = 'https://schema.org/OTC'
    OBSERVATIONAL = 'https://schema.org/Observational'
    OBSTETRIC = 'https://schema.org/Obstetric'
    ONCOLOGIC = 'https://schema.org/Oncologic'
    OPEN_TRIAL = 'https://schema.org/OpenTrial'
    OPTOMETRIC = 'https://schema.org/Optometric'
    OSTEOPATHIC = 'https://schema.org/Osteopathic'
    OTOLARYNGOLOGIC = 'https://schema.org/Otolaryngologic'
    PET = 'https://schema.org/PET'
    PATHOLOGY = 'https://schema.org/Pathology'
    PEDIATRIC = 'https://schema.org/Pediatric'
    PERCUTANEOUS_PROCEDURE = 'https://schema.org/PercutaneousProcedure'
    PHARMACY_SPECIALTY = 'https://schema.org/PharmacySpecialty'
    PHYSIOTHERAPY = 'https://schema.org/Physiotherapy'
    PLACEBO_CONTROLLED_TRIAL = 'https://schema.org/PlaceboControlledTrial'
    PLASTIC_SURGERY = 'https://schema.org/PlasticSurgery'
    PODIATRIC = 'https://schema.org/Podiatric'
    PRESCRIPTION_ONLY = 'https://schema.org/PrescriptionOnly'
    PRIMARY_CARE = 'https://schema.org/PrimaryCare'
    PRION = 'https://schema.org/Prion'
    PROTOZOA = 'https://schema.org/Protozoa'
    PSYCHIATRIC = 'https://schema.org/Psychiatric'
    PUBLIC_HEALTH = 'https://schema.org/PublicHealth'
    PULMONARY = 'https://schema.org/Pulmonary'
    RADIOGRAPHY = 'https://schema.org/Radiography'
    RANDOMIZED_TRIAL = 'https://schema.org/RandomizedTrial'
    RECRUITING = 'https://schema.org/Recruiting'
    REGISTRY = 'https://schema.org/Registry'
    REIMBURSEMENT_CAP = 'https://schema.org/ReimbursementCap'
    RENAL = 'https://schema.org/Renal'
    RESPIRATORY_THERAPY = 'https://schema.org/RespiratoryTherapy'
    RESULTS_AVAILABLE = 'https://schema.org/ResultsAvailable'
    RESULTS_NOT_AVAILABLE = 'https://schema.org/ResultsNotAvailable'
    RETAIL = 'https://schema.org/Retail'
    RHEUMATOLOGIC = 'https://schema.org/Rheumatologic'
    SINGLE_BLINDED_TRIAL = 'https://schema.org/SingleBlindedTrial'
    SINGLE_CENTER_TRIAL = 'https://schema.org/SingleCenterTrial'
    SKIN = 'https://schema.org/Skin'
    SPEECH_PATHOLOGY = 'https://schema.org/SpeechPathology'
    SURGICAL = 'https://schema.org/Surgical'
    SUSPENDED = 'https://schema.org/Suspended'
    TERMINATED = 'https://schema.org/Terminated'
    THERAPEUTIC = 'https://schema.org/Therapeutic'
    THROAT = 'https://schema.org/Throat'
    TOXICOLOGIC = 'https://schema.org/Toxicologic'
    TRADITIONAL_CHINESE = 'https://schema.org/TraditionalChinese'
    TRIPLE_BLINDED_TRIAL = 'https://schema.org/TripleBlindedTrial'
    ULTRASOUND = 'https://schema.org/Ultrasound'
    UROLOGIC = 'https://schema.org/Urologic'
    VIRUS = 'https://schema.org/Virus'
    WESTERN_CONVENTIONAL = 'https://schema.org/WesternConventional'
    WHOLESALE = 'https://schema.org/Wholesale'
    WITHDRAWN = 'https://schema.org/Withdrawn'
    X_RAY = 'https://schema.org/XRay'

class MedicalEvidenceLevel(SchemaEnum):
    EVIDENCE_LEVEL_A = 'https://schema.org/EvidenceLevelA'
    EVIDENCE_LEVEL_B = 'https://schema.org/EvidenceLevelB'
    EVIDENCE_LEVEL_C = 'https://schema.org/EvidenceLevelC'

class MedicalImagingTechnique(SchemaEnum):
    CT = 'https://schema.org/CT'
    MRI = 'https://schema.org/MRI'
    PET = 'https://schema.org/PET'
    RADIOGRAPHY = 'https://schema.org/Radiography'
    ULTRASOUND = 'https://schema.org/Ultrasound'
    X_RAY = 'https://schema.org/XRay'

class MedicalObservationalStudyDesign(SchemaEnum):
    CASE_SERIES = 'https://schema.org/CaseSeries'
    COHORT_STUDY = 'https://schema.org/CohortStudy'
    CROSS_SECTIONAL = 'https://schema.org/CrossSectional'
    LONGITUDINAL = 'https://schema.org/Longitudinal'
    OBSERVATIONAL = 'https://schema.org/Observational'
    REGISTRY = 'https://schema.org/Registry'

class MedicalProcedureType(SchemaEnum):
    NONINVASIVE_PROCEDURE = 'https://schema.org/NoninvasiveProcedure'
    PERCUTANEOUS_PROCEDURE = 'https://schema.org/PercutaneousProcedure'

class MedicalSpecialty(SchemaEnum):
    ANESTHESIA = 'https://schema.org/Anesthesia'
    CARDIOVASCULAR = 'https://schema.org/Cardiovascular'
    COMMUNITY_HEALTH = 'https://schema.org/CommunityHealth'
    DENTISTRY = 'https://schema.org/Dentistry'
    DERMATOLOGIC = 'https://schema.org/Dermatologic'
    DERMATOLOGY = 'https://schema.org/Dermatology'
    DIET_NUTRITION = 'https://schema.org/DietNutrition'
    EMERGENCY = 'https://schema.org/Emergency'
    ENDOCRINE = 'https://schema.org/Endocrine'
    GASTROENTEROLOGIC = 'https://schema.org/Gastroenterologic'
    GENETIC = 'https://schema.org/Genetic'
    GERIATRIC = 'https://schema.org/Geriatric'
    GYNECOLOGIC = 'https://schema.org/Gynecologic'
    HEMATOLOGIC = 'https://schema.org/Hematologic'
    INFECTIOUS = 'https://schema.org/Infectious'
    LABORATORY_SCIENCE = 'https://schema.org/LaboratoryScience'
    MIDWIFERY = 'https://schema.org/Midwifery'
    MUSCULOSKELETAL = 'https://schema.org/Musculoskeletal'
    NEUROLOGIC = 'https://schema.org/Neurologic'
    NURSING = 'https://schema.org/Nursing'
    OBSTETRIC = 'https://schema.org/Obstetric'
    ONCOLOGIC = 'https://schema.org/Oncologic'
    OPTOMETRIC = 'https://schema.org/Optometric'
    OTOLARYNGOLOGIC = 'https://schema.org/Otolaryngologic'
    PATHOLOGY = 'https://schema.org/Pathology'
    PEDIATRIC = 'https://schema.org/Pediatric'
    PHARMACY_SPECIALTY = 'https://schema.org/PharmacySpecialty'
    PHYSIOTHERAPY = 'https://schema.org/Physiotherapy'
    PLASTIC_SURGERY = 'https://schema.org/PlasticSurgery'
    PODIATRIC = 'https://schema.org/Podiatric'
    PRIMARY_CARE = 'https://schema.org/PrimaryCare'
    PSYCHIATRIC = 'https://schema.org/Psychiatric'
    PUBLIC_HEALTH = 'https://schema.org/PublicHealth'
    PULMONARY = 'https://schema.org/Pulmonary'
    RADIOGRAPHY = 'https://schema.org/Radiography'
    RENAL = 'https://schema.org/Renal'
    RESPIRATORY_THERAPY = 'https://schema.org/RespiratoryTherapy'
    RHEUMATOLOGIC = 'https://schema.org/Rheumatologic'
    SPEECH_PATHOLOGY = 'https://schema.org/SpeechPathology'
    SURGICAL = 'https://schema.org/Surgical'
    TOXICOLOGIC = 'https://schema.org/Toxicologic'
    UROLOGIC = 'https://schema.org/Urologic'

class MedicalStudyStatus(SchemaEnum):
    ACTIVE_NOT_RECRUITING = 'https://schema.org/ActiveNotRecruiting'
    COMPLETED = 'https://schema.org/Completed'
    ENROLLING_BY_INVITATION = 'https://schema.org/EnrollingByInvitation'
    NOT_YET_RECRUITING = 'https://schema.org/NotYetRecruiting'
    RECRUITING = 'https://schema.org/Recruiting'
    RESULTS_AVAILABLE = 'https://schema.org/ResultsAvailable'
    RESULTS_NOT_AVAILABLE = 'https://schema.org/ResultsNotAvailable'
    SUSPENDED = 'https://schema.org/Suspended'
    TERMINATED = 'https://schema.org/Terminated'
    WITHDRAWN = 'https://schema.org/Withdrawn'

class MedicalTrialDesign(SchemaEnum):
    DOUBLE_BLINDED_TRIAL = 'https://schema.org/DoubleBlindedTrial'
    INTERNATIONAL_TRIAL = 'https://schema.org/InternationalTrial'
    MULTI_CENTER_TRIAL = 'https://schema.org/MultiCenterTrial'
    OPEN_TRIAL = 'https://schema.org/OpenTrial'
    PLACEBO_CONTROLLED_TRIAL = 'https://schema.org/PlaceboControlledTrial'
    RANDOMIZED_TRIAL = 'https://schema.org/RandomizedTrial'
    SINGLE_BLINDED_TRIAL = 'https://schema.org/SingleBlindedTrial'
    SINGLE_CENTER_TRIAL = 'https://schema.org/SingleCenterTrial'
    TRIPLE_BLINDED_TRIAL = 'https://schema.org/TripleBlindedTrial'

class MedicineSystem(SchemaEnum):
    AYURVEDIC = 'https://schema.org/Ayurvedic'
    CHIROPRACTIC = 'https://schema.org/Chiropractic'
    HOMEOPATHIC = 'https://schema.org/Homeopathic'
    OSTEOPATHIC = 'https://schema.org/Osteopathic'
    TRADITIONAL_CHINESE = 'https://schema.org/TraditionalChinese'
    WESTERN_CONVENTIONAL = 'https://schema.org/WesternConventional'

class MerchantReturnEnumeration(SchemaEnum):
    MERCHANT_RETURN_FINITE_RETURN_WINDOW = 'https://schema.org/MerchantReturnFiniteReturnWindow'
    MERCHANT_RETURN_NOT_PERMITTED = 'https://schema.org/MerchantReturnNotPermitted'
    MERCHANT_RETURN_UNLIMITED_WINDOW = 'https://schema.org/MerchantReturnUnlimitedWindow'
    MERCHANT_RETURN_UNSPECIFIED = 'https://schema.org/MerchantReturnUnspecified'

class MusicAlbumProductionType(SchemaEnum):
    COMPILATION_ALBUM = 'https://schema.org/CompilationAlbum'
    DJ_MIX_ALBUM = 'https://schema.org/DJMixAlbum'
    DEMO_ALBUM = 'https://schema.org/DemoAlbum'
    LIVE_ALBUM = 'https://schema.org/LiveAlbum'
    MIXTAPE_ALBUM = 'https://schema.org/MixtapeAlbum'
    REMIX_ALBUM = 'https://schema.org/RemixAlbum'
    SOUNDTRACK_ALBUM = 'https://schema.org/SoundtrackAlbum'
    SPOKEN_WORD_ALBUM = 'https://schema.org/SpokenWordAlbum'
    STUDIO_ALBUM = 'https://schema.org/StudioAlbum'

class MusicAlbumReleaseType(SchemaEnum):
    ALBUM_RELEASE = 'https://schema.org/AlbumRelease'
    BROADCAST_RELEASE = 'https://schema.org/BroadcastRelease'
    EP_RELEASE = 'https://schema.org/EPRelease'
    SINGLE_RELEASE = 'https://schema.org/SingleRelease'

class MusicReleaseFormatType(SchemaEnum):
    CD_FORMAT = 'https://schema.org/CDFormat'
    CASSETTE_FORMAT = 'https://schema.org/CassetteFormat'
    DVD_FORMAT = 'https://schema.org/DVDFormat'
    DIGITAL_AUDIO_TAPE_FORMAT = 'https://schema.org/DigitalAudioTapeFormat'
    DIGITAL_FORMAT = 'https://schema.org/DigitalFormat'
    LASER_DISC_FORMAT = 'https://schema.org/LaserDiscFormat'
    VINYL_FORMAT = 'https://schema.org/VinylFormat'

class NLNonprofitType(SchemaEnum):
    NONPROFIT_ANBI = 'https://schema.org/NonprofitANBI'
    NONPROFIT_SBBI = 'https://schema.org/NonprofitSBBI'

class NonprofitType(SchemaEnum):
    CHARITABLE_INCORPORATED_ORGANIZATION = 'https://schema.org/CharitableIncorporatedOrganization'
    DE_COOPERATIVE_CHARITY = 'https://schema.org/DECooperativeCharity'
    DE_FOUNDATION_CHARITY = 'https://schema.org/DEFoundationCharity'
    DE_JOINT_STOCK_COMPANY_CHARITY = 'https://schema.org/DEJointStockCompanyCharity'
    DE_LIMITED_LIABILITY_CHARITY = 'https://schema.org/DELimitedLiabilityCharity'
    DE_NOT_REGISTERED_ASSOCIATION_CHARITY = 'https://schema.org/DENotRegisteredAssociationCharity'
    DE_PUBLIC_CHARITY = 'https://schema.org/DEPublicCharity'
    DE_REGISTERED_ASSOCIATION_CHARITY = 'https://schema.org/DERegisteredAssociationCharity'
    IT_COOPERATIVE_CHARITY = 'https://schema.org/ITCooperativeCharity'
    IT_MUTUAL_AID_CHARITY = 'https://schema.org/ITMutualAidCharity'
    IT_SOCIAL_COMPANY_CHARITY = 'https://schema.org/ITSocialCompanyCharity'
    IT_SOCIAL_PROMOTION_CHARITY = 'https://schema.org/ITSocialPromotionCharity'
    IT_SPORT_COMPANY_CHARITY = 'https://schema.org/ITSportCompanyCharity'
    IT_VOLUNTEER_ASSOCIATION_CHARITY = 'https://schema.org/ITVolunteerAssociationCharity'
    LIMITED_BY_GUARANTEE_CHARITY = 'https://schema.org/LimitedByGuaranteeCharity'
    NONPROFIT501A = 'https://schema.org/Nonprofit501a'
    NONPROFIT501C1 = 'https://schema.org/Nonprofit501c1'
    NONPROFIT501C10 = 'https://schema.org/Nonprofit501c10'
    NONPROFIT501C11 = 'https://schema.org/Nonprofit501c11'
    NONPROFIT501C12 = 'https://schema.org/Nonprofit501c12'
    NONPROFIT501C13 = 'https://schema.org/Nonprofit501c13'
    NONPROFIT501C14 = 'https://schema.org/Nonprofit501c14'
    NONPROFIT501C15 = 'https://schema.org/Nonprofit501c15'
    NONPROFIT501C16 = 'https://schema.org/Nonprofit501c16'
    NONPROFIT501C17 = 'https://schema.org/Nonprofit501c17'
    NONPROFIT501C18 = 'https://schema.org/Nonprofit501c18'
    NONPROFIT501C19 = 'https://schema.org/Nonprofit501c19'
    NONPROFIT501C2 = 'https://schema.org/Nonprofit501c2'
    NONPROFIT501C20 = 'https://schema.org/Nonprofit501c20'
    NONPROFIT501C21 = 'https://schema.org/Nonprofit501c21'
    NONPROFIT501C22 = 'https://schema.org/Nonprofit501c22'
    NONPROFIT501C23 = 'https://schema.org/Nonprofit501c23'
    NONPROFIT501C24 = 'https://schema.org/Nonprofit501c24'
    NONPROFIT501C25 = 'https://schema.org/Nonprofit501c25'
    NONPROFIT501C26 = 'https://schema.org/Nonprofit501c26'
    NONPROFIT501C27 = 'https://schema.org/Nonprofit501c27'
    NONPROFIT501C28 = 'https://schema.org/Nonprofit501c28'
    NONPROFIT501C3 = 'https://schema.org/Nonprofit501c3'
    NONPROFIT501C4 = 'https://schema.org/Nonprofit501c4'
    NONPROFIT501C5 = 'https://schema.org/Nonprofit501c5'
    NONPROFIT501C6 = 'https://schema.org/Nonprofit501c6'
    NONPROFIT501C7 = 'https://schema.org/Nonprofit501c7'
    NONPROFIT501C8 = 'https://schema.org/Nonprofit501c8'
    NONPROFIT501C9 = 'https://schema.org/Nonprofit501c9'
    NONPROFIT501D = 'https://schema.org/Nonprofit501d'
    NONPROFIT501E = 'https://schema.org/Nonprofit501e'
    NONPROFIT501F = 'https://schema.org/Nonprofit501f'
    NONPROFIT501K = 'https://schema.org/Nonprofit501k'
    NONPROFIT501N = 'https://schema.org/Nonprofit501n'
    NONPROFIT501Q = 'https://schema.org/Nonprofit501q'
    NONPROFIT527 = 'https://schema.org/Nonprofit527'
    NONPROFIT_ANBI = 'https://schema.org/NonprofitANBI'
    NONPROFIT_SBBI = 'https://schema.org/NonprofitSBBI'
    UK_TRUST = 'https://schema.org/UKTrust'
    UNINCORPORATED_ASSOCIATION_CHARITY = 'https://schema.org/UnincorporatedAssociationCharity'

class OfferItemCondition(SchemaEnum):
    DAMAGED_CONDITION = 'https://schema.org/DamagedCondition'
    NEW_CONDITION = 'https://schema.org/NewCondition'
    REFURBISHED_CONDITION = 'https://schema.org/RefurbishedCondition'
    USED_CONDITION = 'https://schema.org/UsedCondition'

class OrderStatus(SchemaEnum):
    ORDER_CANCELLED = 'https://schema.org/OrderCancelled'
    ORDER_DELIVERED = 'https://schema.org/OrderDelivered'
    ORDER_IN_TRANSIT = 'https://schema.org/OrderInTransit'
    ORDER_PAYMENT_DUE = 'https://schema.org/OrderPaymentDue'
    ORDER_PICKUP_AVAILABLE = 'https://schema.org/OrderPickupAvailable'
    ORDER_PROBLEM = 'https://schema.org/OrderProblem'
    ORDER_PROCESSING = 'https://schema.org/OrderProcessing'
    ORDER_RETURNED = 'https://schema.org/OrderReturned'

class PaymentMethodType(SchemaEnum):
    BY_BANK_TRANSFER_IN_ADVANCE = 'https://schema.org/ByBankTransferInAdvance'
    BY_INVOICE = 'https://schema.org/ByInvoice'
    COD = 'https://schema.org/COD'
    CASH = 'https://schema.org/Cash'
    CHECK_IN_ADVANCE = 'https://schema.org/CheckInAdvance'
    DIRECT_DEBIT = 'https://schema.org/DirectDebit'
    IN_STORE_PREPAY = 'https://schema.org/InStorePrepay'
    PHONE_CARRIER_PAYMENT = 'https://schema.org/PhoneCarrierPayment'

class PaymentStatusType(SchemaEnum):
    PAYMENT_AUTOMATICALLY_APPLIED = 'https://schema.org/PaymentAutomaticallyApplied'
    PAYMENT_COMPLETE = 'https://schema.org/PaymentComplete'
    PAYMENT_DECLINED = 'https://schema.org/PaymentDeclined'
    PAYMENT_DUE = 'https://schema.org/PaymentDue'
    PAYMENT_PAST_DUE = 'https://schema.org/PaymentPastDue'

class PhysicalActivityCategory(SchemaEnum):
    AEROBIC_ACTIVITY = 'https://schema.org/AerobicActivity'
    ANAEROBIC_ACTIVITY = 'https://schema.org/AnaerobicActivity'
    BALANCE = 'https://schema.org/Balance'
    FLEXIBILITY = 'https://schema.org/Flexibility'
    LEISURE_TIME_ACTIVITY = 'https://schema.org/LeisureTimeActivity'
    OCCUPATIONAL_ACTIVITY = 'https://schema.org/OccupationalActivity'
    STRENGTH_TRAINING = 'https://schema.org/StrengthTraining'

class PhysicalExam(SchemaEnum):
    ABDOMEN = 'https://schema.org/Abdomen'
    APPEARANCE = 'https://schema.org/Appearance'
    CARDIOVASCULAR_EXAM = 'https://schema.org/CardiovascularExam'
    EAR = 'https://schema.org/Ear'
    EYE = 'https://schema.org/Eye'
    GENITOURINARY = 'https://schema.org/Genitourinary'
    HEAD = 'https://schema.org/Head'
    LUNG = 'https://schema.org/Lung'
    MUSCULOSKELETAL_EXAM = 'https://schema.org/MusculoskeletalExam'
    NECK = 'https://schema.org/Neck'
    NEURO = 'https://schema.org/Neuro'
    NOSE = 'https://schema.org/Nose'
    SKIN = 'https://schema.org/Skin'
    THROAT = 'https://schema.org/Throat'

class PriceComponentTypeEnumeration(SchemaEnum):
    ACTIVATION_FEE = 'https://schema.org/ActivationFee'
    CLEANING_FEE = 'https://schema.org/CleaningFee'
    DISTANCE_FEE = 'https://schema.org/DistanceFee'
    DOWNPAYMENT = 'https://schema.org/Downpayment'
    INSTALLMENT = 'https://schema.org/Installment'
    SUBSCRIPTION = 'https://schema.org/Subscription'

class PriceTypeEnumeration(SchemaEnum):
    INVOICE_PRICE = 'https://schema.org/InvoicePrice'
    LIST_PRICE = 'https://schema.org/ListPrice'
    MSRP = 'https://schema.org/MSRP'
    MINIMUM_ADVERTISED_PRICE = 'https://schema.org/MinimumAdvertisedPrice'
    REGULAR_PRICE = 'https://schema.org/RegularPrice'
    SRP = 'https://schema.org/SRP'
    SALE_PRICE = 'https://schema.org/SalePrice'
    STRIKETHROUGH_PRICE = 'https://schema.org/StrikethroughPrice'

class ProductReturnEnumeration(SchemaEnum):
    PRODUCT_RETURN_FINITE_RETURN_WINDOW = 'https://schema.org/ProductReturnFiniteReturnWindow'
    PRODUCT_RETURN_NOT_PERMITTED = 'https://schema.org/ProductReturnNotPermitted'
    PRODUCT_RETURN_UNLIMITED_WINDOW = 'https://schema.org/ProductReturnUnlimitedWindow'
    PRODUCT_RETURN_UNSPECIFIED = 'https://schema.org/ProductReturnUnspecified'

class PurchaseType(SchemaEnum):
    PURCHASE_TYPE_LEASE = 'https://schema.org/PurchaseTypeLease'
    PURCHASE_TYPE_NEW_PURCHASE = 'https://schema.org/PurchaseTypeNewPurchase'
    PURCHASE_TYPE_TRADE_IN = 'https://schema.org/PurchaseTypeTradeIn'
    PURCHASE_TYPE_USED_PURCHASE = 'https://schema.org/PurchaseTypeUsedPurchase'

class QualitativeValue(SchemaEnum):
    ALL_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/AllWheelDriveConfiguration'
    FOUR_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/FourWheelDriveConfiguration'
    FRONT_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/FrontWheelDriveConfiguration'
    LEFT_HAND_DRIVING = 'https://schema.org/LeftHandDriving'
    REAR_WHEEL_DRIVE_CONFIGURATION = 'https://schema.org/RearWheelDriveConfiguration'
    RIGHT_HAND_DRIVING = 'https://schema.org/RightHandDriving'

class RefundTypeEnumeration(SchemaEnum):
    EXCHANGE_REFUND = 'https://schema.org/ExchangeRefund'
    FULL_REFUND = 'https://schema.org/FullRefund'
    STORE_CREDIT_REFUND = 'https://schema.org/StoreCreditRefund'

class ReservationStatusType(SchemaEnum):
    RESERVATION_CANCELLED = 'https://schema.org/ReservationCancelled'
    RESERVATION_CONFIRMED = 'https://schema.org/ReservationConfirmed'
    RESERVATION_HOLD = 'https://schema.org/ReservationHold'
    RESERVATION_PENDING = 'https://schema.org/ReservationPending'

class RestrictedDiet(SchemaEnum):
    DIABETIC_DIET = 'https://schema.org/DiabeticDiet'
    GLUTEN_FREE_DIET = 'https://schema.org/GlutenFreeDiet'
    HALAL_DIET = 'https://schema.org/HalalDiet'
    HINDU_DIET = 'https://schema.org/HinduDiet'
    KOSHER_DIET = 'https://schema.org/KosherDiet'
    LOW_CALORIE_DIET = 'https://schema.org/LowCalorieDiet'
    LOW_FAT_DIET = 'https://schema.org/LowFatDiet'
    LOW_LACTOSE_DIET = 'https://schema.org/LowLactoseDiet'
    LOW_SALT_DIET = 'https://schema.org/LowSaltDiet'
    VEGAN_DIET = 'https://schema.org/VeganDiet'
    VEGETARIAN_DIET = 'https://schema.org/VegetarianDiet'

class ReturnFeesEnumeration(SchemaEnum):
    FREE_RETURN = 'https://schema.org/FreeReturn'
    ORIGINAL_SHIPPING_FEES = 'https://schema.org/OriginalShippingFees'
    RESTOCKING_FEES = 'https://schema.org/RestockingFees'
    RETURN_FEES_CUSTOMER_RESPONSIBILITY = 'https://schema.org/ReturnFeesCustomerResponsibility'
    RETURN_SHIPPING_FEES = 'https://schema.org/ReturnShippingFees'

class ReturnLabelSourceEnumeration(SchemaEnum):
    RETURN_LABEL_CUSTOMER_RESPONSIBILITY = 'https://schema.org/ReturnLabelCustomerResponsibility'
    RETURN_LABEL_DOWNLOAD_AND_PRINT = 'https://schema.org/ReturnLabelDownloadAndPrint'
    RETURN_LABEL_IN_BOX = 'https://schema.org/ReturnLabelInBox'

class ReturnMethodEnumeration(SchemaEnum):
    KEEP_PRODUCT = 'https://schema.org/KeepProduct'
    RETURN_AT_KIOSK = 'https://schema.org/ReturnAtKiosk'
    RETURN_BY_MAIL = 'https://schema.org/ReturnByMail'
    RETURN_IN_STORE = 'https://schema.org/ReturnInStore'

class RsvpResponseType(SchemaEnum):
    RSVP_RESPONSE_MAYBE = 'https://schema.org/RsvpResponseMaybe'
    RSVP_RESPONSE_NO = 'https://schema.org/RsvpResponseNo'
    RSVP_RESPONSE_YES = 'https://schema.org/RsvpResponseYes'

class SizeGroupEnumeration(SchemaEnum):
    WEARABLE_SIZE_GROUP_BIG = 'https://schema.org/WearableSizeGroupBig'
    WEARABLE_SIZE_GROUP_BOYS = 'https://schema.org/WearableSizeGroupBoys'
    WEARABLE_SIZE_GROUP_EXTRA_SHORT = 'https://schema.org/WearableSizeGroupExtraShort'
    WEARABLE_SIZE_GROUP_EXTRA_TALL = 'https://schema.org/WearableSizeGroupExtraTall'
    WEARABLE_SIZE_GROUP_GIRLS = 'https://schema.org/WearableSizeGroupGirls'
    WEARABLE_SIZE_GROUP_HUSKY = 'https://schema.org/WearableSizeGroupHusky'
    WEARABLE_SIZE_GROUP_INFANTS = 'https://schema.org/WearableSizeGroupInfants'
    WEARABLE_SIZE_GROUP_JUNIORS = 'https://schema.org/WearableSizeGroupJuniors'
    WEARABLE_SIZE_GROUP_MATERNITY = 'https://schema.org/WearableSizeGroupMaternity'
    WEARABLE_SIZE_GROUP_MENS = 'https://schema.org/WearableSizeGroupMens'
    WEARABLE_SIZE_GROUP_MISSES = 'https://schema.org/WearableSizeGroupMisses'
    WEARABLE_SIZE_GROUP_PETITE = 'https://schema.org/WearableSizeGroupPetite'
    WEARABLE_SIZE_GROUP_PLUS = 'https://schema.org/WearableSizeGroupPlus'
    WEARABLE_SIZE_GROUP_REGULAR = 'https://schema.org/WearableSizeGroupRegular'
    WEARABLE_SIZE_GROUP_SHORT = 'https://schema.org/WearableSizeGroupShort'
    WEARABLE_SIZE_GROUP_TALL = 'https://schema.org/WearableSizeGroupTall'
    WEARABLE_SIZE_GROUP_WOMENS = 'https://schema.org/WearableSizeGroupWomens'

class SizeSpecification(SchemaEnum):
    pass

class SizeSystemEnumeration(SchemaEnum):
    SIZE_SYSTEM_IMPERIAL = 'https://schema.org/SizeSystemImperial'
    SIZE_SYSTEM_METRIC = 'https://schema.org/SizeSystemMetric'
    WEARABLE_SIZE_SYSTEM_AU = 'https://schema.org/WearableSizeSystemAU'
    WEARABLE_SIZE_SYSTEM_BR = 'https://schema.org/WearableSizeSystemBR'
    WEARABLE_SIZE_SYSTEM_CN = 'https://schema.org/WearableSizeSystemCN'
    WEARABLE_SIZE_SYSTEM_CONTINENTAL = 'https://schema.org/WearableSizeSystemContinental'
    WEARABLE_SIZE_SYSTEM_DE = 'https://schema.org/WearableSizeSystemDE'
    WEARABLE_SIZE_SYSTEM_EN13402 = 'https://schema.org/WearableSizeSystemEN13402'
    WEARABLE_SIZE_SYSTEM_EUROPE = 'https://schema.org/WearableSizeSystemEurope'
    WEARABLE_SIZE_SYSTEM_FR = 'https://schema.org/WearableSizeSystemFR'
    WEARABLE_SIZE_SYSTEM_GS1 = 'https://schema.org/WearableSizeSystemGS1'
    WEARABLE_SIZE_SYSTEM_IT = 'https://schema.org/WearableSizeSystemIT'
    WEARABLE_SIZE_SYSTEM_JP = 'https://schema.org/WearableSizeSystemJP'
    WEARABLE_SIZE_SYSTEM_MX = 'https://schema.org/WearableSizeSystemMX'
    WEARABLE_SIZE_SYSTEM_UK = 'https://schema.org/WearableSizeSystemUK'
    WEARABLE_SIZE_SYSTEM_US = 'https://schema.org/WearableSizeSystemUS'

class Specialty(SchemaEnum):
    ANESTHESIA = 'https://schema.org/Anesthesia'
    CARDIOVASCULAR = 'https://schema.org/Cardiovascular'
    COMMUNITY_HEALTH = 'https://schema.org/CommunityHealth'
    DENTISTRY = 'https://schema.org/Dentistry'
    DERMATOLOGIC = 'https://schema.org/Dermatologic'
    DERMATOLOGY = 'https://schema.org/Dermatology'
    DIET_NUTRITION = 'https://schema.org/DietNutrition'
    EMERGENCY = 'https://schema.org/Emergency'
    ENDOCRINE = 'https://schema.org/Endocrine'
    GASTROENTEROLOGIC = 'https://schema.org/Gastroenterologic'
    GENETIC = 'https://schema.org/Genetic'
    GERIATRIC = 'https://schema.org/Geriatric'
    GYNECOLOGIC = 'https://schema.org/Gynecologic'
    HEMATOLOGIC = 'https://schema.org/Hematologic'
    INFECTIOUS = 'https://schema.org/Infectious'
    LABORATORY_SCIENCE = 'https://schema.org/LaboratoryScience'
    MIDWIFERY = 'https://schema.org/Midwifery'
    MUSCULOSKELETAL = 'https://schema.org/Musculoskeletal'
    NEUROLOGIC = 'https://schema.org/Neurologic'
    NURSING = 'https://schema.org/Nursing'
    OBSTETRIC = 'https://schema.org/Obstetric'
    ONCOLOGIC = 'https://schema.org/Oncologic'
    OPTOMETRIC = 'https://schema.org/Optometric'
    OTOLARYNGOLOGIC = 'https://schema.org/Otolaryngologic'
    PATHOLOGY = 'https://schema.org/Pathology'
    PEDIATRIC = 'https://schema.org/Pediatric'
    PHARMACY_SPECIALTY = 'https://schema.org/PharmacySpecialty'
    PHYSIOTHERAPY = 'https://schema.org/Physiotherapy'
    PLASTIC_SURGERY = 'https://schema.org/PlasticSurgery'
    PODIATRIC = 'https://schema.org/Podiatric'
    PRIMARY_CARE = 'https://schema.org/PrimaryCare'
    PSYCHIATRIC = 'https://schema.org/Psychiatric'
    PUBLIC_HEALTH = 'https://schema.org/PublicHealth'
    PULMONARY = 'https://schema.org/Pulmonary'
    RADIOGRAPHY = 'https://schema.org/Radiography'
    RENAL = 'https://schema.org/Renal'
    RESPIRATORY_THERAPY = 'https://schema.org/RespiratoryTherapy'
    RHEUMATOLOGIC = 'https://schema.org/Rheumatologic'
    SPEECH_PATHOLOGY = 'https://schema.org/SpeechPathology'
    SURGICAL = 'https://schema.org/Surgical'
    TOXICOLOGIC = 'https://schema.org/Toxicologic'
    UROLOGIC = 'https://schema.org/Urologic'

class StatusEnumeration(SchemaEnum):
    ACTIVE_ACTION_STATUS = 'https://schema.org/ActiveActionStatus'
    COMPLETED_ACTION_STATUS = 'https://schema.org/CompletedActionStatus'
    EVENT_CANCELLED = 'https://schema.org/EventCancelled'
    EVENT_MOVED_ONLINE = 'https://schema.org/EventMovedOnline'
    EVENT_POSTPONED = 'https://schema.org/EventPostponed'
    EVENT_RESCHEDULED = 'https://schema.org/EventRescheduled'
    EVENT_SCHEDULED = 'https://schema.org/EventScheduled'
    FAILED_ACTION_STATUS = 'https://schema.org/FailedActionStatus'
    IN_FORCE = 'https://schema.org/InForce'
    NOT_IN_FORCE = 'https://schema.org/NotInForce'
    OFFLINE_PERMANENTLY = 'https://schema.org/OfflinePermanently'
    OFFLINE_TEMPORARILY = 'https://schema.org/OfflineTemporarily'
    ONLINE = 'https://schema.org/Online'
    ONLINE_FULL = 'https://schema.org/OnlineFull'
    ORDER_CANCELLED = 'https://schema.org/OrderCancelled'
    ORDER_DELIVERED = 'https://schema.org/OrderDelivered'
    ORDER_IN_TRANSIT = 'https://schema.org/OrderInTransit'
    ORDER_PAYMENT_DUE = 'https://schema.org/OrderPaymentDue'
    ORDER_PICKUP_AVAILABLE = 'https://schema.org/OrderPickupAvailable'
    ORDER_PROBLEM = 'https://schema.org/OrderProblem'
    ORDER_PROCESSING = 'https://schema.org/OrderProcessing'
    ORDER_RETURNED = 'https://schema.org/OrderReturned'
    PARTIALLY_IN_FORCE = 'https://schema.org/PartiallyInForce'
    PAYMENT_AUTOMATICALLY_APPLIED = 'https://schema.org/PaymentAutomaticallyApplied'
    PAYMENT_COMPLETE = 'https://schema.org/PaymentComplete'
    PAYMENT_DECLINED = 'https://schema.org/PaymentDeclined'
    PAYMENT_DUE = 'https://schema.org/PaymentDue'
    PAYMENT_PAST_DUE = 'https://schema.org/PaymentPastDue'
    POTENTIAL_ACTION_STATUS = 'https://schema.org/PotentialActionStatus'
    RESERVATION_CANCELLED = 'https://schema.org/ReservationCancelled'
    RESERVATION_CONFIRMED = 'https://schema.org/ReservationConfirmed'
    RESERVATION_HOLD = 'https://schema.org/ReservationHold'
    RESERVATION_PENDING = 'https://schema.org/ReservationPending'

class SteeringPositionValue(SchemaEnum):
    LEFT_HAND_DRIVING = 'https://schema.org/LeftHandDriving'
    RIGHT_HAND_DRIVING = 'https://schema.org/RightHandDriving'

class TierBenefitEnumeration(SchemaEnum):
    TIER_BENEFIT_LOYALTY_POINTS = 'https://schema.org/TierBenefitLoyaltyPoints'
    TIER_BENEFIT_LOYALTY_PRICE = 'https://schema.org/TierBenefitLoyaltyPrice'
    TIER_BENEFIT_LOYALTY_RETURNS = 'https://schema.org/TierBenefitLoyaltyReturns'
    TIER_BENEFIT_LOYALTY_SHIPPING = 'https://schema.org/TierBenefitLoyaltyShipping'

class UKNonprofitType(SchemaEnum):
    CHARITABLE_INCORPORATED_ORGANIZATION = 'https://schema.org/CharitableIncorporatedOrganization'
    LIMITED_BY_GUARANTEE_CHARITY = 'https://schema.org/LimitedByGuaranteeCharity'
    UK_TRUST = 'https://schema.org/UKTrust'
    UNINCORPORATED_ASSOCIATION_CHARITY = 'https://schema.org/UnincorporatedAssociationCharity'

class USNonprofitType(SchemaEnum):
    NONPROFIT501A = 'https://schema.org/Nonprofit501a'
    NONPROFIT501C1 = 'https://schema.org/Nonprofit501c1'
    NONPROFIT501C10 = 'https://schema.org/Nonprofit501c10'
    NONPROFIT501C11 = 'https://schema.org/Nonprofit501c11'
    NONPROFIT501C12 = 'https://schema.org/Nonprofit501c12'
    NONPROFIT501C13 = 'https://schema.org/Nonprofit501c13'
    NONPROFIT501C14 = 'https://schema.org/Nonprofit501c14'
    NONPROFIT501C15 = 'https://schema.org/Nonprofit501c15'
    NONPROFIT501C16 = 'https://schema.org/Nonprofit501c16'
    NONPROFIT501C17 = 'https://schema.org/Nonprofit501c17'
    NONPROFIT501C18 = 'https://schema.org/Nonprofit501c18'
    NONPROFIT501C19 = 'https://schema.org/Nonprofit501c19'
    NONPROFIT501C2 = 'https://schema.org/Nonprofit501c2'
    NONPROFIT501C20 = 'https://schema.org/Nonprofit501c20'
    NONPROFIT501C21 = 'https://schema.org/Nonprofit501c21'
    NONPROFIT501C22 = 'https://schema.org/Nonprofit501c22'
    NONPROFIT501C23 = 'https://schema.org/Nonprofit501c23'
    NONPROFIT501C24 = 'https://schema.org/Nonprofit501c24'
    NONPROFIT501C25 = 'https://schema.org/Nonprofit501c25'
    NONPROFIT501C26 = 'https://schema.org/Nonprofit501c26'
    NONPROFIT501C27 = 'https://schema.org/Nonprofit501c27'
    NONPROFIT501C28 = 'https://schema.org/Nonprofit501c28'
    NONPROFIT501C3 = 'https://schema.org/Nonprofit501c3'
    NONPROFIT501C4 = 'https://schema.org/Nonprofit501c4'
    NONPROFIT501C5 = 'https://schema.org/Nonprofit501c5'
    NONPROFIT501C6 = 'https://schema.org/Nonprofit501c6'
    NONPROFIT501C7 = 'https://schema.org/Nonprofit501c7'
    NONPROFIT501C8 = 'https://schema.org/Nonprofit501c8'
    NONPROFIT501C9 = 'https://schema.org/Nonprofit501c9'
    NONPROFIT501D = 'https://schema.org/Nonprofit501d'
    NONPROFIT501E = 'https://schema.org/Nonprofit501e'
    NONPROFIT501F = 'https://schema.org/Nonprofit501f'
    NONPROFIT501K = 'https://schema.org/Nonprofit501k'
    NONPROFIT501N = 'https://schema.org/Nonprofit501n'
    NONPROFIT501Q = 'https://schema.org/Nonprofit501q'
    NONPROFIT527 = 'https://schema.org/Nonprofit527'

class WarrantyScope(SchemaEnum):
    pass

class WearableMeasurementTypeEnumeration(SchemaEnum):
    WEARABLE_MEASUREMENT_BACK = 'https://schema.org/WearableMeasurementBack'
    WEARABLE_MEASUREMENT_CHEST_OR_BUST = 'https://schema.org/WearableMeasurementChestOrBust'
    WEARABLE_MEASUREMENT_COLLAR = 'https://schema.org/WearableMeasurementCollar'
    WEARABLE_MEASUREMENT_CUP = 'https://schema.org/WearableMeasurementCup'
    WEARABLE_MEASUREMENT_HEIGHT = 'https://schema.org/WearableMeasurementHeight'
    WEARABLE_MEASUREMENT_HIPS = 'https://schema.org/WearableMeasurementHips'
    WEARABLE_MEASUREMENT_INSEAM = 'https://schema.org/WearableMeasurementInseam'
    WEARABLE_MEASUREMENT_LENGTH = 'https://schema.org/WearableMeasurementLength'
    WEARABLE_MEASUREMENT_OUTSIDE_LEG = 'https://schema.org/WearableMeasurementOutsideLeg'
    WEARABLE_MEASUREMENT_SLEEVE = 'https://schema.org/WearableMeasurementSleeve'
    WEARABLE_MEASUREMENT_WAIST = 'https://schema.org/WearableMeasurementWaist'
    WEARABLE_MEASUREMENT_WIDTH = 'https://schema.org/WearableMeasurementWidth'

class WearableSizeGroupEnumeration(SchemaEnum):
    WEARABLE_SIZE_GROUP_BIG = 'https://schema.org/WearableSizeGroupBig'
    WEARABLE_SIZE_GROUP_BOYS = 'https://schema.org/WearableSizeGroupBoys'
    WEARABLE_SIZE_GROUP_EXTRA_SHORT = 'https://schema.org/WearableSizeGroupExtraShort'
    WEARABLE_SIZE_GROUP_EXTRA_TALL = 'https://schema.org/WearableSizeGroupExtraTall'
    WEARABLE_SIZE_GROUP_GIRLS = 'https://schema.org/WearableSizeGroupGirls'
    WEARABLE_SIZE_GROUP_HUSKY = 'https://schema.org/WearableSizeGroupHusky'
    WEARABLE_SIZE_GROUP_INFANTS = 'https://schema.org/WearableSizeGroupInfants'
    WEARABLE_SIZE_GROUP_JUNIORS = 'https://schema.org/WearableSizeGroupJuniors'
    WEARABLE_SIZE_GROUP_MATERNITY = 'https://schema.org/WearableSizeGroupMaternity'
    WEARABLE_SIZE_GROUP_MENS = 'https://schema.org/WearableSizeGroupMens'
    WEARABLE_SIZE_GROUP_MISSES = 'https://schema.org/WearableSizeGroupMisses'
    WEARABLE_SIZE_GROUP_PETITE = 'https://schema.org/WearableSizeGroupPetite'
    WEARABLE_SIZE_GROUP_PLUS = 'https://schema.org/WearableSizeGroupPlus'
    WEARABLE_SIZE_GROUP_REGULAR = 'https://schema.org/WearableSizeGroupRegular'
    WEARABLE_SIZE_GROUP_SHORT = 'https://schema.org/WearableSizeGroupShort'
    WEARABLE_SIZE_GROUP_TALL = 'https://schema.org/WearableSizeGroupTall'
    WEARABLE_SIZE_GROUP_WOMENS = 'https://schema.org/WearableSizeGroupWomens'

class WearableSizeSystemEnumeration(SchemaEnum):
    WEARABLE_SIZE_SYSTEM_AU = 'https://schema.org/WearableSizeSystemAU'
    WEARABLE_SIZE_SYSTEM_BR = 'https://schema.org/WearableSizeSystemBR'
    WEARABLE_SIZE_SYSTEM_CN = 'https://schema.org/WearableSizeSystemCN'
    WEARABLE_SIZE_SYSTEM_CONTINENTAL = 'https://schema.org/WearableSizeSystemContinental'
    WEARABLE_SIZE_SYSTEM_DE = 'https://schema.org/WearableSizeSystemDE'
    WEARABLE_SIZE_SYSTEM_EN13402 = 'https://schema.org/WearableSizeSystemEN13402'
    WEARABLE_SIZE_SYSTEM_EUROPE = 'https://schema.org/WearableSizeSystemEurope'
    WEARABLE_SIZE_SYSTEM_FR = 'https://schema.org/WearableSizeSystemFR'
    WEARABLE_SIZE_SYSTEM_GS1 = 'https://schema.org/WearableSizeSystemGS1'
    WEARABLE_SIZE_SYSTEM_IT = 'https://schema.org/WearableSizeSystemIT'
    WEARABLE_SIZE_SYSTEM_JP = 'https://schema.org/WearableSizeSystemJP'
    WEARABLE_SIZE_SYSTEM_MX = 'https://schema.org/WearableSizeSystemMX'
    WEARABLE_SIZE_SYSTEM_UK = 'https://schema.org/WearableSizeSystemUK'
    WEARABLE_SIZE_SYSTEM_US = 'https://schema.org/WearableSizeSystemUS'
