# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar, Literal

from pydantic import Field

from schema_org.base import PropertyMetadata
from schema_org.models.structured_value import StructuredValue

if TYPE_CHECKING:
    from schema_org.datatypes import Date, DateTime, Number, Text


class CDCPMDRecord(StructuredValue):
    __doc__ = 'https://schema.org/CDCPMDRecord\n\nA CDCPMDRecord is a data structure representing a record in a CDC tabular data format\n      used for hospital data reporting. See [documentation](/docs/cdc-covid.html) for details, and the linked CDC materials for authoritative\n      definitions used as the source here.\n      '
    SCHEMA_TYPE: ClassVar[str] = 'CDCPMDRecord'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('CDCPMDRecord', 'StructuredValue', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='cvd_collection_date', schema_name='cvdCollectionDate', schema_url='https://schema.org/cvdCollectionDate', ranges=('DateTime', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='collectiondate - Date for which patient counts are reported.', label='cvdCollectionDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_facility_county', schema_name='cvdFacilityCounty', schema_url='https://schema.org/cvdFacilityCounty', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='Name of the County of the NHSN facility that this data record applies to. Use [[cvdFacilityId]] to identify the facility. To provide other details, [[healthcareReportingData]] can be used on a [[Hospital]] entry.', label='cvdFacilityCounty', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_facility_id', schema_name='cvdFacilityId', schema_url='https://schema.org/cvdFacilityId', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='Identifier of the NHSN facility that this data record applies to. Use [[cvdFacilityCounty]] to indicate the county. To provide other details, [[healthcareReportingData]] can be used on a [[Hospital]] entry.', label='cvdFacilityId', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_beds', schema_name='cvdNumBeds', schema_url='https://schema.org/cvdNumBeds', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numbeds - HOSPITAL INPATIENT BEDS: Inpatient beds, including all staffed, licensed, and overflow (surge) beds used for inpatients.', label='cvdNumBeds', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_beds_occ', schema_name='cvdNumBedsOcc', schema_url='https://schema.org/cvdNumBedsOcc', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numbedsocc - HOSPITAL INPATIENT BED OCCUPANCY: Total number of staffed inpatient beds that are occupied.', label='cvdNumBedsOcc', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_c19_died', schema_name='cvdNumC19Died', schema_url='https://schema.org/cvdNumC19Died', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numc19died - DEATHS: Patients with suspected or confirmed COVID-19 who died in the hospital, ED, or any overflow location.', label='cvdNumC19Died', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_c19_ho_pats', schema_name='cvdNumC19HOPats', schema_url='https://schema.org/cvdNumC19HOPats', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numc19hopats - HOSPITAL ONSET: Patients hospitalized in an NHSN inpatient care location with onset of suspected or confirmed COVID-19 14 or more days after hospitalization.', label='cvdNumC19HOPats', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_c19_hosp_pats', schema_name='cvdNumC19HospPats', schema_url='https://schema.org/cvdNumC19HospPats', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numc19hosppats - HOSPITALIZED: Patients currently hospitalized in an inpatient care location who have suspected or confirmed COVID-19.', label='cvdNumC19HospPats', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_c19_mech_vent_pats', schema_name='cvdNumC19MechVentPats', schema_url='https://schema.org/cvdNumC19MechVentPats', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numc19mechventpats - HOSPITALIZED and VENTILATED: Patients hospitalized in an NHSN inpatient care location who have suspected or confirmed COVID-19 and are on a mechanical ventilator.', label='cvdNumC19MechVentPats', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_c19_of_mech_vent_pats', schema_name='cvdNumC19OFMechVentPats', schema_url='https://schema.org/cvdNumC19OFMechVentPats', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numc19ofmechventpats - ED/OVERFLOW and VENTILATED: Patients with suspected or confirmed COVID-19 who are in the ED or any overflow location awaiting an inpatient bed and on a mechanical ventilator.', label='cvdNumC19OFMechVentPats', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_c19_overflow_pats', schema_name='cvdNumC19OverflowPats', schema_url='https://schema.org/cvdNumC19OverflowPats', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numc19overflowpats - ED/OVERFLOW: Patients with suspected or confirmed COVID-19 who are in the ED or any overflow location awaiting an inpatient bed.', label='cvdNumC19OverflowPats', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_icu_beds', schema_name='cvdNumICUBeds', schema_url='https://schema.org/cvdNumICUBeds', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numicubeds - ICU BEDS: Total number of staffed inpatient intensive care unit (ICU) beds.', label='cvdNumICUBeds', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_icu_beds_occ', schema_name='cvdNumICUBedsOcc', schema_url='https://schema.org/cvdNumICUBedsOcc', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numicubedsocc - ICU BED OCCUPANCY: Total number of staffed inpatient ICU beds that are occupied.', label='cvdNumICUBedsOcc', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_tot_beds', schema_name='cvdNumTotBeds', schema_url='https://schema.org/cvdNumTotBeds', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numtotbeds - ALL HOSPITAL BEDS: Total number of all inpatient and outpatient beds, including all staffed, ICU, licensed, and overflow (surge) beds used for inpatients or outpatients.', label='cvdNumTotBeds', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_vent', schema_name='cvdNumVent', schema_url='https://schema.org/cvdNumVent', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numvent - MECHANICAL VENTILATORS: Total number of ventilators available.', label='cvdNumVent', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='cvd_num_vent_use', schema_name='cvdNumVentUse', schema_url='https://schema.org/cvdNumVentUse', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord',), external_domains=(), comment='numventuse - MECHANICAL VENTILATORS IN USE: Total number of ventilators in use.', label='cvdNumVentUse', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2521',)),
        PropertyMetadata(name='date_posted', schema_name='datePosted', schema_url='https://schema.org/datePosted', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord', 'JobPosting', 'RealEstateListing', 'SpecialAnnouncement'), external_domains=(), comment='Publication date of an online listing.', label='datePosted', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2490', 'https://github.com/schemaorg/schemaorg/issues/2521')),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['CDCPMDRecord'] = Field(default='CDCPMDRecord', alias='@type', frozen=True)
    cvd_collection_date: DateTime | Text | list[DateTime | Text] | None = Field(default=None, alias='cvdCollectionDate', description='collectiondate - Date for which patient counts are reported.')
    cvd_facility_county: Text | list[Text] | None = Field(default=None, alias='cvdFacilityCounty', description='Name of the County of the NHSN facility that this data record applies to. Use [[cvdFacilityId]] to identify the facility. To provide other details, [[healthcareReportingData]] can be used on a [[Hospital]] entry.')
    cvd_facility_id: Text | list[Text] | None = Field(default=None, alias='cvdFacilityId', description='Identifier of the NHSN facility that this data record applies to. Use [[cvdFacilityCounty]] to indicate the county. To provide other details, [[healthcareReportingData]] can be used on a [[Hospital]] entry.')
    cvd_num_beds: Number | list[Number] | None = Field(default=None, alias='cvdNumBeds', description='numbeds - HOSPITAL INPATIENT BEDS: Inpatient beds, including all staffed, licensed, and overflow (surge) beds used for inpatients.')
    cvd_num_beds_occ: Number | list[Number] | None = Field(default=None, alias='cvdNumBedsOcc', description='numbedsocc - HOSPITAL INPATIENT BED OCCUPANCY: Total number of staffed inpatient beds that are occupied.')
    cvd_num_c19_died: Number | list[Number] | None = Field(default=None, alias='cvdNumC19Died', description='numc19died - DEATHS: Patients with suspected or confirmed COVID-19 who died in the hospital, ED, or any overflow location.')
    cvd_num_c19_ho_pats: Number | list[Number] | None = Field(default=None, alias='cvdNumC19HOPats', description='numc19hopats - HOSPITAL ONSET: Patients hospitalized in an NHSN inpatient care location with onset of suspected or confirmed COVID-19 14 or more days after hospitalization.')
    cvd_num_c19_hosp_pats: Number | list[Number] | None = Field(default=None, alias='cvdNumC19HospPats', description='numc19hosppats - HOSPITALIZED: Patients currently hospitalized in an inpatient care location who have suspected or confirmed COVID-19.')
    cvd_num_c19_mech_vent_pats: Number | list[Number] | None = Field(default=None, alias='cvdNumC19MechVentPats', description='numc19mechventpats - HOSPITALIZED and VENTILATED: Patients hospitalized in an NHSN inpatient care location who have suspected or confirmed COVID-19 and are on a mechanical ventilator.')
    cvd_num_c19_of_mech_vent_pats: Number | list[Number] | None = Field(default=None, alias='cvdNumC19OFMechVentPats', description='numc19ofmechventpats - ED/OVERFLOW and VENTILATED: Patients with suspected or confirmed COVID-19 who are in the ED or any overflow location awaiting an inpatient bed and on a mechanical ventilator.')
    cvd_num_c19_overflow_pats: Number | list[Number] | None = Field(default=None, alias='cvdNumC19OverflowPats', description='numc19overflowpats - ED/OVERFLOW: Patients with suspected or confirmed COVID-19 who are in the ED or any overflow location awaiting an inpatient bed.')
    cvd_num_icu_beds: Number | list[Number] | None = Field(default=None, alias='cvdNumICUBeds', description='numicubeds - ICU BEDS: Total number of staffed inpatient intensive care unit (ICU) beds.')
    cvd_num_icu_beds_occ: Number | list[Number] | None = Field(default=None, alias='cvdNumICUBedsOcc', description='numicubedsocc - ICU BED OCCUPANCY: Total number of staffed inpatient ICU beds that are occupied.')
    cvd_num_tot_beds: Number | list[Number] | None = Field(default=None, alias='cvdNumTotBeds', description='numtotbeds - ALL HOSPITAL BEDS: Total number of all inpatient and outpatient beds, including all staffed, ICU, licensed, and overflow (surge) beds used for inpatients or outpatients.')
    cvd_num_vent: Number | list[Number] | None = Field(default=None, alias='cvdNumVent', description='numvent - MECHANICAL VENTILATORS: Total number of ventilators available.')
    cvd_num_vent_use: Number | list[Number] | None = Field(default=None, alias='cvdNumVentUse', description='numventuse - MECHANICAL VENTILATORS IN USE: Total number of ventilators in use.')
    date_posted: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='datePosted', description='Publication date of an online listing.')
