# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Duration
from schema_org.datatypes import Integer
from schema_org.datatypes import Text
from schema_org.datatypes import Time
from schema_org.datatypes import URL
from schema_org.enums import EventAttendanceModeEnumeration
from schema_org.enums import EventStatusType
from schema_org.models.event import Event

class ComedyEvent(Event):
    __doc__ = 'https://schema.org/ComedyEvent\n\nEvent type: Comedy event.'
    SCHEMA_TYPE: ClassVar[str] = 'ComedyEvent'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('ComedyEvent', 'Event', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='about', schema_name='about', schema_url='https://schema.org/about', ranges=('Thing',), external_ranges=(), inverse_of='subjectOf', superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/subject',), subproperty_of=(), domains=('Certification', 'CommunicateAction', 'CreativeWork', 'DefinedTerm', 'DefinedTermSet', 'Event'), external_domains=(), comment='The subject matter of an object.', label='about', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670', 'https://github.com/schemaorg/schemaorg/issues/4588')),
        PropertyMetadata(name='actor', schema_name='actor', schema_url='https://schema.org/actor', ranges=('PerformingGroup', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('actors',), equivalent_properties=(), subproperty_of=(), domains=('Clip', 'CreativeWorkSeason', 'Episode', 'Event', 'Movie', 'MovieSeries', 'PodcastSeries', 'RadioSeries', 'TVSeries', 'VideoGame', 'VideoGameSeries', 'VideoObject'), external_domains=(), comment='An actor (individual or a group), e.g. in TV, radio, movie, video games etc., or in an event. Actors can be associated with individual items or with a series, episode, clip.', label='actor', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='aggregate_rating', schema_name='aggregateRating', schema_url='https://schema.org/aggregateRating', ranges=('AggregateRating',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='The overall rating, based on a collection of reviews or ratings, of the item.', label='aggregateRating', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='attendee', schema_name='attendee', schema_url='https://schema.org/attendee', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('attendees',), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='A person or organization attending the event.', label='attendee', contributors=(), sources=()),
        PropertyMetadata(name='attendees', schema_name='attendees', schema_url='https://schema.org/attendees', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by='attendee', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='A person attending the event.', label='attendees', contributors=(), sources=()),
        PropertyMetadata(name='audience', schema_name='audience', schema_url='https://schema.org/audience', ranges=('Audience',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('serviceAudience',), equivalent_properties=('http://purl.org/dc/terms/audience',), subproperty_of=(), domains=('CreativeWork', 'Event', 'LodgingBusiness', 'PlayAction', 'Product', 'Service'), external_domains=(), comment='An intended audience, i.e. a group for whom something was created.', label='audience', contributors=(), sources=()),
        PropertyMetadata(name='composer', schema_name='composer', schema_url='https://schema.org/composer', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event', 'MusicComposition'), external_domains=(), comment='The person or organization who wrote a composition, or who is the composer of a work performed at some event.', label='composer', contributors=('https://schema.org/docs/collab/MBZ',), sources=()),
        PropertyMetadata(name='contributor', schema_name='contributor', schema_url='https://schema.org/contributor', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/contributor',), subproperty_of=(), domains=('CreativeWork', 'Event'), external_domains=(), comment='A secondary contributor to the CreativeWork or Event.', label='contributor', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='director', schema_name='director', schema_url='https://schema.org/director', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('directors',), equivalent_properties=(), subproperty_of=(), domains=('Clip', 'CreativeWorkSeason', 'Episode', 'Event', 'Movie', 'MovieSeries', 'RadioSeries', 'TVSeries', 'VideoGame', 'VideoGameSeries', 'VideoObject'), external_domains=(), comment='A director of e.g. TV, radio, movie, video gaming etc. content, or of an event. Directors can be associated with individual items or with a series, episode, clip.', label='director', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='door_time', schema_name='doorTime', schema_url='https://schema.org/doorTime', ranges=('DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The time admission will commence.', label='doorTime', contributors=(), sources=()),
        PropertyMetadata(name='duration', schema_name='duration', schema_url='https://schema.org/duration', ranges=('Duration', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Audiobook', 'Episode', 'Event', 'MediaObject', 'Movie', 'MusicRecording', 'MusicRelease', 'QuantitativeValueDistribution', 'Schedule', 'ServicePeriod'), external_domains=(), comment='The duration of the item (movie, audio recording, event, etc.) in [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601).', label='duration', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1457', 'https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/3617')),
        PropertyMetadata(name='end_date', schema_name='endDate', schema_url='https://schema.org/endDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasEndDate',), subproperty_of=(), domains=('CreativeWorkSeason', 'CreativeWorkSeries', 'DatedMoneySpecification', 'EducationalOccupationalProgram', 'Event', 'MerchantReturnPolicySeasonalOverride', 'Role', 'Schedule'), external_domains=(), comment='The end date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).', label='endDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2486',)),
        PropertyMetadata(name='event_attendance_mode', schema_name='eventAttendanceMode', schema_url='https://schema.org/eventAttendanceMode', ranges=('EventAttendanceModeEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The eventAttendanceMode of an event indicates whether it occurs online, offline, or a mix.', label='eventAttendanceMode', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1842',)),
        PropertyMetadata(name='event_schedule', schema_name='eventSchedule', schema_url='https://schema.org/eventSchedule', ranges=('Schedule',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='Associates an [[Event]] with a [[Schedule]]. There are circumstances where it is preferable to share a schedule for a series of\n      repeating events rather than data on the individual events themselves. For example, a website or application might prefer to publish a schedule for a weekly\n      gym class rather than provide data on every event. A schedule could be processed by applications to add forthcoming events to a calendar. An [[Event]] that\n      is associated with a [[Schedule]] using this property should not have [[startDate]] or [[endDate]] properties. These are instead defined within the associated\n      [[Schedule]], this avoids any ambiguity for clients using the data. The property might have repeated values to specify different schedules, e.g. for different months\n      or seasons.', label='eventSchedule', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1457',)),
        PropertyMetadata(name='event_status', schema_name='eventStatus', schema_url='https://schema.org/eventStatus', ranges=('EventStatusType',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='An eventStatus of an event represents its status; particularly useful when an event is cancelled or rescheduled.', label='eventStatus', contributors=(), sources=()),
        PropertyMetadata(name='funder', schema_name='funder', schema_url='https://schema.org/funder', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('sponsor',), domains=('CreativeWork', 'Event', 'Grant', 'MonetaryGrant', 'Organization', 'Person'), external_domains=(), comment='A person or organization that supports (sponsors) something through some kind of financial contribution.', label='funder', contributors=(), sources=()),
        PropertyMetadata(name='funding', schema_name='funding', schema_url='https://schema.org/funding', ranges=('Grant',), external_ranges=(), inverse_of='fundedItem', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity', 'CreativeWork', 'Event', 'MedicalEntity', 'Organization', 'Person', 'Product'), external_domains=(), comment='A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].', label='funding', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/383',)),
        PropertyMetadata(name='has_participation_offer', schema_name='hasParticipationOffer', schema_url='https://schema.org/hasParticipationOffer', ranges=('Offer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='An offer to participate in the event, for example, Call for Proposals, Call for Speakers, or Call for Performers.', label='hasParticipationOffer', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4495',)),
        PropertyMetadata(name='has_sponsorship_offer', schema_name='hasSponsorshipOffer', schema_url='https://schema.org/hasSponsorshipOffer', ranges=('Offer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='An offer to sponsor the event, for example, Sponsorship Prospectus, Sponsorship Opportunities, or Sponsor Packages.', label='hasSponsorshipOffer', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4495',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='in_language', schema_name='inLanguage', schema_url='https://schema.org/inLanguage', ranges=('Language', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('language',), equivalent_properties=('http://purl.org/dc/terms/language',), subproperty_of=(), domains=('BroadcastService', 'CommunicateAction', 'CreativeWork', 'Event', 'LinkRole', 'PronounceableText', 'WriteAction'), external_domains=(), comment='The language of the content or performance or used in an action. Please use one of the language codes from the [IETF BCP 47 standard](http://tools.ietf.org/html/bcp47). See also [[availableLanguage]].', label='inLanguage', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2382',)),
        PropertyMetadata(name='is_accessible_for_free', schema_name='isAccessibleForFree', schema_url='https://schema.org/isAccessibleForFree', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('free',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Place'), external_domains=(), comment='A flag to signal that the item, event, or place is accessible for free.', label='isAccessibleForFree', contributors=(), sources=()),
        PropertyMetadata(name='keywords', schema_name='keywords', schema_url='https://schema.org/keywords', ranges=('DefinedTerm', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Organization', 'Place', 'Product'), external_domains=(), comment='Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.', label='keywords', contributors=(), sources=()),
        PropertyMetadata(name='location', schema_name='location', schema_url='https://schema.org/location', ranges=('Place', 'PostalAddress', 'Text', 'VirtualLocation'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/Locations/isLocatedIn',), subproperty_of=(), domains=('Action', 'Event', 'InteractionCounter', 'Organization'), external_domains=(), comment='The location of, for example, where an event is happening, where an organization is located, or where an action takes place.', label='location', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='maximum_attendee_capacity', schema_name='maximumAttendeeCapacity', schema_url='https://schema.org/maximumAttendeeCapacity', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Quantities/hasUpperBound',), domains=('Event', 'Place'), external_domains=(), comment='The total number of individuals that may attend an event or venue.', label='maximumAttendeeCapacity', contributors=(), sources=()),
        PropertyMetadata(name='maximum_physical_attendee_capacity', schema_name='maximumPhysicalAttendeeCapacity', schema_url='https://schema.org/maximumPhysicalAttendeeCapacity', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The maximum physical attendee capacity of an [[Event]] whose [[eventAttendanceMode]] is [[OfflineEventAttendanceMode]] (or the offline aspects, in the case of a [[MixedEventAttendanceMode]]). ', label='maximumPhysicalAttendeeCapacity', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1842',)),
        PropertyMetadata(name='maximum_virtual_attendee_capacity', schema_name='maximumVirtualAttendeeCapacity', schema_url='https://schema.org/maximumVirtualAttendeeCapacity', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The maximum virtual attendee capacity of an [[Event]] whose [[eventAttendanceMode]] is [[OnlineEventAttendanceMode]] (or the online aspects, in the case of a [[MixedEventAttendanceMode]]). ', label='maximumVirtualAttendeeCapacity', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1842',)),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='offers', schema_name='offers', schema_url='https://schema.org/offers', ranges=('Demand', 'Offer'), external_ranges=(), inverse_of='itemOffered', superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/isProductOf',), subproperty_of=(), domains=('AggregateOffer', 'CreativeWork', 'EducationalOccupationalProgram', 'Event', 'MenuItem', 'Product', 'Service', 'Trip'), external_domains=(), comment='An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.\n      ', label='offers', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='organizer', schema_name='organizer', schema_url='https://schema.org/organizer', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='An organizer of an Event.', label='organizer', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='performer', schema_name='performer', schema_url='https://schema.org/performer', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('performers',), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='A performer at the event&#x2014;for example, a presenter, musician, musical group or actor.', label='performer', contributors=(), sources=()),
        PropertyMetadata(name='performers', schema_name='performers', schema_url='https://schema.org/performers', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by='performer', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The main performer or performers of the event&#x2014;for example, a presenter, musician, or actor.', label='performers', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='previous_start_date', schema_name='previousStartDate', schema_url='https://schema.org/previousStartDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='Used in conjunction with eventStatus for rescheduled or cancelled events. This property contains the previously scheduled start date. For rescheduled events, the startDate property should be used for the newly scheduled start date. In the (rare) case of an event that has been postponed and rescheduled multiple times, this field may be repeated.', label='previousStartDate', contributors=(), sources=()),
        PropertyMetadata(name='recorded_in', schema_name='recordedIn', schema_url='https://schema.org/recordedIn', ranges=('CreativeWork',), external_ranges=(), inverse_of='recordedAt', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The CreativeWork that captured all or part of this Event.', label='recordedIn', contributors=(), sources=()),
        PropertyMetadata(name='remaining_attendee_capacity', schema_name='remainingAttendeeCapacity', schema_url='https://schema.org/remainingAttendeeCapacity', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='The number of attendee places for an event that remain unallocated.', label='remainingAttendeeCapacity', contributors=(), sources=()),
        PropertyMetadata(name='review', schema_name='review', schema_url='https://schema.org/review', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('reviews',), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A review of the item.', label='review', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='sponsor', schema_name='sponsor', schema_url='https://schema.org/sponsor', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Grant', 'MedicalStudy', 'Organization', 'Person'), external_domains=(), comment='A person or organization that supports a thing through a pledge, promise, or financial contribution. E.g. a sponsor of a Medical Study or a corporate sponsor of an event.', label='sponsor', contributors=(), sources=()),
        PropertyMetadata(name='start_date', schema_name='startDate', schema_url='https://schema.org/startDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasStartDate',), subproperty_of=(), domains=('CreativeWorkSeason', 'CreativeWorkSeries', 'DatedMoneySpecification', 'EducationalOccupationalProgram', 'Event', 'MerchantReturnPolicySeasonalOverride', 'Role', 'Schedule'), external_domains=(), comment='The start date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).', label='startDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2486',)),
        PropertyMetadata(name='sub_event', schema_name='subEvent', schema_url='https://schema.org/subEvent', ranges=('Event',), external_ranges=(), inverse_of='superEvent', superseded_by=None, supersedes=('subEvents',), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='An Event that is part of this event. For example, a conference event includes many presentations, each of which is a subEvent of the conference.', label='subEvent', contributors=(), sources=()),
        PropertyMetadata(name='sub_events', schema_name='subEvents', schema_url='https://schema.org/subEvents', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by='subEvent', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='Events that are a part of this event. For example, a conference event includes many presentations, each subEvents of the conference.', label='subEvents', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='super_event', schema_name='superEvent', schema_url='https://schema.org/superEvent', ranges=('Event',), external_ranges=(), inverse_of='subEvent', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='An event that this event is a part of. For example, a collection of individual music performances might each have a music festival as their superEvent.', label='superEvent', contributors=(), sources=()),
        PropertyMetadata(name='translator', schema_name='translator', schema_url='https://schema.org/translator', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event'), external_domains=(), comment='Organization or person who adapts a creative work to different languages, regional differences and technical requirements of a target market, or that translates during some event.', label='translator', contributors=(), sources=()),
        PropertyMetadata(name='typical_age_range', schema_name='typicalAgeRange', schema_url='https://schema.org/typicalAgeRange', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event'), external_domains=(), comment="The typical expected age range, e.g. '7-9', '11-'.", label='typicalAgeRange', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='work_featured', schema_name='workFeatured', schema_url='https://schema.org/workFeatured', ranges=('CreativeWork',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Event',), external_domains=(), comment='A work featured in some event, e.g. exhibited in an ExhibitionEvent.\n       Specific subproperties are available for workPerformed (e.g. a play), or a workPresented (a Movie at a ScreeningEvent).', label='workFeatured', contributors=(), sources=()),
        PropertyMetadata(name='work_performed', schema_name='workPerformed', schema_url='https://schema.org/workPerformed', ranges=('CreativeWork',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('workFeatured',), domains=('Event',), external_domains=(), comment='A work performed in some event, for example a play performed in a TheaterEvent.', label='workPerformed', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['ComedyEvent'] = Field(default='ComedyEvent', alias='@type', frozen=True)
