# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Text
from schema_org.datatypes import Time
from schema_org.datatypes import URL
from schema_org.enums import BusinessEntityType
from schema_org.enums import BusinessFunction
from schema_org.enums import DeliveryMethod
from schema_org.enums import ItemAvailability
from schema_org.enums import OfferItemCondition
from schema_org.models.intangible import Intangible

class Demand(Intangible):
    __doc__ = 'https://schema.org/Demand\n\nA demand entity represents the public, not necessarily binding, not necessarily exclusive, announcement by an organization or person to seek a certain type of goods or services. For describing demand using this type, the very same properties used for Offer apply.'
    SCHEMA_TYPE: ClassVar[str] = 'Demand'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Demand', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='accepted_payment_method', schema_name='acceptedPaymentMethod', schema_url='https://schema.org/acceptedPaymentMethod', ranges=('LoanOrCredit', 'PaymentMethod', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'Organization'), external_domains=(), comment='The payment method(s) that are accepted in general by an organization, or for some specific demand or offer.', label='acceptedPaymentMethod', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3537',)),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='advance_booking_requirement', schema_name='advanceBookingRequirement', schema_url='https://schema.org/advanceBookingRequirement', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The amount of time that is required between accepting the offer and the actual usage of the resource or service.', label='advanceBookingRequirement', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='area_served', schema_name='areaServed', schema_url='https://schema.org/areaServed', ranges=('AdministrativeArea', 'GeoShape', 'Place', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('serviceArea',), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasServiceArea',), subproperty_of=(), domains=('ContactPoint', 'DeliveryChargeSpecification', 'Demand', 'FinancialIncentive', 'Offer', 'Organization', 'Service'), external_domains=(), comment='The geographic area where a service or offered item is provided.', label='areaServed', contributors=(), sources=()),
        PropertyMetadata(name='asin', schema_name='asin', schema_url='https://schema.org/asin', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment="An Amazon Standard Identification Number (ASIN) is a 10-character alphanumeric unique identifier assigned by Amazon.com and its partners for product identification within the Amazon organization (summary from [Wikipedia](https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number)'s article).\n\nNote also that this is a definition for how to include ASINs in Schema.org data, and not a definition of ASINs in general - see documentation from Amazon for authoritative details.\nASINs are most commonly encoded as text strings, but the [asin] property supports URL/URI as potential values too.", label='asin', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='availability', schema_name='availability', schema_url='https://schema.org/availability', ranges=('ItemAvailability',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The availability of this item&#x2014;for example In stock, Out of stock, Pre-order, etc.', label='availability', contributors=(), sources=()),
        PropertyMetadata(name='availability_ends', schema_name='availabilityEnds', schema_url='https://schema.org/availabilityEnds', ranges=('Date', 'DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ActionAccessSpecification', 'Demand', 'Offer'), external_domains=(), comment='The end of the availability of the product or service included in the offer.', label='availabilityEnds', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/1741',)),
        PropertyMetadata(name='availability_starts', schema_name='availabilityStarts', schema_url='https://schema.org/availabilityStarts', ranges=('Date', 'DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ActionAccessSpecification', 'Demand', 'Offer'), external_domains=(), comment='The beginning of the availability of the product or service included in the offer.', label='availabilityStarts', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/1741',)),
        PropertyMetadata(name='available_at_or_from', schema_name='availableAtOrFrom', schema_url='https://schema.org/availableAtOrFrom', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('areaServed',), domains=('Demand', 'Offer'), external_domains=(), comment='The place(s) from which the offer can be obtained (e.g. store locations).', label='availableAtOrFrom', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='available_delivery_method', schema_name='availableDeliveryMethod', schema_url='https://schema.org/availableDeliveryMethod', ranges=('DeliveryMethod',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The delivery method(s) available for this offer.', label='availableDeliveryMethod', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='business_function', schema_name='businessFunction', schema_url='https://schema.org/businessFunction', ranges=('BusinessFunction',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'TypeAndQuantityNode'), external_domains=(), comment='The business function (e.g. sell, lease, repair, dispose) of the offer or component of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.', label='businessFunction', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='delivery_lead_time', schema_name='deliveryLeadTime', schema_url='https://schema.org/deliveryLeadTime', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The typical delay between the receipt of the order and the goods either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup.', label='deliveryLeadTime', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='eligible_customer_type', schema_name='eligibleCustomerType', schema_url='https://schema.org/eligibleCustomerType', ranges=('BusinessEntityType',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The type(s) of customers for which the given offer is valid.', label='eligibleCustomerType', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='eligible_duration', schema_name='eligibleDuration', schema_url='https://schema.org/eligibleDuration', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The duration for which the given offer is valid.', label='eligibleDuration', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='eligible_quantity', schema_name='eligibleQuantity', schema_url='https://schema.org/eligibleQuantity', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'PriceSpecification'), external_domains=(), comment='The interval and unit of measurement of ordering quantities for which the offer or price specification is valid. This allows e.g. specifying that a certain freight charge is valid only for a certain quantity.', label='eligibleQuantity', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='eligible_region', schema_name='eligibleRegion', schema_url='https://schema.org/eligibleRegion', ranges=('GeoShape', 'Place', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('areaServed',), domains=('ActionAccessSpecification', 'DeliveryChargeSpecification', 'Demand', 'Offer'), external_domains=(), comment='The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is valid.\\n\\nSee also [[ineligibleRegion]].\n    ', label='eligibleRegion', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/1741',)),
        PropertyMetadata(name='eligible_transaction_volume', schema_name='eligibleTransactionVolume', schema_url='https://schema.org/eligibleTransactionVolume', ranges=('PriceSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'PriceSpecification'), external_domains=(), comment='The transaction volume, in a monetary unit, for which the offer or price specification is valid, e.g. for indicating a minimal purchasing volume, to express free shipping above a certain order volume, or to limit the acceptance of credit cards to purchases to a certain minimal amount.', label='eligibleTransactionVolume', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='gtin', schema_name='gtin', schema_url='https://schema.org/gtin', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#gTINId', 'https://ref.gs1.org/voc/gtin'), subproperty_of=('identifier',), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='A Global Trade Item Number ([GTIN](https://www.gs1.org/standards/id-keys/gtin)). GTINs identify trade items, including products and services, using numeric identification codes.\n\nA correct [[gtin]] value should be a valid GTIN, which means that it should be an all-numeric string of either 8, 12, 13 or 14 digits, or a "GS1 Digital Link" URL based on such a string. The numeric component should also have a [valid GS1 check digit](https://www.gs1.org/services/check-digit-calculator) and meet the other rules for valid GTINs. See also [GS1\'s GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) and [Wikipedia](https://en.wikipedia.org/wiki/Global_Trade_Item_Number) for more details. Left-padding of the gtin values is not required or encouraged. The [[gtin]] property generalizes the earlier [[gtin8]], [[gtin12]], [[gtin13]], and [[gtin14]] properties.\n\nThe GS1 [digital link specifications](https://www.gs1.org/standards/Digital-Link/) expresses GTINs as URLs (URIs, IRIs, etc.).\nDigital Links should be populated into the [[hasGS1DigitalLink]] attribute.\n\nNote also that this is a definition for how to include GTINs in Schema.org data, and not a definition of GTINs in general - see the GS1 documentation for authoritative details.', label='gtin', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='gtin12', schema_name='gtin12', schema_url='https://schema.org/gtin12', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-12 code of the product, or the product to which the offer refers. The GTIN-12 is the 12-digit GS1 Identification Key composed of a U.P.C. Company Prefix, Item Reference, and Check Digit used to identify trade items. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin12', contributors=(), sources=()),
        PropertyMetadata(name='gtin13', schema_name='gtin13', schema_url='https://schema.org/gtin13', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-13 code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceding zero. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin13', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='gtin14', schema_name='gtin14', schema_url='https://schema.org/gtin14', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-14 code of the product, or the product to which the offer refers. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin14', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='gtin8', schema_name='gtin8', schema_url='https://schema.org/gtin8', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-8 code of the product, or the product to which the offer refers. This code is also known as EAN/UCC-8 or 8-digit EAN. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin8', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='includes_object', schema_name='includesObject', schema_url='https://schema.org/includesObject', ranges=('TypeAndQuantityNode',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'ProductCollection'), external_domains=(), comment='This links to a node or nodes indicating the exact quantity of the products included in  an [[Offer]] or [[ProductCollection]].', label='includesObject', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='ineligible_region', schema_name='ineligibleRegion', schema_url='https://schema.org/ineligibleRegion', ranges=('GeoShape', 'Place', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ActionAccessSpecification', 'DeliveryChargeSpecification', 'Demand', 'MediaObject', 'Offer'), external_domains=(), comment='The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is not valid, e.g. a region where the transaction is not allowed.\\n\\nSee also [[eligibleRegion]].\n      ', label='ineligibleRegion', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2242',)),
        PropertyMetadata(name='inventory_level', schema_name='inventoryLevel', schema_url='https://schema.org/inventoryLevel', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'SomeProducts'), external_domains=(), comment='The current approximate inventory level for the item or items.', label='inventoryLevel', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='item_condition', schema_name='itemCondition', schema_url='https://schema.org/itemCondition', ranges=('OfferItemCondition',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'MerchantReturnPolicy', 'Offer', 'Product'), external_domains=(), comment='A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.', label='itemCondition', contributors=(), sources=()),
        PropertyMetadata(name='item_offered', schema_name='itemOffered', schema_url='https://schema.org/itemOffered', ranges=('AggregateOffer', 'CreativeWork', 'Event', 'MenuItem', 'Product', 'Service', 'Trip'), external_ranges=(), inverse_of='offers', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='An item being offered (or demanded). The transactional nature of the offer or demand is documented using [[businessFunction]], e.g. sell, lease etc. While several common expected types are listed explicitly in this definition, others can be used. Using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.', label='itemOffered', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='mpn', schema_name='mpn', schema_url='https://schema.org/mpn', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#manufacturerAssignedId',), subproperty_of=(), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The Manufacturer Part Number (MPN) of the product, or the product to which the offer refers.', label='mpn', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='price_specification', schema_name='priceSpecification', schema_url='https://schema.org/priceSpecification', ranges=('PriceSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'DonateAction', 'Offer', 'TradeAction'), external_domains=(), comment='One or more detailed price specifications, indicating the unit price and delivery or payment charges.', label='priceSpecification', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='seller', schema_name='seller', schema_url='https://schema.org/seller', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('merchant', 'vendor'), equivalent_properties=('http://unece.org/vocab#Seller',), subproperty_of=('participant', 'https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasSupplier'), domains=('BuyAction', 'Demand', 'Flight', 'Offer', 'Order'), external_domains=(), comment='An entity which offers (sells / leases / lends / loans) the services / goods.  A seller may also be a provider.', label='seller', contributors=(), sources=()),
        PropertyMetadata(name='serial_number', schema_name='serialNumber', schema_url='https://schema.org/serialNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#SerialId',), subproperty_of=('identifier',), domains=('Demand', 'IndividualProduct', 'Offer'), external_domains=(), comment='The serial number or any alphanumeric identifier of a particular product. When attached to an offer, it is a shortcut for the serial number of the product included in the offer.', label='serialNumber', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='sku', schema_name='sku', schema_url='https://schema.org/sku', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#sellerAssignedId',), subproperty_of=('identifier',), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.', label='sku', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='valid_from', schema_name='validFrom', schema_url='https://schema.org/validFrom', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasStartDate',), subproperty_of=(), domains=('Certification', 'Demand', 'FinancialIncentive', 'LocationFeatureSpecification', 'MonetaryAmount', 'Offer', 'OpeningHoursSpecification', 'Permit', 'PriceSpecification'), external_domains=(), comment='The date when the item becomes valid.', label='validFrom', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='valid_through', schema_name='validThrough', schema_url='https://schema.org/validThrough', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasEndDate',), subproperty_of=(), domains=('Demand', 'FinancialIncentive', 'JobPosting', 'LocationFeatureSpecification', 'MonetaryAmount', 'Offer', 'OpeningHoursSpecification', 'PriceSpecification'), external_domains=(), comment='The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.', label='validThrough', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='warranty', schema_name='warranty', schema_url='https://schema.org/warranty', ranges=('WarrantyPromise',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('warrantyPromise',), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer'), external_domains=(), comment='The warranty promise(s) included in the offer.', label='warranty', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Demand'] = Field(default='Demand', alias='@type', frozen=True)
    accepted_payment_method: LoanOrCredit | PaymentMethod | Text | list[LoanOrCredit | PaymentMethod | Text] | None = Field(default=None, alias='acceptedPaymentMethod', description='The payment method(s) that are accepted in general by an organization, or for some specific demand or offer.')
    advance_booking_requirement: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='advanceBookingRequirement', description='The amount of time that is required between accepting the offer and the actual usage of the resource or service.')
    area_served: AdministrativeArea | GeoShape | Place | Text | list[AdministrativeArea | GeoShape | Place | Text] | None = Field(default=None, alias='areaServed', description='The geographic area where a service or offered item is provided.\n\nSupersedes `serviceArea`.')
    asin: Text | URL | list[Text | URL] | None = Field(default=None, alias='asin', description="An Amazon Standard Identification Number (ASIN) is a 10-character alphanumeric unique identifier assigned by Amazon.com and its partners for product identification within the Amazon organization (summary from [Wikipedia](https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number)'s article).\n\nNote also that this is a definition for how to include ASINs in Schema.org data, and not a definition of ASINs in general - see documentation from Amazon for authoritative details.\nASINs are most commonly encoded as text strings, but the [asin] property supports URL/URI as potential values too.")
    availability: ItemAvailability | list[ItemAvailability] | None = Field(default=None, alias='availability', description='The availability of this item&#x2014;for example In stock, Out of stock, Pre-order, etc.')
    availability_ends: Date | DateTime | Time | list[Date | DateTime | Time] | None = Field(default=None, alias='availabilityEnds', description='The end of the availability of the product or service included in the offer.')
    availability_starts: Date | DateTime | Time | list[Date | DateTime | Time] | None = Field(default=None, alias='availabilityStarts', description='The beginning of the availability of the product or service included in the offer.')
    available_at_or_from: Place | list[Place] | None = Field(default=None, alias='availableAtOrFrom', description='The place(s) from which the offer can be obtained (e.g. store locations).')
    available_delivery_method: DeliveryMethod | list[DeliveryMethod] | None = Field(default=None, alias='availableDeliveryMethod', description='The delivery method(s) available for this offer.')
    business_function: BusinessFunction | list[BusinessFunction] | None = Field(default=None, alias='businessFunction', description='The business function (e.g. sell, lease, repair, dispose) of the offer or component of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.')
    delivery_lead_time: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='deliveryLeadTime', description='The typical delay between the receipt of the order and the goods either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup.')
    eligible_customer_type: BusinessEntityType | list[BusinessEntityType] | None = Field(default=None, alias='eligibleCustomerType', description='The type(s) of customers for which the given offer is valid.')
    eligible_duration: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='eligibleDuration', description='The duration for which the given offer is valid.')
    eligible_quantity: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='eligibleQuantity', description='The interval and unit of measurement of ordering quantities for which the offer or price specification is valid. This allows e.g. specifying that a certain freight charge is valid only for a certain quantity.')
    eligible_region: GeoShape | Place | Text | list[GeoShape | Place | Text] | None = Field(default=None, alias='eligibleRegion', description='The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is valid.\\n\\nSee also [[ineligibleRegion]].\n    ')
    eligible_transaction_volume: PriceSpecification | list[PriceSpecification] | None = Field(default=None, alias='eligibleTransactionVolume', description='The transaction volume, in a monetary unit, for which the offer or price specification is valid, e.g. for indicating a minimal purchasing volume, to express free shipping above a certain order volume, or to limit the acceptance of credit cards to purchases to a certain minimal amount.')
    gtin: Text | URL | list[Text | URL] | None = Field(default=None, alias='gtin', description='A Global Trade Item Number ([GTIN](https://www.gs1.org/standards/id-keys/gtin)). GTINs identify trade items, including products and services, using numeric identification codes.\n\nA correct [[gtin]] value should be a valid GTIN, which means that it should be an all-numeric string of either 8, 12, 13 or 14 digits, or a "GS1 Digital Link" URL based on such a string. The numeric component should also have a [valid GS1 check digit](https://www.gs1.org/services/check-digit-calculator) and meet the other rules for valid GTINs. See also [GS1\'s GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) and [Wikipedia](https://en.wikipedia.org/wiki/Global_Trade_Item_Number) for more details. Left-padding of the gtin values is not required or encouraged. The [[gtin]] property generalizes the earlier [[gtin8]], [[gtin12]], [[gtin13]], and [[gtin14]] properties.\n\nThe GS1 [digital link specifications](https://www.gs1.org/standards/Digital-Link/) expresses GTINs as URLs (URIs, IRIs, etc.).\nDigital Links should be populated into the [[hasGS1DigitalLink]] attribute.\n\nNote also that this is a definition for how to include GTINs in Schema.org data, and not a definition of GTINs in general - see the GS1 documentation for authoritative details.')
    gtin12: Text | list[Text] | None = Field(default=None, alias='gtin12', description='The GTIN-12 code of the product, or the product to which the offer refers. The GTIN-12 is the 12-digit GS1 Identification Key composed of a U.P.C. Company Prefix, Item Reference, and Check Digit used to identify trade items. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.')
    gtin13: Text | list[Text] | None = Field(default=None, alias='gtin13', description='The GTIN-13 code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceding zero. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.')
    gtin14: Text | list[Text] | None = Field(default=None, alias='gtin14', description='The GTIN-14 code of the product, or the product to which the offer refers. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.')
    gtin8: Text | list[Text] | None = Field(default=None, alias='gtin8', description='The GTIN-8 code of the product, or the product to which the offer refers. This code is also known as EAN/UCC-8 or 8-digit EAN. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.')
    includes_object: TypeAndQuantityNode | list[TypeAndQuantityNode] | None = Field(default=None, alias='includesObject', description='This links to a node or nodes indicating the exact quantity of the products included in  an [[Offer]] or [[ProductCollection]].')
    ineligible_region: GeoShape | Place | Text | list[GeoShape | Place | Text] | None = Field(default=None, alias='ineligibleRegion', description='The ISO 3166-1 (ISO 3166-1 alpha-2) or ISO 3166-2 code, the place, or the GeoShape for the geo-political region(s) for which the offer or delivery charge specification is not valid, e.g. a region where the transaction is not allowed.\\n\\nSee also [[eligibleRegion]].\n      ')
    inventory_level: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='inventoryLevel', description='The current approximate inventory level for the item or items.')
    item_condition: OfferItemCondition | list[OfferItemCondition] | None = Field(default=None, alias='itemCondition', description='A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.')
    item_offered: AggregateOffer | CreativeWork | Event | MenuItem | Product | Service | Trip | list[AggregateOffer | CreativeWork | Event | MenuItem | Product | Service | Trip] | None = Field(default=None, alias='itemOffered', description='An item being offered (or demanded). The transactional nature of the offer or demand is documented using [[businessFunction]], e.g. sell, lease etc. While several common expected types are listed explicitly in this definition, others can be used. Using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.\n\nInverse-property: `offers`.')
    mpn: Text | list[Text] | None = Field(default=None, alias='mpn', description='The Manufacturer Part Number (MPN) of the product, or the product to which the offer refers.')
    price_specification: PriceSpecification | list[PriceSpecification] | None = Field(default=None, alias='priceSpecification', description='One or more detailed price specifications, indicating the unit price and delivery or payment charges.')
    seller: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='seller', description='An entity which offers (sells / leases / lends / loans) the services / goods.  A seller may also be a provider.\n\nSupersedes `merchant`.\n\nSupersedes `vendor`.')
    serial_number: Text | list[Text] | None = Field(default=None, alias='serialNumber', description='The serial number or any alphanumeric identifier of a particular product. When attached to an offer, it is a shortcut for the serial number of the product included in the offer.')
    sku: Text | list[Text] | None = Field(default=None, alias='sku', description='The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.')
    valid_from: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='validFrom', description='The date when the item becomes valid.')
    valid_through: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='validThrough', description='The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.')
    warranty: WarrantyPromise | list[WarrantyPromise] | None = Field(default=None, alias='warranty', description='The warranty promise(s) included in the offer.\n\nSupersedes `warrantyPromise`.')
