# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Duration
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import DayOfWeek
from schema_org.models.intangible import Intangible

class EducationalOccupationalProgram(Intangible):
    __doc__ = 'https://schema.org/EducationalOccupationalProgram\n\nA program offered by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate. This would define a discrete set of opportunities (e.g., job, courses) that together constitute a program with a clear start, end, set of requirements, and transition to a new occupational opportunity (e.g., a job), or sometimes a higher educational opportunity (e.g., an advanced degree).'
    SCHEMA_TYPE: ClassVar[str] = 'EducationalOccupationalProgram'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('EducationalOccupationalProgram', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='application_deadline', schema_name='applicationDeadline', schema_url='https://schema.org/applicationDeadline', ranges=('Date', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The date on which the program stops collecting applications for the next enrollment cycle. Flexible application deadlines (for example, a program with rolling admissions) can be described in a textual string, rather than as a DateTime.', label='applicationDeadline', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='application_start_date', schema_name='applicationStartDate', schema_url='https://schema.org/applicationStartDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The date at which the program begins collecting applications for the next enrollment cycle.', label='applicationStartDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='day_of_week', schema_name='dayOfWeek', schema_url='https://schema.org/dayOfWeek', ranges=('DayOfWeek',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram', 'OpeningHoursSpecification'), external_domains=(), comment='The day of the week for which these opening hours are valid.', label='dayOfWeek', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='educational_credential_awarded', schema_name='educationalCredentialAwarded', schema_url='https://schema.org/educationalCredentialAwarded', ranges=('EducationalOccupationalCredential', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Course', 'EducationalOccupationalProgram'), external_domains=(), comment='A description of the qualification, award, certificate, diploma or other educational credential awarded as a consequence of successful completion of this course or program.', label='educationalCredentialAwarded', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='educational_program_mode', schema_name='educationalProgramMode', schema_url='https://schema.org/educationalProgramMode', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='Similar to courseMode, the medium or means of delivery of the program as a whole. The value may either be a text label (e.g. "online", "onsite" or "blended"; "synchronous" or "asynchronous"; "full-time" or "part-time") or a URL reference to a term from a controlled vocabulary (e.g. https://ceds.ed.gov/element/001311#Asynchronous ).', label='educationalProgramMode', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='end_date', schema_name='endDate', schema_url='https://schema.org/endDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasEndDate',), subproperty_of=(), domains=('CreativeWorkSeason', 'CreativeWorkSeries', 'DatedMoneySpecification', 'EducationalOccupationalProgram', 'Event', 'MerchantReturnPolicySeasonalOverride', 'Role', 'Schedule'), external_domains=(), comment='The end date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).', label='endDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2486',)),
        PropertyMetadata(name='financial_aid_eligible', schema_name='financialAidEligible', schema_url='https://schema.org/financialAidEligible', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Course', 'EducationalOccupationalProgram'), external_domains=(), comment='A financial aid type or program which students may use to pay for tuition or fees associated with the program.', label='financialAidEligible', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2418',)),
        PropertyMetadata(name='has_course', schema_name='hasCourse', schema_url='https://schema.org/hasCourse', ranges=('Course',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='A course or class that is one of the learning opportunities that constitute an educational / occupational program. No information is implied about whether the course is mandatory or optional; no guarantee is implied about whether the course will be available to everyone on the program.', label='hasCourse', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2483',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='maximum_enrollment', schema_name='maximumEnrollment', schema_url='https://schema.org/maximumEnrollment', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The maximum number of students who may be enrolled in the program.', label='maximumEnrollment', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='number_of_credits', schema_name='numberOfCredits', schema_url='https://schema.org/numberOfCredits', ranges=('Integer', 'StructuredValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Course', 'EducationalOccupationalProgram'), external_domains=(), comment='The number of credits or units awarded by a Course or required to complete an EducationalOccupationalProgram.', label='numberOfCredits', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='occupational_category', schema_name='occupationalCategory', schema_url='https://schema.org/occupationalCategory', ranges=('CategoryCode', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram', 'JobPosting', 'Occupation', 'Physician', 'WorkBasedProgram'), external_domains=(), comment='A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\\n\nNote: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.', label='occupationalCategory', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2192', 'https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2460', 'https://github.com/schemaorg/schemaorg/issues/3420')),
        PropertyMetadata(name='occupational_credential_awarded', schema_name='occupationalCredentialAwarded', schema_url='https://schema.org/occupationalCredentialAwarded', ranges=('EducationalOccupationalCredential', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Course', 'EducationalOccupationalProgram'), external_domains=(), comment='A description of the qualification, award, certificate, diploma or other occupational credential awarded as a consequence of successful completion of this course or program.', label='occupationalCredentialAwarded', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='offers', schema_name='offers', schema_url='https://schema.org/offers', ranges=('Demand', 'Offer'), external_ranges=(), inverse_of='itemOffered', superseded_by=None, supersedes=None, equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/isProductOf',), subproperty_of=(), domains=('AggregateOffer', 'CreativeWork', 'EducationalOccupationalProgram', 'Event', 'MenuItem', 'Product', 'Service', 'Trip'), external_domains=(), comment='An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.\n      ', label='offers', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='program_prerequisites', schema_name='programPrerequisites', schema_url='https://schema.org/programPrerequisites', ranges=('AlignmentObject', 'Course', 'EducationalOccupationalCredential', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='Prerequisites for enrolling in the program.', label='programPrerequisites', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='program_type', schema_name='programType', schema_url='https://schema.org/programType', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The type of educational or occupational program. For example, classroom, internship, alternance, etc.', label='programType', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2460',)),
        PropertyMetadata(name='provider', schema_name='provider', schema_url='https://schema.org/provider', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='carrier', equivalent_properties=('http://unece.org/vocab#ServiceProvider',), subproperty_of=(), domains=('Action', 'CreativeWork', 'EducationalOccupationalProgram', 'FinancialIncentive', 'Invoice', 'ParcelDelivery', 'Reservation', 'Service', 'Trip'), external_domains=(), comment='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.', label='provider', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2927')),
        PropertyMetadata(name='salary_upon_completion', schema_name='salaryUponCompletion', schema_url='https://schema.org/salaryUponCompletion', ranges=('MonetaryAmountDistribution',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The expected salary upon completing the training.', label='salaryUponCompletion', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='start_date', schema_name='startDate', schema_url='https://schema.org/startDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasStartDate',), subproperty_of=(), domains=('CreativeWorkSeason', 'CreativeWorkSeries', 'DatedMoneySpecification', 'EducationalOccupationalProgram', 'Event', 'MerchantReturnPolicySeasonalOverride', 'Role', 'Schedule'), external_domains=(), comment='The start date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).', label='startDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2486',)),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='term_duration', schema_name='termDuration', schema_url='https://schema.org/termDuration', ranges=('Duration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The amount of time in a term as defined by the institution. A term is a length of time where students take one or more classes. Semesters and quarters are common units for term.', label='termDuration', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='terms_per_year', schema_name='termsPerYear', schema_url='https://schema.org/termsPerYear', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The number of times terms of study are offered per year. Semesters and quarters are common units for term. For example, if the student can only take 2 semesters for the program in one year, then termsPerYear should be 2.', label='termsPerYear', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='time_of_day', schema_name='timeOfDay', schema_url='https://schema.org/timeOfDay', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The time of day the program normally runs. For example, "evenings".', label='timeOfDay', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='time_to_complete', schema_name='timeToComplete', schema_url='https://schema.org/timeToComplete', ranges=('Duration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment='The expected length of time to complete the program if attending full-time.', label='timeToComplete', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='training_salary', schema_name='trainingSalary', schema_url='https://schema.org/trainingSalary', ranges=('MonetaryAmountDistribution',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram', 'WorkBasedProgram'), external_domains=(), comment='The estimated salary earned while in the program.', label='trainingSalary', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2460')),
        PropertyMetadata(name='typical_credits_per_term', schema_name='typicalCreditsPerTerm', schema_url='https://schema.org/typicalCreditsPerTerm', ranges=('Integer', 'StructuredValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram',), external_domains=(), comment="The number of credits or units a full-time student would be expected to take in 1 term however 'term' is defined by the institution.", label='typicalCreditsPerTerm', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2419',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['EducationalOccupationalProgram'] = Field(default='EducationalOccupationalProgram', alias='@type', frozen=True)
    application_deadline: Date | Text | list[Date | Text] | None = Field(default=None, alias='applicationDeadline', description='The date on which the program stops collecting applications for the next enrollment cycle. Flexible application deadlines (for example, a program with rolling admissions) can be described in a textual string, rather than as a DateTime.')
    application_start_date: Date | list[Date] | None = Field(default=None, alias='applicationStartDate', description='The date at which the program begins collecting applications for the next enrollment cycle.')
    day_of_week: DayOfWeek | list[DayOfWeek] | None = Field(default=None, alias='dayOfWeek', description='The day of the week for which these opening hours are valid.')
    educational_credential_awarded: EducationalOccupationalCredential | Text | URL | list[EducationalOccupationalCredential | Text | URL] | None = Field(default=None, alias='educationalCredentialAwarded', description='A description of the qualification, award, certificate, diploma or other educational credential awarded as a consequence of successful completion of this course or program.')
    educational_program_mode: Text | URL | list[Text | URL] | None = Field(default=None, alias='educationalProgramMode', description='Similar to courseMode, the medium or means of delivery of the program as a whole. The value may either be a text label (e.g. "online", "onsite" or "blended"; "synchronous" or "asynchronous"; "full-time" or "part-time") or a URL reference to a term from a controlled vocabulary (e.g. https://ceds.ed.gov/element/001311#Asynchronous ).')
    end_date: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='endDate', description='The end date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).')
    financial_aid_eligible: DefinedTerm | Text | list[DefinedTerm | Text] | None = Field(default=None, alias='financialAidEligible', description='A financial aid type or program which students may use to pay for tuition or fees associated with the program.')
    has_course: Course | list[Course] | None = Field(default=None, alias='hasCourse', description='A course or class that is one of the learning opportunities that constitute an educational / occupational program. No information is implied about whether the course is mandatory or optional; no guarantee is implied about whether the course will be available to everyone on the program.')
    maximum_enrollment: Integer | list[Integer] | None = Field(default=None, alias='maximumEnrollment', description='The maximum number of students who may be enrolled in the program.')
    number_of_credits: Integer | StructuredValue | list[Integer | StructuredValue] | None = Field(default=None, alias='numberOfCredits', description='The number of credits or units awarded by a Course or required to complete an EducationalOccupationalProgram.')
    occupational_category: CategoryCode | Text | list[CategoryCode | Text] | None = Field(default=None, alias='occupationalCategory', description='A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\\n\nNote: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.')
    occupational_credential_awarded: EducationalOccupationalCredential | Text | URL | list[EducationalOccupationalCredential | Text | URL] | None = Field(default=None, alias='occupationalCredentialAwarded', description='A description of the qualification, award, certificate, diploma or other occupational credential awarded as a consequence of successful completion of this course or program.')
    offers: Demand | Offer | list[Demand | Offer] | None = Field(default=None, alias='offers', description='An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.\n      \n\nInverse-property: `itemOffered`.')
    program_prerequisites: AlignmentObject | Course | EducationalOccupationalCredential | Text | list[AlignmentObject | Course | EducationalOccupationalCredential | Text] | None = Field(default=None, alias='programPrerequisites', description='Prerequisites for enrolling in the program.')
    program_type: DefinedTerm | Text | list[DefinedTerm | Text] | None = Field(default=None, alias='programType', description='The type of educational or occupational program. For example, classroom, internship, alternance, etc.')
    provider: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='provider', description='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.\n\nSupersedes `carrier`.')
    salary_upon_completion: MonetaryAmountDistribution | list[MonetaryAmountDistribution] | None = Field(default=None, alias='salaryUponCompletion', description='The expected salary upon completing the training.')
    start_date: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='startDate', description='The start date and time of the item (in [ISO 8601 date format](http://en.wikipedia.org/wiki/ISO_8601)).')
    term_duration: Duration | list[Duration] | None = Field(default=None, alias='termDuration', description='The amount of time in a term as defined by the institution. A term is a length of time where students take one or more classes. Semesters and quarters are common units for term.')
    terms_per_year: Number | list[Number] | None = Field(default=None, alias='termsPerYear', description='The number of times terms of study are offered per year. Semesters and quarters are common units for term. For example, if the student can only take 2 semesters for the program in one year, then termsPerYear should be 2.')
    time_of_day: Text | list[Text] | None = Field(default=None, alias='timeOfDay', description='The time of day the program normally runs. For example, "evenings".')
    time_to_complete: Duration | list[Duration] | None = Field(default=None, alias='timeToComplete', description='The expected length of time to complete the program if attending full-time.')
    training_salary: MonetaryAmountDistribution | list[MonetaryAmountDistribution] | None = Field(default=None, alias='trainingSalary', description='The estimated salary earned while in the program.')
    typical_credits_per_term: Integer | StructuredValue | list[Integer | StructuredValue] | None = Field(default=None, alias='typicalCreditsPerTerm', description="The number of credits or units a full-time student would be expected to take in 1 term however 'term' is defined by the institution.")
