# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import DateTime
from schema_org.datatypes import Distance
from schema_org.datatypes import Text
from schema_org.datatypes import Time
from schema_org.datatypes import URL
from schema_org.enums import ActionStatusType
from schema_org.models.play_action import PlayAction

class ExerciseAction(PlayAction):
    __doc__ = 'https://schema.org/ExerciseAction\n\nThe act of participating in exertive activity for the purposes of improving health and fitness.'
    SCHEMA_TYPE: ClassVar[str] = 'ExerciseAction'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('ExerciseAction', 'PlayAction', 'Action', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='action_process', schema_name='actionProcess', schema_url='https://schema.org/actionProcess', ranges=('HowTo',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='Description of the process by which the action was performed.', label='actionProcess', contributors=(), sources=()),
        PropertyMetadata(name='action_status', schema_name='actionStatus', schema_url='https://schema.org/actionStatus', ranges=('ActionStatusType',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='Indicates the current disposition of the Action.', label='actionStatus', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='agent', schema_name='agent', schema_url='https://schema.org/agent', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='The direct performer or driver of the action (animate or inanimate). E.g. *John* wrote a book.', label='agent', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='audience', schema_name='audience', schema_url='https://schema.org/audience', ranges=('Audience',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('serviceAudience',), equivalent_properties=('http://purl.org/dc/terms/audience',), subproperty_of=(), domains=('CreativeWork', 'Event', 'LodgingBusiness', 'PlayAction', 'Product', 'Service'), external_domains=(), comment='An intended audience, i.e. a group for whom something was created.', label='audience', contributors=(), sources=()),
        PropertyMetadata(name='course', schema_name='course', schema_url='https://schema.org/course', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by='exerciseCourse', supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of location. The course where this action was taken.', label='course', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='diet', schema_name='diet', schema_url='https://schema.org/diet', ranges=('Diet',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('instrument',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of instrument. The diet used in this action.', label='diet', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='distance', schema_name='distance', schema_url='https://schema.org/distance', ranges=('Distance',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ExerciseAction', 'TravelAction'), external_domains=(), comment='The distance travelled, e.g. exercising or travelling.', label='distance', contributors=(), sources=()),
        PropertyMetadata(name='end_time', schema_name='endTime', schema_url='https://schema.org/endTime', ranges=('DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action', 'FoodEstablishmentReservation', 'InteractionCounter', 'MediaObject', 'Schedule'), external_domains=(), comment="The endTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to end. For actions that span a period of time, when the action was performed. E.g. John wrote a book from January to *December*. For media, including audio and video, it's the time offset of the end of a clip within a larger file.\\n\\nNote that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.", label='endTime', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2493',)),
        PropertyMetadata(name='error', schema_name='error', schema_url='https://schema.org/error', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='For failed actions, more information on the cause of the failure. Consider using the Error type.', label='error', contributors=(), sources=()),
        PropertyMetadata(name='event', schema_name='event', schema_url='https://schema.org/event', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('events',), equivalent_properties=(), subproperty_of=(), domains=('InformAction', 'InviteAction', 'JoinAction', 'LeaveAction', 'Organization', 'Place', 'PlayAction'), external_domains=(), comment='Upcoming or past event associated with this place, organization, or action.', label='event', contributors=(), sources=()),
        PropertyMetadata(name='exercise_course', schema_name='exerciseCourse', schema_url='https://schema.org/exerciseCourse', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('course',), equivalent_properties=(), subproperty_of=('location',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of location. The course where this action was taken.', label='exerciseCourse', contributors=(), sources=()),
        PropertyMetadata(name='exercise_plan', schema_name='exercisePlan', schema_url='https://schema.org/exercisePlan', ranges=('ExercisePlan',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('instrument',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of instrument. The exercise plan used on this action.', label='exercisePlan', contributors=(), sources=()),
        PropertyMetadata(name='exercise_related_diet', schema_name='exerciseRelatedDiet', schema_url='https://schema.org/exerciseRelatedDiet', ranges=('Diet',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('instrument',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of instrument. The diet used in this action.', label='exerciseRelatedDiet', contributors=(), sources=()),
        PropertyMetadata(name='exercise_type', schema_name='exerciseType', schema_url='https://schema.org/exerciseType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ExerciseAction', 'ExercisePlan'), external_domains=(), comment='Type(s) of exercise or activity, such as strength training, flexibility training, aerobics, cardiac rehabilitation, etc.', label='exerciseType', contributors=(), sources=()),
        PropertyMetadata(name='from_location', schema_name='fromLocation', schema_url='https://schema.org/fromLocation', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('ExerciseAction', 'MoveAction', 'TransferAction'), external_domains=(), comment='A sub property of location. The original location of the object or the agent before the action.', label='fromLocation', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='instrument', schema_name='instrument', schema_url='https://schema.org/instrument', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='The object that helped the agent perform the action. E.g. John wrote a book with *a pen*.', label='instrument', contributors=(), sources=()),
        PropertyMetadata(name='location', schema_name='location', schema_url='https://schema.org/location', ranges=('Place', 'PostalAddress', 'Text', 'VirtualLocation'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/Locations/isLocatedIn',), subproperty_of=(), domains=('Action', 'Event', 'InteractionCounter', 'Organization'), external_domains=(), comment='The location of, for example, where an event is happening, where an organization is located, or where an action takes place.', label='location', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='object', schema_name='object', schema_url='https://schema.org/object', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment="The object upon which the action is carried out, whose state is kept intact or changed. Also known as the semantic roles patient, affected or undergoer (which change their state) or theme (which doesn't). E.g. John read *a book*.", label='object', contributors=(), sources=()),
        PropertyMetadata(name='opponent', schema_name='opponent', schema_url='https://schema.org/opponent', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('participant',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of participant. The opponent on this action.', label='opponent', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='participant', schema_name='participant', schema_url='https://schema.org/participant', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='Other co-agents that participated in the action indirectly. E.g. John wrote a book with *Steve*.', label='participant', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='provider', schema_name='provider', schema_url='https://schema.org/provider', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('carrier',), equivalent_properties=('http://unece.org/vocab#ServiceProvider',), subproperty_of=(), domains=('Action', 'CreativeWork', 'EducationalOccupationalProgram', 'FinancialIncentive', 'Invoice', 'ParcelDelivery', 'Reservation', 'Service', 'Trip'), external_domains=(), comment='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.', label='provider', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2927')),
        PropertyMetadata(name='result', schema_name='result', schema_url='https://schema.org/result', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='The result produced in the action. E.g. John wrote *a book*.', label='result', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='sports_activity_location', schema_name='sportsActivityLocation', schema_url='https://schema.org/sportsActivityLocation', ranges=('SportsActivityLocation',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of location. The sports activity location where this action occurred.', label='sportsActivityLocation', contributors=(), sources=()),
        PropertyMetadata(name='sports_event', schema_name='sportsEvent', schema_url='https://schema.org/sportsEvent', ranges=('SportsEvent',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of location. The sports event where this action occurred.', label='sportsEvent', contributors=(), sources=()),
        PropertyMetadata(name='sports_team', schema_name='sportsTeam', schema_url='https://schema.org/sportsTeam', ranges=('SportsTeam',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('participant',), domains=('ExerciseAction',), external_domains=(), comment='A sub property of participant. The sports team that participated on this action.', label='sportsTeam', contributors=(), sources=()),
        PropertyMetadata(name='start_time', schema_name='startTime', schema_url='https://schema.org/startTime', ranges=('DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action', 'FoodEstablishmentReservation', 'InteractionCounter', 'MediaObject', 'Schedule'), external_domains=(), comment="The startTime of something. For a reserved event or service (e.g. FoodEstablishmentReservation), the time that it is expected to start. For actions that span a period of time, when the action was performed. E.g. John wrote a book from *January* to December. For media, including audio and video, it's the time offset of the start of a clip within a larger file.\\n\\nNote that Event uses startDate/endDate instead of startTime/endTime, even when describing dates with times. This situation may be clarified in future revisions.", label='startTime', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2493',)),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='target', schema_name='target', schema_url='https://schema.org/target', ranges=('EntryPoint', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Action',), external_domains=(), comment='Indicates a target EntryPoint, or url, for an Action.', label='target', contributors=(), sources=()),
        PropertyMetadata(name='to_location', schema_name='toLocation', schema_url='https://schema.org/toLocation', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('ExerciseAction', 'InsertAction', 'MoveAction', 'TransferAction'), external_domains=(), comment='A sub property of location. The final location of the object or the agent after the action.', label='toLocation', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['ExerciseAction'] = Field(default='ExerciseAction', alias='@type', frozen=True)
    course: Place | list[Place] | None = Field(default=None, alias='course', description='A sub property of location. The course where this action was taken.\n\nSuperseded by `exerciseCourse`.')
    diet: Diet | list[Diet] | None = Field(default=None, alias='diet', description='A sub property of instrument. The diet used in this action.')
    distance: Distance | list[Distance] | None = Field(default=None, alias='distance', description='The distance travelled, e.g. exercising or travelling.')
    exercise_course: Place | list[Place] | None = Field(default=None, alias='exerciseCourse', description='A sub property of location. The course where this action was taken.\n\nSupersedes `course`.')
    exercise_plan: ExercisePlan | list[ExercisePlan] | None = Field(default=None, alias='exercisePlan', description='A sub property of instrument. The exercise plan used on this action.')
    exercise_related_diet: Diet | list[Diet] | None = Field(default=None, alias='exerciseRelatedDiet', description='A sub property of instrument. The diet used in this action.')
    exercise_type: Text | list[Text] | None = Field(default=None, alias='exerciseType', description='Type(s) of exercise or activity, such as strength training, flexibility training, aerobics, cardiac rehabilitation, etc.')
    from_location: Place | list[Place] | None = Field(default=None, alias='fromLocation', description='A sub property of location. The original location of the object or the agent before the action.')
    opponent: Person | list[Person] | None = Field(default=None, alias='opponent', description='A sub property of participant. The opponent on this action.')
    sports_activity_location: SportsActivityLocation | list[SportsActivityLocation] | None = Field(default=None, alias='sportsActivityLocation', description='A sub property of location. The sports activity location where this action occurred.')
    sports_event: SportsEvent | list[SportsEvent] | None = Field(default=None, alias='sportsEvent', description='A sub property of location. The sports event where this action occurred.')
    sports_team: SportsTeam | list[SportsTeam] | None = Field(default=None, alias='sportsTeam', description='A sub property of participant. The sports team that participated on this action.')
    to_location: Place | list[Place] | None = Field(default=None, alias='toLocation', description='A sub property of location. The final location of the object or the agent after the action.')
