# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.intangible import Intangible

class FloorPlan(Intangible):
    __doc__ = 'https://schema.org/FloorPlan\n\nA FloorPlan is an explicit representation of a collection of similar accommodations, allowing the provision of common information (room counts, sizes, layout diagrams) and offers for rental or sale. In typical use, some [[ApartmentComplex]] has an [[accommodationFloorPlan]] which is a [[FloorPlan]].  A FloorPlan is always in the context of a particular place, either a larger [[ApartmentComplex]] or a single [[Apartment]]. The visual/spatial aspects of a floor plan (i.e. room layout, [see wikipedia](https://en.wikipedia.org/wiki/Floor_plan)) can be indicated using [[image]]. '
    SCHEMA_TYPE: ClassVar[str] = 'FloorPlan'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('FloorPlan', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='amenity_feature', schema_name='amenityFeature', schema_url='https://schema.org/amenityFeature', ranges=('LocationFeatureSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan', 'LodgingBusiness', 'Place'), external_domains=(), comment='An amenity feature (e.g. a characteristic or service) of the Accommodation. This generic property does not make a statement about whether the feature is included in an offer for the main accommodation or available at extra costs.', label='amenityFeature', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='floor_size', schema_name='floorSize', schema_url='https://schema.org/floorSize', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan'), external_domains=(), comment='The size of the accommodation, e.g. in square meter or squarefoot.\nTypical unit code(s): MTK for square meter, FTK for square foot, or YDK for square yard.', label='floorSize', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='is_plan_for_apartment', schema_name='isPlanForApartment', schema_url='https://schema.org/isPlanForApartment', ranges=('Accommodation',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('FloorPlan',), external_domains=(), comment='Indicates some accommodation that this floor plan describes.', label='isPlanForApartment', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='layout_image', schema_name='layoutImage', schema_url='https://schema.org/layoutImage', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('image',), domains=('FloorPlan',), external_domains=(), comment='A schematic image showing the floorplan layout.', label='layoutImage', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2690',)),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='number_of_accommodation_units', schema_name='numberOfAccommodationUnits', schema_url='https://schema.org/numberOfAccommodationUnits', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ApartmentComplex', 'FloorPlan'), external_domains=(), comment='Indicates the total (available plus unavailable) number of accommodation units in an [[ApartmentComplex]], or the number of accommodation units for a specific [[FloorPlan]] (within its specific [[ApartmentComplex]]). See also [[numberOfAvailableAccommodationUnits]].', label='numberOfAccommodationUnits', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='number_of_available_accommodation_units', schema_name='numberOfAvailableAccommodationUnits', schema_url='https://schema.org/numberOfAvailableAccommodationUnits', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ApartmentComplex', 'FloorPlan'), external_domains=(), comment='Indicates the number of available accommodation units in an [[ApartmentComplex]], or the number of accommodation units for a specific [[FloorPlan]] (within its specific [[ApartmentComplex]]). See also [[numberOfAccommodationUnits]].', label='numberOfAvailableAccommodationUnits', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='number_of_bathrooms_total', schema_name='numberOfBathroomsTotal', schema_url='https://schema.org/numberOfBathroomsTotal', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan'), external_domains=(), comment='The total integer number of bathrooms in some [[Accommodation]], following real estate conventions as [documented in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsTotalInteger+Field): "The simple sum of the number of bathrooms. For example for a property with two Full Bathrooms and one Half Bathroom, the Bathrooms Total Integer will be 3.". See also [[numberOfRooms]].', label='numberOfBathroomsTotal', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='number_of_bedrooms', schema_name='numberOfBedrooms', schema_url='https://schema.org/numberOfBedrooms', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'ApartmentComplex', 'FloorPlan'), external_domains=(), comment='The total integer number of bedrooms in a some [[Accommodation]], [[ApartmentComplex]] or [[FloorPlan]].', label='numberOfBedrooms', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='number_of_full_bathrooms', schema_name='numberOfFullBathrooms', schema_url='https://schema.org/numberOfFullBathrooms', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan'), external_domains=(), comment='Number of full bathrooms - The total number of full and ¾ bathrooms in an [[Accommodation]]. This corresponds to the [BathroomsFull field in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsFull+Field).', label='numberOfFullBathrooms', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='number_of_partial_bathrooms', schema_name='numberOfPartialBathrooms', schema_url='https://schema.org/numberOfPartialBathrooms', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan'), external_domains=(), comment='Number of partial bathrooms - The total number of half and ¼ bathrooms in an [[Accommodation]]. This corresponds to the [BathroomsPartial field in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsPartial+Field). ', label='numberOfPartialBathrooms', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='number_of_rooms', schema_name='numberOfRooms', schema_url='https://schema.org/numberOfRooms', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'Apartment', 'FloorPlan', 'House', 'LodgingBusiness', 'SingleFamilyResidence', 'Suite'), external_domains=(), comment='The number of rooms (excluding bathrooms and closets) of the accommodation or lodging business.\nTypical unit code(s): ROM for room or C62 for no unit. The type of room can be put in the unitText property of the QuantitativeValue.', label='numberOfRooms', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='pets_allowed', schema_name='petsAllowed', schema_url='https://schema.org/petsAllowed', ranges=('Boolean', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'ApartmentComplex', 'FloorPlan', 'LodgingBusiness'), external_domains=(), comment='Indicates whether pets are allowed to enter the accommodation or lodging business. More detailed information can be put in a text value.', label='petsAllowed', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['FloorPlan'] = Field(default='FloorPlan', alias='@type', frozen=True)
    amenity_feature: LocationFeatureSpecification | list[LocationFeatureSpecification] | None = Field(default=None, alias='amenityFeature', description='An amenity feature (e.g. a characteristic or service) of the Accommodation. This generic property does not make a statement about whether the feature is included in an offer for the main accommodation or available at extra costs.')
    floor_size: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='floorSize', description='The size of the accommodation, e.g. in square meter or squarefoot.\nTypical unit code(s): MTK for square meter, FTK for square foot, or YDK for square yard.')
    is_plan_for_apartment: Accommodation | list[Accommodation] | None = Field(default=None, alias='isPlanForApartment', description='Indicates some accommodation that this floor plan describes.')
    layout_image: ImageObject | URL | list[ImageObject | URL] | None = Field(default=None, alias='layoutImage', description='A schematic image showing the floorplan layout.')
    number_of_accommodation_units: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='numberOfAccommodationUnits', description='Indicates the total (available plus unavailable) number of accommodation units in an [[ApartmentComplex]], or the number of accommodation units for a specific [[FloorPlan]] (within its specific [[ApartmentComplex]]). See also [[numberOfAvailableAccommodationUnits]].')
    number_of_available_accommodation_units: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='numberOfAvailableAccommodationUnits', description='Indicates the number of available accommodation units in an [[ApartmentComplex]], or the number of accommodation units for a specific [[FloorPlan]] (within its specific [[ApartmentComplex]]). See also [[numberOfAccommodationUnits]].')
    number_of_bathrooms_total: Integer | list[Integer] | None = Field(default=None, alias='numberOfBathroomsTotal', description='The total integer number of bathrooms in some [[Accommodation]], following real estate conventions as [documented in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsTotalInteger+Field): "The simple sum of the number of bathrooms. For example for a property with two Full Bathrooms and one Half Bathroom, the Bathrooms Total Integer will be 3.". See also [[numberOfRooms]].')
    number_of_bedrooms: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='numberOfBedrooms', description='The total integer number of bedrooms in a some [[Accommodation]], [[ApartmentComplex]] or [[FloorPlan]].')
    number_of_full_bathrooms: Number | list[Number] | None = Field(default=None, alias='numberOfFullBathrooms', description='Number of full bathrooms - The total number of full and ¾ bathrooms in an [[Accommodation]]. This corresponds to the [BathroomsFull field in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsFull+Field).')
    number_of_partial_bathrooms: Number | list[Number] | None = Field(default=None, alias='numberOfPartialBathrooms', description='Number of partial bathrooms - The total number of half and ¼ bathrooms in an [[Accommodation]]. This corresponds to the [BathroomsPartial field in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsPartial+Field). ')
    number_of_rooms: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='numberOfRooms', description='The number of rooms (excluding bathrooms and closets) of the accommodation or lodging business.\nTypical unit code(s): ROM for room or C62 for no unit. The type of room can be put in the unitText property of the QuantitativeValue.')
    pets_allowed: Boolean | Text | list[Boolean | Text] | None = Field(default=None, alias='petsAllowed', description='Indicates whether pets are allowed to enter the accommodation or lodging business. More detailed information can be put in a text value.')
