# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import GovernmentBenefitsType
from schema_org.enums import PhysicalActivityCategory
from schema_org.models.service import Service

class FoodService(Service):
    __doc__ = 'https://schema.org/FoodService\n\nA food service, like breakfast, lunch, or dinner.'
    SCHEMA_TYPE: ClassVar[str] = 'FoodService'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('FoodService', 'Service', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='aggregate_rating', schema_name='aggregateRating', schema_url='https://schema.org/aggregateRating', ranges=('AggregateRating',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='The overall rating, based on a collection of reviews or ratings, of the item.', label='aggregateRating', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='area_served', schema_name='areaServed', schema_url='https://schema.org/areaServed', ranges=('AdministrativeArea', 'GeoShape', 'Place', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='serviceArea', equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasServiceArea',), subproperty_of=(), domains=('ContactPoint', 'DeliveryChargeSpecification', 'Demand', 'FinancialIncentive', 'Offer', 'Organization', 'Service'), external_domains=(), comment='The geographic area where a service or offered item is provided.', label='areaServed', contributors=(), sources=()),
        PropertyMetadata(name='audience', schema_name='audience', schema_url='https://schema.org/audience', ranges=('Audience',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='serviceAudience', equivalent_properties=('http://purl.org/dc/terms/audience',), subproperty_of=(), domains=('CreativeWork', 'Event', 'LodgingBusiness', 'PlayAction', 'Product', 'Service'), external_domains=(), comment='An intended audience, i.e. a group for whom something was created.', label='audience', contributors=(), sources=()),
        PropertyMetadata(name='available_channel', schema_name='availableChannel', schema_url='https://schema.org/availableChannel', ranges=('ServiceChannel',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment='A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).', label='availableChannel', contributors=(), sources=()),
        PropertyMetadata(name='award', schema_name='award', schema_url='https://schema.org/award', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='awards', equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='An award won by or for this item.', label='award', contributors=(), sources=()),
        PropertyMetadata(name='brand', schema_name='brand', schema_url='https://schema.org/brand', ranges=('Brand', 'Organization'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#brandName',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/hasDesignation',), domains=('Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.', label='brand', contributors=(), sources=()),
        PropertyMetadata(name='broker', schema_name='broker', schema_url='https://schema.org/broker', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='bookingAgent', equivalent_properties=(), subproperty_of=(), domains=('Invoice', 'Order', 'Reservation', 'Service'), external_domains=(), comment='An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.', label='broker', contributors=(), sources=()),
        PropertyMetadata(name='category', schema_name='category', schema_url='https://schema.org/category', ranges=('CategoryCode', 'PhysicalActivityCategory', 'Text', 'Thing', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ActionAccessSpecification', 'Guide', 'Invoice', 'Offer', 'PhysicalActivity', 'Product', 'Recommendation', 'Service', 'SpecialAnnouncement'), external_domains=(), comment='A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.', label='category', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1741', 'https://github.com/schemaorg/schemaorg/issues/2490')),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='has_certification', schema_name='hasCertification', schema_url='https://schema.org/hasCertification', ranges=('Certification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#ApplicableCertificate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/isReferencedIn', 'https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy'), domains=('Organization', 'Person', 'Place', 'Product', 'Service'), external_domains=(), comment='Certification information about a product, organization, service, place, or person.', label='hasCertification', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3230',)),
        PropertyMetadata(name='has_offer_catalog', schema_name='hasOfferCatalog', schema_url='https://schema.org/hasOfferCatalog', ranges=('OfferCatalog',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person', 'Service'), external_domains=(), comment='Indicates an OfferCatalog listing for this Organization, Person, or Service.', label='hasOfferCatalog', contributors=(), sources=()),
        PropertyMetadata(name='hours_available', schema_name='hoursAvailable', schema_url='https://schema.org/hoursAvailable', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ContactPoint', 'LocationFeatureSpecification', 'Service'), external_domains=(), comment='The hours during which this service or contact is available.', label='hoursAvailable', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='is_related_to', schema_name='isRelatedTo', schema_url='https://schema.org/isRelatedTo', ranges=('Product', 'Service'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#RelatedProduct',), subproperty_of=(), domains=('Product', 'Service'), external_domains=(), comment='A pointer to another, somehow related product (or multiple products).', label='isRelatedTo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='is_similar_to', schema_name='isSimilarTo', schema_url='https://schema.org/isSimilarTo', ranges=('Product', 'Service'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#SubstituteProduct',), subproperty_of=(), domains=('Product', 'Service'), external_domains=(), comment='A pointer to another, functionally similar product (or multiple products).', label='isSimilarTo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='logo', schema_name='logo', schema_url='https://schema.org/logo', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#logoReferencedDocument',), subproperty_of=('image',), domains=('Brand', 'Certification', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='An associated logo.', label='logo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='offers', schema_name='offers', schema_url='https://schema.org/offers', ranges=('Demand', 'Offer'), external_ranges=(), inverse_of='itemOffered', superseded_by=None, supersedes=None, equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/isProductOf',), subproperty_of=(), domains=('AggregateOffer', 'CreativeWork', 'EducationalOccupationalProgram', 'Event', 'MenuItem', 'Product', 'Service', 'Trip'), external_domains=(), comment='An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.\n      ', label='offers', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='produces', schema_name='produces', schema_url='https://schema.org/produces', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by='serviceOutput', supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment='The tangible thing generated by the service, e.g. a passport, permit, etc.', label='produces', contributors=(), sources=()),
        PropertyMetadata(name='provider', schema_name='provider', schema_url='https://schema.org/provider', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='carrier', equivalent_properties=('http://unece.org/vocab#ServiceProvider',), subproperty_of=(), domains=('Action', 'CreativeWork', 'EducationalOccupationalProgram', 'FinancialIncentive', 'Invoice', 'ParcelDelivery', 'Reservation', 'Service', 'Trip'), external_domains=(), comment='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.', label='provider', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2927')),
        PropertyMetadata(name='provider_mobility', schema_name='providerMobility', schema_url='https://schema.org/providerMobility', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment="Indicates the mobility of a provided service (e.g. 'static', 'dynamic').", label='providerMobility', contributors=(), sources=()),
        PropertyMetadata(name='review', schema_name='review', schema_url='https://schema.org/review', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='reviews', equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A review of the item.', label='review', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='service_area', schema_name='serviceArea', schema_url='https://schema.org/serviceArea', ranges=('AdministrativeArea', 'GeoShape', 'Place'), external_ranges=(), inverse_of=None, superseded_by='areaServed', supersedes='area', equivalent_properties=(), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Service'), external_domains=(), comment='The geographic area where the service is provided.', label='serviceArea', contributors=(), sources=()),
        PropertyMetadata(name='service_audience', schema_name='serviceAudience', schema_url='https://schema.org/serviceAudience', ranges=('Audience',), external_ranges=(), inverse_of=None, superseded_by='audience', supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment='The audience eligible for this service.', label='serviceAudience', contributors=(), sources=()),
        PropertyMetadata(name='service_output', schema_name='serviceOutput', schema_url='https://schema.org/serviceOutput', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='produces', equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment='The tangible thing generated by the service, e.g. a passport, permit, etc.', label='serviceOutput', contributors=(), sources=()),
        PropertyMetadata(name='service_type', schema_name='serviceType', schema_url='https://schema.org/serviceType', ranges=('GovernmentBenefitsType', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment="The type of service being offered, e.g. veterans' benefits, emergency relief, etc.", label='serviceType', contributors=(), sources=()),
        PropertyMetadata(name='slogan', schema_name='slogan', schema_url='https://schema.org/slogan', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#PromotionalMessage',), subproperty_of=(), domains=('Brand', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A slogan or motto associated with the item.', label='slogan', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='terms_of_service', schema_name='termsOfService', schema_url='https://schema.org/termsOfService', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Service',), external_domains=(), comment='Human-readable terms of service documentation.', label='termsOfService', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1423',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['FoodService'] = Field(default='FoodService', alias='@type', frozen=True)
