# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.structured_value import StructuredValue

class GeoCoordinates(StructuredValue):
    __doc__ = 'https://schema.org/GeoCoordinates\n\nThe geographic coordinates of a place or event.'
    SCHEMA_TYPE: ClassVar[str] = 'GeoCoordinates'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('GeoCoordinates', 'StructuredValue', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='address', schema_name='address', schema_url='https://schema.org/address', ranges=('PostalAddress', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('https://ref.gs1.org/voc/address',), subproperty_of=(), domains=('GeoCoordinates', 'GeoShape', 'Organization', 'Person', 'Place'), external_domains=(), comment='Physical address of the item.', label='address', contributors=(), sources=()),
        PropertyMetadata(name='address_country', schema_name='addressCountry', schema_url='https://schema.org/addressCountry', ranges=('Country', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('DefinedRegion', 'GeoCoordinates', 'GeoShape', 'PostalAddress'), external_domains=(), comment='The country. Recommended to be in 2-letter [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1) format, for example "US". For backward compatibility, a 3-letter [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) country code such as "SGP" or a full country name such as "Singapore" can also be used.', label='addressCountry', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506',)),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='elevation', schema_name='elevation', schema_url='https://schema.org/elevation', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('GeoCoordinates', 'GeoShape'), external_domains=(), comment="The elevation of a location ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)). Values may be of the form 'NUMBER UNIT\\_OF\\_MEASUREMENT' (e.g., '1,000 m', '3,200 ft') while numbers alone should be assumed to be a value in meters.", label='elevation', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='latitude', schema_name='latitude', schema_url='https://schema.org/latitude', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLatitude',), domains=('GeoCoordinates', 'Place'), external_domains=(), comment='The latitude of a location. For example ```37.42242``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).', label='latitude', contributors=(), sources=()),
        PropertyMetadata(name='longitude', schema_name='longitude', schema_url='https://schema.org/longitude', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLongitude',), domains=('GeoCoordinates', 'Place'), external_domains=(), comment='The longitude of a location. For example ```-122.08585``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).', label='longitude', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='postal_code', schema_name='postalCode', schema_url='https://schema.org/postalCode', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#postcodeCode', 'https://ref.gs1.org/voc/postalCode', 'https://spec.edmcouncil.org/fibo/ontology/FND/Places/Addresses/hasPostalCode'), subproperty_of=(), domains=('DefinedRegion', 'GeoCoordinates', 'GeoShape', 'PostalAddress'), external_domains=(), comment='The postal code. For example, 94043.', label='postalCode', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['GeoCoordinates'] = Field(default='GeoCoordinates', alias='@type', frozen=True)
    address: PostalAddress | Text | list[PostalAddress | Text] | None = Field(default=None, alias='address', description='Physical address of the item.')
    address_country: Country | Text | list[Country | Text] | None = Field(default=None, alias='addressCountry', description='The country. Recommended to be in 2-letter [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1) format, for example "US". For backward compatibility, a 3-letter [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) country code such as "SGP" or a full country name such as "Singapore" can also be used.')
    elevation: Number | Text | list[Number | Text] | None = Field(default=None, alias='elevation', description="The elevation of a location ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)). Values may be of the form 'NUMBER UNIT\\_OF\\_MEASUREMENT' (e.g., '1,000 m', '3,200 ft') while numbers alone should be assumed to be a value in meters.")
    latitude: Number | Text | list[Number | Text] | None = Field(default=None, alias='latitude', description='The latitude of a location. For example ```37.42242``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).')
    longitude: Number | Text | list[Number | Text] | None = Field(default=None, alias='longitude', description='The longitude of a location. For example ```-122.08585``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).')
    postal_code: Text | list[Text] | None = Field(default=None, alias='postalCode', description='The postal code. For example, 94043.')
