# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.intangible import Intangible

class HealthInsurancePlan(Intangible):
    __doc__ = 'A US-style health insurance plan, including PPOs, EPOs, and HMOs.'
    SCHEMA_TYPE: ClassVar[str] = 'HealthInsurancePlan'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('HealthInsurancePlan', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='benefits_summary_url', schema_name='benefitsSummaryUrl', schema_url='https://schema.org/benefitsSummaryUrl', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='The URL that goes directly to the summary of benefits and coverage for the specific standard plan or plan variation.', label='benefitsSummaryUrl', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='contact_point', schema_name='contactPoint', schema_url='https://schema.org/contactPoint', ranges=('ContactPoint',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='contactPoints', equivalent_properties=('https://ref.gs1.org/voc/contactPoint', 'https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/Organizations/hasContactPoint'), subproperty_of=(), domains=('HealthInsurancePlan', 'Organization', 'Person'), external_domains=(), comment='A contact point for a person or organization.', label='contactPoint', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='health_plan_drug_option', schema_name='healthPlanDrugOption', schema_url='https://schema.org/healthPlanDrugOption', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='TODO.', label='healthPlanDrugOption', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='health_plan_drug_tier', schema_name='healthPlanDrugTier', schema_url='https://schema.org/healthPlanDrugTier', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan', 'HealthPlanFormulary'), external_domains=(), comment='The tier(s) of drugs offered by this formulary or insurance plan.', label='healthPlanDrugTier', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='health_plan_id', schema_name='healthPlanId', schema_url='https://schema.org/healthPlanId', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='The 14-character, HIOS-generated Plan ID number. (Plan IDs must be unique, even across different markets.)', label='healthPlanId', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='health_plan_marketing_url', schema_name='healthPlanMarketingUrl', schema_url='https://schema.org/healthPlanMarketingUrl', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='The URL that goes directly to the plan brochure for the specific standard plan or plan variation.', label='healthPlanMarketingUrl', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='includes_health_plan_formulary', schema_name='includesHealthPlanFormulary', schema_url='https://schema.org/includesHealthPlanFormulary', ranges=('HealthPlanFormulary',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='Formularies covered by this plan.', label='includesHealthPlanFormulary', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='includes_health_plan_network', schema_name='includesHealthPlanNetwork', schema_url='https://schema.org/includesHealthPlanNetwork', ranges=('HealthPlanNetwork',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='Networks covered by this plan.', label='includesHealthPlanNetwork', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='uses_health_plan_id_standard', schema_name='usesHealthPlanIdStandard', schema_url='https://schema.org/usesHealthPlanIdStandard', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('HealthInsurancePlan',), external_domains=(), comment='The standard for interpreting the Plan ID. The preferred is "HIOS". See the Centers for Medicare & Medicaid Services for more details.', label='usesHealthPlanIdStandard', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1062',)),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['HealthInsurancePlan'] = Field(default='HealthInsurancePlan', alias='@type', frozen=True)
    benefits_summary_url: URL | list[URL] | None = Field(default=None, alias='benefitsSummaryUrl', description='The URL that goes directly to the summary of benefits and coverage for the specific standard plan or plan variation.')
    contact_point: ContactPoint | list[ContactPoint] | None = Field(default=None, alias='contactPoint', description='A contact point for a person or organization.')
    health_plan_drug_option: Text | list[Text] | None = Field(default=None, alias='healthPlanDrugOption', description='TODO.')
    health_plan_drug_tier: Text | list[Text] | None = Field(default=None, alias='healthPlanDrugTier', description='The tier(s) of drugs offered by this formulary or insurance plan.')
    health_plan_id: Text | list[Text] | None = Field(default=None, alias='healthPlanId', description='The 14-character, HIOS-generated Plan ID number. (Plan IDs must be unique, even across different markets.)')
    health_plan_marketing_url: URL | list[URL] | None = Field(default=None, alias='healthPlanMarketingUrl', description='The URL that goes directly to the plan brochure for the specific standard plan or plan variation.')
    includes_health_plan_formulary: HealthPlanFormulary | list[HealthPlanFormulary] | None = Field(default=None, alias='includesHealthPlanFormulary', description='Formularies covered by this plan.')
    includes_health_plan_network: HealthPlanNetwork | list[HealthPlanNetwork] | None = Field(default=None, alias='includesHealthPlanNetwork', description='Networks covered by this plan.')
    uses_health_plan_id_standard: Text | URL | list[Text | URL] | None = Field(default=None, alias='usesHealthPlanIdStandard', description='The standard for interpreting the Plan ID. The preferred is "HIOS". See the Centers for Medicare & Medicaid Services for more details.')
