# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Duration
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import PaymentStatusType
from schema_org.enums import PhysicalActivityCategory
from schema_org.models.intangible import Intangible

class Invoice(Intangible):
    __doc__ = 'A statement of the money due for goods or services; a bill.'
    SCHEMA_TYPE: ClassVar[str] = 'Invoice'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Invoice', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='account_id', schema_name='accountId', schema_url='https://schema.org/accountId', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('identifier',), domains=('Invoice',), external_domains=(), comment='The identifier for the account the payment will be applied to.', label='accountId', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='billing_period', schema_name='billingPeriod', schema_url='https://schema.org/billingPeriod', ranges=('Duration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#billingPeriod',), subproperty_of=(), domains=('Invoice',), external_domains=(), comment='The time interval used to compute the invoice.', label='billingPeriod', contributors=(), sources=()),
        PropertyMetadata(name='broker', schema_name='broker', schema_url='https://schema.org/broker', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='bookingAgent', equivalent_properties=(), subproperty_of=(), domains=('Invoice', 'Order', 'Reservation', 'Service'), external_domains=(), comment='An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.', label='broker', contributors=(), sources=()),
        PropertyMetadata(name='category', schema_name='category', schema_url='https://schema.org/category', ranges=('CategoryCode', 'PhysicalActivityCategory', 'Text', 'Thing', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ActionAccessSpecification', 'Guide', 'Invoice', 'Offer', 'PhysicalActivity', 'Product', 'Recommendation', 'Service', 'SpecialAnnouncement'), external_domains=(), comment='A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.', label='category', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1741', 'https://github.com/schemaorg/schemaorg/issues/2490')),
        PropertyMetadata(name='confirmation_number', schema_name='confirmationNumber', schema_url='https://schema.org/confirmationNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('identifier',), domains=('Invoice', 'Order'), external_domains=(), comment='A number that confirms the given order or payment has been received.', label='confirmationNumber', contributors=(), sources=()),
        PropertyMetadata(name='customer', schema_name='customer', schema_url='https://schema.org/customer', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Invoice', 'Order'), external_domains=(), comment='Party placing the order or paying the invoice.', label='customer', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='minimum_payment_due', schema_name='minimumPaymentDue', schema_url='https://schema.org/minimumPaymentDue', ranges=('MonetaryAmount', 'PriceSpecification'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/hasMonetaryAmount', 'https://www.omg.org/spec/Commons/Quantities/hasLowerBound'), domains=('Invoice',), external_domains=(), comment='The minimum payment required at this time.', label='minimumPaymentDue', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='payment_due', schema_name='paymentDue', schema_url='https://schema.org/paymentDue', ranges=('DateTime',), external_ranges=(), inverse_of=None, superseded_by='paymentDueDate', supersedes=None, equivalent_properties=('http://unece.org/vocab#PaymentDueDate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt/hasPaymentDueDate',), domains=('Invoice', 'Order'), external_domains=(), comment='The date that payment is due.', label='paymentDue', contributors=(), sources=()),
        PropertyMetadata(name='payment_due_date', schema_name='paymentDueDate', schema_url='https://schema.org/paymentDueDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='paymentDue', equivalent_properties=('http://unece.org/vocab#PaymentDueDate',), subproperty_of=(), domains=('Invoice', 'Order'), external_domains=(), comment='The date that payment is due.', label='paymentDueDate', contributors=(), sources=()),
        PropertyMetadata(name='payment_method', schema_name='paymentMethod', schema_url='https://schema.org/paymentMethod', ranges=('PaymentMethod', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/hasPaymentMechanism',), domains=('Invoice', 'Order'), external_domains=(), comment='The name of the credit card or other method of payment for the order.', label='paymentMethod', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3537',)),
        PropertyMetadata(name='payment_method_id', schema_name='paymentMethodId', schema_url='https://schema.org/paymentMethodId', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#PaymentMeansID',), subproperty_of=(), domains=('Invoice', 'Order'), external_domains=(), comment='An identifier for the method of payment used (e.g. the last 4 digits of the credit card).', label='paymentMethodId', contributors=(), sources=()),
        PropertyMetadata(name='payment_status', schema_name='paymentStatus', schema_url='https://schema.org/paymentStatus', ranges=('PaymentStatusType', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Invoice',), external_domains=(), comment='The status of payment; whether the invoice has been paid or not.', label='paymentStatus', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='provider', schema_name='provider', schema_url='https://schema.org/provider', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='carrier', equivalent_properties=('http://unece.org/vocab#ServiceProvider',), subproperty_of=(), domains=('Action', 'CreativeWork', 'EducationalOccupationalProgram', 'FinancialIncentive', 'Invoice', 'ParcelDelivery', 'Reservation', 'Service', 'Trip'), external_domains=(), comment='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.', label='provider', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2927')),
        PropertyMetadata(name='references_order', schema_name='referencesOrder', schema_url='https://schema.org/referencesOrder', ranges=('Order',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Invoice',), external_domains=(), comment='The Order(s) related to this Invoice. One or more Orders may be combined into a single Invoice.', label='referencesOrder', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='scheduled_payment_date', schema_name='scheduledPaymentDate', schema_url='https://schema.org/scheduledPaymentDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Invoice',), external_domains=(), comment='The date the invoice is scheduled to be paid.', label='scheduledPaymentDate', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='total_payment_due', schema_name='totalPaymentDue', schema_url='https://schema.org/totalPaymentDue', ranges=('MonetaryAmount', 'PriceSpecification'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Invoice',), external_domains=(), comment='The total amount due.', label='totalPaymentDue', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Invoice'] = Field(default='Invoice', alias='@type', frozen=True)
    account_id: Text | list[Text] | None = Field(default=None, alias='accountId', description='The identifier for the account the payment will be applied to.')
    billing_period: Duration | list[Duration] | None = Field(default=None, alias='billingPeriod', description='The time interval used to compute the invoice.')
    broker: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='broker', description='An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.')
    category: CategoryCode | PhysicalActivityCategory | Text | Thing | URL | list[CategoryCode | PhysicalActivityCategory | Text | Thing | URL] | None = Field(default=None, alias='category', description='A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.')
    confirmation_number: Text | list[Text] | None = Field(default=None, alias='confirmationNumber', description='A number that confirms the given order or payment has been received.')
    customer: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='customer', description='Party placing the order or paying the invoice.')
    minimum_payment_due: MonetaryAmount | PriceSpecification | list[MonetaryAmount | PriceSpecification] | None = Field(default=None, alias='minimumPaymentDue', description='The minimum payment required at this time.')
    payment_due: DateTime | list[DateTime] | None = Field(default=None, alias='paymentDue', description='The date that payment is due.')
    payment_due_date: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='paymentDueDate', description='The date that payment is due.')
    payment_method: PaymentMethod | Text | list[PaymentMethod | Text] | None = Field(default=None, alias='paymentMethod', description='The name of the credit card or other method of payment for the order.')
    payment_method_id: Text | list[Text] | None = Field(default=None, alias='paymentMethodId', description='An identifier for the method of payment used (e.g. the last 4 digits of the credit card).')
    payment_status: PaymentStatusType | Text | list[PaymentStatusType | Text] | None = Field(default=None, alias='paymentStatus', description='The status of payment; whether the invoice has been paid or not.')
    provider: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='provider', description='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.')
    references_order: Order | list[Order] | None = Field(default=None, alias='referencesOrder', description='The Order(s) related to this Invoice. One or more Orders may be combined into a single Invoice.')
    scheduled_payment_date: Date | list[Date] | None = Field(default=None, alias='scheduledPaymentDate', description='The date the invoice is scheduled to be paid.')
    total_payment_due: MonetaryAmount | PriceSpecification | list[MonetaryAmount | PriceSpecification] | None = Field(default=None, alias='totalPaymentDue', description='The total amount due.')
