# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar, Literal

from pydantic import Field

from schema_org.base import PropertyMetadata
from schema_org.models.intangible import Intangible

if TYPE_CHECKING:
    from schema_org.datatypes import (
        URL,
        Boolean,
        Date,
        DateTime,
        Duration,
        Integer,
        Number,
        Text,
    )
    from schema_org.models import (
        AdministrativeArea,
        CategoryCode,
        ContactPoint,
        Credential,
        DefinedTerm,
        EducationalOccupationalCredential,
        MonetaryAmount,
        MonetaryAmountDistribution,
        Occupation,
        OccupationalExperienceRequirements,
        Organization,
        Person,
        Place,
        PriceSpecification,
        QuantitativeValue,
    )


class JobPosting(Intangible):
    __doc__ = 'https://schema.org/JobPosting\n\nA listing that describes a job opening in a certain organization.'
    SCHEMA_TYPE: ClassVar[str] = 'JobPosting'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('JobPosting', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='applicant_location_requirements', schema_name='applicantLocationRequirements', schema_url='https://schema.org/applicantLocationRequirements', ranges=('AdministrativeArea',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The location(s) applicants can apply from. This is usually used for telecommuting jobs where the applicant does not need to be in a physical office. Note: This should not be used for citizenship or work visa requirements.', label='applicantLocationRequirements', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2083',)),
        PropertyMetadata(name='application_contact', schema_name='applicationContact', schema_url='https://schema.org/applicationContact', ranges=('ContactPoint',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Contact details for further information relevant to this job posting.', label='applicationContact', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2396',)),
        PropertyMetadata(name='base_salary', schema_name='baseSalary', schema_url='https://schema.org/baseSalary', ranges=('MonetaryAmount', 'Number', 'PriceSpecification'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('EmployeeRole', 'JobPosting'), external_domains=(), comment='The base salary of the job or of an employee in an EmployeeRole.', label='baseSalary', contributors=(), sources=()),
        PropertyMetadata(name='benefits', schema_name='benefits', schema_url='https://schema.org/benefits', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by='jobBenefits', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Description of benefits associated with the job.', label='benefits', contributors=(), sources=()),
        PropertyMetadata(name='date_posted', schema_name='datePosted', schema_url='https://schema.org/datePosted', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CDCPMDRecord', 'JobPosting', 'RealEstateListing', 'SpecialAnnouncement'), external_domains=(), comment='Publication date of an online listing.', label='datePosted', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2490', 'https://github.com/schemaorg/schemaorg/issues/2521')),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='direct_apply', schema_name='directApply', schema_url='https://schema.org/directApply', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Indicates whether an [[url]] that is associated with a [[JobPosting]] enables direct application for the job, via the posting website. A job posting is considered to have directApply of [[True]] if an application process for the specified job can be directly initiated via the url(s) given (noting that e.g. multiple internet domains might nevertheless be involved at an implementation level). A value of [[False]] is appropriate if there is no clear path to applying directly online for the specified job, navigating directly from the JobPosting url(s) supplied.', label='directApply', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2907',)),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='education_requirements', schema_name='educationRequirements', schema_url='https://schema.org/educationRequirements', ranges=('EducationalOccupationalCredential', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Educational background needed for the position or Occupation.', label='educationRequirements', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/1779')),
        PropertyMetadata(name='eligibility_to_work_requirement', schema_name='eligibilityToWorkRequirement', schema_url='https://schema.org/eligibilityToWorkRequirement', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The legal requirements such as citizenship, visa and other documentation required for an applicant to this job.', label='eligibilityToWorkRequirement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2384',)),
        PropertyMetadata(name='employer_overview', schema_name='employerOverview', schema_url='https://schema.org/employerOverview', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='A description of the employer, career opportunities and work environment for this position.', label='employerOverview', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2396',)),
        PropertyMetadata(name='employment_type', schema_name='employmentType', schema_url='https://schema.org/employmentType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Type of employment (e.g. full-time, part-time, contract, temporary, seasonal, internship).', label='employmentType', contributors=(), sources=()),
        PropertyMetadata(name='employment_unit', schema_name='employmentUnit', schema_url='https://schema.org/employmentUnit', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Indicates the department, unit and/or facility where the employee reports and/or in which the job is to be performed.', label='employmentUnit', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2296',)),
        PropertyMetadata(name='estimated_salary', schema_name='estimatedSalary', schema_url='https://schema.org/estimatedSalary', ranges=('MonetaryAmount', 'MonetaryAmountDistribution', 'Number'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.', label='estimatedSalary', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='experience_in_place_of_education', schema_name='experienceInPlaceOfEducation', schema_url='https://schema.org/experienceInPlaceOfEducation', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Indicates whether a [[JobPosting]] will accept experience (as indicated by [[OccupationalExperienceRequirements]]) in place of its formal educational qualifications (as indicated by [[educationRequirements]]). If true, indicates that satisfying one of these requirements is sufficient.', label='experienceInPlaceOfEducation', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2681',)),
        PropertyMetadata(name='experience_requirements', schema_name='experienceRequirements', schema_url='https://schema.org/experienceRequirements', ranges=('OccupationalExperienceRequirements', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Description of skills and experience needed for the position or Occupation.', label='experienceRequirements', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='hiring_organization', schema_name='hiringOrganization', schema_url='https://schema.org/hiringOrganization', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Organization or Person offering the job position.', label='hiringOrganization', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='incentive_compensation', schema_name='incentiveCompensation', schema_url='https://schema.org/incentiveCompensation', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('incentives',), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Description of bonus and commission compensation aspects of the job.', label='incentiveCompensation', contributors=(), sources=()),
        PropertyMetadata(name='incentives', schema_name='incentives', schema_url='https://schema.org/incentives', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by='incentiveCompensation', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Description of bonus and commission compensation aspects of the job.', label='incentives', contributors=(), sources=()),
        PropertyMetadata(name='industry', schema_name='industry', schema_url='https://schema.org/industry', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The industry associated with the job position.', label='industry', contributors=(), sources=()),
        PropertyMetadata(name='job_benefits', schema_name='jobBenefits', schema_url='https://schema.org/jobBenefits', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('benefits',), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Description of benefits associated with the job.', label='jobBenefits', contributors=(), sources=()),
        PropertyMetadata(name='job_duration', schema_name='jobDuration', schema_url='https://schema.org/jobDuration', ranges=('Duration', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The expected duration of an employment offer as advertised by the employer. Relevant for job postings that have a clearly defined period in mind such as seasonal work, substitutes for maternal leave or any other temporary employment.', label='jobDuration', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4475',)),
        PropertyMetadata(name='job_immediate_start', schema_name='jobImmediateStart', schema_url='https://schema.org/jobImmediateStart', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='An indicator as to whether a position is available for an immediate start.', label='jobImmediateStart', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2244',)),
        PropertyMetadata(name='job_location', schema_name='jobLocation', schema_url='https://schema.org/jobLocation', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='A (typically single) geographic location associated with the job position.', label='jobLocation', contributors=(), sources=()),
        PropertyMetadata(name='job_location_type', schema_name='jobLocationType', schema_url='https://schema.org/jobLocationType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='A description of the job location (e.g. TELECOMMUTE for telecommute jobs).', label='jobLocationType', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1591',)),
        PropertyMetadata(name='job_start_date', schema_name='jobStartDate', schema_url='https://schema.org/jobStartDate', ranges=('Date', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The date on which a successful applicant for this job would be expected to start work. Choose a specific date in the future or use the jobImmediateStart property to indicate the position is to be filled as soon as possible.', label='jobStartDate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2244',)),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='occupational_category', schema_name='occupationalCategory', schema_url='https://schema.org/occupationalCategory', ranges=('CategoryCode', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram', 'JobPosting', 'Occupation', 'Physician', 'WorkBasedProgram'), external_domains=(), comment='A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\\n\nNote: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.', label='occupationalCategory', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2192', 'https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2460', 'https://github.com/schemaorg/schemaorg/issues/3420')),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='physical_requirement', schema_name='physicalRequirement', schema_url='https://schema.org/physicalRequirement', ranges=('DefinedTerm', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='A description of the types of physical activity associated with the job. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.', label='physicalRequirement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2384',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='qualifications', schema_name='qualifications', schema_url='https://schema.org/qualifications', ranges=('Credential', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Specific qualifications required for this role or Occupation.', label='qualifications', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/1779')),
        PropertyMetadata(name='relevant_occupation', schema_name='relevantOccupation', schema_url='https://schema.org/relevantOccupation', ranges=('Occupation',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The Occupation for the JobPosting.', label='relevantOccupation', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='responsibilities', schema_name='responsibilities', schema_url='https://schema.org/responsibilities', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Responsibilities associated with this role or Occupation.', label='responsibilities', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='salary_currency', schema_name='salaryCurrency', schema_url='https://schema.org/salaryCurrency', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('EmployeeRole', 'JobPosting'), external_domains=(), comment='The currency (coded using [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217)) used for the main salary information in this job posting or for this employee.', label='salaryCurrency', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='security_clearance_requirement', schema_name='securityClearanceRequirement', schema_url='https://schema.org/securityClearanceRequirement', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='A description of any security clearance requirements of the job.', label='securityClearanceRequirement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2384',)),
        PropertyMetadata(name='sensory_requirement', schema_name='sensoryRequirement', schema_url='https://schema.org/sensoryRequirement', ranges=('DefinedTerm', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='A description of any sensory requirements and levels necessary to function on the job, including hearing and vision. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.', label='sensoryRequirement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2384',)),
        PropertyMetadata(name='skills', schema_name='skills', schema_url='https://schema.org/skills', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation', 'Organization', 'Person'), external_domains=(), comment='A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.', label='skills', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2322')),
        PropertyMetadata(name='special_commitments', schema_name='specialCommitments', schema_url='https://schema.org/specialCommitments', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='Any special commitments associated with this job posting. Valid entries include VeteranCommit, MilitarySpouseCommit, etc.', label='specialCommitments', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='title', schema_name='title', schema_url='https://schema.org/title', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The title of the job.', label='title', contributors=(), sources=()),
        PropertyMetadata(name='total_job_openings', schema_name='totalJobOpenings', schema_url='https://schema.org/totalJobOpenings', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The number of positions open for this job posting. Use a positive integer. Do not use if the number of positions is unclear or not known.', label='totalJobOpenings', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2329',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='valid_through', schema_name='validThrough', schema_url='https://schema.org/validThrough', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/DatesAndTimes/hasEndDate',), subproperty_of=(), domains=('Demand', 'FinancialIncentive', 'JobPosting', 'LocationFeatureSpecification', 'MonetaryAmount', 'Offer', 'OpeningHoursSpecification', 'PriceSpecification'), external_domains=(), comment='The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.', label='validThrough', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='work_hours', schema_name='workHours', schema_url='https://schema.org/workHours', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting',), external_domains=(), comment='The typical working hours for this job (e.g. 1st shift, night shift, 8am-5pm).', label='workHours', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['JobPosting'] = Field(default='JobPosting', alias='@type', frozen=True)
    applicant_location_requirements: AdministrativeArea | list[AdministrativeArea] | None = Field(default=None, alias='applicantLocationRequirements', description='The location(s) applicants can apply from. This is usually used for telecommuting jobs where the applicant does not need to be in a physical office. Note: This should not be used for citizenship or work visa requirements.')
    application_contact: ContactPoint | list[ContactPoint] | None = Field(default=None, alias='applicationContact', description='Contact details for further information relevant to this job posting.')
    base_salary: MonetaryAmount | Number | PriceSpecification | list[MonetaryAmount | Number | PriceSpecification] | None = Field(default=None, alias='baseSalary', description='The base salary of the job or of an employee in an EmployeeRole.')
    benefits: Text | list[Text] | None = Field(default=None, alias='benefits', description='Description of benefits associated with the job.\n\nSuperseded by `jobBenefits`.')
    date_posted: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='datePosted', description='Publication date of an online listing.')
    direct_apply: Boolean | list[Boolean] | None = Field(default=None, alias='directApply', description='Indicates whether an [[url]] that is associated with a [[JobPosting]] enables direct application for the job, via the posting website. A job posting is considered to have directApply of [[True]] if an application process for the specified job can be directly initiated via the url(s) given (noting that e.g. multiple internet domains might nevertheless be involved at an implementation level). A value of [[False]] is appropriate if there is no clear path to applying directly online for the specified job, navigating directly from the JobPosting url(s) supplied.')
    education_requirements: EducationalOccupationalCredential | Text | list[EducationalOccupationalCredential | Text] | None = Field(default=None, alias='educationRequirements', description='Educational background needed for the position or Occupation.')
    eligibility_to_work_requirement: Text | list[Text] | None = Field(default=None, alias='eligibilityToWorkRequirement', description='The legal requirements such as citizenship, visa and other documentation required for an applicant to this job.')
    employer_overview: Text | list[Text] | None = Field(default=None, alias='employerOverview', description='A description of the employer, career opportunities and work environment for this position.')
    employment_type: Text | list[Text] | None = Field(default=None, alias='employmentType', description='Type of employment (e.g. full-time, part-time, contract, temporary, seasonal, internship).')
    employment_unit: Organization | list[Organization] | None = Field(default=None, alias='employmentUnit', description='Indicates the department, unit and/or facility where the employee reports and/or in which the job is to be performed.')
    estimated_salary: MonetaryAmount | MonetaryAmountDistribution | Number | list[MonetaryAmount | MonetaryAmountDistribution | Number] | None = Field(default=None, alias='estimatedSalary', description='An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.')
    experience_in_place_of_education: Boolean | list[Boolean] | None = Field(default=None, alias='experienceInPlaceOfEducation', description='Indicates whether a [[JobPosting]] will accept experience (as indicated by [[OccupationalExperienceRequirements]]) in place of its formal educational qualifications (as indicated by [[educationRequirements]]). If true, indicates that satisfying one of these requirements is sufficient.')
    experience_requirements: OccupationalExperienceRequirements | Text | list[OccupationalExperienceRequirements | Text] | None = Field(default=None, alias='experienceRequirements', description='Description of skills and experience needed for the position or Occupation.')
    hiring_organization: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='hiringOrganization', description='Organization or Person offering the job position.')
    incentive_compensation: Text | list[Text] | None = Field(default=None, alias='incentiveCompensation', description='Description of bonus and commission compensation aspects of the job.\n\nSupersedes `incentives`.')
    incentives: Text | list[Text] | None = Field(default=None, alias='incentives', description='Description of bonus and commission compensation aspects of the job.\n\nSuperseded by `incentiveCompensation`.')
    industry: DefinedTerm | Text | list[DefinedTerm | Text] | None = Field(default=None, alias='industry', description='The industry associated with the job position.')
    job_benefits: Text | list[Text] | None = Field(default=None, alias='jobBenefits', description='Description of benefits associated with the job.\n\nSupersedes `benefits`.')
    job_duration: Duration | QuantitativeValue | list[Duration | QuantitativeValue] | None = Field(default=None, alias='jobDuration', description='The expected duration of an employment offer as advertised by the employer. Relevant for job postings that have a clearly defined period in mind such as seasonal work, substitutes for maternal leave or any other temporary employment.')
    job_immediate_start: Boolean | list[Boolean] | None = Field(default=None, alias='jobImmediateStart', description='An indicator as to whether a position is available for an immediate start.')
    job_location: Place | list[Place] | None = Field(default=None, alias='jobLocation', description='A (typically single) geographic location associated with the job position.')
    job_location_type: Text | list[Text] | None = Field(default=None, alias='jobLocationType', description='A description of the job location (e.g. TELECOMMUTE for telecommute jobs).')
    job_start_date: Date | Text | list[Date | Text] | None = Field(default=None, alias='jobStartDate', description='The date on which a successful applicant for this job would be expected to start work. Choose a specific date in the future or use the jobImmediateStart property to indicate the position is to be filled as soon as possible.')
    occupational_category: CategoryCode | Text | list[CategoryCode | Text] | None = Field(default=None, alias='occupationalCategory', description='A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\\n\nNote: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.')
    physical_requirement: DefinedTerm | Text | URL | list[DefinedTerm | Text | URL] | None = Field(default=None, alias='physicalRequirement', description='A description of the types of physical activity associated with the job. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.')
    qualifications: Credential | Text | list[Credential | Text] | None = Field(default=None, alias='qualifications', description='Specific qualifications required for this role or Occupation.')
    relevant_occupation: Occupation | list[Occupation] | None = Field(default=None, alias='relevantOccupation', description='The Occupation for the JobPosting.')
    responsibilities: Text | list[Text] | None = Field(default=None, alias='responsibilities', description='Responsibilities associated with this role or Occupation.')
    salary_currency: Text | list[Text] | None = Field(default=None, alias='salaryCurrency', description='The currency (coded using [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217)) used for the main salary information in this job posting or for this employee.')
    security_clearance_requirement: Text | URL | list[Text | URL] | None = Field(default=None, alias='securityClearanceRequirement', description='A description of any security clearance requirements of the job.')
    sensory_requirement: DefinedTerm | Text | URL | list[DefinedTerm | Text | URL] | None = Field(default=None, alias='sensoryRequirement', description='A description of any sensory requirements and levels necessary to function on the job, including hearing and vision. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.')
    skills: DefinedTerm | Text | list[DefinedTerm | Text] | None = Field(default=None, alias='skills', description='A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.')
    special_commitments: Text | list[Text] | None = Field(default=None, alias='specialCommitments', description='Any special commitments associated with this job posting. Valid entries include VeteranCommit, MilitarySpouseCommit, etc.')
    title: Text | list[Text] | None = Field(default=None, alias='title', description='The title of the job.')
    total_job_openings: Integer | list[Integer] | None = Field(default=None, alias='totalJobOpenings', description='The number of positions open for this job posting. Use a positive integer. Do not use if the number of positions is unclear or not known.')
    valid_through: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='validThrough', description='The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.')
    work_hours: Text | list[Text] | None = Field(default=None, alias='workHours', description='The typical working hours for this job (e.g. 1st shift, night shift, 8am-5pm).')
