# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import DateTime
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import Time
from schema_org.datatypes import URL
from schema_org.enums import BedType
from schema_org.enums import DriveWheelConfigurationValue
from schema_org.enums import QualitativeValue
from schema_org.enums import ReservationStatusType
from schema_org.enums import SizeSpecification
from schema_org.enums import SteeringPositionValue
from schema_org.models.reservation import Reservation

class LodgingReservation(Reservation):
    __doc__ = 'https://schema.org/LodgingReservation\n\nA reservation for lodging at a hotel, motel, inn, etc.\\n\\nNote: This type is for information about actual reservations, e.g. in confirmation emails or HTML pages with individual confirmations of reservations.'
    SCHEMA_TYPE: ClassVar[str] = 'LodgingReservation'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('LodgingReservation', 'Reservation', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='booking_agent', schema_name='bookingAgent', schema_url='https://schema.org/bookingAgent', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by='broker', supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment="'bookingAgent' is an out-dated term indicating a 'broker' that serves as a booking agent.", label='bookingAgent', contributors=(), sources=()),
        PropertyMetadata(name='booking_time', schema_name='bookingTime', schema_url='https://schema.org/bookingTime', ranges=('DateTime',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='The date and time the reservation was booked.', label='bookingTime', contributors=(), sources=()),
        PropertyMetadata(name='broker', schema_name='broker', schema_url='https://schema.org/broker', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='bookingAgent', equivalent_properties=(), subproperty_of=(), domains=('Invoice', 'Order', 'Reservation', 'Service'), external_domains=(), comment='An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.', label='broker', contributors=(), sources=()),
        PropertyMetadata(name='checkin_time', schema_name='checkinTime', schema_url='https://schema.org/checkinTime', ranges=('DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('LodgingBusiness', 'LodgingReservation'), external_domains=(), comment='The earliest someone may check into a lodging establishment.', label='checkinTime', contributors=(), sources=()),
        PropertyMetadata(name='checkout_time', schema_name='checkoutTime', schema_url='https://schema.org/checkoutTime', ranges=('DateTime', 'Time'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('LodgingBusiness', 'LodgingReservation'), external_domains=(), comment='The latest someone may check out of a lodging establishment.', label='checkoutTime', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='lodging_unit_description', schema_name='lodgingUnitDescription', schema_url='https://schema.org/lodgingUnitDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('LodgingReservation',), external_domains=(), comment='A full description of the lodging unit.', label='lodgingUnitDescription', contributors=(), sources=()),
        PropertyMetadata(name='lodging_unit_type', schema_name='lodgingUnitType', schema_url='https://schema.org/lodgingUnitType', ranges=('QualitativeValue', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('LodgingReservation',), external_domains=(), comment='Textual description of the unit type (including suite vs. room, size of bed, etc.).', label='lodgingUnitType', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='modified_time', schema_name='modifiedTime', schema_url='https://schema.org/modifiedTime', ranges=('DateTime',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='The date and time the reservation was modified.', label='modifiedTime', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='num_adults', schema_name='numAdults', schema_url='https://schema.org/numAdults', ranges=('Integer', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('LodgingReservation',), external_domains=(), comment='The number of adults staying in the unit.', label='numAdults', contributors=(), sources=()),
        PropertyMetadata(name='num_children', schema_name='numChildren', schema_url='https://schema.org/numChildren', ranges=('Integer', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('LodgingReservation',), external_domains=(), comment='The number of children staying in the unit.', label='numChildren', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='price_currency', schema_name='priceCurrency', schema_url='https://schema.org/priceCurrency', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/hasCurrency',), domains=('DonateAction', 'Offer', 'PriceSpecification', 'Reservation', 'Ticket', 'TradeAction'), external_domains=(), comment='The currency of the price, or a price component when attached to [[PriceSpecification]] and its subtypes.\\n\\nUse standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR".', label='priceCurrency', contributors=(), sources=()),
        PropertyMetadata(name='program_membership_used', schema_name='programMembershipUsed', schema_url='https://schema.org/programMembershipUsed', ranges=('ProgramMembership',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='Any membership in a frequent flyer, hotel loyalty program, etc. being applied to the reservation.', label='programMembershipUsed', contributors=(), sources=()),
        PropertyMetadata(name='provider', schema_name='provider', schema_url='https://schema.org/provider', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='carrier', equivalent_properties=('http://unece.org/vocab#ServiceProvider',), subproperty_of=(), domains=('Action', 'CreativeWork', 'EducationalOccupationalProgram', 'FinancialIncentive', 'Invoice', 'ParcelDelivery', 'Reservation', 'Service', 'Trip'), external_domains=(), comment='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.', label='provider', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2927')),
        PropertyMetadata(name='reservation_for', schema_name='reservationFor', schema_url='https://schema.org/reservationFor', ranges=('Thing',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='The thing -- flight, event, restaurant, etc. being reserved.', label='reservationFor', contributors=(), sources=()),
        PropertyMetadata(name='reservation_id', schema_name='reservationId', schema_url='https://schema.org/reservationId', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='A unique identifier for the reservation.', label='reservationId', contributors=(), sources=()),
        PropertyMetadata(name='reservation_status', schema_name='reservationStatus', schema_url='https://schema.org/reservationStatus', ranges=('ReservationStatusType',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='The current status of the reservation.', label='reservationStatus', contributors=(), sources=()),
        PropertyMetadata(name='reserved_ticket', schema_name='reservedTicket', schema_url='https://schema.org/reservedTicket', ranges=('Ticket',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation',), external_domains=(), comment='A ticket associated with the reservation.', label='reservedTicket', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='total_price', schema_name='totalPrice', schema_url='https://schema.org/totalPrice', ranges=('Number', 'PriceSpecification', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation', 'Ticket'), external_domains=(), comment="The total price for the reservation or ticket, including applicable taxes, shipping, etc.\\n\\nUsage guidelines:\\n\\n* Use values from 0123456789 (Unicode 'DIGIT ZERO' (U+0030) to 'DIGIT NINE' (U+0039)) rather than superficially similar Unicode symbols.\\n* Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator.", label='totalPrice', contributors=(), sources=()),
        PropertyMetadata(name='under_name', schema_name='underName', schema_url='https://schema.org/underName', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Reservation', 'Ticket'), external_domains=(), comment='The person or organization the reservation or ticket is for.', label='underName', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['LodgingReservation'] = Field(default='LodgingReservation', alias='@type', frozen=True)
    checkin_time: DateTime | Time | list[DateTime | Time] | None = Field(default=None, alias='checkinTime', description='The earliest someone may check into a lodging establishment.')
    checkout_time: DateTime | Time | list[DateTime | Time] | None = Field(default=None, alias='checkoutTime', description='The latest someone may check out of a lodging establishment.')
    lodging_unit_description: Text | list[Text] | None = Field(default=None, alias='lodgingUnitDescription', description='A full description of the lodging unit.')
    lodging_unit_type: QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | list[QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text] | None = Field(default=None, alias='lodgingUnitType', description='Textual description of the unit type (including suite vs. room, size of bed, etc.).')
    num_adults: Integer | QuantitativeValue | list[Integer | QuantitativeValue] | None = Field(default=None, alias='numAdults', description='The number of adults staying in the unit.')
    num_children: Integer | QuantitativeValue | list[Integer | QuantitativeValue] | None = Field(default=None, alias='numChildren', description='The number of children staying in the unit.')
