# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import MerchantReturnEnumeration
from schema_org.enums import OfferItemCondition
from schema_org.enums import RefundTypeEnumeration
from schema_org.enums import ReturnFeesEnumeration
from schema_org.enums import ReturnLabelSourceEnumeration
from schema_org.enums import ReturnMethodEnumeration
from schema_org.models.intangible import Intangible

class MerchantReturnPolicy(Intangible):
    __doc__ = 'https://schema.org/MerchantReturnPolicy\n\nA MerchantReturnPolicy provides information about product return policies associated with an [[Organization]], [[Product]], or [[Offer]].\n\nSupersedes `ProductReturnPolicy`.'
    SCHEMA_TYPE: ClassVar[str] = 'MerchantReturnPolicy'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('MerchantReturnPolicy', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_property', schema_name='additionalProperty', schema_url='https://schema.org/additionalProperty', ranges=('PropertyValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'Offer', 'Place', 'Product', 'QualitativeValue', 'QuantitativeValue'), external_domains=(), comment='A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\\n\\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.\n', label='additionalProperty', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='applicable_country', schema_name='applicableCountry', schema_url='https://schema.org/applicableCountry', ranges=('Country', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='A country where a particular merchant return policy applies to, for example the two-letter ISO 3166-1 alpha-2 country code.', label='applicableCountry', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3001',)),
        PropertyMetadata(name='customer_remorse_return_fees', schema_name='customerRemorseReturnFees', schema_url='https://schema.org/customerRemorseReturnFees', ranges=('ReturnFeesEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The type of return fees if the product is returned due to customer remorse.', label='customerRemorseReturnFees', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='customer_remorse_return_label_source', schema_name='customerRemorseReturnLabelSource', schema_url='https://schema.org/customerRemorseReturnLabelSource', ranges=('ReturnLabelSourceEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The method (from an enumeration) by which the customer obtains a return shipping label for a product returned due to customer remorse.', label='customerRemorseReturnLabelSource', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='customer_remorse_return_shipping_fees_amount', schema_name='customerRemorseReturnShippingFeesAmount', schema_url='https://schema.org/customerRemorseReturnShippingFeesAmount', ranges=('MonetaryAmount',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The amount of shipping costs if a product is returned due to customer remorse. Applicable when property [[customerRemorseReturnFees]] equals [[ReturnShippingFees]].', label='customerRemorseReturnShippingFeesAmount', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='in_store_returns_offered', schema_name='inStoreReturnsOffered', schema_url='https://schema.org/inStoreReturnsOffered', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='Are in-store returns offered? (For more advanced return methods use the [[returnMethod]] property.)', label='inStoreReturnsOffered', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='item_condition', schema_name='itemCondition', schema_url='https://schema.org/itemCondition', ranges=('OfferItemCondition',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Demand', 'MerchantReturnPolicy', 'Offer', 'Product'), external_domains=(), comment='A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.', label='itemCondition', contributors=(), sources=()),
        PropertyMetadata(name='item_defect_return_fees', schema_name='itemDefectReturnFees', schema_url='https://schema.org/itemDefectReturnFees', ranges=('ReturnFeesEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The type of return fees for returns of defect products.', label='itemDefectReturnFees', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='item_defect_return_label_source', schema_name='itemDefectReturnLabelSource', schema_url='https://schema.org/itemDefectReturnLabelSource', ranges=('ReturnLabelSourceEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The method (from an enumeration) by which the customer obtains a return shipping label for a defect product.', label='itemDefectReturnLabelSource', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='item_defect_return_shipping_fees_amount', schema_name='itemDefectReturnShippingFeesAmount', schema_url='https://schema.org/itemDefectReturnShippingFeesAmount', ranges=('MonetaryAmount',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='Amount of shipping costs for defect product returns. Applicable when property [[itemDefectReturnFees]] equals [[ReturnShippingFees]].', label='itemDefectReturnShippingFeesAmount', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='merchant_return_days', schema_name='merchantReturnDays', schema_url='https://schema.org/merchantReturnDays', ranges=('Date', 'DateTime', 'Integer'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='productReturnDays', equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='Specifies either a fixed return date or the number of days (from the delivery date) that a product can be returned. Used when the [[returnPolicyCategory]] property is specified as [[MerchantReturnFiniteReturnWindow]].', label='merchantReturnDays', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='merchant_return_link', schema_name='merchantReturnLink', schema_url='https://schema.org/merchantReturnLink', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='productReturnLink', equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='Specifies a Web page or service by URL, for product returns.', label='merchantReturnLink', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='refund_type', schema_name='refundType', schema_url='https://schema.org/refundType', ranges=('RefundTypeEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='A refund type, from an enumerated list.', label='refundType', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='restocking_fee', schema_name='restockingFee', schema_url='https://schema.org/restockingFee', ranges=('MonetaryAmount', 'Number'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='Use [[MonetaryAmount]] to specify a fixed restocking fee for product returns, or use [[Number]] to specify a percentage of the product price paid by the customer.', label='restockingFee', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='return_fees', schema_name='returnFees', schema_url='https://schema.org/returnFees', ranges=('ReturnFeesEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='The type of return fees for purchased products (for any return reason).', label='returnFees', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='return_label_source', schema_name='returnLabelSource', schema_url='https://schema.org/returnLabelSource', ranges=('ReturnLabelSourceEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The method (from an enumeration) by which the customer obtains a return shipping label for a product returned for any reason.', label='returnLabelSource', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='return_method', schema_name='returnMethod', schema_url='https://schema.org/returnMethod', ranges=('ReturnMethodEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='The type of return method offered, specified from an enumeration.', label='returnMethod', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='return_policy_category', schema_name='returnPolicyCategory', schema_url='https://schema.org/returnPolicyCategory', ranges=('MerchantReturnEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='Specifies an applicable return policy (from an enumeration).', label='returnPolicyCategory', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='return_policy_country', schema_name='returnPolicyCountry', schema_url='https://schema.org/returnPolicyCountry', ranges=('Country', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='The country where the product has to be sent to for returns, for example "Ireland" using the [[name]] property of [[Country]]. You can also provide the two-letter [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1). Note that this can be different from the country where the product was originally shipped from or sent to.', label='returnPolicyCountry', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='return_policy_seasonal_override', schema_name='returnPolicySeasonalOverride', schema_url='https://schema.org/returnPolicySeasonalOverride', ranges=('MerchantReturnPolicySeasonalOverride',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy',), external_domains=(), comment='Seasonal override of a return policy.', label='returnPolicySeasonalOverride', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='return_shipping_fees_amount', schema_name='returnShippingFeesAmount', schema_url='https://schema.org/returnShippingFeesAmount', ranges=('MonetaryAmount',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'MerchantReturnPolicySeasonalOverride'), external_domains=(), comment='Amount of shipping costs for product returns (for any reason). Applicable when property [[returnFees]] equals [[ReturnShippingFees]].', label='returnShippingFeesAmount', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2880',)),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='valid_for_member_tier', schema_name='validForMemberTier', schema_url='https://schema.org/validForMemberTier', ranges=('MemberProgramTier',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'Offer', 'OfferShippingDetails', 'PriceSpecification', 'ShippingService'), external_domains=(), comment='The membership program tier(s) an Offer (or a PriceSpecification, OfferShippingDetails, or MerchantReturnPolicy under an Offer) is valid for.', label='validForMemberTier', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3563', 'https://github.com/schemaorg/schemaorg/issues/3617')),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['MerchantReturnPolicy'] = Field(default='MerchantReturnPolicy', alias='@type', frozen=True)
    additional_property: PropertyValue | list[PropertyValue] | None = Field(default=None, alias='additionalProperty', description='A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\\n\\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.\n')
    applicable_country: Country | Text | list[Country | Text] | None = Field(default=None, alias='applicableCountry', description='A country where a particular merchant return policy applies to, for example the two-letter ISO 3166-1 alpha-2 country code.')
    customer_remorse_return_fees: ReturnFeesEnumeration | list[ReturnFeesEnumeration] | None = Field(default=None, alias='customerRemorseReturnFees', description='The type of return fees if the product is returned due to customer remorse.')
    customer_remorse_return_label_source: ReturnLabelSourceEnumeration | list[ReturnLabelSourceEnumeration] | None = Field(default=None, alias='customerRemorseReturnLabelSource', description='The method (from an enumeration) by which the customer obtains a return shipping label for a product returned due to customer remorse.')
    customer_remorse_return_shipping_fees_amount: MonetaryAmount | list[MonetaryAmount] | None = Field(default=None, alias='customerRemorseReturnShippingFeesAmount', description='The amount of shipping costs if a product is returned due to customer remorse. Applicable when property [[customerRemorseReturnFees]] equals [[ReturnShippingFees]].')
    in_store_returns_offered: Boolean | list[Boolean] | None = Field(default=None, alias='inStoreReturnsOffered', description='Are in-store returns offered? (For more advanced return methods use the [[returnMethod]] property.)')
    item_condition: OfferItemCondition | list[OfferItemCondition] | None = Field(default=None, alias='itemCondition', description='A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.')
    item_defect_return_fees: ReturnFeesEnumeration | list[ReturnFeesEnumeration] | None = Field(default=None, alias='itemDefectReturnFees', description='The type of return fees for returns of defect products.')
    item_defect_return_label_source: ReturnLabelSourceEnumeration | list[ReturnLabelSourceEnumeration] | None = Field(default=None, alias='itemDefectReturnLabelSource', description='The method (from an enumeration) by which the customer obtains a return shipping label for a defect product.')
    item_defect_return_shipping_fees_amount: MonetaryAmount | list[MonetaryAmount] | None = Field(default=None, alias='itemDefectReturnShippingFeesAmount', description='Amount of shipping costs for defect product returns. Applicable when property [[itemDefectReturnFees]] equals [[ReturnShippingFees]].')
    merchant_return_days: Date | DateTime | Integer | list[Date | DateTime | Integer] | None = Field(default=None, alias='merchantReturnDays', description='Specifies either a fixed return date or the number of days (from the delivery date) that a product can be returned. Used when the [[returnPolicyCategory]] property is specified as [[MerchantReturnFiniteReturnWindow]].\n\nSupersedes `productReturnDays`.')
    merchant_return_link: URL | list[URL] | None = Field(default=None, alias='merchantReturnLink', description='Specifies a Web page or service by URL, for product returns.\n\nSupersedes `productReturnLink`.')
    refund_type: RefundTypeEnumeration | list[RefundTypeEnumeration] | None = Field(default=None, alias='refundType', description='A refund type, from an enumerated list.')
    restocking_fee: MonetaryAmount | Number | list[MonetaryAmount | Number] | None = Field(default=None, alias='restockingFee', description='Use [[MonetaryAmount]] to specify a fixed restocking fee for product returns, or use [[Number]] to specify a percentage of the product price paid by the customer.')
    return_fees: ReturnFeesEnumeration | list[ReturnFeesEnumeration] | None = Field(default=None, alias='returnFees', description='The type of return fees for purchased products (for any return reason).')
    return_label_source: ReturnLabelSourceEnumeration | list[ReturnLabelSourceEnumeration] | None = Field(default=None, alias='returnLabelSource', description='The method (from an enumeration) by which the customer obtains a return shipping label for a product returned for any reason.')
    return_method: ReturnMethodEnumeration | list[ReturnMethodEnumeration] | None = Field(default=None, alias='returnMethod', description='The type of return method offered, specified from an enumeration.')
    return_policy_category: MerchantReturnEnumeration | list[MerchantReturnEnumeration] | None = Field(default=None, alias='returnPolicyCategory', description='Specifies an applicable return policy (from an enumeration).')
    return_policy_country: Country | Text | list[Country | Text] | None = Field(default=None, alias='returnPolicyCountry', description='The country where the product has to be sent to for returns, for example "Ireland" using the [[name]] property of [[Country]]. You can also provide the two-letter [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1). Note that this can be different from the country where the product was originally shipped from or sent to.')
    return_policy_seasonal_override: MerchantReturnPolicySeasonalOverride | list[MerchantReturnPolicySeasonalOverride] | None = Field(default=None, alias='returnPolicySeasonalOverride', description='Seasonal override of a return policy.')
    return_shipping_fees_amount: MonetaryAmount | list[MonetaryAmount] | None = Field(default=None, alias='returnShippingFeesAmount', description='Amount of shipping costs for product returns (for any reason). Applicable when property [[returnFees]] equals [[ReturnShippingFees]].')
    valid_for_member_tier: MemberProgramTier | list[MemberProgramTier] | None = Field(default=None, alias='validForMemberTier', description='The membership program tier(s) an Offer (or a PriceSpecification, OfferShippingDetails, or MerchantReturnPolicy under an Offer) is valid for.')
