# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.bio_chem_entity import BioChemEntity

class MolecularEntity(BioChemEntity):
    __doc__ = 'https://schema.org/MolecularEntity\n\nAny constitutionally or isotopically distinct atom, molecule, ion, ion pair, radical, radical ion, complex, conformer etc., identifiable as a separately distinguishable entity.'
    SCHEMA_TYPE: ClassVar[str] = 'MolecularEntity'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('MolecularEntity', 'BioChemEntity', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='associated_disease', schema_name='associatedDisease', schema_url='https://schema.org/associatedDisease', ranges=('MedicalCondition', 'PropertyValue', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Disease associated to this BioChemEntity. Such disease can be a MedicalCondition or a URL. If you want to add an evidence supporting the association, please use PropertyValue.', label='associatedDisease', contributors=(), sources=('http://www.bioschemas.org/BioChemEntity',)),
        PropertyMetadata(name='bio_chem_interaction', schema_name='bioChemInteraction', schema_url='https://schema.org/bioChemInteraction', ranges=('BioChemEntity',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='A BioChemEntity that is known to interact with this item.', label='bioChemInteraction', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='bio_chem_similarity', schema_name='bioChemSimilarity', schema_url='https://schema.org/bioChemSimilarity', ranges=('BioChemEntity',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='A similar BioChemEntity, e.g., obtained by fingerprint similarity algorithms.', label='bioChemSimilarity', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='biological_role', schema_name='biologicalRole', schema_url='https://schema.org/biologicalRole', ranges=('DefinedTerm',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='A role played by the BioChemEntity within a biological context.', label='biologicalRole', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='chemical_role', schema_name='chemicalRole', schema_url='https://schema.org/chemicalRole', ranges=('DefinedTerm',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ChemicalSubstance', 'MolecularEntity'), external_domains=(), comment='A role played by the BioChemEntity within a chemical context.', label='chemicalRole', contributors=(), sources=('http://www.bioschemas.org/ChemicalSubstance',)),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='funding', schema_name='funding', schema_url='https://schema.org/funding', ranges=('Grant',), external_ranges=(), inverse_of='fundedItem', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity', 'CreativeWork', 'Event', 'MedicalEntity', 'Organization', 'Person', 'Product'), external_domains=(), comment='A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].', label='funding', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/383',)),
        PropertyMetadata(name='has_bio_chem_entity_part', schema_name='hasBioChemEntityPart', schema_url='https://schema.org/hasBioChemEntityPart', ranges=('BioChemEntity',), external_ranges=(), inverse_of='isPartOfBioChemEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Indicates a BioChemEntity that (in some sense) has this BioChemEntity as a part. ', label='hasBioChemEntityPart', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='has_molecular_function', schema_name='hasMolecularFunction', schema_url='https://schema.org/hasMolecularFunction', ranges=('DefinedTerm', 'PropertyValue', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Molecular function performed by this BioChemEntity; please use PropertyValue if you want to include any evidence.', label='hasMolecularFunction', contributors=(), sources=('http://www.bioschemas.org/BioChemEntity',)),
        PropertyMetadata(name='has_representation', schema_name='hasRepresentation', schema_url='https://schema.org/hasRepresentation', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='A common representation such as a protein sequence or chemical structure for this entity. For images use schema.org/image.', label='hasRepresentation', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='in_ch_i', schema_name='inChI', schema_url='https://schema.org/inChI', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('hasRepresentation',), domains=('MolecularEntity',), external_domains=(), comment='Non-proprietary identifier for molecular entity that can be used in printed and electronic data sources thus enabling easier linking of diverse data compilations.', label='inChI', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='in_ch_i_key', schema_name='inChIKey', schema_url='https://schema.org/inChIKey', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('hasRepresentation',), domains=('MolecularEntity',), external_domains=(), comment='InChIKey is a hashed version of the full InChI (using the SHA-256 algorithm).', label='inChIKey', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='is_encoded_by_bio_chem_entity', schema_name='isEncodedByBioChemEntity', schema_url='https://schema.org/isEncodedByBioChemEntity', ranges=('Gene',), external_ranges=(), inverse_of='encodesBioChemEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Another BioChemEntity encoding by this one.', label='isEncodedByBioChemEntity', contributors=(), sources=('http://www.bioschemas.org/Gene',)),
        PropertyMetadata(name='is_involved_in_biological_process', schema_name='isInvolvedInBiologicalProcess', schema_url='https://schema.org/isInvolvedInBiologicalProcess', ranges=('DefinedTerm', 'PropertyValue', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Biological process this BioChemEntity is involved in; please use PropertyValue if you want to include any evidence.', label='isInvolvedInBiologicalProcess', contributors=(), sources=('http://www.bioschemas.org/BioChemEntity',)),
        PropertyMetadata(name='is_located_in_subcellular_location', schema_name='isLocatedInSubcellularLocation', schema_url='https://schema.org/isLocatedInSubcellularLocation', ranges=('DefinedTerm', 'PropertyValue', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Subcellular location where this BioChemEntity is located; please use PropertyValue if you want to include any evidence.', label='isLocatedInSubcellularLocation', contributors=(), sources=('http://www.bioschemas.org/BioChemEntity',)),
        PropertyMetadata(name='is_part_of_bio_chem_entity', schema_name='isPartOfBioChemEntity', schema_url='https://schema.org/isPartOfBioChemEntity', ranges=('BioChemEntity',), external_ranges=(), inverse_of='hasBioChemEntityPart', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='Indicates a BioChemEntity that is (in some sense) a part of this BioChemEntity. ', label='isPartOfBioChemEntity', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='iupac_name', schema_name='iupacName', schema_url='https://schema.org/iupacName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MolecularEntity',), external_domains=(), comment='Systematic method of naming chemical compounds as recommended by the International Union of Pure and Applied Chemistry (IUPAC).', label='iupacName', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='molecular_formula', schema_name='molecularFormula', schema_url='https://schema.org/molecularFormula', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MolecularEntity',), external_domains=(), comment='The empirical formula is the simplest whole number ratio of all the atoms in a molecule.', label='molecularFormula', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='molecular_weight', schema_name='molecularWeight', schema_url='https://schema.org/molecularWeight', ranges=('QuantitativeValue', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MolecularEntity',), external_domains=(), comment="This is the molecular weight of the entity being described, not of the parent. Units should be included in the form '&lt;Number&gt; &lt;unit&gt;', for example '12 amu' or as '&lt;QuantitativeValue&gt;.", label='molecularWeight', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='monoisotopic_molecular_weight', schema_name='monoisotopicMolecularWeight', schema_url='https://schema.org/monoisotopicMolecularWeight', ranges=('QuantitativeValue', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MolecularEntity',), external_domains=(), comment="The monoisotopic mass is the sum of the masses of the atoms in a molecule using the unbound, ground-state, rest mass of the principal (most abundant) isotope for each element instead of the isotopic average mass. Please include the units in the form '&lt;Number&gt; &lt;unit&gt;', for example '770.230488 g/mol' or as '&lt;QuantitativeValue&gt;.", label='monoisotopicMolecularWeight', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='potential_use', schema_name='potentialUse', schema_url='https://schema.org/potentialUse', ranges=('DefinedTerm',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ChemicalSubstance', 'MolecularEntity'), external_domains=(), comment='Intended use of the BioChemEntity by humans.', label='potentialUse', contributors=(), sources=('http://www.bioschemas.org/ChemicalSubstance',)),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='smiles', schema_name='smiles', schema_url='https://schema.org/smiles', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('hasRepresentation',), domains=('MolecularEntity',), external_domains=(), comment='A specification in form of a line notation for describing the structure of chemical species using short ASCII strings.  Double bond stereochemistry \\ indicators may need to be escaped in the string in formats where the backslash is an escape character.', label='smiles', contributors=(), sources=('http://www.bioschemas.org/MolecularEntity',)),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='taxonomic_range', schema_name='taxonomicRange', schema_url='https://schema.org/taxonomicRange', ranges=('DefinedTerm', 'Taxon', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity',), external_domains=(), comment='The taxonomic grouping of the organism that expresses, encodes, or in some way related to the BioChemEntity.', label='taxonomicRange', contributors=(), sources=('http://www.bioschemas.org',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['MolecularEntity'] = Field(default='MolecularEntity', alias='@type', frozen=True)
    chemical_role: DefinedTerm | list[DefinedTerm] | None = Field(default=None, alias='chemicalRole', description='A role played by the BioChemEntity within a chemical context.')
    in_ch_i: Text | list[Text] | None = Field(default=None, alias='inChI', description='Non-proprietary identifier for molecular entity that can be used in printed and electronic data sources thus enabling easier linking of diverse data compilations.')
    in_ch_i_key: Text | list[Text] | None = Field(default=None, alias='inChIKey', description='InChIKey is a hashed version of the full InChI (using the SHA-256 algorithm).')
    iupac_name: Text | list[Text] | None = Field(default=None, alias='iupacName', description='Systematic method of naming chemical compounds as recommended by the International Union of Pure and Applied Chemistry (IUPAC).')
    molecular_formula: Text | list[Text] | None = Field(default=None, alias='molecularFormula', description='The empirical formula is the simplest whole number ratio of all the atoms in a molecule.')
    molecular_weight: QuantitativeValue | Text | list[QuantitativeValue | Text] | None = Field(default=None, alias='molecularWeight', description="This is the molecular weight of the entity being described, not of the parent. Units should be included in the form '&lt;Number&gt; &lt;unit&gt;', for example '12 amu' or as '&lt;QuantitativeValue&gt;.")
    monoisotopic_molecular_weight: QuantitativeValue | Text | list[QuantitativeValue | Text] | None = Field(default=None, alias='monoisotopicMolecularWeight', description="The monoisotopic mass is the sum of the masses of the atoms in a molecule using the unbound, ground-state, rest mass of the principal (most abundant) isotope for each element instead of the isotopic average mass. Please include the units in the form '&lt;Number&gt; &lt;unit&gt;', for example '770.230488 g/mol' or as '&lt;QuantitativeValue&gt;.")
    potential_use: DefinedTerm | list[DefinedTerm] | None = Field(default=None, alias='potentialUse', description='Intended use of the BioChemEntity by humans.')
    smiles: Text | list[Text] | None = Field(default=None, alias='smiles', description='A specification in form of a line notation for describing the structure of chemical species using short ASCII strings.  Double bond stereochemistry \\ indicators may need to be escaped in the string in formats where the backslash is an escape character.')
