# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Energy
from schema_org.datatypes import Mass
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.structured_value import StructuredValue

class NutritionInformation(StructuredValue):
    __doc__ = 'https://schema.org/NutritionInformation\n\nNutritional information about the recipe.'
    SCHEMA_TYPE: ClassVar[str] = 'NutritionInformation'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('NutritionInformation', 'StructuredValue', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='calories', schema_name='calories', schema_url='https://schema.org/calories', ranges=('Energy',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of calories.', label='calories', contributors=(), sources=()),
        PropertyMetadata(name='carbohydrate_content', schema_name='carbohydrateContent', schema_url='https://schema.org/carbohydrateContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of carbohydrates.', label='carbohydrateContent', contributors=(), sources=()),
        PropertyMetadata(name='cholesterol_content', schema_name='cholesterolContent', schema_url='https://schema.org/cholesterolContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of milligrams of cholesterol.', label='cholesterolContent', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='fat_content', schema_name='fatContent', schema_url='https://schema.org/fatContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of fat.', label='fatContent', contributors=(), sources=()),
        PropertyMetadata(name='fiber_content', schema_name='fiberContent', schema_url='https://schema.org/fiberContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of fiber.', label='fiberContent', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='protein_content', schema_name='proteinContent', schema_url='https://schema.org/proteinContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of protein.', label='proteinContent', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='saturated_fat_content', schema_name='saturatedFatContent', schema_url='https://schema.org/saturatedFatContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of saturated fat.', label='saturatedFatContent', contributors=(), sources=()),
        PropertyMetadata(name='serving_size', schema_name='servingSize', schema_url='https://schema.org/servingSize', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The serving size, in terms of the number of volume or mass.', label='servingSize', contributors=(), sources=()),
        PropertyMetadata(name='sodium_content', schema_name='sodiumContent', schema_url='https://schema.org/sodiumContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of milligrams of sodium.', label='sodiumContent', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='sugar_content', schema_name='sugarContent', schema_url='https://schema.org/sugarContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of sugar.', label='sugarContent', contributors=(), sources=()),
        PropertyMetadata(name='trans_fat_content', schema_name='transFatContent', schema_url='https://schema.org/transFatContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of trans fat.', label='transFatContent', contributors=(), sources=()),
        PropertyMetadata(name='unsaturated_fat_content', schema_name='unsaturatedFatContent', schema_url='https://schema.org/unsaturatedFatContent', ranges=('Mass',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NutritionInformation',), external_domains=(), comment='The number of grams of unsaturated fat.', label='unsaturatedFatContent', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['NutritionInformation'] = Field(default='NutritionInformation', alias='@type', frozen=True)
    calories: Energy | list[Energy] | None = Field(default=None, alias='calories', description='The number of calories.')
    carbohydrate_content: Mass | list[Mass] | None = Field(default=None, alias='carbohydrateContent', description='The number of grams of carbohydrates.')
    cholesterol_content: Mass | list[Mass] | None = Field(default=None, alias='cholesterolContent', description='The number of milligrams of cholesterol.')
    fat_content: Mass | list[Mass] | None = Field(default=None, alias='fatContent', description='The number of grams of fat.')
    fiber_content: Mass | list[Mass] | None = Field(default=None, alias='fiberContent', description='The number of grams of fiber.')
    protein_content: Mass | list[Mass] | None = Field(default=None, alias='proteinContent', description='The number of grams of protein.')
    saturated_fat_content: Mass | list[Mass] | None = Field(default=None, alias='saturatedFatContent', description='The number of grams of saturated fat.')
    serving_size: Text | list[Text] | None = Field(default=None, alias='servingSize', description='The serving size, in terms of the number of volume or mass.')
    sodium_content: Mass | list[Mass] | None = Field(default=None, alias='sodiumContent', description='The number of milligrams of sodium.')
    sugar_content: Mass | list[Mass] | None = Field(default=None, alias='sugarContent', description='The number of grams of sugar.')
    trans_fat_content: Mass | list[Mass] | None = Field(default=None, alias='transFatContent', description='The number of grams of trans fat.')
    unsaturated_fat_content: Mass | list[Mass] | None = Field(default=None, alias='unsaturatedFatContent', description='The number of grams of unsaturated fat.')
