# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar, Literal

from pydantic import Field

from schema_org.base import PropertyMetadata
from schema_org.models.intangible import Intangible

if TYPE_CHECKING:
    from schema_org.datatypes import Number, Text
    from schema_org.models import (
        AdministrativeArea,
        CategoryCode,
        Credential,
        DefinedTerm,
        EducationalOccupationalCredential,
        MonetaryAmount,
        MonetaryAmountDistribution,
        OccupationalExperienceRequirements,
    )


class Occupation(Intangible):
    __doc__ = 'https://schema.org/Occupation\n\nA profession, may involve prolonged training and/or a formal qualification.'
    SCHEMA_TYPE: ClassVar[str] = 'Occupation'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Occupation', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='education_requirements', schema_name='educationRequirements', schema_url='https://schema.org/educationRequirements', ranges=('EducationalOccupationalCredential', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Educational background needed for the position or Occupation.', label='educationRequirements', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/1779')),
        PropertyMetadata(name='estimated_salary', schema_name='estimatedSalary', schema_url='https://schema.org/estimatedSalary', ranges=('MonetaryAmount', 'MonetaryAmountDistribution', 'Number'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.', label='estimatedSalary', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='experience_requirements', schema_name='experienceRequirements', schema_url='https://schema.org/experienceRequirements', ranges=('OccupationalExperienceRequirements', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Description of skills and experience needed for the position or Occupation.', label='experienceRequirements', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='occupation_location', schema_name='occupationLocation', schema_url='https://schema.org/occupationLocation', ranges=('AdministrativeArea',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Occupation',), external_domains=(), comment=' The region/country for which this occupational description is appropriate. Note that educational requirements and qualifications can vary between jurisdictions.', label='occupationLocation', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='occupational_category', schema_name='occupationalCategory', schema_url='https://schema.org/occupationalCategory', ranges=('CategoryCode', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('EducationalOccupationalProgram', 'JobPosting', 'Occupation', 'Physician', 'WorkBasedProgram'), external_domains=(), comment='A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\\n\nNote: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.', label='occupationalCategory', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2192', 'https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2460', 'https://github.com/schemaorg/schemaorg/issues/3420')),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='qualifications', schema_name='qualifications', schema_url='https://schema.org/qualifications', ranges=('Credential', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Specific qualifications required for this role or Occupation.', label='qualifications', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/1779')),
        PropertyMetadata(name='responsibilities', schema_name='responsibilities', schema_url='https://schema.org/responsibilities', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation'), external_domains=(), comment='Responsibilities associated with this role or Occupation.', label='responsibilities', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='skills', schema_name='skills', schema_url='https://schema.org/skills', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation', 'Organization', 'Person'), external_domains=(), comment='A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.', label='skills', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2322')),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Occupation'] = Field(default='Occupation', alias='@type', frozen=True)
    education_requirements: EducationalOccupationalCredential | Text | list[EducationalOccupationalCredential | Text] | None = Field(default=None, alias='educationRequirements', description='Educational background needed for the position or Occupation.')
    estimated_salary: MonetaryAmount | MonetaryAmountDistribution | Number | list[MonetaryAmount | MonetaryAmountDistribution | Number] | None = Field(default=None, alias='estimatedSalary', description='An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.')
    experience_requirements: OccupationalExperienceRequirements | Text | list[OccupationalExperienceRequirements | Text] | None = Field(default=None, alias='experienceRequirements', description='Description of skills and experience needed for the position or Occupation.')
    occupation_location: AdministrativeArea | list[AdministrativeArea] | None = Field(default=None, alias='occupationLocation', description=' The region/country for which this occupational description is appropriate. Note that educational requirements and qualifications can vary between jurisdictions.')
    occupational_category: CategoryCode | Text | list[CategoryCode | Text] | None = Field(default=None, alias='occupationalCategory', description='A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\\n\nNote: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.')
    qualifications: Credential | Text | list[Credential | Text] | None = Field(default=None, alias='qualifications', description='Specific qualifications required for this role or Occupation.')
    responsibilities: Text | list[Text] | None = Field(default=None, alias='responsibilities', description='Responsibilities associated with this role or Occupation.')
    skills: DefinedTerm | Text | list[DefinedTerm | Text] | None = Field(default=None, alias='skills', description='A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.')
