# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import OrderStatus
from schema_org.models.intangible import Intangible

class Order(Intangible):
    __doc__ = 'https://schema.org/Order\n\nAn order is a confirmation of a transaction (a receipt), which can contain multiple line items, each represented by an Offer that has been accepted by the customer.'
    SCHEMA_TYPE: ClassVar[str] = 'Order'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Order', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='accepted_offer', schema_name='acceptedOffer', schema_url='https://schema.org/acceptedOffer', ranges=('Offer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment='The offer(s) -- e.g., product, quantity and price combinations -- included in the order.', label='acceptedOffer', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='billing_address', schema_name='billingAddress', schema_url='https://schema.org/billingAddress', ranges=('PostalAddress',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#BillingAddress',), subproperty_of=(), domains=('Order',), external_domains=(), comment='The billing address for the order.', label='billingAddress', contributors=(), sources=()),
        PropertyMetadata(name='broker', schema_name='broker', schema_url='https://schema.org/broker', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('bookingAgent',), equivalent_properties=(), subproperty_of=(), domains=('Invoice', 'Order', 'Reservation', 'Service'), external_domains=(), comment='An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.', label='broker', contributors=(), sources=()),
        PropertyMetadata(name='confirmation_number', schema_name='confirmationNumber', schema_url='https://schema.org/confirmationNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Invoice', 'Order'), external_domains=(), comment='A number that confirms the given order or payment has been received.', label='confirmationNumber', contributors=(), sources=()),
        PropertyMetadata(name='customer', schema_name='customer', schema_url='https://schema.org/customer', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Invoice', 'Order'), external_domains=(), comment='Party placing the order or paying the invoice.', label='customer', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='discount', schema_name='discount', schema_url='https://schema.org/discount', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment='Any discount applied (to an Order).', label='discount', contributors=(), sources=()),
        PropertyMetadata(name='discount_code', schema_name='discountCode', schema_url='https://schema.org/discountCode', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment='Code used to redeem a discount.', label='discountCode', contributors=(), sources=()),
        PropertyMetadata(name='discount_currency', schema_name='discountCurrency', schema_url='https://schema.org/discountCurrency', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment='The currency of the discount.\\n\\nUse standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR".', label='discountCurrency', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='is_gift', schema_name='isGift', schema_url='https://schema.org/isGift', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment='Indicates whether the offer was accepted as a gift for someone other than the buyer.', label='isGift', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='merchant', schema_name='merchant', schema_url='https://schema.org/merchant', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by='seller', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment="'merchant' is an out-dated term for 'seller'.", label='merchant', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='order_date', schema_name='orderDate', schema_url='https://schema.org/orderDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#OrderDate',), subproperty_of=('https://www.omg.org/spec/Commons/DatesAndTimes/hasDate',), domains=('Order',), external_domains=(), comment='Date order was placed.', label='orderDate', contributors=(), sources=()),
        PropertyMetadata(name='order_delivery', schema_name='orderDelivery', schema_url='https://schema.org/orderDelivery', ranges=('ParcelDelivery',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order', 'OrderItem'), external_domains=(), comment='The delivery of the parcel related to this order or order item.', label='orderDelivery', contributors=(), sources=()),
        PropertyMetadata(name='order_number', schema_name='orderNumber', schema_url='https://schema.org/orderNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#OrderIdentifier',), subproperty_of=('identifier',), domains=('Order',), external_domains=(), comment='The identifier of the transaction.', label='orderNumber', contributors=(), sources=()),
        PropertyMetadata(name='order_status', schema_name='orderStatus', schema_url='https://schema.org/orderStatus', ranges=('OrderStatus',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Order',), external_domains=(), comment='The current status of the order.', label='orderStatus', contributors=(), sources=()),
        PropertyMetadata(name='ordered_item', schema_name='orderedItem', schema_url='https://schema.org/orderedItem', ranges=('OrderItem', 'Product', 'Service'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasProduct',), domains=('Order', 'OrderItem'), external_domains=(), comment='The item ordered.', label='orderedItem', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='part_of_invoice', schema_name='partOfInvoice', schema_url='https://schema.org/partOfInvoice', ranges=('Invoice',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/isReferencedIn', 'https://www.omg.org/spec/Commons/Collections/isPartOf'), domains=('Order',), external_domains=(), comment='The order is being paid as part of the referenced Invoice.', label='partOfInvoice', contributors=(), sources=()),
        PropertyMetadata(name='payment_due', schema_name='paymentDue', schema_url='https://schema.org/paymentDue', ranges=('DateTime',), external_ranges=(), inverse_of=None, superseded_by='paymentDueDate', supersedes=(), equivalent_properties=('http://unece.org/vocab#PaymentDueDate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt/hasPaymentDueDate',), domains=('Invoice', 'Order'), external_domains=(), comment='The date that payment is due.', label='paymentDue', contributors=(), sources=()),
        PropertyMetadata(name='payment_due_date', schema_name='paymentDueDate', schema_url='https://schema.org/paymentDueDate', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('paymentDue',), equivalent_properties=('http://unece.org/vocab#PaymentDueDate',), subproperty_of=(), domains=('Invoice', 'Order'), external_domains=(), comment='The date that payment is due.', label='paymentDueDate', contributors=(), sources=()),
        PropertyMetadata(name='payment_method', schema_name='paymentMethod', schema_url='https://schema.org/paymentMethod', ranges=('PaymentMethod', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/hasPaymentMechanism',), domains=('Invoice', 'Order'), external_domains=(), comment='The name of the credit card or other method of payment for the order.', label='paymentMethod', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3537',)),
        PropertyMetadata(name='payment_method_id', schema_name='paymentMethodId', schema_url='https://schema.org/paymentMethodId', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#PaymentMeansID',), subproperty_of=(), domains=('Invoice', 'Order'), external_domains=(), comment='An identifier for the method of payment used (e.g. the last 4 digits of the credit card).', label='paymentMethodId', contributors=(), sources=()),
        PropertyMetadata(name='payment_url', schema_name='paymentUrl', schema_url='https://schema.org/paymentUrl', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasAddress',), domains=('Order',), external_domains=(), comment='The URL for sending a payment.', label='paymentUrl', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='seller', schema_name='seller', schema_url='https://schema.org/seller', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('merchant', 'vendor'), equivalent_properties=('http://unece.org/vocab#Seller',), subproperty_of=('participant', 'https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasSupplier'), domains=('BuyAction', 'Demand', 'Flight', 'Offer', 'Order'), external_domains=(), comment='An entity which offers (sells / leases / lends / loans) the services / goods.  A seller may also be a provider.', label='seller', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Order'] = Field(default='Order', alias='@type', frozen=True)
    accepted_offer: Offer | list[Offer] | None = Field(default=None, alias='acceptedOffer', description='The offer(s) -- e.g., product, quantity and price combinations -- included in the order.')
    billing_address: PostalAddress | list[PostalAddress] | None = Field(default=None, alias='billingAddress', description='The billing address for the order.')
    broker: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='broker', description='An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.\n\nSupersedes `bookingAgent`.')
    confirmation_number: Text | list[Text] | None = Field(default=None, alias='confirmationNumber', description='A number that confirms the given order or payment has been received.')
    customer: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='customer', description='Party placing the order or paying the invoice.')
    discount: Number | Text | list[Number | Text] | None = Field(default=None, alias='discount', description='Any discount applied (to an Order).')
    discount_code: Text | list[Text] | None = Field(default=None, alias='discountCode', description='Code used to redeem a discount.')
    discount_currency: Text | list[Text] | None = Field(default=None, alias='discountCurrency', description='The currency of the discount.\\n\\nUse standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR".')
    is_gift: Boolean | list[Boolean] | None = Field(default=None, alias='isGift', description='Indicates whether the offer was accepted as a gift for someone other than the buyer.')
    merchant: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='merchant', description="'merchant' is an out-dated term for 'seller'.\n\nSuperseded by `seller`.")
    order_date: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='orderDate', description='Date order was placed.')
    order_delivery: ParcelDelivery | list[ParcelDelivery] | None = Field(default=None, alias='orderDelivery', description='The delivery of the parcel related to this order or order item.')
    order_number: Text | list[Text] | None = Field(default=None, alias='orderNumber', description='The identifier of the transaction.')
    order_status: OrderStatus | list[OrderStatus] | None = Field(default=None, alias='orderStatus', description='The current status of the order.')
    ordered_item: OrderItem | Product | Service | list[OrderItem | Product | Service] | None = Field(default=None, alias='orderedItem', description='The item ordered.')
    part_of_invoice: Invoice | list[Invoice] | None = Field(default=None, alias='partOfInvoice', description='The order is being paid as part of the referenced Invoice.')
    payment_due: DateTime | list[DateTime] | None = Field(default=None, alias='paymentDue', description='The date that payment is due.\n\nSuperseded by `paymentDueDate`.')
    payment_due_date: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='paymentDueDate', description='The date that payment is due.\n\nSupersedes `paymentDue`.')
    payment_method: PaymentMethod | Text | list[PaymentMethod | Text] | None = Field(default=None, alias='paymentMethod', description='The name of the credit card or other method of payment for the order.')
    payment_method_id: Text | list[Text] | None = Field(default=None, alias='paymentMethodId', description='An identifier for the method of payment used (e.g. the last 4 digits of the credit card).')
    payment_url: URL | list[URL] | None = Field(default=None, alias='paymentUrl', description='The URL for sending a payment.')
    seller: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='seller', description='An entity which offers (sells / leases / lends / loans) the services / goods.  A seller may also be a provider.\n\nSupersedes `merchant`.\n\nSupersedes `vendor`.')
