# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Date
from schema_org.datatypes import DateTime
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import DeliveryMethod
from schema_org.models.intangible import Intangible

class ParcelDelivery(Intangible):
    __doc__ = 'https://schema.org/ParcelDelivery\n\nThe delivery of a parcel either via the postal service or a commercial service.'
    SCHEMA_TYPE: ClassVar[str] = 'ParcelDelivery'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('ParcelDelivery', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='carrier', schema_name='carrier', schema_url='https://schema.org/carrier', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by='provider', supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Flight', 'ParcelDelivery'), external_domains=(), comment="'carrier' is an out-dated term indicating the 'provider' for parcel delivery and flights.", label='carrier', contributors=(), sources=()),
        PropertyMetadata(name='delivery_address', schema_name='deliveryAddress', schema_url='https://schema.org/deliveryAddress', ranges=('PostalAddress',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#ShipToAddress',), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment='Destination address.', label='deliveryAddress', contributors=(), sources=()),
        PropertyMetadata(name='delivery_status', schema_name='deliveryStatus', schema_url='https://schema.org/deliveryStatus', ranges=('DeliveryEvent',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment='New entry added as the package passes through each leg of its journey (from shipment to final delivery).', label='deliveryStatus', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='expected_arrival_from', schema_name='expectedArrivalFrom', schema_url='https://schema.org/expectedArrivalFrom', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment='The earliest date the package may arrive.', label='expectedArrivalFrom', contributors=(), sources=()),
        PropertyMetadata(name='expected_arrival_until', schema_name='expectedArrivalUntil', schema_url='https://schema.org/expectedArrivalUntil', ranges=('Date', 'DateTime'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment='The latest date the package may arrive.', label='expectedArrivalUntil', contributors=(), sources=()),
        PropertyMetadata(name='has_delivery_method', schema_name='hasDeliveryMethod', schema_url='https://schema.org/hasDeliveryMethod', ranges=('DeliveryMethod',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('DeliveryEvent', 'ParcelDelivery'), external_domains=(), comment='Method used for delivery or shipping.', label='hasDeliveryMethod', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='item_shipped', schema_name='itemShipped', schema_url='https://schema.org/itemShipped', ranges=('Product',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#IncludedConsignmentItem',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasProduct',), domains=('ParcelDelivery',), external_domains=(), comment='Item(s) being shipped.', label='itemShipped', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='origin_address', schema_name='originAddress', schema_url='https://schema.org/originAddress', ranges=('PostalAddress',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment="Shipper's address.", label='originAddress', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='part_of_order', schema_name='partOfOrder', schema_url='https://schema.org/partOfOrder', ranges=('Order',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#ReferencedOrder',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/refersTo',), domains=('ParcelDelivery',), external_domains=(), comment='The overall order the items in this delivery were included in.', label='partOfOrder', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='provider', schema_name='provider', schema_url='https://schema.org/provider', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes='carrier', equivalent_properties=('http://unece.org/vocab#ServiceProvider',), subproperty_of=(), domains=('Action', 'CreativeWork', 'EducationalOccupationalProgram', 'FinancialIncentive', 'Invoice', 'ParcelDelivery', 'Reservation', 'Service', 'Trip'), external_domains=(), comment='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.', label='provider', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289', 'https://github.com/schemaorg/schemaorg/issues/2927')),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='tracking_number', schema_name='trackingNumber', schema_url='https://schema.org/trackingNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment='Shipper tracking number.', label='trackingNumber', contributors=(), sources=()),
        PropertyMetadata(name='tracking_url', schema_name='trackingUrl', schema_url='https://schema.org/trackingUrl', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ParcelDelivery',), external_domains=(), comment='Tracking url for the parcel delivery.', label='trackingUrl', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['ParcelDelivery'] = Field(default='ParcelDelivery', alias='@type', frozen=True)
    carrier: Organization | list[Organization] | None = Field(default=None, alias='carrier', description="'carrier' is an out-dated term indicating the 'provider' for parcel delivery and flights.\n\nSuperseded by `provider`.")
    delivery_address: PostalAddress | list[PostalAddress] | None = Field(default=None, alias='deliveryAddress', description='Destination address.')
    delivery_status: DeliveryEvent | list[DeliveryEvent] | None = Field(default=None, alias='deliveryStatus', description='New entry added as the package passes through each leg of its journey (from shipment to final delivery).')
    expected_arrival_from: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='expectedArrivalFrom', description='The earliest date the package may arrive.')
    expected_arrival_until: Date | DateTime | list[Date | DateTime] | None = Field(default=None, alias='expectedArrivalUntil', description='The latest date the package may arrive.')
    has_delivery_method: DeliveryMethod | list[DeliveryMethod] | None = Field(default=None, alias='hasDeliveryMethod', description='Method used for delivery or shipping.')
    item_shipped: Product | list[Product] | None = Field(default=None, alias='itemShipped', description='Item(s) being shipped.')
    origin_address: PostalAddress | list[PostalAddress] | None = Field(default=None, alias='originAddress', description="Shipper's address.")
    part_of_order: Order | list[Order] | None = Field(default=None, alias='partOfOrder', description='The overall order the items in this delivery were included in.')
    provider: Organization | Person | list[Organization | Person] | None = Field(default=None, alias='provider', description='The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.\n\nSupersedes `carrier`.')
    tracking_number: Text | list[Text] | None = Field(default=None, alias='trackingNumber', description='Shipper tracking number.')
    tracking_url: URL | list[URL] | None = Field(default=None, alias='trackingUrl', description='Tracking url for the parcel delivery.')
