# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Date
from schema_org.datatypes import Distance
from schema_org.datatypes import Integer
from schema_org.datatypes import Mass
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import GenderType
from schema_org.models.medical_audience import MedicalAudience
from schema_org.models.person import Person

class Patient(MedicalAudience, Person):
    __doc__ = 'https://schema.org/Patient\n\nA patient is any person recipient of health care services.'
    SCHEMA_TYPE: ClassVar[str] = 'Patient'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Patient', 'MedicalAudience', 'Person', 'Audience', 'PeopleAudience', 'Thing', 'Intangible')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_name', schema_name='additionalName', schema_url='https://schema.org/additionalName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('alternateName',), domains=('Person',), external_domains=(), comment='An additional name for a Person, can be used for a middle name.', label='additionalName', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='address', schema_name='address', schema_url='https://schema.org/address', ranges=('PostalAddress', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/address',), subproperty_of=(), domains=('GeoCoordinates', 'GeoShape', 'Organization', 'Person', 'Place'), external_domains=(), comment='Physical address of the item.', label='address', contributors=(), sources=()),
        PropertyMetadata(name='affiliation', schema_name='affiliation', schema_url='https://schema.org/affiliation', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('memberOf',), domains=('Person',), external_domains=(), comment='An organization that this person is affiliated with. For example, a school/university, a club, or a team.', label='affiliation', contributors=(), sources=()),
        PropertyMetadata(name='agent_interaction_statistic', schema_name='agentInteractionStatistic', schema_url='https://schema.org/agentInteractionStatistic', ranges=('InteractionCounter',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment="The number of completed interactions for this entity, in a particular role (the 'agent'), in a particular action (indicated in the statistic), and in a particular context (i.e. interactionService).", label='agentInteractionStatistic', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2858',)),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='alumni_of', schema_name='alumniOf', schema_url='https://schema.org/alumniOf', ranges=('EducationalOrganization', 'Organization'), external_ranges=(), inverse_of='alumni', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='An organization that the person is an alumni of.', label='alumniOf', contributors=(), sources=()),
        PropertyMetadata(name='audience_type', schema_name='audienceType', schema_url='https://schema.org/audienceType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Audience',), external_domains=(), comment='The target group associated with a given audience (e.g. veterans, car owners, musicians, etc.).', label='audienceType', contributors=(), sources=()),
        PropertyMetadata(name='award', schema_name='award', schema_url='https://schema.org/award', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('awards',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='An award won by or for this item.', label='award', contributors=(), sources=()),
        PropertyMetadata(name='awards', schema_name='awards', schema_url='https://schema.org/awards', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by='award', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product'), external_domains=(), comment='Awards won by or for this item.', label='awards', contributors=(), sources=()),
        PropertyMetadata(name='birth_date', schema_name='birthDate', schema_url='https://schema.org/birthDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Date of birth.', label='birthDate', contributors=(), sources=()),
        PropertyMetadata(name='birth_place', schema_name='birthPlace', schema_url='https://schema.org/birthPlace', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The place where the person was born.', label='birthPlace', contributors=(), sources=()),
        PropertyMetadata(name='brand', schema_name='brand', schema_url='https://schema.org/brand', ranges=('Brand', 'Organization'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#brandName',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/hasDesignation',), domains=('Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.', label='brand', contributors=(), sources=()),
        PropertyMetadata(name='call_sign', schema_name='callSign', schema_url='https://schema.org/callSign', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('BroadcastService', 'Person', 'Vehicle'), external_domains=(), comment='A [callsign](https://en.wikipedia.org/wiki/Call_sign), as used in broadcasting and radio communications to identify people, radio and TV stations, or vehicles.', label='callSign', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2109',)),
        PropertyMetadata(name='children', schema_name='children', schema_url='https://schema.org/children', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A child of the person.', label='children', contributors=(), sources=()),
        PropertyMetadata(name='colleague', schema_name='colleague', schema_url='https://schema.org/colleague', ranges=('Person', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('colleagues',), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A colleague of the person.', label='colleague', contributors=(), sources=()),
        PropertyMetadata(name='colleagues', schema_name='colleagues', schema_url='https://schema.org/colleagues', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by='colleague', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A colleague of the person.', label='colleagues', contributors=(), sources=()),
        PropertyMetadata(name='contact_point', schema_name='contactPoint', schema_url='https://schema.org/contactPoint', ranges=('ContactPoint',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('contactPoints',), equivalent_properties=('https://ref.gs1.org/voc/contactPoint', 'https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/Organizations/hasContactPoint'), subproperty_of=(), domains=('HealthInsurancePlan', 'Organization', 'Person'), external_domains=(), comment='A contact point for a person or organization.', label='contactPoint', contributors=(), sources=()),
        PropertyMetadata(name='contact_points', schema_name='contactPoints', schema_url='https://schema.org/contactPoints', ranges=('ContactPoint',), external_ranges=(), inverse_of=None, superseded_by='contactPoint', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A contact point for a person or organization.', label='contactPoints', contributors=(), sources=()),
        PropertyMetadata(name='death_date', schema_name='deathDate', schema_url='https://schema.org/deathDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Date of death.', label='deathDate', contributors=(), sources=()),
        PropertyMetadata(name='death_place', schema_name='deathPlace', schema_url='https://schema.org/deathPlace', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The place where the person died.', label='deathPlace', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='diagnosis', schema_name='diagnosis', schema_url='https://schema.org/diagnosis', ranges=('MedicalCondition',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('DDxElement', 'Patient'), external_domains=(), comment='One or more alternative conditions considered in the differential diagnosis process as output of a diagnosis process.', label='diagnosis', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='drug', schema_name='drug', schema_url='https://schema.org/drug', ranges=('Drug',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('DrugClass', 'MedicalCondition', 'Patient', 'TherapeuticProcedure'), external_domains=(), comment='Specifying a drug or medicine used in a medication procedure.', label='drug', contributors=(), sources=()),
        PropertyMetadata(name='duns', schema_name='duns', schema_url='https://schema.org/duns', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#dUNSId',), subproperty_of=('identifier',), domains=('Organization', 'Person'), external_domains=(), comment='The Dun & Bradstreet DUNS number for identifying an organization or business person.', label='duns', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='email', schema_name='email', schema_url='https://schema.org/email', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/email',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person'), external_domains=(), comment='Email address.', label='email', contributors=(), sources=()),
        PropertyMetadata(name='family_name', schema_name='familyName', schema_url='https://schema.org/familyName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Family name. In the U.S., the last name of a Person.', label='familyName', contributors=(), sources=()),
        PropertyMetadata(name='fax_number', schema_name='faxNumber', schema_url='https://schema.org/faxNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/faxNumber',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The fax number.', label='faxNumber', contributors=(), sources=()),
        PropertyMetadata(name='follows', schema_name='follows', schema_url='https://schema.org/follows', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The most generic uni-directional social relation.', label='follows', contributors=(), sources=()),
        PropertyMetadata(name='funder', schema_name='funder', schema_url='https://schema.org/funder', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('sponsor',), domains=('CreativeWork', 'Event', 'Grant', 'MonetaryGrant', 'Organization', 'Person'), external_domains=(), comment='A person or organization that supports (sponsors) something through some kind of financial contribution.', label='funder', contributors=(), sources=()),
        PropertyMetadata(name='funding', schema_name='funding', schema_url='https://schema.org/funding', ranges=('Grant',), external_ranges=(), inverse_of='fundedItem', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity', 'CreativeWork', 'Event', 'MedicalEntity', 'Organization', 'Person', 'Product'), external_domains=(), comment='A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].', label='funding', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/383',)),
        PropertyMetadata(name='gender', schema_name='gender', schema_url='https://schema.org/gender', ranges=('GenderType', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person', 'SportsTeam'), external_domains=(), comment='Gender of something, typically a [[Person]], but possibly also fictional characters, animals, etc. While https://schema.org/Male and https://schema.org/Female may be used, text strings are also acceptable for people who are not a binary gender. The [[gender]] property can also be used in an extended sense to cover e.g. the gender of sports teams. As with the gender of individuals, we do not try to enumerate all possibilities. A mixed-gender [[SportsTeam]] can be indicated with a text value of "Mixed".', label='gender', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2341',)),
        PropertyMetadata(name='geographic_area', schema_name='geographicArea', schema_url='https://schema.org/geographicArea', ranges=('AdministrativeArea',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Audience',), external_domains=(), comment='The geographic area associated with the audience.', label='geographicArea', contributors=(), sources=()),
        PropertyMetadata(name='given_name', schema_name='givenName', schema_url='https://schema.org/givenName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Given name. In the U.S., the first name of a Person.', label='givenName', contributors=(), sources=()),
        PropertyMetadata(name='global_location_number', schema_name='globalLocationNumber', schema_url='https://schema.org/globalLocationNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#gLNId', 'https://ref.gs1.org/voc/globalLocationNumber'), subproperty_of=('identifier',), domains=('Organization', 'Person', 'Place'), external_domains=(), comment='The [Global Location Number](http://www.gs1.org/gln) (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', label='globalLocationNumber', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='has_certification', schema_name='hasCertification', schema_url='https://schema.org/hasCertification', ranges=('Certification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ApplicableCertificate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/isReferencedIn', 'https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy'), domains=('Organization', 'Person', 'Place', 'Product', 'Service'), external_domains=(), comment='Certification information about a product, organization, service, place, or person.', label='hasCertification', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3230',)),
        PropertyMetadata(name='has_credential', schema_name='hasCredential', schema_url='https://schema.org/hasCredential', ranges=('Credential',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A credential awarded to the Person or Organization.', label='hasCredential', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='has_occupation', schema_name='hasOccupation', schema_url='https://schema.org/hasOccupation', ranges=('Occupation',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment="The Person's occupation. For past professions, use Role for expressing dates.", label='hasOccupation', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698',)),
        PropertyMetadata(name='has_offer_catalog', schema_name='hasOfferCatalog', schema_url='https://schema.org/hasOfferCatalog', ranges=('OfferCatalog',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person', 'Service'), external_domains=(), comment='Indicates an OfferCatalog listing for this Organization, Person, or Service.', label='hasOfferCatalog', contributors=(), sources=()),
        PropertyMetadata(name='has_pos', schema_name='hasPOS', schema_url='https://schema.org/hasPOS', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Points-of-Sales operated by the organization or person.', label='hasPOS', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='health_condition', schema_name='healthCondition', schema_url='https://schema.org/healthCondition', ranges=('MedicalCondition',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalStudy', 'Patient', 'PeopleAudience'), external_domains=(), comment='Specifying the health condition(s) of a patient, medical study, or other target audience.', label='healthCondition', contributors=(), sources=()),
        PropertyMetadata(name='height', schema_name='height', schema_url='https://schema.org/height', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MediaObject', 'OfferShippingDetails', 'Person', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The height of the item.', label='height', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='home_location', schema_name='homeLocation', schema_url='https://schema.org/homeLocation', ranges=('ContactPoint', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('Person',), external_domains=(), comment="A contact location for a person's residence.", label='homeLocation', contributors=(), sources=()),
        PropertyMetadata(name='honorific_prefix', schema_name='honorificPrefix', schema_url='https://schema.org/honorificPrefix', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment="An honorific prefix preceding a Person's name such as Dr/Mrs/Mr.", label='honorificPrefix', contributors=(), sources=()),
        PropertyMetadata(name='honorific_suffix', schema_name='honorificSuffix', schema_url='https://schema.org/honorificSuffix', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment="An honorific suffix following a Person's name such as M.D./PhD/MSCSW.", label='honorificSuffix', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='interaction_statistic', schema_name='interactionStatistic', schema_url='https://schema.org/interactionStatistic', ranges=('InteractionCounter',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('interactionCount',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person'), external_domains=(), comment='The number of interactions for the CreativeWork using the WebSite or SoftwareApplication. The most specific child type of InteractionCounter should be used.', label='interactionStatistic', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2421',)),
        PropertyMetadata(name='isic_v4', schema_name='isicV4', schema_url='https://schema.org/isicV4', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person', 'Place'), external_domains=(), comment='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', label='isicV4', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='job_title', schema_name='jobTitle', schema_url='https://schema.org/jobTitle', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The job title of the person (for example, Financial Manager).', label='jobTitle', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2192',)),
        PropertyMetadata(name='knows', schema_name='knows', schema_url='https://schema.org/knows', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The most generic bi-directional social/work relation.', label='knows', contributors=(), sources=()),
        PropertyMetadata(name='knows_about', schema_name='knowsAbout', schema_url='https://schema.org/knowsAbout', ranges=('Text', 'Thing', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Of a [[Person]], and less typically of an [[Organization]], to indicate a topic that is known about - suggesting possible expertise but not implying it. We do not distinguish skill levels here, or relate this to educational content, events, objectives or [[JobPosting]] descriptions.', label='knowsAbout', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1688',)),
        PropertyMetadata(name='knows_language', schema_name='knowsLanguage', schema_url='https://schema.org/knowsLanguage', ranges=('Language', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Of a [[Person]], and less typically of an [[Organization]], to indicate a known language. We do not distinguish skill levels or reading/writing/speaking/signing here. Use language codes from the [IETF BCP 47 standard](http://tools.ietf.org/html/bcp47).', label='knowsLanguage', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1688',)),
        PropertyMetadata(name='life_event', schema_name='lifeEvent', schema_url='https://schema.org/lifeEvent', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A life event like baptism, communions, Bar Mitzvahs, Aqiqah, Namakarana, Miyamairi, burial, ....', label='lifeEvent', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4540',)),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='makes_offer', schema_name='makesOffer', schema_url='https://schema.org/makesOffer', ranges=('Offer',), external_ranges=(), inverse_of='offeredBy', superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/offers',), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A pointer to products or services offered by the organization or person.', label='makesOffer', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='member_of', schema_name='memberOf', schema_url='https://schema.org/memberOf', ranges=('MemberProgramTier', 'Organization', 'ProgramMembership'), external_ranges=(), inverse_of='member', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='An Organization (or ProgramMembership) to which this Person or Organization belongs.', label='memberOf', contributors=(), sources=()),
        PropertyMetadata(name='naics', schema_name='naics', schema_url='https://schema.org/naics', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy',), domains=('Organization', 'Person'), external_domains=(), comment='The North American Industry Classification System (NAICS) code for a particular organization or business person.', label='naics', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='nationality', schema_name='nationality', schema_url='https://schema.org/nationality', ranges=('Country',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Nationality of the person.', label='nationality', contributors=(), sources=()),
        PropertyMetadata(name='net_worth', schema_name='netWorth', schema_url='https://schema.org/netWorth', ranges=('MonetaryAmount', 'PriceSpecification'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The total financial value of the person as calculated by subtracting the total value of liabilities from the total value of assets.', label='netWorth', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='owns', schema_name='owns', schema_url='https://schema.org/owns', ranges=('Thing',), external_ranges=(), inverse_of='owner', superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/owns',), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Things owned by the organization or person.', label='owns', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='parent', schema_name='parent', schema_url='https://schema.org/parent', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('parents',), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A parent of this person.', label='parent', contributors=(), sources=()),
        PropertyMetadata(name='parents', schema_name='parents', schema_url='https://schema.org/parents', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by='parent', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A parents of the person.', label='parents', contributors=(), sources=()),
        PropertyMetadata(name='performer_in', schema_name='performerIn', schema_url='https://schema.org/performerIn', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Event that this person is a performer or participant in.', label='performerIn', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='pronouns', schema_name='pronouns', schema_url='https://schema.org/pronouns', ranges=('DefinedTerm', 'StructuredValue', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A short string listing or describing pronouns for a person. Typically the person concerned is the best authority as pronouns are a critical part of personal identity and expression. Publishers and consumers of this information are reminded to treat this data responsibly, take country-specific laws related to gender expression into account, and be wary of out-of-date data and drawing unwarranted inferences about the person being described.\n\nIn English, formulations such as "they/them", "she/her", and "he/him" are commonly used online and can also be used here. We do not intend to enumerate all possible micro-syntaxes in all languages. More structured and well-defined external values for pronouns can be referenced using the [[StructuredValue]] or [[DefinedTerm]] values.\n', label='pronouns', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2935',)),
        PropertyMetadata(name='publishing_principles', schema_name='publishingPrinciples', schema_url='https://schema.org/publishingPrinciples', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person'), external_domains=(), comment='The publishingPrinciples property indicates (typically via [[URL]]) a document describing the editorial principles of an [[Organization]] (or individual, e.g. a [[Person]] writing a blog) that relate to their activities as a publisher, e.g. ethics or diversity policies. When applied to a [[CreativeWork]] (e.g. [[NewsArticle]]) the principles are those of the party primarily responsible for the creation of the [[CreativeWork]].\n\nWhile such policies are most typically expressed in natural language, sometimes related information (e.g. indicating a [[funder]]) can be expressed using schema.org terminology.\n', label='publishingPrinciples', contributors=(), sources=()),
        PropertyMetadata(name='related_to', schema_name='relatedTo', schema_url='https://schema.org/relatedTo', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='The most generic familial relation.', label='relatedTo', contributors=(), sources=()),
        PropertyMetadata(name='required_gender', schema_name='requiredGender', schema_url='https://schema.org/requiredGender', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment="Audiences defined by a person's gender.", label='requiredGender', contributors=(), sources=()),
        PropertyMetadata(name='required_max_age', schema_name='requiredMaxAge', schema_url='https://schema.org/requiredMaxAge', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment="Audiences defined by a person's maximum age.", label='requiredMaxAge', contributors=(), sources=()),
        PropertyMetadata(name='required_min_age', schema_name='requiredMinAge', schema_url='https://schema.org/requiredMinAge', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment="Audiences defined by a person's minimum age.", label='requiredMinAge', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='seeks', schema_name='seeks', schema_url='https://schema.org/seeks', ranges=('Demand',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A pointer to products or services sought by the organization or person (demand).', label='seeks', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='sibling', schema_name='sibling', schema_url='https://schema.org/sibling', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('siblings',), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A sibling of the person.', label='sibling', contributors=(), sources=()),
        PropertyMetadata(name='siblings', schema_name='siblings', schema_url='https://schema.org/siblings', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by='sibling', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='A sibling of the person.', label='siblings', contributors=(), sources=()),
        PropertyMetadata(name='skills', schema_name='skills', schema_url='https://schema.org/skills', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation', 'Organization', 'Person'), external_domains=(), comment='A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.', label='skills', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2322')),
        PropertyMetadata(name='sponsor', schema_name='sponsor', schema_url='https://schema.org/sponsor', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Grant', 'MedicalStudy', 'Organization', 'Person'), external_domains=(), comment='A person or organization that supports a thing through a pledge, promise, or financial contribution. E.g. a sponsor of a Medical Study or a corporate sponsor of an event.', label='sponsor', contributors=(), sources=()),
        PropertyMetadata(name='spouse', schema_name='spouse', schema_url='https://schema.org/spouse', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment="The person's spouse.", label='spouse', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='suggested_age', schema_name='suggestedAge', schema_url='https://schema.org/suggestedAge', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience', 'SizeSpecification'), external_domains=(), comment='The age or age range for the intended audience or person, for example 3-12 months for infants, 1-5 years for toddlers.', label='suggestedAge', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2811',)),
        PropertyMetadata(name='suggested_gender', schema_name='suggestedGender', schema_url='https://schema.org/suggestedGender', ranges=('GenderType', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience', 'SizeSpecification'), external_domains=(), comment='The suggested gender of the intended person or audience, for example "male", "female", or "unisex".', label='suggestedGender', contributors=(), sources=()),
        PropertyMetadata(name='suggested_max_age', schema_name='suggestedMaxAge', schema_url='https://schema.org/suggestedMaxAge', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment='Maximum recommended age in years for the audience or user.', label='suggestedMaxAge', contributors=(), sources=()),
        PropertyMetadata(name='suggested_measurement', schema_name='suggestedMeasurement', schema_url='https://schema.org/suggestedMeasurement', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience', 'SizeSpecification'), external_domains=(), comment='A suggested range of body measurements for the intended audience or person, for example inseam between 32 and 34 inches or height between 170 and 190 cm. Typically found on a size chart for wearable products.', label='suggestedMeasurement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2811',)),
        PropertyMetadata(name='suggested_min_age', schema_name='suggestedMinAge', schema_url='https://schema.org/suggestedMinAge', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment='Minimum recommended age in years for the audience or user.', label='suggestedMinAge', contributors=(), sources=()),
        PropertyMetadata(name='tax_id', schema_name='taxID', schema_url='https://schema.org/taxID', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Parties/hasTaxIdentifier',), subproperty_of=('identifier',), domains=('Organization', 'Person'), external_domains=(), comment='The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.', label='taxID', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='telephone', schema_name='telephone', schema_url='https://schema.org/telephone', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/telephone',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The telephone number.', label='telephone', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='vat_id', schema_name='vatID', schema_url='https://schema.org/vatID', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='The value-added Tax ID of the organization or person with national prefix (for example IT123456789). Can also be described as [[iso6523Code]] with proper prefix.', label='vatID', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='weight', schema_name='weight', schema_url='https://schema.org/weight', ranges=('Mass', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'Person', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The weight of the product or person.', label='weight', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='work_location', schema_name='workLocation', schema_url='https://schema.org/workLocation', ranges=('ContactPoint', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('location',), domains=('Person',), external_domains=(), comment="A contact location for a person's place of work.", label='workLocation', contributors=(), sources=()),
        PropertyMetadata(name='works_for', schema_name='worksFor', schema_url='https://schema.org/worksFor', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Person',), external_domains=(), comment='Organizations that the person works for.', label='worksFor', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Patient'] = Field(default='Patient', alias='@type', frozen=True)
    diagnosis: MedicalCondition | list[MedicalCondition] | None = Field(default=None, alias='diagnosis', description='One or more alternative conditions considered in the differential diagnosis process as output of a diagnosis process.')
    drug: Drug | list[Drug] | None = Field(default=None, alias='drug', description='Specifying a drug or medicine used in a medication procedure.')
    health_condition: MedicalCondition | list[MedicalCondition] | None = Field(default=None, alias='healthCondition', description='Specifying the health condition(s) of a patient, medical study, or other target audience.')
