# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import GenderType
from schema_org.models.audience import Audience

class PeopleAudience(Audience):
    __doc__ = "https://schema.org/PeopleAudience\n\nA set of characteristics belonging to people, e.g. who compose an item's target audience."
    SCHEMA_TYPE: ClassVar[str] = 'PeopleAudience'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('PeopleAudience', 'Audience', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='audience_type', schema_name='audienceType', schema_url='https://schema.org/audienceType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Audience',), external_domains=(), comment='The target group associated with a given audience (e.g. veterans, car owners, musicians, etc.).', label='audienceType', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='geographic_area', schema_name='geographicArea', schema_url='https://schema.org/geographicArea', ranges=('AdministrativeArea',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Audience',), external_domains=(), comment='The geographic area associated with the audience.', label='geographicArea', contributors=(), sources=()),
        PropertyMetadata(name='health_condition', schema_name='healthCondition', schema_url='https://schema.org/healthCondition', ranges=('MedicalCondition',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalStudy', 'Patient', 'PeopleAudience'), external_domains=(), comment='Specifying the health condition(s) of a patient, medical study, or other target audience.', label='healthCondition', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='required_gender', schema_name='requiredGender', schema_url='https://schema.org/requiredGender', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment="Audiences defined by a person's gender.", label='requiredGender', contributors=(), sources=()),
        PropertyMetadata(name='required_max_age', schema_name='requiredMaxAge', schema_url='https://schema.org/requiredMaxAge', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment="Audiences defined by a person's maximum age.", label='requiredMaxAge', contributors=(), sources=()),
        PropertyMetadata(name='required_min_age', schema_name='requiredMinAge', schema_url='https://schema.org/requiredMinAge', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment="Audiences defined by a person's minimum age.", label='requiredMinAge', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='suggested_age', schema_name='suggestedAge', schema_url='https://schema.org/suggestedAge', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience', 'SizeSpecification'), external_domains=(), comment='The age or age range for the intended audience or person, for example 3-12 months for infants, 1-5 years for toddlers.', label='suggestedAge', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2811',)),
        PropertyMetadata(name='suggested_gender', schema_name='suggestedGender', schema_url='https://schema.org/suggestedGender', ranges=('GenderType', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience', 'SizeSpecification'), external_domains=(), comment='The suggested gender of the intended person or audience, for example "male", "female", or "unisex".', label='suggestedGender', contributors=(), sources=()),
        PropertyMetadata(name='suggested_max_age', schema_name='suggestedMaxAge', schema_url='https://schema.org/suggestedMaxAge', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment='Maximum recommended age in years for the audience or user.', label='suggestedMaxAge', contributors=(), sources=()),
        PropertyMetadata(name='suggested_measurement', schema_name='suggestedMeasurement', schema_url='https://schema.org/suggestedMeasurement', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience', 'SizeSpecification'), external_domains=(), comment='A suggested range of body measurements for the intended audience or person, for example inseam between 32 and 34 inches or height between 170 and 190 cm. Typically found on a size chart for wearable products.', label='suggestedMeasurement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2811',)),
        PropertyMetadata(name='suggested_min_age', schema_name='suggestedMinAge', schema_url='https://schema.org/suggestedMinAge', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PeopleAudience',), external_domains=(), comment='Minimum recommended age in years for the audience or user.', label='suggestedMinAge', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['PeopleAudience'] = Field(default='PeopleAudience', alias='@type', frozen=True)
    health_condition: MedicalCondition | list[MedicalCondition] | None = Field(default=None, alias='healthCondition', description='Specifying the health condition(s) of a patient, medical study, or other target audience.')
    required_gender: Text | list[Text] | None = Field(default=None, alias='requiredGender', description="Audiences defined by a person's gender.")
    required_max_age: Integer | list[Integer] | None = Field(default=None, alias='requiredMaxAge', description="Audiences defined by a person's maximum age.")
    required_min_age: Integer | list[Integer] | None = Field(default=None, alias='requiredMinAge', description="Audiences defined by a person's minimum age.")
    suggested_age: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='suggestedAge', description='The age or age range for the intended audience or person, for example 3-12 months for infants, 1-5 years for toddlers.')
    suggested_gender: GenderType | Text | list[GenderType | Text] | None = Field(default=None, alias='suggestedGender', description='The suggested gender of the intended person or audience, for example "male", "female", or "unisex".')
    suggested_max_age: Number | list[Number] | None = Field(default=None, alias='suggestedMaxAge', description='Maximum recommended age in years for the audience or user.')
    suggested_measurement: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='suggestedMeasurement', description='A suggested range of body measurements for the intended audience or person, for example inseam between 32 and 34 inches or height between 170 and 190 cm. Typically found on a size chart for wearable products.')
    suggested_min_age: Number | list[Number] | None = Field(default=None, alias='suggestedMinAge', description='Minimum recommended age in years for the audience or user.')
