# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar, Literal

from pydantic import Field

from schema_org.base import PropertyMetadata
from schema_org.models.contact_point import ContactPoint

if TYPE_CHECKING:
    from schema_org.datatypes import Text
    from schema_org.models import AdministrativeArea, Country


class PostalAddress(ContactPoint):
    __doc__ = 'https://schema.org/PostalAddress\n\nThe mailing address.'
    SCHEMA_TYPE: ClassVar[str] = 'PostalAddress'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('PostalAddress', 'ContactPoint', 'StructuredValue', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='address_country', schema_name='addressCountry', schema_url='https://schema.org/addressCountry', ranges=('Country', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('DefinedRegion', 'GeoCoordinates', 'GeoShape', 'PostalAddress'), external_domains=(), comment='The country. Recommended to be in 2-letter [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1) format, for example "US". For backward compatibility, a 3-letter [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) country code such as "SGP" or a full country name such as "Singapore" can also be used.', label='addressCountry', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506',)),
        PropertyMetadata(name='address_locality', schema_name='addressLocality', schema_url='https://schema.org/addressLocality', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/addressLocality', 'https://spec.edmcouncil.org/fibo/ontology/FND/Places/Addresses/hasMunicipality'), subproperty_of=(), domains=('PostalAddress',), external_domains=(), comment='The locality in which the street address is, and which is in the region. For example, Mountain View.', label='addressLocality', contributors=(), sources=()),
        PropertyMetadata(name='address_region', schema_name='addressRegion', schema_url='https://schema.org/addressRegion', ranges=('AdministrativeArea', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/Places/Addresses/hasCountrySubdivision',), subproperty_of=(), domains=('DefinedRegion', 'PostalAddress'), external_domains=(), comment='The region in which the locality is, and which is in the country. For example, California or another appropriate first-level [Administrative division](https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country) such as the Province in Italy or Region in Germany.', label='addressRegion', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506',)),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='area_served', schema_name='areaServed', schema_url='https://schema.org/areaServed', ranges=('AdministrativeArea', 'GeoShape', 'Place', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('serviceArea',), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasServiceArea',), subproperty_of=(), domains=('ContactPoint', 'DeliveryChargeSpecification', 'Demand', 'FinancialIncentive', 'Offer', 'Organization', 'Service'), external_domains=(), comment='The geographic area where a service or offered item is provided.', label='areaServed', contributors=(), sources=()),
        PropertyMetadata(name='available_language', schema_name='availableLanguage', schema_url='https://schema.org/availableLanguage', ranges=('Language', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/availableLanguage',), subproperty_of=(), domains=('ContactPoint', 'Course', 'LodgingBusiness', 'ServiceChannel', 'TouristAttraction'), external_domains=(), comment='A language someone may use with or at the item, service or place. Please use one of the language codes from the [IETF BCP 47 standard](http://tools.ietf.org/html/bcp47). See also [[inLanguage]].', label='availableLanguage', contributors=(), sources=()),
        PropertyMetadata(name='contact_option', schema_name='contactOption', schema_url='https://schema.org/contactOption', ranges=('ContactPointOption',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ContactPoint',), external_domains=(), comment='An option available on this contact point (e.g. a toll-free number or support for hearing-impaired callers).', label='contactOption', contributors=(), sources=()),
        PropertyMetadata(name='contact_type', schema_name='contactType', schema_url='https://schema.org/contactType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/contactType',), subproperty_of=(), domains=('ContactPoint',), external_domains=(), comment='A person or organization can have different contact points, for different purposes. For example, a sales contact point, a PR contact point and so on. This property is used to specify the kind of contact point.', label='contactType', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='email', schema_name='email', schema_url='https://schema.org/email', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/email',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person'), external_domains=(), comment='Email address.', label='email', contributors=(), sources=()),
        PropertyMetadata(name='extended_address', schema_name='extendedAddress', schema_url='https://schema.org/extendedAddress', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('PostalAddress',), external_domains=(), comment='An address extension such as an apartment number, C/O or alternative name.', label='extendedAddress', contributors=(), sources=()),
        PropertyMetadata(name='fax_number', schema_name='faxNumber', schema_url='https://schema.org/faxNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/faxNumber',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The fax number.', label='faxNumber', contributors=(), sources=()),
        PropertyMetadata(name='hours_available', schema_name='hoursAvailable', schema_url='https://schema.org/hoursAvailable', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ContactPoint', 'LocationFeatureSpecification', 'Service'), external_domains=(), comment='The hours during which this service or contact is available.', label='hoursAvailable', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='post_office_box_number', schema_name='postOfficeBoxNumber', schema_url='https://schema.org/postOfficeBoxNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#postOfficeBox', 'https://ref.gs1.org/voc/postOfficeBoxNumber'), subproperty_of=(), domains=('PostalAddress',), external_domains=(), comment='The post office box number for PO box addresses.', label='postOfficeBoxNumber', contributors=(), sources=()),
        PropertyMetadata(name='postal_code', schema_name='postalCode', schema_url='https://schema.org/postalCode', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#postcodeCode', 'https://ref.gs1.org/voc/postalCode', 'https://spec.edmcouncil.org/fibo/ontology/FND/Places/Addresses/hasPostalCode'), subproperty_of=(), domains=('DefinedRegion', 'GeoCoordinates', 'GeoShape', 'PostalAddress'), external_domains=(), comment='The postal code. For example, 94043.', label='postalCode', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='product_supported', schema_name='productSupported', schema_url='https://schema.org/productSupported', ranges=('Product', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ContactPoint',), external_domains=(), comment='The product or service this support contact point is related to (such as product support for a particular product line). This can be a specific product or product line (e.g. "iPhone") or a general category of products or services (e.g. "smartphones").', label='productSupported', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='service_area', schema_name='serviceArea', schema_url='https://schema.org/serviceArea', ranges=('AdministrativeArea', 'GeoShape', 'Place'), external_ranges=(), inverse_of=None, superseded_by='areaServed', supersedes=('area',), equivalent_properties=(), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Service'), external_domains=(), comment='The geographic area where the service is provided.', label='serviceArea', contributors=(), sources=()),
        PropertyMetadata(name='street_address', schema_name='streetAddress', schema_url='https://schema.org/streetAddress', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/streetAddress',), subproperty_of=(), domains=('PostalAddress',), external_domains=(), comment='The street address. For example, 1600 Amphitheatre Pkwy.', label='streetAddress', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='telephone', schema_name='telephone', schema_url='https://schema.org/telephone', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/telephone',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The telephone number.', label='telephone', contributors=(), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['PostalAddress'] = Field(default='PostalAddress', alias='@type', frozen=True)
    address_country: Country | Text | list[Country | Text] | None = Field(default=None, alias='addressCountry', description='The country. Recommended to be in 2-letter [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1) format, for example "US". For backward compatibility, a 3-letter [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) country code such as "SGP" or a full country name such as "Singapore" can also be used.')
    address_locality: Text | list[Text] | None = Field(default=None, alias='addressLocality', description='The locality in which the street address is, and which is in the region. For example, Mountain View.')
    address_region: AdministrativeArea | Text | list[AdministrativeArea | Text] | None = Field(default=None, alias='addressRegion', description='The region in which the locality is, and which is in the country. For example, California or another appropriate first-level [Administrative division](https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country) such as the Province in Italy or Region in Germany.')
    extended_address: Text | list[Text] | None = Field(default=None, alias='extendedAddress', description='An address extension such as an apartment number, C/O or alternative name.')
    post_office_box_number: Text | list[Text] | None = Field(default=None, alias='postOfficeBoxNumber', description='The post office box number for PO box addresses.')
    postal_code: Text | list[Text] | None = Field(default=None, alias='postalCode', description='The postal code. For example, 94043.')
    street_address: Text | list[Text] | None = Field(default=None, alias='streetAddress', description='The street address. For example, 1600 Amphitheatre Pkwy.')
