# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import DrugCostCategory
from schema_org.enums import DrugPregnancyCategory
from schema_org.enums import DrugPrescriptionStatus
from schema_org.enums import EventStatusType
from schema_org.enums import InfectiousAgentClass
from schema_org.enums import MedicalAudienceType
from schema_org.enums import MedicalDevicePurpose
from schema_org.enums import MedicalEnumeration
from schema_org.enums import MedicalEvidenceLevel
from schema_org.enums import MedicalImagingTechnique
from schema_org.enums import MedicalObservationalStudyDesign
from schema_org.enums import MedicalProcedureType
from schema_org.enums import MedicalSpecialty
from schema_org.enums import MedicalStudyStatus
from schema_org.enums import MedicalTrialDesign
from schema_org.enums import MedicineSystem
from schema_org.enums import PhysicalExam
from schema_org.models.therapeutic_procedure import TherapeuticProcedure

class PsychologicalTreatment(TherapeuticProcedure):
    __doc__ = 'https://schema.org/PsychologicalTreatment\n\nA process of care relying upon counseling, dialogue and communication  aimed at improving a mental health condition without use of drugs.'
    SCHEMA_TYPE: ClassVar[str] = 'PsychologicalTreatment'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('PsychologicalTreatment', 'TherapeuticProcedure', 'MedicalProcedure', 'MedicalEntity', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='adverse_outcome', schema_name='adverseOutcome', schema_url='https://schema.org/adverseOutcome', ranges=('MedicalEntity',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalDevice', 'TherapeuticProcedure'), external_domains=(), comment='A possible complication and/or side effect of this therapy. If it is known that an adverse outcome is serious (resulting in death, disability, or permanent damage; requiring hospitalization; or otherwise life-threatening or requiring immediate medical attention), tag it as a seriousAdverseOutcome instead.', label='adverseOutcome', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='body_location', schema_name='bodyLocation', schema_url='https://schema.org/bodyLocation', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('AnatomicalStructure', 'MedicalProcedure'), external_domains=(), comment='Location in the body of the anatomical structure.', label='bodyLocation', contributors=(), sources=()),
        PropertyMetadata(name='code', schema_name='code', schema_url='https://schema.org/code', ranges=('MedicalCode',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalEntity',), external_domains=(), comment='A medical code for the entity, taken from a controlled vocabulary or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.', label='code', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='dose_schedule', schema_name='doseSchedule', schema_url='https://schema.org/doseSchedule', ranges=('DoseSchedule',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Drug', 'TherapeuticProcedure'), external_domains=(), comment='A dosing schedule for the drug for a given population, either observed, recommended, or maximum dose based on the type used.', label='doseSchedule', contributors=(), sources=()),
        PropertyMetadata(name='drug', schema_name='drug', schema_url='https://schema.org/drug', ranges=('Drug',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('DrugClass', 'MedicalCondition', 'Patient', 'TherapeuticProcedure'), external_domains=(), comment='Specifying a drug or medicine used in a medication procedure.', label='drug', contributors=(), sources=()),
        PropertyMetadata(name='followup', schema_name='followup', schema_url='https://schema.org/followup', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalProcedure',), external_domains=(), comment='Typical or recommended followup care after the procedure is performed.', label='followup', contributors=(), sources=()),
        PropertyMetadata(name='funding', schema_name='funding', schema_url='https://schema.org/funding', ranges=('Grant',), external_ranges=(), inverse_of='fundedItem', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity', 'CreativeWork', 'Event', 'MedicalEntity', 'Organization', 'Person', 'Product'), external_domains=(), comment='A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].', label='funding', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/383',)),
        PropertyMetadata(name='guideline', schema_name='guideline', schema_url='https://schema.org/guideline', ranges=('MedicalGuideline',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalEntity',), external_domains=(), comment='A medical guideline related to this entity.', label='guideline', contributors=(), sources=()),
        PropertyMetadata(name='how_performed', schema_name='howPerformed', schema_url='https://schema.org/howPerformed', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalProcedure',), external_domains=(), comment='How the procedure is performed.', label='howPerformed', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='legal_status', schema_name='legalStatus', schema_url='https://schema.org/legalStatus', ranges=('DrugLegalStatus', 'MedicalEnumeration', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('DietarySupplement', 'Drug', 'MedicalEntity'), external_domains=(), comment="The drug or supplement's legal status, including any controlled substance schedules that apply.", label='legalStatus', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='medicine_system', schema_name='medicineSystem', schema_url='https://schema.org/medicineSystem', ranges=('MedicineSystem',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalEntity',), external_domains=(), comment="The system of medicine that includes this MedicalEntity, for example 'evidence-based', 'homeopathic', 'chiropractic', etc.", label='medicineSystem', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='preparation', schema_name='preparation', schema_url='https://schema.org/preparation', ranges=('MedicalEntity', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalProcedure',), external_domains=(), comment='Typical preparation that a patient must undergo before having the procedure performed.', label='preparation', contributors=(), sources=()),
        PropertyMetadata(name='procedure_type', schema_name='procedureType', schema_url='https://schema.org/procedureType', ranges=('MedicalProcedureType',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalProcedure',), external_domains=(), comment='The type of procedure, for example Surgical, Noninvasive, or Percutaneous.', label='procedureType', contributors=(), sources=()),
        PropertyMetadata(name='recognizing_authority', schema_name='recognizingAuthority', schema_url='https://schema.org/recognizingAuthority', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalEntity',), external_domains=(), comment='If applicable, the organization that officially recognizes this entity as part of its endorsed system of medicine.', label='recognizingAuthority', contributors=(), sources=()),
        PropertyMetadata(name='relevant_specialty', schema_name='relevantSpecialty', schema_url='https://schema.org/relevantSpecialty', ranges=('MedicalSpecialty',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalEntity',), external_domains=(), comment='If applicable, a medical specialty in which this entity is relevant.', label='relevantSpecialty', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='status', schema_name='status', schema_url='https://schema.org/status', ranges=('EventStatusType', 'MedicalStudyStatus', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalCondition', 'MedicalProcedure', 'MedicalStudy'), external_domains=(), comment='The status of the study (enumerated).', label='status', contributors=(), sources=()),
        PropertyMetadata(name='study', schema_name='study', schema_url='https://schema.org/study', ranges=('MedicalStudy',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MedicalEntity',), external_domains=(), comment='A medical study or trial related to this entity.', label='study', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['PsychologicalTreatment'] = Field(default='PsychologicalTreatment', alias='@type', frozen=True)
