# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Distance
from schema_org.datatypes import Mass
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.structured_value import StructuredValue

class ShippingConditions(StructuredValue):
    __doc__ = 'https://schema.org/ShippingConditions\n\nShippingConditions represent a set of constraints and information about the conditions of shipping a product. Such conditions may apply to only a subset of the products being shipped, depending on aspects of the product like weight, size, price, destination, and others. All the specified conditions must be met for this ShippingConditions to apply.\n\nSupersedes `DeliveryTimeSettings`.'
    SCHEMA_TYPE: ClassVar[str] = 'ShippingConditions'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('ShippingConditions', 'StructuredValue', 'Intangible', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='depth', schema_name='depth', schema_url='https://schema.org/depth', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The depth of the item.', label='depth', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='does_not_ship', schema_name='doesNotShip', schema_url='https://schema.org/doesNotShip', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'ShippingConditions', 'ShippingRateSettings'), external_domains=(), comment='Indicates when shipping to a particular [[shippingDestination]] is not available.', label='doesNotShip', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506', 'https://github.com/schemaorg/schemaorg/issues/3617')),
        PropertyMetadata(name='height', schema_name='height', schema_url='https://schema.org/height', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MediaObject', 'OfferShippingDetails', 'Person', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The height of the item.', label='height', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='num_items', schema_name='numItems', schema_url='https://schema.org/numItems', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ShippingConditions',), external_domains=(), comment='Limits the number of items being shipped for which these conditions apply.', label='numItems', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='order_value', schema_name='orderValue', schema_url='https://schema.org/orderValue', ranges=('MonetaryAmount',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ShippingConditions',), external_domains=(), comment='Minimum and maximum order value for which these shipping conditions are valid.', label='orderValue', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='seasonal_override', schema_name='seasonalOverride', schema_url='https://schema.org/seasonalOverride', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ShippingConditions',), external_domains=(), comment='Limited period during which these shipping conditions apply.', label='seasonalOverride', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='shipping_destination', schema_name='shippingDestination', schema_url='https://schema.org/shippingDestination', ranges=('DefinedRegion',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('DeliveryTimeSettings', 'OfferShippingDetails', 'ShippingConditions', 'ShippingRateSettings'), external_domains=(), comment='indicates (possibly multiple) shipping destinations. These can be defined in several ways, e.g. postalCode ranges.', label='shippingDestination', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506', 'https://github.com/schemaorg/schemaorg/issues/3617')),
        PropertyMetadata(name='shipping_origin', schema_name='shippingOrigin', schema_url='https://schema.org/shippingOrigin', ranges=('DefinedRegion',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://unece.org/vocab#DespatchLocation',), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLocation',), domains=('OfferShippingDetails', 'ShippingConditions'), external_domains=(), comment='Indicates the origin of a shipment, i.e. where it should be coming from.', label='shippingOrigin', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3122', 'https://github.com/schemaorg/schemaorg/issues/3617')),
        PropertyMetadata(name='shipping_rate', schema_name='shippingRate', schema_url='https://schema.org/shippingRate', ranges=('MonetaryAmount', 'ShippingRateSettings'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'ShippingConditions', 'ShippingRateSettings'), external_domains=(), comment='The shipping rate is the cost of shipping to the specified destination. Typically, the maxValue and currency values (of the [[MonetaryAmount]]) are most appropriate.', label='shippingRate', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506', 'https://github.com/schemaorg/schemaorg/issues/3617')),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='transit_time', schema_name='transitTime', schema_url='https://schema.org/transitTime', ranges=('QuantitativeValue', 'ServicePeriod'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('ShippingConditions', 'ShippingDeliveryTime'), external_domains=(), comment='The typical delay the order has been sent for delivery and the goods reach the final customer.\n\n  In the context of [[ShippingDeliveryTime]], use the [[QuantitativeValue]]. Typical properties: minValue, maxValue, unitCode (d for DAY).\n\n  In the context of [[ShippingConditions]], use the [[ServicePeriod]]. It has a duration (as a [[QuantitativeValue]]) and also business days and a cut-off time.\n', label='transitTime', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2506', 'https://github.com/schemaorg/schemaorg/issues/3617')),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='weight', schema_name='weight', schema_url='https://schema.org/weight', ranges=('Mass', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'Person', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The weight of the product or person.', label='weight', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='width', schema_name='width', schema_url='https://schema.org/width', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=None, equivalent_properties=(), subproperty_of=(), domains=('MediaObject', 'OfferShippingDetails', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The width of the item.', label='width', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['ShippingConditions'] = Field(default='ShippingConditions', alias='@type', frozen=True)
    depth: Distance | QuantitativeValue | list[Distance | QuantitativeValue] | None = Field(default=None, alias='depth', description='The depth of the item.')
    does_not_ship: Boolean | list[Boolean] | None = Field(default=None, alias='doesNotShip', description='Indicates when shipping to a particular [[shippingDestination]] is not available.')
    height: Distance | QuantitativeValue | list[Distance | QuantitativeValue] | None = Field(default=None, alias='height', description='The height of the item.')
    num_items: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='numItems', description='Limits the number of items being shipped for which these conditions apply.')
    order_value: MonetaryAmount | list[MonetaryAmount] | None = Field(default=None, alias='orderValue', description='Minimum and maximum order value for which these shipping conditions are valid.')
    seasonal_override: OpeningHoursSpecification | list[OpeningHoursSpecification] | None = Field(default=None, alias='seasonalOverride', description='Limited period during which these shipping conditions apply.')
    shipping_destination: DefinedRegion | list[DefinedRegion] | None = Field(default=None, alias='shippingDestination', description='indicates (possibly multiple) shipping destinations. These can be defined in several ways, e.g. postalCode ranges.')
    shipping_origin: DefinedRegion | list[DefinedRegion] | None = Field(default=None, alias='shippingOrigin', description='Indicates the origin of a shipment, i.e. where it should be coming from.')
    shipping_rate: MonetaryAmount | ShippingRateSettings | list[MonetaryAmount | ShippingRateSettings] | None = Field(default=None, alias='shippingRate', description='The shipping rate is the cost of shipping to the specified destination. Typically, the maxValue and currency values (of the [[MonetaryAmount]]) are most appropriate.')
    transit_time: QuantitativeValue | ServicePeriod | list[QuantitativeValue | ServicePeriod] | None = Field(default=None, alias='transitTime', description='The typical delay the order has been sent for delivery and the goods reach the final customer.\n\n  In the context of [[ShippingDeliveryTime]], use the [[QuantitativeValue]]. Typical properties: minValue, maxValue, unitCode (d for DAY).\n\n  In the context of [[ShippingConditions]], use the [[ServicePeriod]]. It has a duration (as a [[QuantitativeValue]]) and also business days and a cut-off time.\n')
    weight: Mass | QuantitativeValue | list[Mass | QuantitativeValue] | None = Field(default=None, alias='weight', description='The weight of the product or person.')
    width: Distance | QuantitativeValue | list[Distance | QuantitativeValue] | None = Field(default=None, alias='width', description='The width of the item.')
