# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Date
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.enums import DENonprofitType
from schema_org.enums import ITNonprofitType
from schema_org.enums import NLNonprofitType
from schema_org.enums import NonprofitType
from schema_org.enums import UKNonprofitType
from schema_org.enums import USNonprofitType
from schema_org.models.local_business import LocalBusiness

class Store(LocalBusiness):
    __doc__ = 'https://schema.org/Store\n\nA retail good store.'
    SCHEMA_TYPE: ClassVar[str] = 'Store'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Store', 'LocalBusiness', 'Organization', 'Place', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='accepted_payment_method', schema_name='acceptedPaymentMethod', schema_url='https://schema.org/acceptedPaymentMethod', ranges=('LoanOrCredit', 'PaymentMethod', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'Offer', 'Organization'), external_domains=(), comment='The payment method(s) that are accepted in general by an organization, or for some specific demand or offer.', label='acceptedPaymentMethod', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3537',)),
        PropertyMetadata(name='actionable_feedback_policy', schema_name='actionableFeedbackPolicy', schema_url='https://schema.org/actionableFeedbackPolicy', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('publishingPrinciples',), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='For a [[NewsMediaOrganization]] or other news-related [[Organization]], a statement about public engagement activities (for news media, the newsroom’s), including involving the public - digitally or otherwise -- in coverage decisions, reporting and activities after publication.', label='actionableFeedbackPolicy', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='additional_property', schema_name='additionalProperty', schema_url='https://schema.org/additionalProperty', ranges=('PropertyValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'Offer', 'Place', 'Product', 'QualitativeValue', 'QuantitativeValue'), external_domains=(), comment='A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\\n\\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.\n', label='additionalProperty', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='address', schema_name='address', schema_url='https://schema.org/address', ranges=('PostalAddress', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/address',), subproperty_of=(), domains=('GeoCoordinates', 'GeoShape', 'Organization', 'Person', 'Place'), external_domains=(), comment='Physical address of the item.', label='address', contributors=(), sources=()),
        PropertyMetadata(name='agent_interaction_statistic', schema_name='agentInteractionStatistic', schema_url='https://schema.org/agentInteractionStatistic', ranges=('InteractionCounter',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment="The number of completed interactions for this entity, in a particular role (the 'agent'), in a particular action (indicated in the statistic), and in a particular context (i.e. interactionService).", label='agentInteractionStatistic', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2858',)),
        PropertyMetadata(name='aggregate_rating', schema_name='aggregateRating', schema_url='https://schema.org/aggregateRating', ranges=('AggregateRating',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='The overall rating, based on a collection of reviews or ratings, of the item.', label='aggregateRating', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='alumni', schema_name='alumni', schema_url='https://schema.org/alumni', ranges=('Person',), external_ranges=(), inverse_of='alumniOf', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('EducationalOrganization', 'Organization'), external_domains=(), comment='Alumni of an organization.', label='alumni', contributors=(), sources=()),
        PropertyMetadata(name='amenity_feature', schema_name='amenityFeature', schema_url='https://schema.org/amenityFeature', ranges=('LocationFeatureSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan', 'LodgingBusiness', 'Place'), external_domains=(), comment='An amenity feature (e.g. a characteristic or service) of the Accommodation. This generic property does not make a statement about whether the feature is included in an offer for the main accommodation or available at extra costs.', label='amenityFeature', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='area_served', schema_name='areaServed', schema_url='https://schema.org/areaServed', ranges=('AdministrativeArea', 'GeoShape', 'Place', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('serviceArea',), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/hasServiceArea',), subproperty_of=(), domains=('ContactPoint', 'DeliveryChargeSpecification', 'Demand', 'FinancialIncentive', 'Offer', 'Organization', 'Service'), external_domains=(), comment='The geographic area where a service or offered item is provided.', label='areaServed', contributors=(), sources=()),
        PropertyMetadata(name='award', schema_name='award', schema_url='https://schema.org/award', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('awards',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='An award won by or for this item.', label='award', contributors=(), sources=()),
        PropertyMetadata(name='awards', schema_name='awards', schema_url='https://schema.org/awards', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by='award', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product'), external_domains=(), comment='Awards won by or for this item.', label='awards', contributors=(), sources=()),
        PropertyMetadata(name='branch_code', schema_name='branchCode', schema_url='https://schema.org/branchCode', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A short textual code (also called "store code") that uniquely identifies a place of business. The code is typically assigned by the parentOrganization and used in structured URLs.\\n\\nFor example, in the URL http://www.starbucks.co.uk/store-locator/etc/detail/3047 the code "3047" is a branchCode for a particular branch.\n      ', label='branchCode', contributors=(), sources=()),
        PropertyMetadata(name='branch_of', schema_name='branchOf', schema_url='https://schema.org/branchOf', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by='parentOrganization', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('LocalBusiness',), external_domains=(), comment='The larger organization that this local business is a branch of, if any. Not to be confused with (anatomical) [[branch]].', label='branchOf', contributors=(), sources=()),
        PropertyMetadata(name='brand', schema_name='brand', schema_url='https://schema.org/brand', ranges=('Brand', 'Organization'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#brandName',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/hasDesignation',), domains=('Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.', label='brand', contributors=(), sources=()),
        PropertyMetadata(name='company_registration', schema_name='companyRegistration', schema_url='https://schema.org/companyRegistration', ranges=('Certification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='The official registration information of a business including the organization that issued it such as Company House or Chamber of Commerce in form of a Certification.', label='companyRegistration', contributors=(), sources=()),
        PropertyMetadata(name='contact_point', schema_name='contactPoint', schema_url='https://schema.org/contactPoint', ranges=('ContactPoint',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('contactPoints',), equivalent_properties=('https://ref.gs1.org/voc/contactPoint', 'https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/Organizations/hasContactPoint'), subproperty_of=(), domains=('HealthInsurancePlan', 'Organization', 'Person'), external_domains=(), comment='A contact point for a person or organization.', label='contactPoint', contributors=(), sources=()),
        PropertyMetadata(name='contact_points', schema_name='contactPoints', schema_url='https://schema.org/contactPoints', ranges=('ContactPoint',), external_ranges=(), inverse_of=None, superseded_by='contactPoint', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A contact point for a person or organization.', label='contactPoints', contributors=(), sources=()),
        PropertyMetadata(name='contained_in', schema_name='containedIn', schema_url='https://schema.org/containedIn', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by='containedInPlace', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The basic containment relation between a place and one that contains it.', label='containedIn', contributors=(), sources=()),
        PropertyMetadata(name='contained_in_place', schema_name='containedInPlace', schema_url='https://schema.org/containedInPlace', ranges=('Place',), external_ranges=(), inverse_of='containsPlace', superseded_by=None, supersedes=('containedIn',), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The basic containment relation between a place and one that contains it.', label='containedInPlace', contributors=(), sources=()),
        PropertyMetadata(name='contains_place', schema_name='containsPlace', schema_url='https://schema.org/containsPlace', ranges=('Place',), external_ranges=(), inverse_of='containedInPlace', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The basic containment relation between a place and another that it contains.', label='containsPlace', contributors=(), sources=()),
        PropertyMetadata(name='corrections_policy', schema_name='correctionsPolicy', schema_url='https://schema.org/correctionsPolicy', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('publishingPrinciples',), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='For an [[Organization]] (e.g. [[NewsMediaOrganization]]), a statement describing (in news media, the newsroom’s) disclosure and correction policy for errors.', label='correctionsPolicy', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='currencies_accepted', schema_name='currenciesAccepted', schema_url='https://schema.org/currenciesAccepted', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('LocalBusiness',), external_domains=(), comment='The currency accepted.\\n\\nUse standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR".', label='currenciesAccepted', contributors=(), sources=()),
        PropertyMetadata(name='department', schema_name='department', schema_url='https://schema.org/department', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='A relationship between an organization and a department of that organization, also described as an organization (allowing different urls, logos, opening hours). For example: a store with a pharmacy, or a bakery with a cafe.', label='department', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='dissolution_date', schema_name='dissolutionDate', schema_url='https://schema.org/dissolutionDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/organizationTerminationDate',), subproperty_of=(), domains=('Organization',), external_domains=(), comment='The date that this organization was dissolved.', label='dissolutionDate', contributors=(), sources=()),
        PropertyMetadata(name='diversity_policy', schema_name='diversityPolicy', schema_url='https://schema.org/diversityPolicy', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='Statement on diversity policy by an [[Organization]] e.g. a [[NewsMediaOrganization]]. For a [[NewsMediaOrganization]], a statement describing the newsroom’s diversity policy on both staffing and sources, typically providing staffing data.', label='diversityPolicy', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='diversity_staffing_report', schema_name='diversityStaffingReport', schema_url='https://schema.org/diversityStaffingReport', ranges=('Article', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('publishingPrinciples',), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='For an [[Organization]] (often but not necessarily a [[NewsMediaOrganization]]), a report on staffing diversity issues. In a news context this might be for example ASNE or RTDNA (US) reports, or self-reported.', label='diversityStaffingReport', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='duns', schema_name='duns', schema_url='https://schema.org/duns', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#dUNSId',), subproperty_of=('identifier',), domains=('Organization', 'Person'), external_domains=(), comment='The Dun & Bradstreet DUNS number for identifying an organization or business person.', label='duns', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='email', schema_name='email', schema_url='https://schema.org/email', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/email',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person'), external_domains=(), comment='Email address.', label='email', contributors=(), sources=()),
        PropertyMetadata(name='employee', schema_name='employee', schema_url='https://schema.org/employee', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('employees',), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='Someone working for this organization.', label='employee', contributors=(), sources=()),
        PropertyMetadata(name='employees', schema_name='employees', schema_url='https://schema.org/employees', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by='employee', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='People working for this organization.', label='employees', contributors=(), sources=()),
        PropertyMetadata(name='ethics_policy', schema_name='ethicsPolicy', schema_url='https://schema.org/ethicsPolicy', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='Statement about ethics policy, e.g. of a [[NewsMediaOrganization]] regarding journalistic and publishing practices, or of a [[Restaurant]], a page describing food source policies. In the case of a [[NewsMediaOrganization]], an ethicsPolicy is typically a statement describing the personal, organizational, and corporate standards of behavior expected by the organization.', label='ethicsPolicy', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='event', schema_name='event', schema_url='https://schema.org/event', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('events',), equivalent_properties=(), subproperty_of=(), domains=('InformAction', 'InviteAction', 'JoinAction', 'LeaveAction', 'Organization', 'Place', 'PlayAction'), external_domains=(), comment='Upcoming or past event associated with this place, organization, or action.', label='event', contributors=(), sources=()),
        PropertyMetadata(name='events', schema_name='events', schema_url='https://schema.org/events', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by='event', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Place'), external_domains=(), comment='Upcoming or past events associated with this place or organization.', label='events', contributors=(), sources=()),
        PropertyMetadata(name='fax_number', schema_name='faxNumber', schema_url='https://schema.org/faxNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/faxNumber',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The fax number.', label='faxNumber', contributors=(), sources=()),
        PropertyMetadata(name='floor_level', schema_name='floorLevel', schema_url='https://schema.org/floorLevel', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'LocalBusiness', 'Residence'), external_domains=(), comment='The floor level for an [[Accommodation]] in a multi-storey building. Since counting\n  systems [vary internationally](https://en.wikipedia.org/wiki/Storey#Consecutive_number_floor_designations), the local system should be used where possible.', label='floorLevel', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373', 'https://github.com/schemaorg/schemaorg/issues/4469')),
        PropertyMetadata(name='founder', schema_name='founder', schema_url='https://schema.org/founder', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('founders',), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='A person or organization who founded this organization.', label='founder', contributors=(), sources=()),
        PropertyMetadata(name='founders', schema_name='founders', schema_url='https://schema.org/founders', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by='founder', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='A person who founded this organization.', label='founders', contributors=(), sources=()),
        PropertyMetadata(name='founding_date', schema_name='foundingDate', schema_url='https://schema.org/foundingDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/organizationFormationDate',), subproperty_of=(), domains=('Organization',), external_domains=(), comment='The date that this organization was founded.', label='foundingDate', contributors=(), sources=()),
        PropertyMetadata(name='founding_location', schema_name='foundingLocation', schema_url='https://schema.org/foundingLocation', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='The place where the Organization was founded.', label='foundingLocation', contributors=(), sources=()),
        PropertyMetadata(name='funder', schema_name='funder', schema_url='https://schema.org/funder', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('sponsor',), domains=('CreativeWork', 'Event', 'Grant', 'MonetaryGrant', 'Organization', 'Person'), external_domains=(), comment='A person or organization that supports (sponsors) something through some kind of financial contribution.', label='funder', contributors=(), sources=()),
        PropertyMetadata(name='funding', schema_name='funding', schema_url='https://schema.org/funding', ranges=('Grant',), external_ranges=(), inverse_of='fundedItem', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity', 'CreativeWork', 'Event', 'MedicalEntity', 'Organization', 'Person', 'Product'), external_domains=(), comment='A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].', label='funding', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/383',)),
        PropertyMetadata(name='geo', schema_name='geo', schema_url='https://schema.org/geo', ranges=('GeoCoordinates', 'GeoShape'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The geo coordinates of the place.', label='geo', contributors=(), sources=()),
        PropertyMetadata(name='geo_contains', schema_name='geoContains', schema_url='https://schema.org/geoContains', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a containing geometry to a contained geometry. "a contains b iff no points of b lie in the exterior of a, and at least one point of the interior of b lies in the interior of a". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoContains', contributors=(), sources=()),
        PropertyMetadata(name='geo_covered_by', schema_name='geoCoveredBy', schema_url='https://schema.org/geoCoveredBy', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to another that covers it. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoCoveredBy', contributors=(), sources=()),
        PropertyMetadata(name='geo_covers', schema_name='geoCovers', schema_url='https://schema.org/geoCovers', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a covering geometry to a covered geometry. "Every point of b is a point of (the interior or boundary of) a". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoCovers', contributors=(), sources=()),
        PropertyMetadata(name='geo_crosses', schema_name='geoCrosses', schema_url='https://schema.org/geoCrosses', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to another that crosses it: "a crosses b: they have some but not all interior points in common, and the dimension of the intersection is less than that of at least one of them". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoCrosses', contributors=(), sources=()),
        PropertyMetadata(name='geo_disjoint', schema_name='geoDisjoint', schema_url='https://schema.org/geoDisjoint', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) are topologically disjoint: "they have no point in common. They form a set of disconnected geometries." (A symmetric relationship, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).)', label='geoDisjoint', contributors=(), sources=()),
        PropertyMetadata(name='geo_equals', schema_name='geoEquals', schema_url='https://schema.org/geoEquals', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) are topologically equal, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM). "Two geometries are topologically equal if their interiors intersect and no part of the interior or boundary of one geometry intersects the exterior of the other" (a symmetric relationship).', label='geoEquals', contributors=(), sources=()),
        PropertyMetadata(name='geo_intersects', schema_name='geoIntersects', schema_url='https://schema.org/geoIntersects', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) have at least one point in common. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoIntersects', contributors=(), sources=()),
        PropertyMetadata(name='geo_overlaps', schema_name='geoOverlaps', schema_url='https://schema.org/geoOverlaps', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to another that geospatially overlaps it, i.e. they have some but not all points in common. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoOverlaps', contributors=(), sources=()),
        PropertyMetadata(name='geo_touches', schema_name='geoTouches', schema_url='https://schema.org/geoTouches', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) touch: "they have at least one boundary point in common, but no interior points." (A symmetric relationship, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).)', label='geoTouches', contributors=(), sources=()),
        PropertyMetadata(name='geo_within', schema_name='geoWithin', schema_url='https://schema.org/geoWithin', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to one that contains it, i.e. it is inside (i.e. within) its interior. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoWithin', contributors=(), sources=()),
        PropertyMetadata(name='global_location_number', schema_name='globalLocationNumber', schema_url='https://schema.org/globalLocationNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#gLNId', 'https://ref.gs1.org/voc/globalLocationNumber'), subproperty_of=('identifier',), domains=('Organization', 'Person', 'Place'), external_domains=(), comment='The [Global Location Number](http://www.gs1.org/gln) (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', label='globalLocationNumber', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='has_certification', schema_name='hasCertification', schema_url='https://schema.org/hasCertification', ranges=('Certification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ApplicableCertificate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/isReferencedIn', 'https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy'), domains=('Organization', 'Person', 'Place', 'Product', 'Service'), external_domains=(), comment='Certification information about a product, organization, service, place, or person.', label='hasCertification', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3230',)),
        PropertyMetadata(name='has_credential', schema_name='hasCredential', schema_url='https://schema.org/hasCredential', ranges=('Credential',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A credential awarded to the Person or Organization.', label='hasCredential', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='has_drive_through_service', schema_name='hasDriveThroughService', schema_url='https://schema.org/hasDriveThroughService', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='Indicates whether some facility (e.g. [[FoodEstablishment]], [[CovidTestingFacility]]) offers a service that can be used by driving through in a car. In the case of [[CovidTestingFacility]] such facilities could potentially help with social distancing from other potentially-infected users.', label='hasDriveThroughService', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2490',)),
        PropertyMetadata(name='has_gs1_digital_link', schema_name='hasGS1DigitalLink', schema_url='https://schema.org/hasGS1DigitalLink', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Offer', 'Organization', 'Place', 'Product'), external_domains=(), comment='The <a href="https://www.gs1.org/standards/gs1-digital-link">GS1 digital link</a> associated with the object. This URL should conform to the particular requirements of digital links. The link should only contain the Application Identifiers (AIs) that are relevant for the entity being annotated, for instance a [[Product]] or an [[Organization]], and for the correct granularity. In particular, for products:<ul><li>A Digital Link that contains a serial number (AI <code>21</code>) should only be present on instances of [[IndividualProduct]]</li><li>A Digital Link that contains a lot number (AI <code>10</code>) should be annotated as [[SomeProducts]] if only products from that lot are sold, or [[IndividualProduct]] if there is only a specific product.</li><li>A Digital Link that contains a global model number (AI <code>8013</code>) should be attached to a [[Product]] or a [[ProductModel]].</li></ul> Other item types should be adapted similarly.', label='hasGS1DigitalLink', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3475',)),
        PropertyMetadata(name='has_map', schema_name='hasMap', schema_url='https://schema.org/hasMap', ranges=('Map', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('map', 'maps'), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A URL to a map of the place.', label='hasMap', contributors=(), sources=()),
        PropertyMetadata(name='has_member_program', schema_name='hasMemberProgram', schema_url='https://schema.org/hasMemberProgram', ranges=('MemberProgram',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='MemberProgram offered by an Organization, for example an eCommerce merchant or an airline.', label='hasMemberProgram', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3563',)),
        PropertyMetadata(name='has_merchant_return_policy', schema_name='hasMerchantReturnPolicy', schema_url='https://schema.org/hasMerchantReturnPolicy', ranges=('MerchantReturnPolicy',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('hasProductReturnPolicy',), equivalent_properties=(), subproperty_of=(), domains=('Offer', 'Organization', 'Product'), external_domains=(), comment='Specifies a MerchantReturnPolicy that may be applicable.', label='hasMerchantReturnPolicy', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='has_offer_catalog', schema_name='hasOfferCatalog', schema_url='https://schema.org/hasOfferCatalog', ranges=('OfferCatalog',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person', 'Service'), external_domains=(), comment='Indicates an OfferCatalog listing for this Organization, Person, or Service.', label='hasOfferCatalog', contributors=(), sources=()),
        PropertyMetadata(name='has_pos', schema_name='hasPOS', schema_url='https://schema.org/hasPOS', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Points-of-Sales operated by the organization or person.', label='hasPOS', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='has_product_return_policy', schema_name='hasProductReturnPolicy', schema_url='https://schema.org/hasProductReturnPolicy', ranges=('ProductReturnPolicy',), external_ranges=(), inverse_of=None, superseded_by='hasMerchantReturnPolicy', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Product'), external_domains=(), comment='Indicates a ProductReturnPolicy that may be applicable.', label='hasProductReturnPolicy', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='has_shipping_service', schema_name='hasShippingService', schema_url='https://schema.org/hasShippingService', ranges=('ShippingService',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'Organization'), external_domains=(), comment='Specification of a shipping service offered by the organization.', label='hasShippingService', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='interaction_statistic', schema_name='interactionStatistic', schema_url='https://schema.org/interactionStatistic', ranges=('InteractionCounter',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('interactionCount',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person'), external_domains=(), comment='The number of interactions for the CreativeWork using the WebSite or SoftwareApplication. The most specific child type of InteractionCounter should be used.', label='interactionStatistic', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2421',)),
        PropertyMetadata(name='is_accessible_for_free', schema_name='isAccessibleForFree', schema_url='https://schema.org/isAccessibleForFree', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('free',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Place'), external_domains=(), comment='A flag to signal that the item, event, or place is accessible for free.', label='isAccessibleForFree', contributors=(), sources=()),
        PropertyMetadata(name='isic_v4', schema_name='isicV4', schema_url='https://schema.org/isicV4', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person', 'Place'), external_domains=(), comment='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', label='isicV4', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='iso6523_code', schema_name='iso6523Code', schema_url='https://schema.org/iso6523Code', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='An organization identifier as defined in [ISO 6523(-1)](https://en.wikipedia.org/wiki/ISO/IEC_6523). The identifier should be in the `XXXX:YYYYYY:ZZZ` or `XXXX:YYYYYY`format. Where `XXXX` is a 4 digit _ICD_ (International Code Designator), `YYYYYY` is an _OID_ (Organization Identifier) with all formatting characters (dots, dashes, spaces) removed with a maximal length of 35 characters, and `ZZZ` is an optional OPI (Organization Part Identifier) with a maximum length of 35 characters. The various components (ICD, OID, OPI) are joined with a colon character (ASCII `0x3a`). Note that many existing organization identifiers defined as attributes like [leiCode](https://schema.org/leiCode) (`0199`), [duns](https://schema.org/duns) (`0060`) or [GLN](https://schema.org/globalLocationNumber) (`0088`) can be expressed using ISO-6523. If possible, ISO-6523 codes should be preferred to populating [vatID](https://schema.org/vatID) or [taxID](https://schema.org/taxID), as ISO identifiers are less ambiguous.', label='iso6523Code', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2915',)),
        PropertyMetadata(name='keywords', schema_name='keywords', schema_url='https://schema.org/keywords', ranges=('DefinedTerm', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Organization', 'Place', 'Product'), external_domains=(), comment='Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.', label='keywords', contributors=(), sources=()),
        PropertyMetadata(name='knows_about', schema_name='knowsAbout', schema_url='https://schema.org/knowsAbout', ranges=('Text', 'Thing', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Of a [[Person]], and less typically of an [[Organization]], to indicate a topic that is known about - suggesting possible expertise but not implying it. We do not distinguish skill levels here, or relate this to educational content, events, objectives or [[JobPosting]] descriptions.', label='knowsAbout', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1688',)),
        PropertyMetadata(name='knows_language', schema_name='knowsLanguage', schema_url='https://schema.org/knowsLanguage', ranges=('Language', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Of a [[Person]], and less typically of an [[Organization]], to indicate a known language. We do not distinguish skill levels or reading/writing/speaking/signing here. Use language codes from the [IETF BCP 47 standard](http://tools.ietf.org/html/bcp47).', label='knowsLanguage', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1688',)),
        PropertyMetadata(name='latitude', schema_name='latitude', schema_url='https://schema.org/latitude', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLatitude',), domains=('GeoCoordinates', 'Place'), external_domains=(), comment='The latitude of a location. For example ```37.42242``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).', label='latitude', contributors=(), sources=()),
        PropertyMetadata(name='legal_address', schema_name='legalAddress', schema_url='https://schema.org/legalAddress', ranges=('PostalAddress',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/Places/Addresses/hasRegisteredAddress',), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasAddress',), domains=('Organization',), external_domains=(), comment='The legal address of an organization which acts as the officially registered address used for legal and tax purposes. The legal address can be different from the place of operations of a business and other addresses can be part of an organization.', label='legalAddress', contributors=(), sources=()),
        PropertyMetadata(name='legal_name', schema_name='legalName', schema_url='https://schema.org/legalName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/organizationLegalName', 'https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/hasLegalName'), subproperty_of=('https://www.omg.org/spec/Commons/Text/hasName',), domains=('Organization',), external_domains=(), comment='The official name of the organization, e.g. the registered company name.', label='legalName', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='legal_representative', schema_name='legalRepresentative', schema_url='https://schema.org/legalRepresentative', ranges=('Person',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='One or multiple persons who represent this organization legally such as CEO or sole administrator.', label='legalRepresentative', contributors=(), sources=()),
        PropertyMetadata(name='lei_code', schema_name='leiCode', schema_url='https://schema.org/leiCode', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LegalPersons/hasLegalEntityIdentifier', 'https://www.gleif.org/ontology/L1/hasLEI'), subproperty_of=('identifier',), domains=('Organization',), external_domains=(), comment='An organization identifier that uniquely identifies a legal entity as defined in ISO 17442.', label='leiCode', contributors=('https://schema.org/docs/collab/FIBO', 'https://schema.org/docs/collab/GLEIF'), sources=()),
        PropertyMetadata(name='location', schema_name='location', schema_url='https://schema.org/location', ranges=('Place', 'PostalAddress', 'Text', 'VirtualLocation'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://www.omg.org/spec/Commons/Locations/isLocatedIn',), subproperty_of=(), domains=('Action', 'Event', 'InteractionCounter', 'Organization'), external_domains=(), comment='The location of, for example, where an event is happening, where an organization is located, or where an action takes place.', label='location', contributors=(), sources=()),
        PropertyMetadata(name='logo', schema_name='logo', schema_url='https://schema.org/logo', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#logoReferencedDocument',), subproperty_of=('image',), domains=('Brand', 'Certification', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='An associated logo.', label='logo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='longitude', schema_name='longitude', schema_url='https://schema.org/longitude', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLongitude',), domains=('GeoCoordinates', 'Place'), external_domains=(), comment='The longitude of a location. For example ```-122.08585``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).', label='longitude', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='makes_offer', schema_name='makesOffer', schema_url='https://schema.org/makesOffer', ranges=('Offer',), external_ranges=(), inverse_of='offeredBy', superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/offers',), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A pointer to products or services offered by the organization or person.', label='makesOffer', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='map', schema_name='map', schema_url='https://schema.org/map', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by='hasMap', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A URL to a map of the place.', label='map', contributors=(), sources=()),
        PropertyMetadata(name='maps', schema_name='maps', schema_url='https://schema.org/maps', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by='hasMap', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A URL to a map of the place.', label='maps', contributors=(), sources=()),
        PropertyMetadata(name='maximum_attendee_capacity', schema_name='maximumAttendeeCapacity', schema_url='https://schema.org/maximumAttendeeCapacity', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Quantities/hasUpperBound',), domains=('Event', 'Place'), external_domains=(), comment='The total number of individuals that may attend an event or venue.', label='maximumAttendeeCapacity', contributors=(), sources=()),
        PropertyMetadata(name='member', schema_name='member', schema_url='https://schema.org/member', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='memberOf', superseded_by=None, supersedes=('members', 'musicGroupMember'), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/Organizations/hasMember',), subproperty_of=(), domains=('Organization', 'ProgramMembership'), external_domains=(), comment='A member of an Organization or a ProgramMembership. Organizations can be members of organizations; ProgramMembership is typically for individuals.', label='member', contributors=(), sources=()),
        PropertyMetadata(name='member_of', schema_name='memberOf', schema_url='https://schema.org/memberOf', ranges=('MemberProgramTier', 'Organization', 'ProgramMembership'), external_ranges=(), inverse_of='member', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='An Organization (or ProgramMembership) to which this Person or Organization belongs.', label='memberOf', contributors=(), sources=()),
        PropertyMetadata(name='members', schema_name='members', schema_url='https://schema.org/members', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by='member', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'ProgramMembership'), external_domains=(), comment='A member of this organization.', label='members', contributors=(), sources=()),
        PropertyMetadata(name='naics', schema_name='naics', schema_url='https://schema.org/naics', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy',), domains=('Organization', 'Person'), external_domains=(), comment='The North American Industry Classification System (NAICS) code for a particular organization or business person.', label='naics', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='nonprofit_status', schema_name='nonprofitStatus', schema_url='https://schema.org/nonprofitStatus', ranges=('NonprofitType',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization',), external_domains=(), comment='nonprofitStatus indicates the legal status of a non-profit organization in its primary place of business.', label='nonprofitStatus', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2543',)),
        PropertyMetadata(name='number_of_employees', schema_name='numberOfEmployees', schema_url='https://schema.org/numberOfEmployees', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BusinessAudience', 'Organization'), external_domains=(), comment='The number of employees in an organization, e.g. business.', label='numberOfEmployees', contributors=(), sources=()),
        PropertyMetadata(name='opening_hours', schema_name='openingHours', schema_url='https://schema.org/openingHours', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CivicStructure', 'LocalBusiness'), external_domains=(), comment='The general opening hours for a business. Opening hours can be specified as a weekly time range, starting with days, then times per day. Multiple days can be listed with commas \',\' separating each day. Day or time ranges are specified using a hyphen \'-\'.\\n\\n* Days are specified using the following two-letter combinations: ```Mo```, ```Tu```, ```We```, ```Th```, ```Fr```, ```Sa```, ```Su```.\\n* Times are specified using 24:00 format. For example, 3pm is specified as ```15:00```, 10am as ```10:00```. \\n* Here is an example: <code>&lt;time itemprop="openingHours" datetime=&quot;Tu,Th 16:00-20:00&quot;&gt;Tuesdays and Thursdays 4-8pm&lt;/time&gt;</code>.\\n* If a business is open 7 days a week, then it can be specified as <code>&lt;time itemprop=&quot;openingHours&quot; datetime=&quot;Mo-Su&quot;&gt;Monday through Sunday, all day&lt;/time&gt;</code>.', label='openingHours', contributors=(), sources=()),
        PropertyMetadata(name='opening_hours_specification', schema_name='openingHoursSpecification', schema_url='https://schema.org/openingHoursSpecification', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The opening hours of a certain place.', label='openingHoursSpecification', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='ownership_funding_info', schema_name='ownershipFundingInfo', schema_url='https://schema.org/ownershipFundingInfo', ranges=('AboutPage', 'CreativeWork', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('publishingPrinciples',), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='For an [[Organization]] (often but not necessarily a [[NewsMediaOrganization]]), a description of organizational ownership structure; funding and grants. In a news/media setting, this is with particular reference to editorial independence.   Note that the [[funder]] is also available and can be used to make basic funder information machine-readable.', label='ownershipFundingInfo', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='owns', schema_name='owns', schema_url='https://schema.org/owns', ranges=('Thing',), external_ranges=(), inverse_of='owner', superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/owns',), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='Things owned by the organization or person.', label='owns', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='parent_organization', schema_name='parentOrganization', schema_url='https://schema.org/parentOrganization', ranges=('Organization',), external_ranges=(), inverse_of='subOrganization', superseded_by=None, supersedes=('branchOf',), equivalent_properties=('https://ref.gs1.org/voc/parentOrganization',), subproperty_of=(), domains=('Organization',), external_domains=(), comment='The larger organization that this organization is a [[subOrganization]] of, if any.', label='parentOrganization', contributors=(), sources=()),
        PropertyMetadata(name='payment_accepted', schema_name='paymentAccepted', schema_url='https://schema.org/paymentAccepted', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('LocalBusiness',), external_domains=(), comment='Cash, Credit Card, Cryptocurrency, Local Exchange Tradings System, etc.', label='paymentAccepted', contributors=(), sources=()),
        PropertyMetadata(name='photo', schema_name='photo', schema_url='https://schema.org/photo', ranges=('ImageObject', 'Photograph'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('photos',), equivalent_properties=(), subproperty_of=('image',), domains=('Place',), external_domains=(), comment='A photograph of this place.', label='photo', contributors=(), sources=()),
        PropertyMetadata(name='photos', schema_name='photos', schema_url='https://schema.org/photos', ranges=('ImageObject', 'Photograph'), external_ranges=(), inverse_of=None, superseded_by='photo', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='Photographs of this place.', label='photos', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='price_range', schema_name='priceRange', schema_url='https://schema.org/priceRange', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('LocalBusiness',), external_domains=(), comment='The price range of the business, for example ```$$$```.', label='priceRange', contributors=(), sources=()),
        PropertyMetadata(name='public_access', schema_name='publicAccess', schema_url='https://schema.org/publicAccess', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A flag to signal that the [[Place]] is open to public visitors.  If this property is omitted there is no assumed default boolean value.', label='publicAccess', contributors=(), sources=()),
        PropertyMetadata(name='publishing_principles', schema_name='publishingPrinciples', schema_url='https://schema.org/publishingPrinciples', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person'), external_domains=(), comment='The publishingPrinciples property indicates (typically via [[URL]]) a document describing the editorial principles of an [[Organization]] (or individual, e.g. a [[Person]] writing a blog) that relate to their activities as a publisher, e.g. ethics or diversity policies. When applied to a [[CreativeWork]] (e.g. [[NewsArticle]]) the principles are those of the party primarily responsible for the creation of the [[CreativeWork]].\n\nWhile such policies are most typically expressed in natural language, sometimes related information (e.g. indicating a [[funder]]) can be expressed using schema.org terminology.\n', label='publishingPrinciples', contributors=(), sources=()),
        PropertyMetadata(name='review', schema_name='review', schema_url='https://schema.org/review', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('reviews',), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A review of the item.', label='review', contributors=(), sources=()),
        PropertyMetadata(name='reviews', schema_name='reviews', schema_url='https://schema.org/reviews', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by='review', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Offer', 'Organization', 'Place', 'Product'), external_domains=(), comment='Review of the item.', label='reviews', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='seeks', schema_name='seeks', schema_url='https://schema.org/seeks', ranges=('Demand',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='A pointer to products or services sought by the organization or person (demand).', label='seeks', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='service_area', schema_name='serviceArea', schema_url='https://schema.org/serviceArea', ranges=('AdministrativeArea', 'GeoShape', 'Place'), external_ranges=(), inverse_of=None, superseded_by='areaServed', supersedes=('area',), equivalent_properties=(), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Service'), external_domains=(), comment='The geographic area where the service is provided.', label='serviceArea', contributors=(), sources=()),
        PropertyMetadata(name='skills', schema_name='skills', schema_url='https://schema.org/skills', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('JobPosting', 'Occupation', 'Organization', 'Person'), external_domains=(), comment='A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.', label='skills', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1698', 'https://github.com/schemaorg/schemaorg/issues/2322')),
        PropertyMetadata(name='slogan', schema_name='slogan', schema_url='https://schema.org/slogan', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#PromotionalMessage',), subproperty_of=(), domains=('Brand', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A slogan or motto associated with the item.', label='slogan', contributors=(), sources=()),
        PropertyMetadata(name='smoking_allowed', schema_name='smokingAllowed', schema_url='https://schema.org/smokingAllowed', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='Indicates whether it is allowed to smoke in the place, e.g. in the restaurant, hotel or hotel room.', label='smokingAllowed', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='special_opening_hours_specification', schema_name='specialOpeningHoursSpecification', schema_url='https://schema.org/specialOpeningHoursSpecification', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The special opening hours of a certain place.\\n\\nUse this to explicitly override general opening hours brought in scope by [[openingHoursSpecification]] or [[openingHours]].\n      ', label='specialOpeningHoursSpecification', contributors=(), sources=()),
        PropertyMetadata(name='sponsor', schema_name='sponsor', schema_url='https://schema.org/sponsor', ranges=('Organization', 'Person'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Grant', 'MedicalStudy', 'Organization', 'Person'), external_domains=(), comment='A person or organization that supports a thing through a pledge, promise, or financial contribution. E.g. a sponsor of a Medical Study or a corporate sponsor of an event.', label='sponsor', contributors=(), sources=()),
        PropertyMetadata(name='sub_organization', schema_name='subOrganization', schema_url='https://schema.org/subOrganization', ranges=('Organization',), external_ranges=(), inverse_of='parentOrganization', superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/subOrganization', 'https://spec.edmcouncil.org/fibo/ontology/BE/OwnershipAndControl/CorporateControl/hasSubsidiary'), subproperty_of=(), domains=('Organization',), external_domains=(), comment="A relationship between two organizations where the first includes the second, e.g., as a subsidiary. See also: the more specific 'department' property.", label='subOrganization', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='tax_id', schema_name='taxID', schema_url='https://schema.org/taxID', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Parties/hasTaxIdentifier',), subproperty_of=('identifier',), domains=('Organization', 'Person'), external_domains=(), comment='The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.', label='taxID', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='telephone', schema_name='telephone', schema_url='https://schema.org/telephone', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/telephone',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The telephone number.', label='telephone', contributors=(), sources=()),
        PropertyMetadata(name='tour_booking_page', schema_name='tourBookingPage', schema_url='https://schema.org/tourBookingPage', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'ApartmentComplex', 'Place'), external_domains=(), comment='A page providing information on how to book a tour of some [[Place]], such as an [[Accommodation]] or [[ApartmentComplex]] in a real estate setting, as well as other kinds of tours as appropriate.', label='tourBookingPage', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='unnamed_sources_policy', schema_name='unnamedSourcesPolicy', schema_url='https://schema.org/unnamedSourcesPolicy', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('publishingPrinciples',), domains=('NewsMediaOrganization', 'Organization'), external_domains=(), comment='For an [[Organization]] (typically a [[NewsMediaOrganization]]), a statement about policy on use of unnamed sources and the decision process required.', label='unnamedSourcesPolicy', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/1525',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='vat_id', schema_name='vatID', schema_url='https://schema.org/vatID', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person'), external_domains=(), comment='The value-added Tax ID of the organization or person with national prefix (for example IT123456789). Can also be described as [[iso6523Code]] with proper prefix.', label='vatID', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Store'] = Field(default='Store', alias='@type', frozen=True)
