# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar, Literal

from pydantic import Field

from schema_org.base import PropertyMetadata
from schema_org.models.product import Product

if TYPE_CHECKING:
    from schema_org.datatypes import URL, Date, Number, Text
    from schema_org.enums import (
        BedType,
        CarUsageType,
        DriveWheelConfigurationValue,
        QualitativeValue,
        SizeSpecification,
        SteeringPositionValue,
    )
    from schema_org.models import EngineSpecification, QuantitativeValue


class Vehicle(Product):
    __doc__ = 'https://schema.org/Vehicle\n\nA vehicle is a device that is designed or used to transport people or cargo over land, water, air, or through space.'
    SCHEMA_TYPE: ClassVar[str] = 'Vehicle'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Vehicle', 'Product', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='acceleration_time', schema_name='accelerationTime', schema_url='https://schema.org/accelerationTime', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The time needed to accelerate the vehicle from a given start velocity to a given target velocity.\\n\\nTypical unit code(s): SEC for seconds\\n\\n* Note: There are unfortunately no standard unit codes for seconds/0..100 km/h or seconds/0..60 mph. Simply use "SEC" for seconds and indicate the velocities in the [[name]] of the [[QuantitativeValue]], or use [[valueReference]] with a [[QuantitativeValue]] of 0..60 mph or 0..100 km/h to specify the reference speeds.', label='accelerationTime', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='additional_property', schema_name='additionalProperty', schema_url='https://schema.org/additionalProperty', ranges=('PropertyValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'Offer', 'Place', 'Product', 'QualitativeValue', 'QuantitativeValue'), external_domains=(), comment='A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\\n\\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.\n', label='additionalProperty', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='aggregate_rating', schema_name='aggregateRating', schema_url='https://schema.org/aggregateRating', ranges=('AggregateRating',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='The overall rating, based on a collection of reviews or ratings, of the item.', label='aggregateRating', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='asin', schema_name='asin', schema_url='https://schema.org/asin', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment="An Amazon Standard Identification Number (ASIN) is a 10-character alphanumeric unique identifier assigned by Amazon.com and its partners for product identification within the Amazon organization (summary from [Wikipedia](https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number)'s article).\n\nNote also that this is a definition for how to include ASINs in Schema.org data, and not a definition of ASINs in general - see documentation from Amazon for authoritative details.\nASINs are most commonly encoded as text strings, but the [asin] property supports URL/URI as potential values too.", label='asin', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='audience', schema_name='audience', schema_url='https://schema.org/audience', ranges=('Audience',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('serviceAudience',), equivalent_properties=('http://purl.org/dc/terms/audience',), subproperty_of=(), domains=('CreativeWork', 'Event', 'LodgingBusiness', 'PlayAction', 'Product', 'Service'), external_domains=(), comment='An intended audience, i.e. a group for whom something was created.', label='audience', contributors=(), sources=()),
        PropertyMetadata(name='award', schema_name='award', schema_url='https://schema.org/award', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('awards',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='An award won by or for this item.', label='award', contributors=(), sources=()),
        PropertyMetadata(name='awards', schema_name='awards', schema_url='https://schema.org/awards', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by='award', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Organization', 'Person', 'Product'), external_domains=(), comment='Awards won by or for this item.', label='awards', contributors=(), sources=()),
        PropertyMetadata(name='body_type', schema_name='bodyType', schema_url='https://schema.org/bodyType', ranges=('QualitativeValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='Indicates the design and body style of the vehicle (e.g. station wagon, hatchback, etc.).', label='bodyType', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='brand', schema_name='brand', schema_url='https://schema.org/brand', ranges=('Brand', 'Organization'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#brandName',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/hasDesignation',), domains=('Organization', 'Person', 'Product', 'Service'), external_domains=(), comment='The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.', label='brand', contributors=(), sources=()),
        PropertyMetadata(name='call_sign', schema_name='callSign', schema_url='https://schema.org/callSign', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('BroadcastService', 'Person', 'Vehicle'), external_domains=(), comment='A [callsign](https://en.wikipedia.org/wiki/Call_sign), as used in broadcasting and radio communications to identify people, radio and TV stations, or vehicles.', label='callSign', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2109',)),
        PropertyMetadata(name='cargo_volume', schema_name='cargoVolume', schema_url='https://schema.org/cargoVolume', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The available volume for cargo or luggage. For automobiles, this is usually the trunk volume.\\n\\nTypical unit code(s): LTR for liters, FTQ for cubic foot/feet\\n\\nNote: You can use [[minValue]] and [[maxValue]] to indicate ranges.', label='cargoVolume', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='category', schema_name='category', schema_url='https://schema.org/category', ranges=('CategoryCode', 'PhysicalActivityCategory', 'Text', 'Thing', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('ActionAccessSpecification', 'Guide', 'Invoice', 'Offer', 'PhysicalActivity', 'Product', 'Recommendation', 'Service', 'SpecialAnnouncement'), external_domains=(), comment='A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.', label='category', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1741', 'https://github.com/schemaorg/schemaorg/issues/2490')),
        PropertyMetadata(name='color', schema_name='color', schema_url='https://schema.org/color', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#colourDescription',), subproperty_of=(), domains=('Product',), external_domains=(), comment='The color of the product.', label='color', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='color_swatch', schema_name='colorSwatch', schema_url='https://schema.org/colorSwatch', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('image',), domains=('Product',), external_domains=(), comment='A color swatch image, visualizing the color of a [[Product]]. Should match the textual description specified in the [[color]] property. This can be a URL or a fully described ImageObject.', label='colorSwatch', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3423',)),
        PropertyMetadata(name='country_of_assembly', schema_name='countryOfAssembly', schema_url='https://schema.org/countryOfAssembly', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#finalAssemblyCountry',), subproperty_of=(), domains=('Product',), external_domains=(), comment='The place where the product was assembled.', label='countryOfAssembly', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/991',)),
        PropertyMetadata(name='country_of_last_processing', schema_name='countryOfLastProcessing', schema_url='https://schema.org/countryOfLastProcessing', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ProcessingCountry',), subproperty_of=(), domains=('Product',), external_domains=(), comment='The place where the item (typically [[Product]]) was last processed and tested before importation.', label='countryOfLastProcessing', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/991',)),
        PropertyMetadata(name='country_of_origin', schema_name='countryOfOrigin', schema_url='https://schema.org/countryOfOrigin', ranges=('Country',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#originCountry',), subproperty_of=(), domains=('CreativeWork', 'Movie', 'Product', 'TVEpisode', 'TVSeason', 'TVSeries'), external_domains=(), comment='The country of origin of something, including products as well as creative  works such as movie and TV content.\n\nIn the case of TV and movie, this would be the country of the principle offices of the production company or individual responsible for the movie. For other kinds of [[CreativeWork]] it is difficult to provide fully general guidance, and properties such as [[contentLocation]] and [[locationCreated]] may be more applicable.\n\nIn the case of products, the country of origin of the product. The exact interpretation of this may vary by context and product type, and cannot be fully enumerated here.', label='countryOfOrigin', contributors=(), sources=()),
        PropertyMetadata(name='date_vehicle_first_registered', schema_name='dateVehicleFirstRegistered', schema_url='https://schema.org/dateVehicleFirstRegistered', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The date of the first registration of the vehicle with the respective public authorities.', label='dateVehicleFirstRegistered', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='depth', schema_name='depth', schema_url='https://schema.org/depth', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The depth of the item.', label='depth', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='display_location', schema_name='displayLocation', schema_url='https://schema.org/displayLocation', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Product'), external_domains=(), comment='The location at which an item can be viewed or experienced in-person.', label='displayLocation', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4513',)),
        PropertyMetadata(name='drive_wheel_configuration', schema_name='driveWheelConfiguration', schema_url='https://schema.org/driveWheelConfiguration', ranges=('DriveWheelConfigurationValue', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment="The drive wheel configuration, i.e. which roadwheels will receive torque from the vehicle's engine via the drivetrain.", label='driveWheelConfiguration', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='emissions_co2', schema_name='emissionsCO2', schema_url='https://schema.org/emissionsCO2', ranges=('Number',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The CO2 emissions in g/km. When used in combination with a QuantitativeValue, put "g/km" into the unitText property of that value, since there is no UN/CEFACT Common Code for "g/km".', label='emissionsCO2', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='fuel_capacity', schema_name='fuelCapacity', schema_url='https://schema.org/fuelCapacity', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The capacity of the fuel tank or in the case of electric cars, the battery. If there are multiple components for storage, this should indicate the total of all storage of the same type.\\n\\nTypical unit code(s): LTR for liters, GLL of US gallons, GLI for UK / imperial gallons, AMH for ampere-hours (for electrical vehicles).', label='fuelCapacity', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='fuel_consumption', schema_name='fuelConsumption', schema_url='https://schema.org/fuelConsumption', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The amount of fuel consumed for traveling a particular distance or temporal duration with the given vehicle (e.g. liters per 100 km).\\n\\n* Note 1: There are unfortunately no standard unit codes for liters per 100 km.  Use [[unitText]] to indicate the unit of measurement, e.g. L/100 km.\\n* Note 2: There are two ways of indicating the fuel consumption, [[fuelConsumption]] (e.g. 8 liters per 100 km) and [[fuelEfficiency]] (e.g. 30 miles per gallon). They are reciprocal.\\n* Note 3: Often, the absolute value is useful only when related to driving speed ("at 80 km/h") or usage pattern ("city traffic"). You can use [[valueReference]] to link the value for the fuel consumption to another value.', label='fuelConsumption', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='fuel_efficiency', schema_name='fuelEfficiency', schema_url='https://schema.org/fuelEfficiency', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The distance traveled per unit of fuel used; most commonly miles per gallon (mpg) or kilometers per liter (km/L).\\n\\n* Note 1: There are unfortunately no standard unit codes for miles per gallon or kilometers per liter. Use [[unitText]] to indicate the unit of measurement, e.g. mpg or km/L.\\n* Note 2: There are two ways of indicating the fuel consumption, [[fuelConsumption]] (e.g. 8 liters per 100 km) and [[fuelEfficiency]] (e.g. 30 miles per gallon). They are reciprocal.\\n* Note 3: Often, the absolute value is useful only when related to driving speed ("at 80 km/h") or usage pattern ("city traffic"). You can use [[valueReference]] to link the value for the fuel economy to another value.', label='fuelEfficiency', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='fuel_type', schema_name='fuelType', schema_url='https://schema.org/fuelType', ranges=('QualitativeValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('EngineSpecification', 'Vehicle'), external_domains=(), comment='The type of fuel suitable for the engine or engines of the vehicle. If the vehicle has only one engine, this property can be attached directly to the vehicle.', label='fuelType', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='funding', schema_name='funding', schema_url='https://schema.org/funding', ranges=('Grant',), external_ranges=(), inverse_of='fundedItem', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('BioChemEntity', 'CreativeWork', 'Event', 'MedicalEntity', 'Organization', 'Person', 'Product'), external_domains=(), comment='A [[Grant]] that directly or indirectly provide funding or sponsorship for this item. See also [[ownershipFundingInfo]].', label='funding', contributors=('https://schema.org/docs/collab/TP',), sources=('https://github.com/schemaorg/schemaorg/issues/383',)),
        PropertyMetadata(name='gtin', schema_name='gtin', schema_url='https://schema.org/gtin', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#gTINId', 'https://ref.gs1.org/voc/gtin'), subproperty_of=('identifier',), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='A Global Trade Item Number ([GTIN](https://www.gs1.org/standards/id-keys/gtin)). GTINs identify trade items, including products and services, using numeric identification codes.\n\nA correct [[gtin]] value should be a valid GTIN, which means that it should be an all-numeric string of either 8, 12, 13 or 14 digits, or a "GS1 Digital Link" URL based on such a string. The numeric component should also have a [valid GS1 check digit](https://www.gs1.org/services/check-digit-calculator) and meet the other rules for valid GTINs. See also [GS1\'s GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) and [Wikipedia](https://en.wikipedia.org/wiki/Global_Trade_Item_Number) for more details. Left-padding of the gtin values is not required or encouraged. The [[gtin]] property generalizes the earlier [[gtin8]], [[gtin12]], [[gtin13]], and [[gtin14]] properties.\n\nThe GS1 [digital link specifications](https://www.gs1.org/standards/Digital-Link/) expresses GTINs as URLs (URIs, IRIs, etc.).\nDigital Links should be populated into the [[hasGS1DigitalLink]] attribute.\n\nNote also that this is a definition for how to include GTINs in Schema.org data, and not a definition of GTINs in general - see the GS1 documentation for authoritative details.', label='gtin', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='gtin12', schema_name='gtin12', schema_url='https://schema.org/gtin12', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-12 code of the product, or the product to which the offer refers. The GTIN-12 is the 12-digit GS1 Identification Key composed of a U.P.C. Company Prefix, Item Reference, and Check Digit used to identify trade items. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin12', contributors=(), sources=()),
        PropertyMetadata(name='gtin13', schema_name='gtin13', schema_url='https://schema.org/gtin13', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-13 code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceding zero. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin13', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='gtin14', schema_name='gtin14', schema_url='https://schema.org/gtin14', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-14 code of the product, or the product to which the offer refers. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin14', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='gtin8', schema_name='gtin8', schema_url='https://schema.org/gtin8', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('gtin', 'identifier'), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The GTIN-8 code of the product, or the product to which the offer refers. This code is also known as EAN/UCC-8 or 8-digit EAN. See [GS1 GTIN Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more details.', label='gtin8', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='has_adult_consideration', schema_name='hasAdultConsideration', schema_url='https://schema.org/hasAdultConsideration', ranges=('AdultOrientedEnumeration',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Offer', 'Product'), external_domains=(), comment='Used to tag an item to be intended or suitable for consumption or use by adults only.', label='hasAdultConsideration', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2989',)),
        PropertyMetadata(name='has_certification', schema_name='hasCertification', schema_url='https://schema.org/hasCertification', ranges=('Certification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ApplicableCertificate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/isReferencedIn', 'https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy'), domains=('Organization', 'Person', 'Place', 'Product', 'Service'), external_domains=(), comment='Certification information about a product, organization, service, place, or person.', label='hasCertification', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3230',)),
        PropertyMetadata(name='has_energy_consumption_details', schema_name='hasEnergyConsumptionDetails', schema_url='https://schema.org/hasEnergyConsumptionDetails', ranges=('EnergyConsumptionDetails',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Product',), external_domains=(), comment='Defines the energy efficiency Category (also known as "class" or "rating") for a product according to an international energy efficiency standard.', label='hasEnergyConsumptionDetails', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2670',)),
        PropertyMetadata(name='has_gs1_digital_link', schema_name='hasGS1DigitalLink', schema_url='https://schema.org/hasGS1DigitalLink', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Offer', 'Organization', 'Place', 'Product'), external_domains=(), comment='The <a href="https://www.gs1.org/standards/gs1-digital-link">GS1 digital link</a> associated with the object. This URL should conform to the particular requirements of digital links. The link should only contain the Application Identifiers (AIs) that are relevant for the entity being annotated, for instance a [[Product]] or an [[Organization]], and for the correct granularity. In particular, for products:<ul><li>A Digital Link that contains a serial number (AI <code>21</code>) should only be present on instances of [[IndividualProduct]]</li><li>A Digital Link that contains a lot number (AI <code>10</code>) should be annotated as [[SomeProducts]] if only products from that lot are sold, or [[IndividualProduct]] if there is only a specific product.</li><li>A Digital Link that contains a global model number (AI <code>8013</code>) should be attached to a [[Product]] or a [[ProductModel]].</li></ul> Other item types should be adapted similarly.', label='hasGS1DigitalLink', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3475',)),
        PropertyMetadata(name='has_measurement', schema_name='hasMeasurement', schema_url='https://schema.org/hasMeasurement', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Certification', 'Offer', 'Product', 'SizeSpecification'), external_domains=(), comment='A measurement of an item, For example, the inseam of pants, the wheel size of a bicycle, the gauge of a screw, or the carbon footprint measured for certification by an authority. Usually an exact measurement, but can also be a range of measurements for adjustable products, for example belts and ski bindings.', label='hasMeasurement', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2811',)),
        PropertyMetadata(name='has_merchant_return_policy', schema_name='hasMerchantReturnPolicy', schema_url='https://schema.org/hasMerchantReturnPolicy', ranges=('MerchantReturnPolicy',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('hasProductReturnPolicy',), equivalent_properties=(), subproperty_of=(), domains=('Offer', 'Organization', 'Product'), external_domains=(), comment='Specifies a MerchantReturnPolicy that may be applicable.', label='hasMerchantReturnPolicy', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='has_product_return_policy', schema_name='hasProductReturnPolicy', schema_url='https://schema.org/hasProductReturnPolicy', ranges=('ProductReturnPolicy',), external_ranges=(), inverse_of=None, superseded_by='hasMerchantReturnPolicy', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Product'), external_domains=(), comment='Indicates a ProductReturnPolicy that may be applicable.', label='hasProductReturnPolicy', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2288',)),
        PropertyMetadata(name='height', schema_name='height', schema_url='https://schema.org/height', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MediaObject', 'OfferShippingDetails', 'Person', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The height of the item.', label='height', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='in_product_group_with_id', schema_name='inProductGroupWithID', schema_url='https://schema.org/inProductGroupWithID', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#variantId',), subproperty_of=(), domains=('Product',), external_domains=(), comment='Indicates the [[productGroupID]] for a [[ProductGroup]] that this product [[isVariantOf]]. ', label='inProductGroupWithID', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1797',)),
        PropertyMetadata(name='is_accessory_or_spare_part_for', schema_name='isAccessoryOrSparePartFor', schema_url='https://schema.org/isAccessoryOrSparePartFor', ranges=('Product',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Product',), external_domains=(), comment='A pointer to another product (or multiple products) for which this product is an accessory or spare part.', label='isAccessoryOrSparePartFor', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='is_consumable_for', schema_name='isConsumableFor', schema_url='https://schema.org/isConsumableFor', ranges=('Product',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Product',), external_domains=(), comment='A pointer to another product (or multiple products) for which this product is a consumable.', label='isConsumableFor', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='is_family_friendly', schema_name='isFamilyFriendly', schema_url='https://schema.org/isFamilyFriendly', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Offer', 'Product'), external_domains=(), comment='Indicates whether this content is family friendly.', label='isFamilyFriendly', contributors=(), sources=()),
        PropertyMetadata(name='is_related_to', schema_name='isRelatedTo', schema_url='https://schema.org/isRelatedTo', ranges=('Product', 'Service'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#RelatedProduct',), subproperty_of=(), domains=('Product', 'Service'), external_domains=(), comment='A pointer to another, somehow related product (or multiple products).', label='isRelatedTo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='is_similar_to', schema_name='isSimilarTo', schema_url='https://schema.org/isSimilarTo', ranges=('Product', 'Service'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#SubstituteProduct',), subproperty_of=(), domains=('Product', 'Service'), external_domains=(), comment='A pointer to another, functionally similar product (or multiple products).', label='isSimilarTo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='is_variant_of', schema_name='isVariantOf', schema_url='https://schema.org/isVariantOf', ranges=('ProductGroup', 'ProductModel'), external_ranges=(), inverse_of='hasVariant', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/2004/02/skos/core#broader', 'https://www.omg.org/spec/Commons/Classifiers/exemplifies'), domains=('Product', 'ProductModel'), external_domains=(), comment='Indicates the kind of product that this is a variant of. In the case of [[ProductModel]], this is a pointer (from a ProductModel) to a base product from which this product is a variant. It is safe to infer that the variant inherits all product features from the base model, unless defined locally. This is not transitive. In the case of a [[ProductGroup]], the group description also serves as a template, representing a set of Products that vary on explicitly defined, specific dimensions only (so it defines both a set of variants, as well as which values distinguish amongst those variants). When used with [[ProductGroup]], this property can apply to any [[Product]] included in the group.', label='isVariantOf', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='item_condition', schema_name='itemCondition', schema_url='https://schema.org/itemCondition', ranges=('OfferItemCondition',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Demand', 'MerchantReturnPolicy', 'Offer', 'Product'), external_domains=(), comment='A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.', label='itemCondition', contributors=(), sources=()),
        PropertyMetadata(name='keywords', schema_name='keywords', schema_url='https://schema.org/keywords', ranges=('DefinedTerm', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Organization', 'Place', 'Product'), external_domains=(), comment='Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.', label='keywords', contributors=(), sources=()),
        PropertyMetadata(name='known_vehicle_damages', schema_name='knownVehicleDamages', schema_url='https://schema.org/knownVehicleDamages', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='A textual description of known damages, both repaired and unrepaired.', label='knownVehicleDamages', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='logo', schema_name='logo', schema_url='https://schema.org/logo', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#logoReferencedDocument',), subproperty_of=('image',), domains=('Brand', 'Certification', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='An associated logo.', label='logo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='manufacturer', schema_name='manufacturer', schema_url='https://schema.org/manufacturer', ranges=('Organization',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#manufacturerParty', 'https://ref.gs1.org/voc/manufacturer'), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/isProvisionedBy',), domains=('Product',), external_domains=(), comment='The manufacturer of the product.', label='manufacturer', contributors=(), sources=()),
        PropertyMetadata(name='material', schema_name='material', schema_url='https://schema.org/material', ranges=('Product', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Product'), external_domains=(), comment='A material that something is made from, e.g. leather, wool, cotton, paper.', label='material', contributors=(), sources=()),
        PropertyMetadata(name='meets_emission_standard', schema_name='meetsEmissionStandard', schema_url='https://schema.org/meetsEmissionStandard', ranges=('QualitativeValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='Indicates that the vehicle meets the respective emission standard.', label='meetsEmissionStandard', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='mileage_from_odometer', schema_name='mileageFromOdometer', schema_url='https://schema.org/mileageFromOdometer', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The total distance travelled by the particular vehicle since its initial production, as read from its odometer.\\n\\nTypical unit code(s): KMT for kilometers, SMI for statute miles.', label='mileageFromOdometer', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='mobile_url', schema_name='mobileUrl', schema_url='https://schema.org/mobileUrl', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Offer', 'Product'), external_domains=(), comment='The [[mobileUrl]] property is provided for specific situations in which data consumers need to determine whether one of several provided URLs is a dedicated \'mobile site\'.\n\nTo discourage over-use, and reflecting intial usecases, the property is expected only on [[Product]] and [[Offer]], rather than [[Thing]]. The general trend in web technology is towards [responsive design](https://en.wikipedia.org/wiki/Responsive_web_design) in which content can be flexibly adapted to a wide range of browsing environments. Pages and sites referenced with the long-established [[url]] property should ideally also be usable on a wide variety of devices, including mobile phones. In most cases, it would be pointless and counter productive to attempt to update all [[url]] markup to use [[mobileUrl]] for more mobile-oriented pages. The property is intended for the case when items (primarily [[Product]] and [[Offer]]) have extra URLs hosted on an additional "mobile site" alongside the main one. It should not be taken as an endorsement of this publication style.\n    ', label='mobileUrl', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3134',)),
        PropertyMetadata(name='model', schema_name='model', schema_url='https://schema.org/model', ranges=('ProductModel', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ModelName',), subproperty_of=('https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy',), domains=('Product',), external_domains=(), comment='The model of the product. Use with the URL of a ProductModel or a textual representation of the model identifier. The URL of the ProductModel can be from an external source. It is recommended to additionally provide strong product identifiers via the gtin8/gtin13/gtin14 and mpn properties.', label='model', contributors=(), sources=()),
        PropertyMetadata(name='model_date', schema_name='modelDate', schema_url='https://schema.org/modelDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The release date of a vehicle model (often used to differentiate versions of the same make and model).', label='modelDate', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='mpn', schema_name='mpn', schema_url='https://schema.org/mpn', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#manufacturerAssignedId',), subproperty_of=(), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The Manufacturer Part Number (MPN) of the product, or the product to which the offer refers.', label='mpn', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='negative_notes', schema_name='negativeNotes', schema_url='https://schema.org/negativeNotes', ranges=('ItemList', 'ListItem', 'Text', 'WebContent'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Product', 'Review'), external_domains=(), comment='Provides negative considerations regarding something, most typically in pro/con lists for reviews (alongside [[positiveNotes]]). For symmetry \n\nIn the case of a [[Review]], the property describes the [[itemReviewed]] from the perspective of the review; in the case of a [[Product]], the product itself is being described. Since product descriptions \ntend to emphasise positive claims, it may be relatively unusual to find [[negativeNotes]] used in this way. Nevertheless for the sake of symmetry, [[negativeNotes]] can be used on [[Product]].\n\nThe property values can be expressed either as unstructured text (repeated as necessary), or if ordered, as a list (in which case the most negative is at the beginning of the list).', label='negativeNotes', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2832',)),
        PropertyMetadata(name='nsn', schema_name='nsn', schema_url='https://schema.org/nsn', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#nSNId',), subproperty_of=('identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), domains=('Product',), external_domains=(), comment='Indicates the [NATO stock number](https://en.wikipedia.org/wiki/NATO_Stock_Number) (nsn) of a [[Product]]. ', label='nsn', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2126',)),
        PropertyMetadata(name='number_of_airbags', schema_name='numberOfAirbags', schema_url='https://schema.org/numberOfAirbags', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The number or type of airbags in the vehicle.', label='numberOfAirbags', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='number_of_axles', schema_name='numberOfAxles', schema_url='https://schema.org/numberOfAxles', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The number of axles.\\n\\nTypical unit code(s): C62.', label='numberOfAxles', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='number_of_doors', schema_name='numberOfDoors', schema_url='https://schema.org/numberOfDoors', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The number of doors.\\n\\nTypical unit code(s): C62.', label='numberOfDoors', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='number_of_forward_gears', schema_name='numberOfForwardGears', schema_url='https://schema.org/numberOfForwardGears', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The total number of forward gears available for the transmission system of the vehicle.\\n\\nTypical unit code(s): C62.', label='numberOfForwardGears', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='number_of_previous_owners', schema_name='numberOfPreviousOwners', schema_url='https://schema.org/numberOfPreviousOwners', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The number of owners of the vehicle, including the current one.\\n\\nTypical unit code(s): C62.', label='numberOfPreviousOwners', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='offers', schema_name='offers', schema_url='https://schema.org/offers', ranges=('Demand', 'Offer'), external_ranges=(), inverse_of='itemOffered', superseded_by=None, supersedes=(), equivalent_properties=('https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/isProductOf',), subproperty_of=(), domains=('AggregateOffer', 'CreativeWork', 'EducationalOccupationalProgram', 'Event', 'MenuItem', 'Product', 'Service', 'Trip'), external_domains=(), comment='An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.\n      ', label='offers', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2289',)),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='pattern', schema_name='pattern', schema_url='https://schema.org/pattern', ranges=('DefinedTerm', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#printDesignDescription',), subproperty_of=(), domains=('CreativeWork', 'Product'), external_domains=(), comment="A pattern that something has, for example 'polka dot', 'striped', 'Canadian flag'. Values are typically expressed as text, although links to controlled value schemes are also supported.", label='pattern', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1797',)),
        PropertyMetadata(name='payload', schema_name='payload', schema_url='https://schema.org/payload', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The permitted weight of passengers and cargo, EXCLUDING the weight of the empty vehicle.\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n\\n* Note 1: Many databases specify the permitted TOTAL weight instead, which is the sum of [[weight]] and [[payload]]\\n* Note 2: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 3: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 4: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.', label='payload', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='positive_notes', schema_name='positiveNotes', schema_url='https://schema.org/positiveNotes', ranges=('ItemList', 'ListItem', 'Text', 'WebContent'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Product', 'Review'), external_domains=(), comment='Provides positive considerations regarding something, for example product highlights or (alongside [[negativeNotes]]) pro/con lists for reviews.\n\nIn the case of a [[Review]], the property describes the [[itemReviewed]] from the perspective of the review; in the case of a [[Product]], the product itself is being described.\n\nThe property values can be expressed either as unstructured text (repeated as necessary), or if ordered, as a list (in which case the most positive is at the beginning of the list).', label='positiveNotes', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2832',)),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='product_id', schema_name='productID', schema_url='https://schema.org/productID', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Product',), external_domains=(), comment='The product identifier, such as ISBN. For example: ``` meta itemprop="productID" content="isbn:123-456-789" ```.', label='productID', contributors=(), sources=()),
        PropertyMetadata(name='production_date', schema_name='productionDate', schema_url='https://schema.org/productionDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ProductionDate',), subproperty_of=(), domains=('Product', 'Vehicle'), external_domains=(), comment='The date of production of the item, e.g. vehicle.', label='productionDate', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='purchase_date', schema_name='purchaseDate', schema_url='https://schema.org/purchaseDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Product', 'Vehicle'), external_domains=(), comment='The date the item, e.g. vehicle, was purchased by the current owner.', label='purchaseDate', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='release_date', schema_name='releaseDate', schema_url='https://schema.org/releaseDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ProductAvailabilityDate',), subproperty_of=(), domains=('Product',), external_domains=(), comment='The release date of a product or product model. This can be used to distinguish the exact variant of a product.', label='releaseDate', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='review', schema_name='review', schema_url='https://schema.org/review', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('reviews',), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A review of the item.', label='review', contributors=(), sources=()),
        PropertyMetadata(name='reviews', schema_name='reviews', schema_url='https://schema.org/reviews', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by='review', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Offer', 'Organization', 'Place', 'Product'), external_domains=(), comment='Review of the item.', label='reviews', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='seating_capacity', schema_name='seatingCapacity', schema_url='https://schema.org/seatingCapacity', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The number of persons that can be seated (e.g. in a vehicle), both in terms of the physical space available, and in terms of limitations set by law.\\n\\nTypical unit code(s): C62 for persons.', label='seatingCapacity', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='size', schema_name='size', schema_url='https://schema.org/size', ranges=('DefinedTerm', 'QuantitativeValue', 'SizeSpecification', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#sizeDescription',), subproperty_of=(), domains=('CreativeWork', 'Product'), external_domains=(), comment="A standardized size of a product or creative work, specified either through a simple textual string (for example 'XL', '32Wx34L'), a  QuantitativeValue with a unitCode, or a comprehensive and structured [[SizeSpecification]]; in other cases, the [[width]], [[height]], [[depth]] and [[weight]] properties may be more applicable. ", label='size', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1797',)),
        PropertyMetadata(name='sku', schema_name='sku', schema_url='https://schema.org/sku', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#sellerAssignedId',), subproperty_of=('identifier',), domains=('Demand', 'Offer', 'Product'), external_domains=(), comment='The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product or service, or the product to which the offer refers.', label='sku', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='slogan', schema_name='slogan', schema_url='https://schema.org/slogan', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#PromotionalMessage',), subproperty_of=(), domains=('Brand', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A slogan or motto associated with the item.', label='slogan', contributors=(), sources=()),
        PropertyMetadata(name='speed', schema_name='speed', schema_url='https://schema.org/speed', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The speed range of the vehicle. If the vehicle is powered by an engine, the upper limit of the speed range (indicated by [[maxValue]]) should be the maximum speed achievable under regular conditions.\\n\\nTypical unit code(s): KMH for km/h, HM for mile per hour (0.447 04 m/s), KNT for knot\\n\\n*Note 1: Use [[minValue]] and [[maxValue]] to indicate the range. Typically, the minimal value is zero.\\n* Note 2: There are many different ways of measuring the speed range. You can link to information about how the given value has been determined using the [[valueReference]] property.', label='speed', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='steering_position', schema_name='steeringPosition', schema_url='https://schema.org/steeringPosition', ranges=('SteeringPositionValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The position of the steering wheel or similar device (mostly for cars).', label='steeringPosition', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='stupid_property', schema_name='stupidProperty', schema_url='https://schema.org/stupidProperty', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('StupidType', 'Vehicle'), external_domains=(), comment='This is a StupidProperty! - for testing only.', label='stupidProperty', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='tongue_weight', schema_name='tongueWeight', schema_url='https://schema.org/tongueWeight', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The permitted vertical load (TWR) of a trailer attached to the vehicle. Also referred to as Tongue Load Rating (TLR) or Vertical Load Rating (VLR).\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n\\n* Note 1: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 2: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 3: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.', label='tongueWeight', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='trailer_weight', schema_name='trailerWeight', schema_url='https://schema.org/trailerWeight', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The permitted weight of a trailer attached to the vehicle.\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n* Note 1: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 2: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 3: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.', label='trailerWeight', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
        PropertyMetadata(name='vehicle_configuration', schema_name='vehicleConfiguration', schema_url='https://schema.org/vehicleConfiguration', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment="A short text indicating the configuration of the vehicle, e.g. '5dr hatchback ST 2.5 MT 225 hp' or 'limited edition'.", label='vehicleConfiguration', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_engine', schema_name='vehicleEngine', schema_url='https://schema.org/vehicleEngine', ranges=('EngineSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='Information about the engine or engines of the vehicle.', label='vehicleEngine', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_identification_number', schema_name='vehicleIdentificationNumber', schema_url='https://schema.org/vehicleIdentificationNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('serialNumber',), domains=('Vehicle',), external_domains=(), comment='The Vehicle Identification Number (VIN) is a unique serial number used by the automotive industry to identify individual motor vehicles.', label='vehicleIdentificationNumber', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_interior_color', schema_name='vehicleInteriorColor', schema_url='https://schema.org/vehicleInteriorColor', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The color or color combination of the interior of the vehicle.', label='vehicleInteriorColor', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_interior_type', schema_name='vehicleInteriorType', schema_url='https://schema.org/vehicleInteriorType', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The type or material of the interior of the vehicle (e.g. synthetic fabric, leather, wood, etc.). While most interior types are characterized by the material used, an interior type can also be based on vehicle usage or target audience.', label='vehicleInteriorType', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_model_date', schema_name='vehicleModelDate', schema_url='https://schema.org/vehicleModelDate', ranges=('Date',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The release date of a vehicle model (often used to differentiate versions of the same make and model).', label='vehicleModelDate', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_seating_capacity', schema_name='vehicleSeatingCapacity', schema_url='https://schema.org/vehicleSeatingCapacity', ranges=('Number', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The number of passengers that can be seated in the vehicle, both in terms of the physical space available, and in terms of limitations set by law.\\n\\nTypical unit code(s): C62 for persons.', label='vehicleSeatingCapacity', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_special_usage', schema_name='vehicleSpecialUsage', schema_url='https://schema.org/vehicleSpecialUsage', ranges=('CarUsageType', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='Indicates whether the vehicle has been used for special purposes, like commercial rental, driving school, or as a taxi. The legislation in many countries requires this information to be revealed when offering a car for sale.', label='vehicleSpecialUsage', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='vehicle_transmission', schema_name='vehicleTransmission', schema_url='https://schema.org/vehicleTransmission', ranges=('QualitativeValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The type of component used for transmitting the power from a rotating power source to the wheels or other relevant component(s) ("gearbox" for cars).', label='vehicleTransmission', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='weight', schema_name='weight', schema_url='https://schema.org/weight', ranges=('Mass', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('OfferShippingDetails', 'Person', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The weight of the product or person.', label='weight', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
        PropertyMetadata(name='weight_total', schema_name='weightTotal', schema_url='https://schema.org/weightTotal', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The permitted total weight of the loaded vehicle, including passengers and cargo and the weight of the empty vehicle.\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n\\n* Note 1: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 2: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 3: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.', label='weightTotal', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='wheelbase', schema_name='wheelbase', schema_url='https://schema.org/wheelbase', ranges=('QuantitativeValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Vehicle',), external_domains=(), comment='The distance between the centers of the front and rear wheels.\\n\\nTypical unit code(s): CMT for centimeters, MTR for meters, INH for inches, FOT for foot/feet.', label='wheelbase', contributors=('https://schema.org/docs/collab/Automotive_Ontology_Working_Group',), sources=()),
        PropertyMetadata(name='width', schema_name='width', schema_url='https://schema.org/width', ranges=('Distance', 'QuantitativeValue'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MediaObject', 'OfferShippingDetails', 'Product', 'ShippingConditions', 'VisualArtwork'), external_domains=(), comment='The width of the item.', label='width', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3617',)),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Vehicle'] = Field(default='Vehicle', alias='@type', frozen=True)
    acceleration_time: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='accelerationTime', description='The time needed to accelerate the vehicle from a given start velocity to a given target velocity.\\n\\nTypical unit code(s): SEC for seconds\\n\\n* Note: There are unfortunately no standard unit codes for seconds/0..100 km/h or seconds/0..60 mph. Simply use "SEC" for seconds and indicate the velocities in the [[name]] of the [[QuantitativeValue]], or use [[valueReference]] with a [[QuantitativeValue]] of 0..60 mph or 0..100 km/h to specify the reference speeds.')
    body_type: QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL | list[QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL] | None = Field(default=None, alias='bodyType', description='Indicates the design and body style of the vehicle (e.g. station wagon, hatchback, etc.).')
    call_sign: Text | list[Text] | None = Field(default=None, alias='callSign', description='A [callsign](https://en.wikipedia.org/wiki/Call_sign), as used in broadcasting and radio communications to identify people, radio and TV stations, or vehicles.')
    cargo_volume: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='cargoVolume', description='The available volume for cargo or luggage. For automobiles, this is usually the trunk volume.\\n\\nTypical unit code(s): LTR for liters, FTQ for cubic foot/feet\\n\\nNote: You can use [[minValue]] and [[maxValue]] to indicate ranges.')
    date_vehicle_first_registered: Date | list[Date] | None = Field(default=None, alias='dateVehicleFirstRegistered', description='The date of the first registration of the vehicle with the respective public authorities.')
    drive_wheel_configuration: DriveWheelConfigurationValue | Text | list[DriveWheelConfigurationValue | Text] | None = Field(default=None, alias='driveWheelConfiguration', description="The drive wheel configuration, i.e. which roadwheels will receive torque from the vehicle's engine via the drivetrain.")
    emissions_co2: Number | list[Number] | None = Field(default=None, alias='emissionsCO2', description='The CO2 emissions in g/km. When used in combination with a QuantitativeValue, put "g/km" into the unitText property of that value, since there is no UN/CEFACT Common Code for "g/km".')
    fuel_capacity: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='fuelCapacity', description='The capacity of the fuel tank or in the case of electric cars, the battery. If there are multiple components for storage, this should indicate the total of all storage of the same type.\\n\\nTypical unit code(s): LTR for liters, GLL of US gallons, GLI for UK / imperial gallons, AMH for ampere-hours (for electrical vehicles).')
    fuel_consumption: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='fuelConsumption', description='The amount of fuel consumed for traveling a particular distance or temporal duration with the given vehicle (e.g. liters per 100 km).\\n\\n* Note 1: There are unfortunately no standard unit codes for liters per 100 km.  Use [[unitText]] to indicate the unit of measurement, e.g. L/100 km.\\n* Note 2: There are two ways of indicating the fuel consumption, [[fuelConsumption]] (e.g. 8 liters per 100 km) and [[fuelEfficiency]] (e.g. 30 miles per gallon). They are reciprocal.\\n* Note 3: Often, the absolute value is useful only when related to driving speed ("at 80 km/h") or usage pattern ("city traffic"). You can use [[valueReference]] to link the value for the fuel consumption to another value.')
    fuel_efficiency: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='fuelEfficiency', description='The distance traveled per unit of fuel used; most commonly miles per gallon (mpg) or kilometers per liter (km/L).\\n\\n* Note 1: There are unfortunately no standard unit codes for miles per gallon or kilometers per liter. Use [[unitText]] to indicate the unit of measurement, e.g. mpg or km/L.\\n* Note 2: There are two ways of indicating the fuel consumption, [[fuelConsumption]] (e.g. 8 liters per 100 km) and [[fuelEfficiency]] (e.g. 30 miles per gallon). They are reciprocal.\\n* Note 3: Often, the absolute value is useful only when related to driving speed ("at 80 km/h") or usage pattern ("city traffic"). You can use [[valueReference]] to link the value for the fuel economy to another value.')
    fuel_type: QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL | list[QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL] | None = Field(default=None, alias='fuelType', description='The type of fuel suitable for the engine or engines of the vehicle. If the vehicle has only one engine, this property can be attached directly to the vehicle.')
    known_vehicle_damages: Text | list[Text] | None = Field(default=None, alias='knownVehicleDamages', description='A textual description of known damages, both repaired and unrepaired.')
    meets_emission_standard: QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL | list[QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL] | None = Field(default=None, alias='meetsEmissionStandard', description='Indicates that the vehicle meets the respective emission standard.')
    mileage_from_odometer: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='mileageFromOdometer', description='The total distance travelled by the particular vehicle since its initial production, as read from its odometer.\\n\\nTypical unit code(s): KMT for kilometers, SMI for statute miles.')
    model_date: Date | list[Date] | None = Field(default=None, alias='modelDate', description='The release date of a vehicle model (often used to differentiate versions of the same make and model).')
    number_of_airbags: Number | Text | list[Number | Text] | None = Field(default=None, alias='numberOfAirbags', description='The number or type of airbags in the vehicle.')
    number_of_axles: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='numberOfAxles', description='The number of axles.\\n\\nTypical unit code(s): C62.')
    number_of_doors: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='numberOfDoors', description='The number of doors.\\n\\nTypical unit code(s): C62.')
    number_of_forward_gears: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='numberOfForwardGears', description='The total number of forward gears available for the transmission system of the vehicle.\\n\\nTypical unit code(s): C62.')
    number_of_previous_owners: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='numberOfPreviousOwners', description='The number of owners of the vehicle, including the current one.\\n\\nTypical unit code(s): C62.')
    payload: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='payload', description='The permitted weight of passengers and cargo, EXCLUDING the weight of the empty vehicle.\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n\\n* Note 1: Many databases specify the permitted TOTAL weight instead, which is the sum of [[weight]] and [[payload]]\\n* Note 2: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 3: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 4: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.')
    production_date: Date | list[Date] | None = Field(default=None, alias='productionDate', description='The date of production of the item, e.g. vehicle.')
    purchase_date: Date | list[Date] | None = Field(default=None, alias='purchaseDate', description='The date the item, e.g. vehicle, was purchased by the current owner.')
    seating_capacity: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='seatingCapacity', description='The number of persons that can be seated (e.g. in a vehicle), both in terms of the physical space available, and in terms of limitations set by law.\\n\\nTypical unit code(s): C62 for persons.')
    speed: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='speed', description='The speed range of the vehicle. If the vehicle is powered by an engine, the upper limit of the speed range (indicated by [[maxValue]]) should be the maximum speed achievable under regular conditions.\\n\\nTypical unit code(s): KMH for km/h, HM for mile per hour (0.447 04 m/s), KNT for knot\\n\\n*Note 1: Use [[minValue]] and [[maxValue]] to indicate the range. Typically, the minimal value is zero.\\n* Note 2: There are many different ways of measuring the speed range. You can link to information about how the given value has been determined using the [[valueReference]] property.')
    steering_position: SteeringPositionValue | list[SteeringPositionValue] | None = Field(default=None, alias='steeringPosition', description='The position of the steering wheel or similar device (mostly for cars).')
    stupid_property: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='stupidProperty', description='This is a StupidProperty! - for testing only.')
    tongue_weight: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='tongueWeight', description='The permitted vertical load (TWR) of a trailer attached to the vehicle. Also referred to as Tongue Load Rating (TLR) or Vertical Load Rating (VLR).\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n\\n* Note 1: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 2: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 3: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.')
    trailer_weight: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='trailerWeight', description='The permitted weight of a trailer attached to the vehicle.\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n* Note 1: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 2: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 3: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.')
    vehicle_configuration: Text | list[Text] | None = Field(default=None, alias='vehicleConfiguration', description="A short text indicating the configuration of the vehicle, e.g. '5dr hatchback ST 2.5 MT 225 hp' or 'limited edition'.")
    vehicle_engine: EngineSpecification | list[EngineSpecification] | None = Field(default=None, alias='vehicleEngine', description='Information about the engine or engines of the vehicle.')
    vehicle_identification_number: Text | list[Text] | None = Field(default=None, alias='vehicleIdentificationNumber', description='The Vehicle Identification Number (VIN) is a unique serial number used by the automotive industry to identify individual motor vehicles.')
    vehicle_interior_color: Text | list[Text] | None = Field(default=None, alias='vehicleInteriorColor', description='The color or color combination of the interior of the vehicle.')
    vehicle_interior_type: Text | list[Text] | None = Field(default=None, alias='vehicleInteriorType', description='The type or material of the interior of the vehicle (e.g. synthetic fabric, leather, wood, etc.). While most interior types are characterized by the material used, an interior type can also be based on vehicle usage or target audience.')
    vehicle_model_date: Date | list[Date] | None = Field(default=None, alias='vehicleModelDate', description='The release date of a vehicle model (often used to differentiate versions of the same make and model).')
    vehicle_seating_capacity: Number | QuantitativeValue | list[Number | QuantitativeValue] | None = Field(default=None, alias='vehicleSeatingCapacity', description='The number of passengers that can be seated in the vehicle, both in terms of the physical space available, and in terms of limitations set by law.\\n\\nTypical unit code(s): C62 for persons.')
    vehicle_special_usage: CarUsageType | Text | list[CarUsageType | Text] | None = Field(default=None, alias='vehicleSpecialUsage', description='Indicates whether the vehicle has been used for special purposes, like commercial rental, driving school, or as a taxi. The legislation in many countries requires this information to be revealed when offering a car for sale.')
    vehicle_transmission: QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL | list[QualitativeValue | BedType | DriveWheelConfigurationValue | SizeSpecification | SteeringPositionValue | Text | URL] | None = Field(default=None, alias='vehicleTransmission', description='The type of component used for transmitting the power from a rotating power source to the wheels or other relevant component(s) ("gearbox" for cars).')
    weight_total: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='weightTotal', description='The permitted total weight of the loaded vehicle, including passengers and cargo and the weight of the empty vehicle.\\n\\nTypical unit code(s): KGM for kilogram, LBR for pound\\n\\n* Note 1: You can indicate additional information in the [[name]] of the [[QuantitativeValue]] node.\\n* Note 2: You may also link to a [[QualitativeValue]] node that provides additional information using [[valueReference]].\\n* Note 3: Note that you can use [[minValue]] and [[maxValue]] to indicate ranges.')
    wheelbase: QuantitativeValue | list[QuantitativeValue] | None = Field(default=None, alias='wheelbase', description='The distance between the centers of the front and rear wheels.\\n\\nTypical unit code(s): CMT for centimeters, MTR for meters, INH for inches, FOT for foot/feet.')
