# Generated Python code is licensed under MIT.
# Schema.org descriptions are licensed under CC BY-SA 3.0.
# See LICENSE-SCHEMA-ORG.txt.

from __future__ import annotations

from typing import ClassVar, Literal

from schema_org.base import PropertyMetadata, SchemaModel, SchemaValue
from pydantic import Field
from schema_org.datatypes import Boolean
from schema_org.datatypes import Integer
from schema_org.datatypes import Number
from schema_org.datatypes import Text
from schema_org.datatypes import URL
from schema_org.models.civic_structure import CivicStructure

class Zoo(CivicStructure):
    __doc__ = 'https://schema.org/Zoo\n\nA zoo.'
    SCHEMA_TYPE: ClassVar[str] = 'Zoo'
    SCHEMA_TYPES: ClassVar[tuple[str, ...]] = ('Zoo', 'CivicStructure', 'Place', 'Thing')
    SCHEMA_PROPERTIES: ClassVar[tuple[PropertyMetadata, ...]] = (
        PropertyMetadata(name='additional_property', schema_name='additionalProperty', schema_url='https://schema.org/additionalProperty', ranges=('PropertyValue',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('MerchantReturnPolicy', 'Offer', 'Place', 'Product', 'QualitativeValue', 'QuantitativeValue'), external_domains=(), comment='A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\\n\\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.\n', label='additionalProperty', contributors=(), sources=()),
        PropertyMetadata(name='additional_type', schema_name='additionalType', schema_url='https://schema.org/additionalType', ranges=('Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('http://www.w3.org/1999/02/22-rdf-syntax-ns#type',), domains=('Thing',), external_domains=(), comment='An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.', label='additionalType', contributors=(), sources=()),
        PropertyMetadata(name='address', schema_name='address', schema_url='https://schema.org/address', ranges=('PostalAddress', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/address',), subproperty_of=(), domains=('GeoCoordinates', 'GeoShape', 'Organization', 'Person', 'Place'), external_domains=(), comment='Physical address of the item.', label='address', contributors=(), sources=()),
        PropertyMetadata(name='aggregate_rating', schema_name='aggregateRating', schema_url='https://schema.org/aggregateRating', ranges=('AggregateRating',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='The overall rating, based on a collection of reviews or ratings, of the item.', label='aggregateRating', contributors=(), sources=()),
        PropertyMetadata(name='alternate_name', schema_name='alternateName', schema_url='https://schema.org/alternateName', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An alias for the item.', label='alternateName', contributors=(), sources=()),
        PropertyMetadata(name='amenity_feature', schema_name='amenityFeature', schema_url='https://schema.org/amenityFeature', ranges=('LocationFeatureSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'FloorPlan', 'LodgingBusiness', 'Place'), external_domains=(), comment='An amenity feature (e.g. a characteristic or service) of the Accommodation. This generic property does not make a statement about whether the feature is included in an offer for the main accommodation or available at extra costs.', label='amenityFeature', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='branch_code', schema_name='branchCode', schema_url='https://schema.org/branchCode', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A short textual code (also called "store code") that uniquely identifies a place of business. The code is typically assigned by the parentOrganization and used in structured URLs.\\n\\nFor example, in the URL http://www.starbucks.co.uk/store-locator/etc/detail/3047 the code "3047" is a branchCode for a particular branch.\n      ', label='branchCode', contributors=(), sources=()),
        PropertyMetadata(name='contained_in', schema_name='containedIn', schema_url='https://schema.org/containedIn', ranges=('Place',), external_ranges=(), inverse_of=None, superseded_by='containedInPlace', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The basic containment relation between a place and one that contains it.', label='containedIn', contributors=(), sources=()),
        PropertyMetadata(name='contained_in_place', schema_name='containedInPlace', schema_url='https://schema.org/containedInPlace', ranges=('Place',), external_ranges=(), inverse_of='containsPlace', superseded_by=None, supersedes=('containedIn',), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The basic containment relation between a place and one that contains it.', label='containedInPlace', contributors=(), sources=()),
        PropertyMetadata(name='contains_place', schema_name='containsPlace', schema_url='https://schema.org/containsPlace', ranges=('Place',), external_ranges=(), inverse_of='containedInPlace', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The basic containment relation between a place and another that it contains.', label='containsPlace', contributors=(), sources=()),
        PropertyMetadata(name='description', schema_name='description', schema_url='https://schema.org/description', ranges=('Text', 'TextObject'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#description', 'http://purl.org/dc/terms/description', 'https://ref.gs1.org/voc/description'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A description of the item.', label='description', contributors=(), sources=()),
        PropertyMetadata(name='disambiguating_description', schema_name='disambiguatingDescription', schema_url='https://schema.org/disambiguatingDescription', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('description',), domains=('Thing',), external_domains=(), comment='A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.', label='disambiguatingDescription', contributors=(), sources=()),
        PropertyMetadata(name='event', schema_name='event', schema_url='https://schema.org/event', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('events',), equivalent_properties=(), subproperty_of=(), domains=('InformAction', 'InviteAction', 'JoinAction', 'LeaveAction', 'Organization', 'Place', 'PlayAction'), external_domains=(), comment='Upcoming or past event associated with this place, organization, or action.', label='event', contributors=(), sources=()),
        PropertyMetadata(name='events', schema_name='events', schema_url='https://schema.org/events', ranges=('Event',), external_ranges=(), inverse_of=None, superseded_by='event', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Place'), external_domains=(), comment='Upcoming or past events associated with this place or organization.', label='events', contributors=(), sources=()),
        PropertyMetadata(name='fax_number', schema_name='faxNumber', schema_url='https://schema.org/faxNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/faxNumber',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The fax number.', label='faxNumber', contributors=(), sources=()),
        PropertyMetadata(name='geo', schema_name='geo', schema_url='https://schema.org/geo', ranges=('GeoCoordinates', 'GeoShape'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The geo coordinates of the place.', label='geo', contributors=(), sources=()),
        PropertyMetadata(name='geo_contains', schema_name='geoContains', schema_url='https://schema.org/geoContains', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a containing geometry to a contained geometry. "a contains b iff no points of b lie in the exterior of a, and at least one point of the interior of b lies in the interior of a". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoContains', contributors=(), sources=()),
        PropertyMetadata(name='geo_covered_by', schema_name='geoCoveredBy', schema_url='https://schema.org/geoCoveredBy', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to another that covers it. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoCoveredBy', contributors=(), sources=()),
        PropertyMetadata(name='geo_covers', schema_name='geoCovers', schema_url='https://schema.org/geoCovers', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a covering geometry to a covered geometry. "Every point of b is a point of (the interior or boundary of) a". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoCovers', contributors=(), sources=()),
        PropertyMetadata(name='geo_crosses', schema_name='geoCrosses', schema_url='https://schema.org/geoCrosses', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to another that crosses it: "a crosses b: they have some but not all interior points in common, and the dimension of the intersection is less than that of at least one of them". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoCrosses', contributors=(), sources=()),
        PropertyMetadata(name='geo_disjoint', schema_name='geoDisjoint', schema_url='https://schema.org/geoDisjoint', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) are topologically disjoint: "they have no point in common. They form a set of disconnected geometries." (A symmetric relationship, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).)', label='geoDisjoint', contributors=(), sources=()),
        PropertyMetadata(name='geo_equals', schema_name='geoEquals', schema_url='https://schema.org/geoEquals', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) are topologically equal, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM). "Two geometries are topologically equal if their interiors intersect and no part of the interior or boundary of one geometry intersects the exterior of the other" (a symmetric relationship).', label='geoEquals', contributors=(), sources=()),
        PropertyMetadata(name='geo_intersects', schema_name='geoIntersects', schema_url='https://schema.org/geoIntersects', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) have at least one point in common. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoIntersects', contributors=(), sources=()),
        PropertyMetadata(name='geo_overlaps', schema_name='geoOverlaps', schema_url='https://schema.org/geoOverlaps', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to another that geospatially overlaps it, i.e. they have some but not all points in common. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoOverlaps', contributors=(), sources=()),
        PropertyMetadata(name='geo_touches', schema_name='geoTouches', schema_url='https://schema.org/geoTouches', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents spatial relations in which two geometries (or the places they represent) touch: "they have at least one boundary point in common, but no interior points." (A symmetric relationship, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).)', label='geoTouches', contributors=(), sources=()),
        PropertyMetadata(name='geo_within', schema_name='geoWithin', schema_url='https://schema.org/geoWithin', ranges=('GeospatialGeometry', 'Place'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('GeospatialGeometry', 'Place'), external_domains=(), comment='Represents a relationship between two geometries (or the places they represent), relating a geometry to one that contains it, i.e. it is inside (i.e. within) its interior. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).', label='geoWithin', contributors=(), sources=()),
        PropertyMetadata(name='global_location_number', schema_name='globalLocationNumber', schema_url='https://schema.org/globalLocationNumber', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#gLNId', 'https://ref.gs1.org/voc/globalLocationNumber'), subproperty_of=('identifier',), domains=('Organization', 'Person', 'Place'), external_domains=(), comment='The [Global Location Number](http://www.gs1.org/gln) (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.', label='globalLocationNumber', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='has_certification', schema_name='hasCertification', schema_url='https://schema.org/hasCertification', ranges=('Certification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#ApplicableCertificate',), subproperty_of=('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/isReferencedIn', 'https://www.omg.org/spec/Commons/Classifiers/isClassifiedBy'), domains=('Organization', 'Person', 'Place', 'Product', 'Service'), external_domains=(), comment='Certification information about a product, organization, service, place, or person.', label='hasCertification', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3230',)),
        PropertyMetadata(name='has_drive_through_service', schema_name='hasDriveThroughService', schema_url='https://schema.org/hasDriveThroughService', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='Indicates whether some facility (e.g. [[FoodEstablishment]], [[CovidTestingFacility]]) offers a service that can be used by driving through in a car. In the case of [[CovidTestingFacility]] such facilities could potentially help with social distancing from other potentially-infected users.', label='hasDriveThroughService', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2490',)),
        PropertyMetadata(name='has_gs1_digital_link', schema_name='hasGS1DigitalLink', schema_url='https://schema.org/hasGS1DigitalLink', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('identifier',), domains=('Offer', 'Organization', 'Place', 'Product'), external_domains=(), comment='The <a href="https://www.gs1.org/standards/gs1-digital-link">GS1 digital link</a> associated with the object. This URL should conform to the particular requirements of digital links. The link should only contain the Application Identifiers (AIs) that are relevant for the entity being annotated, for instance a [[Product]] or an [[Organization]], and for the correct granularity. In particular, for products:<ul><li>A Digital Link that contains a serial number (AI <code>21</code>) should only be present on instances of [[IndividualProduct]]</li><li>A Digital Link that contains a lot number (AI <code>10</code>) should be annotated as [[SomeProducts]] if only products from that lot are sold, or [[IndividualProduct]] if there is only a specific product.</li><li>A Digital Link that contains a global model number (AI <code>8013</code>) should be attached to a [[Product]] or a [[ProductModel]].</li></ul> Other item types should be adapted similarly.', label='hasGS1DigitalLink', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/3475',)),
        PropertyMetadata(name='has_map', schema_name='hasMap', schema_url='https://schema.org/hasMap', ranges=('Map', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('map', 'maps'), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A URL to a map of the place.', label='hasMap', contributors=(), sources=()),
        PropertyMetadata(name='identifier', schema_name='identifier', schema_url='https://schema.org/identifier', ranges=('PropertyValue', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://purl.org/dc/terms/identifier', 'https://www.omg.org/spec/Commons/Identifiers/identifiedBy'), subproperty_of=(), domains=('Thing',), external_domains=(), comment='The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.\n        ', label='identifier', contributors=(), sources=()),
        PropertyMetadata(name='image', schema_name='image', schema_url='https://schema.org/image', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#image',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].', label='image', contributors=(), sources=()),
        PropertyMetadata(name='is_accessible_for_free', schema_name='isAccessibleForFree', schema_url='https://schema.org/isAccessibleForFree', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('free',), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Place'), external_domains=(), comment='A flag to signal that the item, event, or place is accessible for free.', label='isAccessibleForFree', contributors=(), sources=()),
        PropertyMetadata(name='isic_v4', schema_name='isicV4', schema_url='https://schema.org/isicV4', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Organization', 'Person', 'Place'), external_domains=(), comment='The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.', label='isicV4', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='keywords', schema_name='keywords', schema_url='https://schema.org/keywords', ranges=('DefinedTerm', 'Text', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Event', 'Organization', 'Place', 'Product'), external_domains=(), comment='Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.', label='keywords', contributors=(), sources=()),
        PropertyMetadata(name='latitude', schema_name='latitude', schema_url='https://schema.org/latitude', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLatitude',), domains=('GeoCoordinates', 'Place'), external_domains=(), comment='The latitude of a location. For example ```37.42242``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).', label='latitude', contributors=(), sources=()),
        PropertyMetadata(name='logo', schema_name='logo', schema_url='https://schema.org/logo', ranges=('ImageObject', 'URL'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#logoReferencedDocument',), subproperty_of=('image',), domains=('Brand', 'Certification', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='An associated logo.', label='logo', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='longitude', schema_name='longitude', schema_url='https://schema.org/longitude', ranges=('Number', 'Text'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Locations/hasLongitude',), domains=('GeoCoordinates', 'Place'), external_domains=(), comment='The longitude of a location. For example ```-122.08585``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).', label='longitude', contributors=(), sources=()),
        PropertyMetadata(name='main_entity_of_page', schema_name='mainEntityOfPage', schema_url='https://schema.org/mainEntityOfPage', ranges=('CreativeWork', 'URL'), external_ranges=(), inverse_of='mainEntity', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.', label='mainEntityOfPage', contributors=(), sources=()),
        PropertyMetadata(name='map', schema_name='map', schema_url='https://schema.org/map', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by='hasMap', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A URL to a map of the place.', label='map', contributors=(), sources=()),
        PropertyMetadata(name='maps', schema_name='maps', schema_url='https://schema.org/maps', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by='hasMap', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A URL to a map of the place.', label='maps', contributors=(), sources=()),
        PropertyMetadata(name='maximum_attendee_capacity', schema_name='maximumAttendeeCapacity', schema_url='https://schema.org/maximumAttendeeCapacity', ranges=('Integer',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=('https://www.omg.org/spec/Commons/Quantities/hasUpperBound',), domains=('Event', 'Place'), external_domains=(), comment='The total number of individuals that may attend an event or venue.', label='maximumAttendeeCapacity', contributors=(), sources=()),
        PropertyMetadata(name='name', schema_name='name', schema_url='https://schema.org/name', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#title', 'http://purl.org/dc/terms/title', 'https://www.omg.org/spec/Commons/Text/hasName'), subproperty_of=('http://www.w3.org/2000/01/rdf-schema#label',), domains=('Thing',), external_domains=(), comment='The name of the item.', label='name', contributors=(), sources=()),
        PropertyMetadata(name='opening_hours', schema_name='openingHours', schema_url='https://schema.org/openingHours', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CivicStructure', 'LocalBusiness'), external_domains=(), comment='The general opening hours for a business. Opening hours can be specified as a weekly time range, starting with days, then times per day. Multiple days can be listed with commas \',\' separating each day. Day or time ranges are specified using a hyphen \'-\'.\\n\\n* Days are specified using the following two-letter combinations: ```Mo```, ```Tu```, ```We```, ```Th```, ```Fr```, ```Sa```, ```Su```.\\n* Times are specified using 24:00 format. For example, 3pm is specified as ```15:00```, 10am as ```10:00```. \\n* Here is an example: <code>&lt;time itemprop="openingHours" datetime=&quot;Tu,Th 16:00-20:00&quot;&gt;Tuesdays and Thursdays 4-8pm&lt;/time&gt;</code>.\\n* If a business is open 7 days a week, then it can be specified as <code>&lt;time itemprop=&quot;openingHours&quot; datetime=&quot;Mo-Su&quot;&gt;Monday through Sunday, all day&lt;/time&gt;</code>.', label='openingHours', contributors=(), sources=()),
        PropertyMetadata(name='opening_hours_specification', schema_name='openingHoursSpecification', schema_url='https://schema.org/openingHoursSpecification', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The opening hours of a certain place.', label='openingHoursSpecification', contributors=('https://schema.org/docs/collab/GoodRelationsTerms',), sources=()),
        PropertyMetadata(name='owner', schema_name='owner', schema_url='https://schema.org/owner', ranges=('Organization', 'Person'), external_ranges=(), inverse_of='owns', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A person or organization who owns this Thing.', label='owner', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/4603',)),
        PropertyMetadata(name='photo', schema_name='photo', schema_url='https://schema.org/photo', ranges=('ImageObject', 'Photograph'), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('photos',), equivalent_properties=(), subproperty_of=('image',), domains=('Place',), external_domains=(), comment='A photograph of this place.', label='photo', contributors=(), sources=()),
        PropertyMetadata(name='photos', schema_name='photos', schema_url='https://schema.org/photos', ranges=('ImageObject', 'Photograph'), external_ranges=(), inverse_of=None, superseded_by='photo', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='Photographs of this place.', label='photos', contributors=(), sources=()),
        PropertyMetadata(name='potential_action', schema_name='potentialAction', schema_url='https://schema.org/potentialAction', ranges=('Action',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.", label='potentialAction', contributors=(), sources=()),
        PropertyMetadata(name='public_access', schema_name='publicAccess', schema_url='https://schema.org/publicAccess', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='A flag to signal that the [[Place]] is open to public visitors.  If this property is omitted there is no assumed default boolean value.', label='publicAccess', contributors=(), sources=()),
        PropertyMetadata(name='review', schema_name='review', schema_url='https://schema.org/review', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=('reviews',), equivalent_properties=(), subproperty_of=(), domains=('Brand', 'CreativeWork', 'Event', 'Offer', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A review of the item.', label='review', contributors=(), sources=()),
        PropertyMetadata(name='reviews', schema_name='reviews', schema_url='https://schema.org/reviews', ranges=('Review',), external_ranges=(), inverse_of=None, superseded_by='review', supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('CreativeWork', 'Offer', 'Organization', 'Place', 'Product'), external_domains=(), comment='Review of the item.', label='reviews', contributors=(), sources=()),
        PropertyMetadata(name='same_as', schema_name='sameAs', schema_url='https://schema.org/sameAs', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment="URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.", label='sameAs', contributors=(), sources=()),
        PropertyMetadata(name='slogan', schema_name='slogan', schema_url='https://schema.org/slogan', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://unece.org/vocab#PromotionalMessage',), subproperty_of=(), domains=('Brand', 'Organization', 'Place', 'Product', 'Service'), external_domains=(), comment='A slogan or motto associated with the item.', label='slogan', contributors=(), sources=()),
        PropertyMetadata(name='smoking_allowed', schema_name='smokingAllowed', schema_url='https://schema.org/smokingAllowed', ranges=('Boolean',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='Indicates whether it is allowed to smoke in the place, e.g. in the restaurant, hotel or hotel room.', label='smokingAllowed', contributors=('https://schema.org/docs/collab/STI_Accommodation_Ontology',), sources=()),
        PropertyMetadata(name='special_opening_hours_specification', schema_name='specialOpeningHoursSpecification', schema_url='https://schema.org/specialOpeningHoursSpecification', ranges=('OpeningHoursSpecification',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Place',), external_domains=(), comment='The special opening hours of a certain place.\\n\\nUse this to explicitly override general opening hours brought in scope by [[openingHoursSpecification]] or [[openingHours]].\n      ', label='specialOpeningHoursSpecification', contributors=(), sources=()),
        PropertyMetadata(name='subject_of', schema_name='subjectOf', schema_url='https://schema.org/subjectOf', ranges=('CreativeWork', 'Event'), external_ranges=(), inverse_of='about', superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Thing',), external_domains=(), comment='A CreativeWork or Event about this Thing.', label='subjectOf', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/1670',)),
        PropertyMetadata(name='telephone', schema_name='telephone', schema_url='https://schema.org/telephone', ranges=('Text',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('https://ref.gs1.org/voc/telephone',), subproperty_of=(), domains=('ContactPoint', 'Organization', 'Person', 'Place'), external_domains=(), comment='The telephone number.', label='telephone', contributors=(), sources=()),
        PropertyMetadata(name='tour_booking_page', schema_name='tourBookingPage', schema_url='https://schema.org/tourBookingPage', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=(), subproperty_of=(), domains=('Accommodation', 'ApartmentComplex', 'Place'), external_domains=(), comment='A page providing information on how to book a tour of some [[Place]], such as an [[Accommodation]] or [[ApartmentComplex]] in a real estate setting, as well as other kinds of tours as appropriate.', label='tourBookingPage', contributors=(), sources=('https://github.com/schemaorg/schemaorg/issues/2373',)),
        PropertyMetadata(name='url', schema_name='url', schema_url='https://schema.org/url', ranges=('URL',), external_ranges=(), inverse_of=None, superseded_by=None, supersedes=(), equivalent_properties=('http://ogp.me/ns#url',), subproperty_of=(), domains=('Thing',), external_domains=(), comment='URL of the item.', label='url', contributors=(), sources=()),
    )
    schema_id: str | None = Field(default=None, alias='@id')
    schema_type: Literal['Zoo'] = Field(default='Zoo', alias='@type', frozen=True)
